deployment/k8s/helm/victoria-metrics/templates/_helpers.tpl

There seems to be a small bug in the definition of `victoria-metrics.vmstorage.fullname` in the `_helpers.tpl` of the cluster Helm chart. This PR should fix that.

Small bug in cluster Helm Chart

---

deployment/k8s/helm/victoria-metrics/templates/vminsert-ingress.yaml
deployment/k8s/helm/victoria-metrics/templates/vmselect-ingress.yaml

This fixes issue #196 . Helm lint now passes:
```
$ helm lint victoria-metrics/
==> Linting victoria-metrics/
[INFO] Chart.yaml: icon is recommended
1 chart(s) linted, no failures
```
Deployment with helm v3 also works (as should v2):
```
helm3 upgrade --install vm victoria-metrics/
Release "vm" does not exist. Installing it now.
NAME: vm
LAST DEPLOYED: 2019-10-02 13:30:51.9474376 +0200 CEST m=+1.756634101
NAMESPACE: default
STATUS: deployed
NOTES:
Write API:
The Victoria Metrics write api can be accessed via port 8480 on the following DNS name from within your cluster:
vm-victoria-metrics-vminsert.default.svc.cluster.local
Get the Victoria Metrics insert service URL by running these commands in the same shell:
export POD_NAME=$(kubectl get pods --namespace default -l "app=vminsert" -o …
```

Fix issue #196 - helm template indentation

---

deployment/docker/docker-compose.yml

The `provisioning/dashboards` folder should be already mounted on the previous line.
This should fix the `/bin/sh: can't create dashboards/vm.json: Permission denied` error on `docker-compose up`
@hagen1778 , could you look into this?

Fix docker-compose cluster

---

dashboards/victoriametrics.json

Hello,
I would like to suggest a small visual change on the cluster dashboard: 4 graphs have a "max" line to visually indicate the upper limit of the graph values. While this is most helpful, having this line drawn in the same way as the other could be misleading.
You already put a static red color which is nice but you could get further by not filling the space between 0 and this line: it helps visually understand that this is not a regular value as the others but is instead the upper limit.
For example:
vs
(my others values are unfortunatly too low to show their are indeed filled as regular series in Grafana, but you can see the "max" serie is not filled but instead is just a visual upper limit while not "coloring" the entire graph)
4 graphs are affected by this change:
* Caches > Cache …

Do not fill max lines on cluster dashboard

---

README.md

`-scrapeInterval` option does not exist. It seems to be a typo of `-selfScrapeInterval`.

Fix a typo in README (selfScrapeInterval)

---

app/vmselect/main.go

Hello,
I was wandering thru VM cluster metrics and I think I found a small typo.
`query_range` path for the `vm_http_requests_total` metric is missing the `{}` tenant placeholder.
While fixing it, I found an even smaller typo: all paths have a leading `/` in the `path` tag, all but `vm_http_request_errors_total`. While this could be intended, it seems very unlikely as it counterpart `vm_http_requests_total` does have it.
TL;DR: check the diff, it will make more sense

Cluster - prometheus metrics fix

---

app/vmselect/promql/rollup.go

rollupOpen(): 
- if **values** is empty => return **prevValue**;
- otherwise return the first value among **values**.
Note: according to the current code if **prevValue** is a valid number => the function returns **prevValue** instead of returning the first value among **values**.
rollupHigh():
-  if **values** is empty => return **prevValue**;
- otherwise return the maximum value among **values**.
Note: according to the current code if **prevValue** is greater than all of the **values** => the function returns **prevValue**, but correct behavior is to return the maximum value among **values**.
rollupLow():
-  if **values** is empty => return **prevValue**;
- otherwise return the minimum value among **values**.
Note: according to the current code if **prevValue** is less than all of the …

fix rollupOpen(), rollupHigh(), rollupLow() functions

---

dashboards/victoriametrics.json

The way how regex for column style in Table panel should be applied has changed in 6.7 Grafana version. The change supposed to fix Flags panel column styles accordingly.

Update dashboard according to new Grafana version.

---

app/vmalert/Makefile
app/vmalert/README.md
app/vmalert/main.go
app/vmalert/notifier/alert.go
app/vmalert/notifier/utils.go
app/vmalert/remotewrite/remotewrite.go
app/vmalert/rule.go
app/vmalert/rule_test.go

If `remotewrite.url` flag is set, vmalert will send alerts state  via remote-write protocol to remote storage. The sending is asynchronous to avoid blocking calls in rules evaluation loop.

app/vmalert: initial remote-write support for alerts state persistence.

---

lib/promscrape/client.go

Make vmagent action same with Prometheus when meet 301/302

fix: vmagent not follow 301/302 redirect bug

---

app/vmalert/Makefile
app/vmalert/README.md
app/vmalert/config.go
app/vmalert/main.go
app/vmalert/rule.go
app/vmalert/rule_test.go
app/vmalert/testdata/rules0-good.rules
app/vmalert/web.go

Vmalert will restore alerts state for rules that have `rule.For` > 0 from previously written timeseries via `remotewrite.url` flag.

app/vmalert: restore alerts state from datasource metrics

---

app/vmagent/main.go
app/vmalert/main.go
app/vmalert/rule.go
app/vmalert/rule_test.go
app/vmalert/web.go
app/vmalert/web_test.go

added config reload with sighup and api call.
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/431
1) rules will be always updated after config reread, maybe it`s better to apply changes only for rules with diff? But in another hand, it`s easier to deal with missing rules.
2) Breaking changes for response code at vmagent config reload api. I need it for future operator integration, it easy to change correct response code at basic prometheus config reload.
But for operator different image is used without such option (https://github.com/thanos-io/thanos/blob/master/pkg/reloader/reloader.go).

vmalert config reload, vmagent changed reload api response code

---

app/vmalert/Makefile
app/vmalert/README.md
app/vmalert/main.go
app/vmalert/remotewrite/remotewrite.go

Change also adds the recommendation for `remotewrite`
queue error.

vmalert: fix flag names and description in README

---

app/vmalert/manager.go
app/vmalert/rule.go

The check for non-nil remoteRead was mistakenly dropped
during refactoring which caused panics when `vmalert`
wasn't configured with `remoteRead` flag.
#473

vmalert: check if remoteRead object was initied before calling Restore

---

app/vmalert/group.go
app/vmalert/group_test.go

During group's update rules deletion was causing slice
mutations while slice index was assumed to be unchanged.
This caused "slice bounds out of range" errors when multiple
rules were deleted sequentially.
#480

vmalert: fix the access to rules slice element by wrong index

---

app/vmalert/Makefile
app/vmalert/config.go
app/vmalert/group.go
app/vmalert/manager.go
app/vmalert/manager_test.go

Configuration reload and rules evaluation can't be executed
in same time now. This may make reload time longer but
prevents potential races.

vmalert: fix potential race during configuration reloads

---

app/vmalert/group.go
app/vmalert/rule.go
app/vmalert/rule_test.go

Before the change we were sending notifications to notifier if:
* alert is in Fire state
* alert is in Inactive state
We were sending Inactive notifications with End set to
last execution time to resolve alert ASAP. Unfortunately,
we were sending resolves for Pending alerts that become
Inactive, which is wrong.
In this change we delete alert from the active list if
it was Pending and become Inactive. In this way we now
have Inactive alerts only if they were in state Fire before.
See test change for example.
#483

vmalert: avoid sending resolves for pending alerts

---

dashboards/victoriametrics.json

The new update introduces new row "Troubleshooting" that
contains panels for churn rate and slow-queries/inserts/loads metrics. This row supposed to be reveal the cause of low performance or other issues.
Panels for storage were updated with "bytes-per-datapoint" and "remaining disk size" panels.
#494 #397

dashboards-single: updates and fixes

---

dashboards/victoriametrics.json

* The new update introduces new row "Troubleshooting" that
contains panels for churn rate and slow-queries/inserts/loads metrics. This row supposed to be reveal the cause of low performance or other issues;
* CPU panel got `short` units instead of `seconds`;
* Overview row was updated with panel showing bytes-per-datapoint stat;
* Overview row was updated with panel showing free disk space.
#494 #407 #397

dashboards: updates and fixes for cluster version

---

dashboards/victoriametrics.json

* Slow metrics load panel was removed since it is hard to interpret without
additional metrics and stats;
* Slow inserts panel was updated to display percentage of slow inserts comparing
to total number of inserts to show the real impact.
#494

dashboards: update troubleshooting row

---

lib/memory/memory.go

Currently the flag -memory.allowedPercent allows values between 10 and 200. In cases when victoriametrics runs on server that have large amount of memory(500GB for example) it consumes at least 50GB(10%) of memory. At the same time, if we have just 2M of active timeseries, even 1% of memory consumed by caches would be decent and a lot of memory wouldn't wasted.

allow to use values lower than 10 with the flag -memory.allowedPercent

---

app/vmselect/netstorage/tmp_blocks_file.go

since `vmselect` stores any fetched data from `storage` to tmp file if the content size is bigger than `vm_tmp_blocks_max_inmemory_file_size_bytes`, we want to find a way to watch the tmp file size.
If there a bunch of "big query"(a bunch of query from grafana with a long time range), it may have cause high IO usage and exhaust the disk space.

feat(vmselect): add tmp block dir size metrics `vm_tmp_blocks_files_size_total`

---

app/vmalert/README.md
app/vmalert/config/config.go
app/vmalert/config/config_test.go
app/vmalert/group_test.go
app/vmalert/main.go
app/vmalert/manager.go
app/vmalert/manager_test.go

This feature may be useful for using `vmalert` with PromQL
compatible datasources like Loki.
#521

vmalert-521: allow to disable rules expression validation.

---

app/vmalert/README.md
app/vmalert/alerting_test.go
app/vmalert/config/config.go
app/vmalert/config/testdata/rules2-good.rules
app/vmalert/group.go
app/vmalert/group_test.go
app/vmalert/helpers_test.go
app/vmalert/main.go
app/vmalert/manager.go
app/vmalert/web_types.go

The feature allows to speed up group rules execution by
executing them concurrently.
Change also contains README changes to reflect configuration
details.
#491

vmalert-491: allow to configure concurrent rules execution per group.

---

app/vmalert/README.md
app/vmalert/alerting.go
app/vmalert/config/config.go
app/vmalert/config/config_test.go
app/vmalert/config/testdata/kube-good.rules
app/vmalert/config/testdata/rules2-good.rules
app/vmalert/group_test.go
app/vmalert/recording.go

Uniqueness of rule is now defined by combination of its name, expression and
labels. The hash of the combination is now used as rule ID and identifies rule within the group.
Set of rules from coreos/kube-prometheus was added for testing purposes to
verify compatibility. The check also showed that `vmalert` doesn't support
`query` template function that was mentioned as limitation in README.
#537 #538

vmalert-537: allow name duplication for rules within one group.

---

app/vmalert/README.md
app/vmalert/main.go
app/vmalert/main_test.go
app/vmalert/remotewrite/remotewrite.go

Add support for TLS optional configuration in a similar fashion to what
is currently supported in other vmutils such as vmagent. TLS
configuration options are distinct for datasource, remoteRead,
remoteWrite as well as notifier.

vmalert: add support for TLS configuration

---

app/vmselect/promql/exec_test.go
app/vmselect/promql/transform.go

As per documentation on `label_replace` function: "If the regular
expression doesn't match then the timeseries is returned unchanged".
Currently this behavior is not enforced, if a regexp on an existing
tag doesn't match then the tag value is copied as-is in the destination
tag. This fix first checks that the regular expression matches the
source tag before applying anything.
Given the current implementation, this fix also changes the behavior
of the **MetricsQL** `label_transform` function which does not
document this behavior at the moment.

vmselect: fix label_replace when mismatch

---

README.md
dashboards/victoriametrics.json
deployment/docker/README.md
deployment/docker/docker-compose.yml
deployment/docker/prometheus.yml
deployment/docker/provisioning/datasources/datasource.yml

vmagent replaces Prometheus to perform scrapes and writes
into VictoriaMetrics installation. Prometheus datasource was
dropped, but its config was reused to feed vmagent.
Change also contains simplification in dashboard propagation
to Grafana container by removing excessive json manipulation
steps.

deployment/docker: replace Prometheus with vmagent

---

lib/promscrape/scrapework.go
lib/promscrape/scrapework_test.go

Fix Auto metrics relabeled errors

---

app/vmselect/prometheus/prometheus.go
app/vmselect/prometheus/prometheus_test.go

My case just like this test
```
{
Timestamps: []int64{100, 200, 300, 400, 500},
Values:     []float64{1, 2, nan, nan, nan},
},
```
Then `queryOffset` is 300, the previous output was
```
{
Timestamps: []int64{100, 200, 300, 400, 500},
Values:     []float64{1, 2, 3, 3, nan},
}
```
After this patch, the output was
```
{
Timestamps: []int64{100, 200, 300, 400, 500},
Values:     []float64{1, 2, nan, nan, nan},
}
```
I think we need to determine  the time of the NonNaN value exceeds `queryOffset`, rather than simply judging the end time of the metric.

fix adjust last points avoid influence earlier value

---

app/vmalert/group.go
app/vmalert/remotewrite/remotewrite.go
app/vmalert/remotewrite/remotewrite_test.go

Remotewrite pkg now does limited number of retries if write request failed.
This suppose to make vmalert state persisting more reliable.
New metrics were added to remotewrite in order to track rows/bytes sent/dropped.
defaultFlushInterval was increased from 1s to 5s for sanity reasons.

app/vmalert: add retries to remotewrite

---

lib/protoparser/graphite/parser_test.go
lib/protoparser/graphite/streamparser.go

Graphite format support "-1" as valid timestamp, which equals to empty timestamp. 
>Carbon-cache will use the time of arrival if the timestamp is set to -1
https://graphite.readthedocs.io/en/latest/feeding-carbon.html
Also, added tests for the Test_streamContext_Read, while timestamp parsing is a part of the Read function.

Fix graphite minus one timestamp

---

lib/protoparser/promremotewrite/streamparser.go

The change fixes the typo in metric name `vm_protoparser_unmarshal_errors` to
respect the naming standard.

lib/protoparser: fix metric name of unmarshal errors in promremotewrite

---

lib/promscrape/scraper.go
lib/promscrape/scrapework.go
lib/promscrape/targetstatus.go

The change to `vm_promscrape_targets` metric suppose to improve observability
for `vmagent` so it will be possible to track how many targets are up or down
for every specific scrape group:
```
vm_promscrape_targets{type="static_configs", status="down"} 1
vm_promscrape_targets{type="static_configs", status="up"} 2
```

Extend metric `vm_promscrape_targets` with `status` label

---

lib/persistentqueue/persistentqueue.go

Metric `vm_persistentqueue_bytes_pending` is a gauge that shows current amount
of bytes in persistentqueue flushed on disk as a difference between write and read
offsets. This metric is very similar to `vmagent_remotewrite_pending_data_bytes`
except of accounting for bytes in-memory.

lib/persistentqueue: add `vm_persistentqueue_bytes_pending` metric

---

lib/flagutil/array.go

Array type flag is currently defined as `value` type in flag description when printed.
This change adds additional description to every Array type flag so it would be
clear what exact type is used:
```
-remoteWrite.urlRelabelConfig array
Optional path to relabel config for the corresponding -remoteWrite.url
Supports array of values separated by comma or specified via multiple flags.
```

lib/flagutil: specify additional description for all Array type flags

---

dashboards/vmagent.json
deployment/docker/docker-compose.yml

`vmagent` Grafana dashboard suppose to provide basic observability over multiple
`vmagent` instances. Dashboard is saved in Grafana export format so it can be easily
imported. Dashboard was integrated into docker-compose environment as well.
To test dashboard import `dashboards/vmagent.json` file into Grafana or [run docker-compose](https://github.com/VictoriaMetrics/VictoriaMetrics#start-with-docker-compose) env from `deployment/docker` directory.

vmagent: add grafana dashboard

---

dashboards/victoriametrics.json

Panel `Concurrent inserts` was moved to `vminsert` row. Its metrics and description
was updated according to #632 issue.

dashboards/victoriametrics: update `Concurrent inserts` panel #632

---

lib/storage/metaindex_row.go

due to memory align the metaindexRow structure use 64-byte pre object.
```
Meta Index Row: 64 byte
TSID:              24 byte
BlockHeadersCount: 4  byte
blank padding:     4  byte
MinTimestamp:      8  byte
MaxTimestamp:      8  byte
IndexBlcokOffset:  8  byte
IndexBlcokSize:    4  byte
blank padding:     4  byte
```
this PR removes the blank padding by changing the field order.
```
Meta Index Row: 56 byte
TSID:              24 byte
MinTimestamp:      8  byte
MaxTimestamp:      8  byte
IndexBlcokOffset:  8  byte
BlockHeadersCount: 4  byte
IndexBlcokSize:    4  byte
```

lib/storage: metaindexRow use memroy more efficiently

---

app/vmalert/Makefile
app/vmalert/README.md
app/vmalert/alerting.go
app/vmalert/alerting_test.go
app/vmalert/config/config.go
app/vmalert/group.go
app/vmalert/group_test.go
app/vmalert/main.go
app/vmalert/manager.go

`external.label` flag supposed to help to distinguish alert or recording rules
source in situations when more than one `vmalert` runs for the same datasource
or AlertManager.

app/vmalert: support `external.label` to specify global labelset for all rules #622

---

package/package_deb.sh

Trivial patch to allow building Debian package for `armhf` architecture as well.

Add option to build 32b ARM Debian package (armhf)

---

app/vmagent/remotewrite/remotewrite.go
lib/decimal/decimal.go

The previous notion was inconsistent with what `decimal.Round` does.
According to [wiki](https://en.wikipedia.org/wiki/Significant_figures) rounding
applied to all significant figures, not just decimal ones.

lib/decimal: rename `significant decimal digits` to `significant figures`

---

lib/backup/actions/util.go

aws sdk has complicated logic for chosing profile name and we shouldn't set
it to `default` value. It leads to bugs and improper configuration.
Set it to empty value by default is safe. It will be automatically set to `default` by sdk.

Changed s3 configProfile flag default  value

---

README.md

Further clarification for #735
* clarify how default range differers from Prometheus API
* avoid `start=0` suggestion when confirming delete, because it will cause a timeout in most deployments

revise /api/v1/series docs

---

lib/promscrape/discovery/kubernetes/endpointslices.go
lib/promscrape/discovery/kubernetes/endpointslices_test.go
lib/promscrape/discovery/kubernetes/kubernetes.go

Started from 1.17 k8s version endpointslices is beta,
it allows to query k8s api for endpoints more efficient.
It presents at scrape_config.yaml as separate role for kubernetes_sd_config.
kubernetes_sd_config:
- role: endpointslices

Added endpointslices discovery to k8s api

---

app/vmalert/config/config.go
app/vmalert/config/config_test.go
app/vmalert/group.go
app/vmalert/manager.go

On config reload event `vmalert` reloads configuration for every group. While
it works for simple configurations, the more complex and heavy installations may
suffer from frequent config reloads.
The change introduces the `checksum` field for every group and is set to md5 hash
of yaml configuration. The checksum will change if on any change to group
definition like rules order or annotation change. Comparing the `checksum` field
on config reload event helps to detect if group should be updated.
The groups update is now done concurrently, so reload duration will be limited by
the slowest group.

vmalert: update groups on config reload only if changes detected

---

app/vmalert/datasource/vm.go

The error will be always nil so no sense in printing it.

vmalert: fix the typo in error message

---

app/vmalert/README.md
app/vmalert/datasource/init.go
app/vmalert/datasource/vm.go
app/vmalert/datasource/vm_test.go
app/vmalert/remoteread/init.go

New datasource flag `datasource.lookback` defines how far to look into
past when evaluating queries.
Address https://github.com/VictoriaMetrics/VictoriaMetrics/issues/668

vmalert: add support for `datasource.lookback` flag

---

lib/filestream/filestream_openbsd.go
lib/fs/fs.go
lib/fs/fs_nix.go
lib/fs/fs_openbsd.go

https://github.com/VictoriaMetrics/VictoriaMetrics/issues/785
removed fadvise for openbsd, added freespace implemenation for openbsd

added openbsd implementations

---

lib/storage/index_db.go
lib/storage/tag_filters.go
lib/storage/tag_filters_timing_test.go

Ref https://github.com/VictoriaMetrics/VictoriaMetrics/issues/781#issuecomment-706000694
I've noticed that some optimized regular expressions actually have very little matching overhead, such as `.+` `.*`. After this PR, the matching priority of these regular expressions will be raised to the highest.
Here's the benchmark results from my machine:
```
name                                  time/op
OptimizedReMatchCost/default-6          0.38ns ±12%
OptimizedReMatchCost/literal_match-6    1.15ns ±23%
OptimizedReMatchCost/foo|bar|baz-6      2.43ns ± 2%
OptimizedReMatchCost/.*-6               0.34ns ± 7%
OptimizedReMatchCost/.+-6               0.38ns ±27%
OptimizedReMatchCost/prefix.*-6         0.90ns ±23%
OptimizedReMatchCost/prefix.+-6         0.84ns ± 9%
OptimizedReMatchCost/.*suffix-6 …
```

evaluate the execution cost of all tag filters

---

lib/httpserver/httpserver.go

I want to import httpserver in VictoriaLogs and need to disable compression on the websocket connection.

disable response compression on websocket

---

app/vmalert/config/config.go
app/vmalert/main.go

add dryRun flag for checking rules in config the error output looks like:
```
2020-10-17T12:11:12.393Z	fatal app/vmalert/main.go:219	config parsing errors:
invalid group "group" in file "config/testdata/dir/rules0-bad.rules": invalid annotations for rule "group"."InvalidAnnotations": errors(1): key "summary", template "{{ $value }": error parsing annotation: template: :1: unexpected "}" in operand
group name "sameGroup" duplicate in file "config/testdata/dir/rules1-bad.rules"
invalid group "group" in file "config/testdata/dir/rules2-bad.rules": invalid labels for rule "group"."UnkownLabelFunction": errors(1): key "summary", template "{{ value|query }}": error parsing annotation: template: :1: function "value" not defined
invalid group "group" in file …
```

vmalert - add dryRun

---

dashboards/victoriametrics.json

Current description led to confusion at https://victoriametrics.slack.com/archives/CGZF1H6L9/p1603270014273800

dashboard: clarify the purpose of `Concurrent flushes on disk` panel

---

deployment/docker/docker-compose.yml

This is necessary for Proxmox VE External Metric Server support.
https://pve.proxmox.com/wiki/External_Metric_Server

Added UDP protocol support for Graphite/Influx in docker-compose deployment

---

app/vmalert/alerting.go
app/vmalert/alerting_test.go

Label `alertgroup` was introduced in #611 and automatically added to generated
time series. By mistake, this new label wasn't correctly purged on restore event
and affected alert's ID uniqueness. This commit removes `alertgroup` label
in restore function.
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/870

vmalert: skip automatically added labels on alerts restore

---

deployment/docker/docker-compose.yml

This is necessary for Proxmox VE External Metric Server support.
https://pve.proxmox.com/wiki/External_Metric_Server
Additionally created Grafana Dashboard for monitoring Proxmox VE hosts.
https://grafana.com/grafana/dashboards/13307
PS: Sorry, I didn't check with InfluxDB in the previous PR. My fall.

Fix InfluxDB support on docker-compose deployment.

---

ports/OpenBSD/README.md
ports/OpenBSD/VictoriaMetrics/Makefile
ports/OpenBSD/VictoriaMetrics/distinfo
ports/OpenBSD/VictoriaMetrics/pkg/DESCR
ports/OpenBSD/VictoriaMetrics/pkg/PLIST
ports/OpenBSD/VictoriaMetrics/pkg/vmetrics.rc
ports/OpenBSD/VictoriaMetrics/pkg/vmlogger.pl

This can be used to propose and integrate Victoria DB in a -OpenBSD- ports system.
I would have use package/OpenBSD but package assumed only debian .
The Directory can be zipped and send to ports@openbsd.org with [NEW] in object and package name 
by the/a maintainer

OpenBSD packaging files

---

lib/httpserver/metrics.go

use case:  Version panel of Grafana dashboard should use a live query, but currently it uses a template query which becomes stale.  Grafana is not able to preform regex substitution on labels.

add short_version label to vm_app_version metric

---

app/vmagent/README.md
docs/vmagent.md
lib/promscrape/config.go
lib/promscrape/targetstatus.go

limits count of droppedTarget, that can be stored for /api/v1/targets page up to 999 items,
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/878

reduces memory usage for vmagent,

---

app/vmstorage/main.go
lib/storage/storage.go
lib/storage/storage_test.go

As discussed briefly in Slack, it would be nice to have this endpoint to use a live victoriametrics instance in testing, when some other component writes some data into it and expects it to be available without waiting for background flushing to kick in.
~~I have implemented it to reuse `forceMergeAuthKey` instead of adding a new key to minimise the scope of the change. I am aware that the name is not very suitable, but both endpoints are internal and do a similar thing: trigger a background process without having to wait for it.~~
Golang is not my "native" tongue, so happy to revisit the changeset until it is good enough to get accepted, but I have also enabled editing by maintainers to speed up one-liner suggestions.

app/vmstorage: add "/internal/force_flush" endpoint

---

app/vmagent/main.go

Label values may contain any Unicode characters.
I've only changed the two api's I'm using, there should be some other api that need to be added to charset as well.

add charset on targets response

---

lib/promauth/config.go
lib/promrelabel/config.go
lib/promscrape/config.go
lib/promscrape/discovery/consul/consul.go
lib/promscrape/discovery/dns/dns.go
lib/promscrape/discovery/dockerswarm/dockerswarm.go
lib/promscrape/discovery/ec2/ec2.go
lib/promscrape/discovery/gce/gce.go
lib/promscrape/discovery/kubernetes/kubernetes.go
lib/promscrape/discovery/openstack/openstack.go

Added the "omitempty" option for the DisableCompression and DisableKeepAlive fields in ScrapeConfig.
We use your models in our code and would like to be able to leave these fields empty. I think, it's not going to be a problem.

Add omitempty for DisableCompression and DisableKeepAlive fields in ScrapeConfig

---

ports/OpenBSD/VictoriaMetrics/Makefile
ports/OpenBSD/VictoriaMetrics/pkg/PLIST
ports/OpenBSD/VictoriaMetrics/pkg/vmetrics.rc
ports/OpenBSD/VictoriaMetrics/pkg/vmlogger.pl

OpenBSD 6.8 port update
fix multi instance logging name:
> use the name of the symlink of rcctl to name the log
, add restore
> add the vmrestore bin
, fix rcctl
> the no timestamp must be used consistently

OpenBSD 6.8 port update (fix multi instance logging name, add restore, fix rcctl)

---

ports/OpenBSD/VictoriaMetrics/pkg/vmlogger.pl

On start the daemon may write an empty line.
Log as warning non managed log level.
Thanks Andrew .F. for pointers

Fix restart and code review

---

docs/MetricsQL.md

if I understand correctly:
* `fun(q)` - fun takes instant vector
* `fun(m[d])` - fun takes range vector

MetricsQL docs: parameter consistency

---

app/vmalert/config/config.go
app/vmalert/config/config_test.go

'for' rule param wasnt marshal properly during checksum calculation.
It leads to incorrect rule reload, when for param was changed for rule.

fixes checksum calculation

---

README.md

This diff is just to suggest wording to let people know there is no future-compatible guaranteed way to make their own native format files for import yet.

Wording suggestion for lack of native format spec

---

lib/protoparser/prometheus/parser.go

fix parse timestamp error if there are some whitespaces after timestamp

prometheus/parser.go: fix parse timestamp error

---

app/vmalert/alerting.go
app/vmalert/alerting_test.go
app/vmalert/config/testdata/rules2-good.rules
app/vmalert/notifier/alert.go

The change fixes bug caused by https://github.com/VictoriaMetrics/VictoriaMetrics/commit/3adf8c5a6f4a8eea5f2025dd53ba975d42f8b8d1.
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/974
------------------
@f41gh7 pls see the test cases in PR. I'd appreciate your review and feel free to suggest additional test cases we may want to check.

vmalert-974: fix order for labels templating

---

lib/netutil/proxy.go
lib/promscrape/client.go
lib/promscrape/config.go
lib/promscrape/discovery/consul/api.go
lib/promscrape/discovery/consul/consul.go
lib/promscrape/discovery/dockerswarm/api.go
lib/promscrape/discovery/dockerswarm/dockerswarm.go
lib/promscrape/discovery/eureka/api.go
lib/promscrape/discovery/eureka/eureka.go
lib/promscrape/discovery/kubernetes/api.go
lib/promscrape/discovery/kubernetes/kubernetes.go
lib/promscrape/discoveryutils/client.go
lib/promscrape/scrapework.go
lib/promscrape/statconn.go

adds proxy_url to the dockerswarm, eureka, kubernetes and consul service discovery,
adds proxy_url to the scrape_config for targets scrapping,
http based proxy is supported atm,
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/503

adds proxy_url support,

---

app/vmalert/README.md
app/vmalert/main.go
app/vmalert/notifier/template_func.go
docs/vmalert.md

at external.alert.source - \n and \r symbols was url encoded, instead of direct usage.
replace it from "\n" to `\n`  allows to skip url encoding.
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/890

adds escape for CRLF

---

deployment/docker/alertmanager.yml
deployment/docker/docker-compose.yml

Currently, alertmanager spams logs with `Notify attempt failed, will retry later` message
because default receiver is unreachable. The change updates default configuration with
blackhole receiver which means alertmanager will continue to accept alerts but won't make
attempts to send them anywhere.
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/995

docker-compose: add blackhole receiver for alertmanager

---

app/vmalert/config/testdata/rules2-good.rules
app/vmalert/notifier/template_func.go

On templates validation stage vmalert does not acutally send queries, so for complex
chained expression validation may fail. To avoid this, we add a blank sample in response
so validation can pass successfully. Later, during the rule execution, stub will be replaced
with real `query` function.
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/989

vmalert-989: return non-empty result in template func `query` stub to pass validation

---

README.md
deployment/docker/alerts.yml
deployment/docker/prometheus.yml

List contains examples for the alerting rules which might be executed
via `vmalert` to track the health state of VM components. It is assumed
that list will be revised and calibrated for each system individually.

docker-compose: provide the example list of alerting rules for vm components

---

app/vmagent/prometheusimport/request_handler.go
app/vminsert/prometheusimport/request_handler.go
lib/promscrape/scrapework.go
lib/protoparser/prometheus/streamparser.go
lib/protoparser/prometheus/streamparser_test.go

properly return error if client cannot read data,
properly suppress scraper errors

Fixes error handling for promscrape.streamParse

---

Makefile

Follow-up from #1011
* Consistent archive/binary artifacts between arm64/amd64 for vmutils release builds
* architecture in archive, checksum file
* not in binaries
* Checksum file contains individual checksum for each binary
Since this involves a name change for the release tar archive, I guess it warrants a mention in the release notes.

Arch consistent filenames

---

app/vmalert/datasource/init.go
app/vmalert/datasource/vm.go
app/vmalert/datasource/vm_test.go
app/vmalert/remoteread/init.go

If you use `vmselect` you have to specify the right endpoint for the alerts query type: `/prometheus` or `/graphite`.
This PR adds an optional `-datasource.appendTypePrefix` flag to `vmalert` to determine the right datasource path. It enables us to specify only base vmselect path as `-datasource.url`, for example: `<vmselect-addr>/select/<tennant>/` and the right prefix will be added based on the alert query type.

Adds ability to query right vmselect endpoint based on the query type

---

dashboards/victoriametrics.json

New panel supposed to display events when VM drops extra label
on exceeding `maxLabelsPerTimeseries` limit.
-----------------------------

Add `Labels limit exceeded` panel to dashboard

---

app/victoria-metrics/testdata/prometheus/with_request_extra_filter.json
app/vmagent/remotewrite/client.go
app/vmagent/remotewrite/remotewrite.go

during shutdown currently sending block was lost,
now its pushed back to fast queue and will be flushed on disk,
it may lead to data duplication.
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1065

fq flush sending block.

---

app/vmselect/netstorage/netstorage.go

when response from one vmstorage node is partially processed and then timeout when reading next block, data from the partially processed response should not be cached

vmselect: fix vmselect cache partial result when timeout

---

app/vmalert/remotewrite/remotewrite.go

remoteWrite.url now accepts query params at provided url,
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1087

adds query params for vmalert

---

docs/vmalert.md

Using the current doc, a cURL call will return something like
```
remoteAddr: "172.17.0.1:26778"; error in "/api/v1/AlertGroupName/AlertGroupID/status":
cannot parse groupID: strconv.ParseUint: parsing "AlertGroupName": invalid syntax
```
Using `/api/v1/AlertGroupID/AlertGroupID/status` returns the expected JSON.

[doc fix] status endpoint needs group ID, not group name

---

app/vmalert/README.md
app/vmalert/main.go
deployment/docker/docker-compose.yml
docs/vmalert.md

- Removing trailing whitespaces in the documentation
- Fixing examples for using external.alert.source in the documentation, fixes https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1117

Fixing examples of external.alert.source in documentation

---

dashboards/victoriametrics.json
deployment/docker/alerts.yml

* add panel `Open FDs` for file descriptors metrics;
* add panel `Disk writes/reads` to show the real read/write
load on storage layer;
* add `process_resident_memory_bytes` metric to memory usage panel;
* add stats panel to show available CPUs, memory and disk space;
* rm flags panel since it didn't prove its usefulness;
* add alert for open FDs.

Single dashboard

---

deployment/docker/docker-compose.yml

Fix a typo introduced in 1eecc214ff58364fecdf3b25f7d3a0bf99de9fb0

deployment: fix typo in vmalert docker-compose definition

---

dashboards/victoriametrics.json
dashboards/vmagent.json

single:
* add number of new series created over last 24h;
* bump version requirements.
vmagent:
* add panel for open file descriptors;
* add panel for disk I/O;
* add panel for `vmagent_remotewrite_packets_dropped_total` metric;
* bump version requirements.

Dashboards update

---

deployment/docker/alerts.yml

Alert `TooHighChurnRate24h` suppose to cover cases when churn rate
is low but results in multiple times higher number than total
number of active series.

deployment: add new alert `TooHighChurnRate24h`

---

Makefile
README.md
app/vmagent/README.md
app/vmalert/README.md
app/vmauth/README.md
app/vmbackup/README.md
app/vmctl/README.md
app/vmgateway/README.md
app/vmrestore/README.md
docs/Articles.md
docs/BestPractices.md
docs/CHANGELOG.md
docs/CaseStudies.md
docs/Cluster-VictoriaMetrics.md
docs/FAQ.md
docs/Home.md
docs/MetricsQL.md
docs/Quick-Start.md
docs/Release-Guide.md
docs/SampleSizeCalculations.md
docs/Single-server-VictoriaMetrics.md
docs/vmagent.md
docs/vmalert.md
docs/vmauth.md
docs/vmbackup.md
docs/vmctl.md
docs/vmgateway.md
docs/vmrestore.md

The major change is adding `sort` directive to docs. For those docs which are copied
from internal packages `sort` is added via makefile command. For the rest it is added
manually since they're updated manually as well.
The rest of changes is connected with markdown formatting. For example, changing headers
in some files (`##` => `#`) makes navigation on .github.io to look better. This especially
useful for `changelog` docs.
Table of contents for `vmctl` is dropped, since we already have it autogenerated on .github.io.
No link changes expected. The corresponding PR to `cluster` branch will be made in follow-up PR.
------------------
Expected change

docs: update docs ordering and formatting

---

app/vmctl/README.md
app/vmctl/opentsdb.go
app/vmctl/opentsdb/opentsdb.go

I realized the documentation should actually describe how the queries work so a user doesn't have to read the code to understand it.
Also, there was a bug in how offsets were handled that I somehow missed in testing. That is fixed.

Improve documentation on OpenTSDB migration tool and fix a bug with hard offsets

---

Makefile

Just like the existing infrastructure for `BUILDINFO_TAG`, this can ease the production of [reproducible builds](https://wiki.freebsd.org/ReproducibleBuilds).
(e.g. in FreeBSD the date the port was committed is used at build time, not the actual build time, so that an identical port produced at different times produces an identical executable)

Allow specifying build date from a variable

---

deployment/docker/alerts.yml

Original query can't be executed via PromQL which results in error
if expression is evaluated by Prometheus. The new expression is
compatible with both engines.

alerts: make alerting rule `RPCErrors` compatible with PromQL

---

dashboards/victoriametrics.json

Previous expression was not correct.

dashboard: fix avg GC duration expression

---

dashboards/victoriametrics.json

https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1206

dashboard: use unit `short` for `Labels limit exceeded` panel

---

app/vmalert/recording.go

Previously, vmalert used `lastExecTime` timestamp when writing recording rules
to the remote storage. This may be incorrect, if vmalert uses `datasource.lookback` flag,
which means rule's expression will be executed at some moment in the past.
To avoid such situations, vmalert now will use returned timestamp instead of `lastExecTime`.

vmalert: keep the returned timestamp when persisting recording rule

---

app/vmalert/alerting.go
app/vmalert/datasource/vm.go
app/vmalert/datasource/vm_test.go
app/vmalert/recording.go

With this change, vmalert will start to use rule's evaluation interval
for truncating the `time` param. This is mostly needed to produce consistent
time series with timestamps unaffected by vmalert start time. Now, timestamp
becomes predictable.
Additionally, adjustment is similar to what Grafana does for plotting range graphs.
Hence, recording rule series and recording rule expression plotted in grafana
suppose to become similar in most of cases.
#1232

Vmalert: adjust `time` param for datasource queries according to `evaluationInterval`

---

app/vmalert/datasource/init.go
app/vmalert/datasource/vm.go
app/vmalert/datasource/vm_test.go

User still can override param by specifying `datasource.queryStep` flag.

vmalert: use rule's `evaluationInterval` as `step` param by default

---

app/vmalert/alerting.go
app/vmalert/main.go
app/vmalert/manager.go

Alerting rules now can return specific error type ErrStateRestore to indicate
whether restore state procedure failed. Such errors were returned and logged
before as well. But now user can specify whether to just log these errors
(remoteRead.ignoreRestoreErrors=true) or to stop the process
(remoteRead.ignoreRestoreErrors=false). The latter is important when VM isn't
ready yet to serve queries from vmalert and it needs to wait.
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1252

vmalert: add flag to control behaviour on startup for state restore errors

---

dashboards/victoriametrics.json

This commit fixes panels descriptions for `Concurrent flushes on disk` (vmstorage)
and `Concurrent inserts` (vminsert).

dashboard: update descriptions for panel

---

app/vmalert/alerting.go
app/vmalert/manager.go

Previously, `startGroup` could exit on restore errors despite the
`remoteRead.ignoreRestoreErrors` flag value. Now vmalert checks the
flag value before deciding whether to return error or just log it.

vmalert: fix error when rule didn't start if restore failed

---

app/vmalert/datasource/init.go
app/vmalert/datasource/vm.go
app/vmalert/datasource/vm_test.go

Starting from v1.56.0 VM supports `round_digits` which allows to limit
the number of digits after the decimal point in response value. The feature
can be used to reduce entropy of produced by recording rules values
and significantly improve the compression. See more details in link below.
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/525

vmalert: add support for `round_digits` param in datasource package

---

lib/promscrape/config.go

when -promscrape.cluster.replicationFactor > 1 
/path/to/vmagent -promscrape.cluster.membersCount=3 -promscrape.cluster.replicationFactor=2 -promscrape.cluster.memberNum=0 -promscrape.config=/path/to/config.yml ...
/path/to/vmagent -promscrape.cluster.membersCount=3 -promscrape.cluster.replicationFactor=2 -promscrape.cluster.memberNum=1 -promscrape.config=/path/to/config.yml ...
/path/to/vmagent -promscrape.cluster.membersCount=3 -promscrape.cluster.replicationFactor=2 -promscrape.cluster.memberNum=2 -promscrape.config=/path/to/config.yml ...
vmagent imbalance problem !

fix vmagent imbalance problem when -promscrape.cluster.replicationFactor > 1 

---

app/vmctl/influx/influx.go
app/vmctl/influx/influx_test.go

The `::tag` type is needed in cases when field and tag names are equal, which
results into unexpected results in InfluxQL. Setting the type explicitly helps
InfluxDB to understand which exact column we apply filter to.
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1299

vmctl: explicitly set `::tag` type for labels selector in `influx` mode

---

app/vmalert/README.md
app/vmalert/alerting.go
app/vmalert/config/config.go
app/vmalert/config/testdata/rules2-good.rules
app/vmalert/datasource/vm.go
app/vmalert/datasource/vm_test.go
app/vmalert/group.go
app/vmalert/manager.go
app/vmalert/recording.go
app/vmalert/web_types.go

The new setting `extra_filter_labels` may be assigned to group.
If it is, then all rules within a group will automatically filter
for configured labels. The feature is well-described here
https://docs.victoriametrics.com#prometheus-querying-api-enhancements
New setting is compatible only with VM datasource.

vmalert: support `extra_filter_labels` setting per-group

---

app/vmalert/Makefile
app/vmalert/README.md
app/vmalert/main.go
app/vmalert/main_test.go
app/vmalert/manager.go
app/vmalert/manager_test.go

New flag `-rule.configCheckInterval` defines how often `vmalert` will re-read
config file. If it detects any changes, the config will be reloaded.
This behaviour is turned off by default.
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/512

vmalert: automatically reload configuration on file change

---

lib/promscrape/client.go
lib/promscrape/scrapework.go

I need to use promscrape.maxScrapeSize to exclude some oversized metrics. Now this option doesn't work with stream parse on. I'm not sure if this is by design, I just want to make this option work with or without stream parse on.

lib/promscrape: apply body size & sample limit to stream parse

---

lib/promscrape/discovery/eureka/eureka.go

file:  lib/promscrape/discovery/eureka/eureka.go
eureka_sd_configs.HTTPClientConfig cannot be read correctly due to a spelling error

fix eureka_sd_configs HTTPClientConfig incorrect parsing

---

app/vmagent/remotewrite/relabel.go
app/vminsert/relabel/relabel.go
docs/vmagent.md
lib/promrelabel/config.go
lib/promrelabel/relabel.go
lib/promscrape/config.go
lib/promscrape/scrapework.go

Use scrape_configs[x].relabel_debug = true to log metric names incl.
labels before and after relabeling. After relabeling related metrics
get dropped, i.e. not submitted to servers.
See #1343

new feature: debug relabeling

---

app/vmalert/Makefile
app/vmalert/README.md
app/vmalert/alerting.go
app/vmalert/alerting_test.go
app/vmalert/config/testdata/rules-replay-good.rules
app/vmalert/datasource/datasource.go
app/vmalert/datasource/datasource_test.go
app/vmalert/datasource/vm.go
app/vmalert/datasource/vm_graphite_api.go
app/vmalert/datasource/vm_prom_api.go
app/vmalert/datasource/vm_test.go
app/vmalert/group.go
app/vmalert/helpers_test.go
app/vmalert/main.go
app/vmalert/manager_test.go
app/vmalert/notifier/alert_test.go
app/vmalert/notifier/template_func.go
app/vmalert/recording.go
app/vmalert/recording_test.go
app/vmalert/replay.go
app/vmalert/replay_test.go
app/vmalert/rule.go
app/vmalert/utils.go

vmalert can `replay` configured rules in the past
and backfill results via remote write protocol.
It supports MetricsQL/PromQL storage as data source,
and can backfill data to remote write compatible
storage.
Supports recording and alerting rules `replay`. See more
details in README.
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/836

vmalert: support rules backfilling (aka `replay`)

---

app/vmalert/datasource/vm_prom_api.go
app/vmalert/datasource/vm_test.go

During the refactoring, the wrong optimisations was applied in
parse function which caused unintentional metric fields reset. 
The change removes this optimisation.
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1369

vmalert: fix mistake with object reuse while parsing response

---

app/vmselect/promql/rollup.go

Due to staleness handling, increase_pure were using incorrect previous value
during calculation in cases where series disappears for period longer
than staleness period and then returns back. The fix suppose to account
for a real datapoint value before staleness takes place. The fix should
remove unexpected spikes while using `increase_pure` for staled series.

promql: fix `increase_pure` calculation for cases with stale series

---

app/vmagent/README.md
app/vmagent/remotewrite/remotewrite.go

Default value of vmagent option '-remotewrite.queues' is 4 and default
size of vmagent ScheudleUnmarshalWorkers is number of CPUs, when available
CPUs is much greater than 4, e.g 32, worker are competing push queues
which will increase scrape interval and may cause scrape timeout.
We have a vmagnet deployed in k8s pod which consumes 32 cores CPU and scrapes 24k active targets. We found that scraping of kube-state-metrics timeout with error message `context deadline exceeded` and scrape duration is about 45s shown in vmagent targets page. When we request the kube-state-metrics endpoint in vmagent container, it costs nearly 1s. 
As shown in following picture, when we increase the option `-remoteWrite.queues` from 10 to 64, the scrape duration decreased to 9s. Timeout error disappeared!
**So …

Change default value of '-remoteWrite.queues' to cgroup.AvailableCPUs * 2

---

dashboards/victoriametrics.json

* rm cumulative visualisation for panel `Disk space used`.
It uses % threshold and cumulative display breaks it.
* remove area filling for resource usage row;
* add job name for panels in resource usage row.

dasbhoard: display tweaks

---

app/vmselect/netstorage/netstorage.go
app/vmstorage/transport/server.go

when i want to use  `-search.maxUniqueTimeseries`  limit too much point return vmselect，avoid vmselect cpu load high，but i found it useless，
so i want add `-search.maxMetricsPointSearch` to limit too much point return vmselect，so as to protect vmselect:

protection vmselect ,avoid metrics point too much let vmselect cup load very, very high

---

app/vmselect/main.go

A small fix for grafana unified alerts to work properly with VM-Cluster.
More details here: https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1493

vm-select/Fix alerts endpoint for grafana8

---

app/vmalert/main.go

In our use case, vmalert failed to parse the config if rule templates are malformed. (e.g. expr is empty).
We prefer to see it happens and send alerts to us.

app/vmalert: add metrics if config parsed failed

---

app/vmalert/alerting.go
app/vmalert/recording.go
app/vmalert/web_types.go

Two new metrics were added to track the number of samples produced during the last evaluation:
* vmalert_recording_rules_last_evaluation_samples
* vmalert_alerting_rules_last_evaluation_samples
The gauge type is used to remain consistent with Prometheus metric
`prometheus_rule_group_last_evaluation_samples` which is on the group level.
However, the counter type was considered as well.
Two metrics instead of one are used to make it easier to separate recording and
alerting rules. It is likely, number of samples produced by recording rules is
more important so people will refer to it more frequently.
The expected usage of the new metric is the following:
```
- alert: RecordingRuleReturnsEmptyResults
expr: sum(vmalert_recording_rules_last_evaluation_samples) by(recording) < 1
annotations: …
```

vmalert: expose new metrics for tracking number of produced samples during last evaluation

---

app/vmalert/README.md
app/vmalert/remotewrite/init.go
app/vmalert/remotewrite/remotewrite.go
docs/vmalert.md

Currently, whatever you configure as `remoteWrite.url` , the path `/api/v1/write` will always be appended to it.
This causes problems when your remote host for one reason or the other does not serve that path, so this PR will add the option to override it with an absolute path if so desired, otherwise keep using the current behaviour.

vmalert: enable configuring explicit path

---

deployment/docker/alerts.yml

rename alert group for cluster, so that they not overlap when you have vmsingle and vmcluster deployed alongside

rename alert group for cluster

---

app/vmalert/remotewrite/remotewrite.go

Some compatible backends respond with http.StatusOK for a successful remotewrite, so supporting that out of the box would be very handy

vmalert: accept http.StatusOK for remotewrite

---

app/vmalert/README.md
app/vmalert/alerting.go
app/vmalert/main.go

The new label added in https://github.com/VictoriaMetrics/VictoriaMetrics/issues/611
may negatively impact deduplication in Alertmanager. The new flag supposed to give
an option to disable adding this label.
To enable flag just add `-disableAlertgroupLabel` to binary execution command.
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1532

vmalert: add flag `disableAlertgroupLabel` for disabling extra label added to series

---

app/vmauth/target_url.go
app/vmauth/target_url_test.go

I have a use-case where I want to grant a user access to the federate endpoint only. Unfortunately, when requesting root URLs from VMAuth, a trailing slash is always appended which then breaks the routing in VMSelect.
What happens:
Requesting `http://user1@vmauth.example.com` returns the error `unsupported path requested: "/select/0/prometheus/federate/"`
What I expected:
VMAuth routes to `/select/0/prometheus/federate` as defined in the config file.
This PR removes the trailing slash in these cases and adds a test to confirm it.
Example VMAuth config:
```yaml
users:
- username: "user1"
password: "***"
url_prefix: "http://mycluster/select/0/prometheus/federate"
```

Remove trailing slash for URLPrefixes with specific path

---

lib/protoparser/opentsdb/parser.go
lib/protoparser/opentsdb/parser_test.go

For #1574,
I changed OpenTSDB put message parser to accept  some spaces between fields and at an end of a row as a deliminator.

lib/protoparser/opentsdb: accept multiple spaces between fields as a deliminator

---

app/vmctl/README.md
app/vmctl/flags.go

The purpose of update is to make README and flags description more
clear to the reader. Especially, show that vm-account-id flag is required
for clustered version of VM.

vmctl: update README and flags description

---

lib/storage/tag_filters.go
lib/storage/tag_filters_test.go

This pull request optimizes queries with `{__name__=~"name_1|...|name_N"}` filters. 
In a microservice, we may use different message queue systems similar to rabbitmq & kafka & pulsar, and their metrics have their own names. When I calculate the consumption success rate of all the message queue systems, I need to join all the metrics to query them, and it is most convenient to use such syntax.
```
1 - (sum(rate({__name__=~"infra_alimq_consumer_processing_errors_total|infra_kafka_consumer_processing_errors_total", service="$service", region=~"$region", venv=~"$venv"}))) / (sum(rate({__name__=~"infra_alimq_consumer_processing_duration_seconds_count|infra_kafka_consumer_processing_duration_seconds_count", service="$service", region=~"$region", venv=~"$venv"}))) or vector(1)
```
Yes, the …

lib/storage: optimize convert multiple values regexp filter to composite tag filter

---

lib/promscrape/discovery/ec2/api.go
lib/promscrape/discovery/ec2/instance.go

filters can be applied only for DescribeInstances requests, like prometheus does.
related issue https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1626

makes filters optional for ec2 api requests

---

app/vmalert/config/config.go
app/vmalert/config/config_test.go
app/vmalert/group.go

`omitempty` tag resulted into skipping this param on marshaling,
which was used as a checksum for groups configuration. Since on
config reload checksums are compared before applying changes,
any change to `interval` only didn't trigger config reload.
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1641

app/vmalert: remove unnecessary `omitempty` tag for `interval` param

---

app/vmselect/promql/exec.go
app/vmselect/promql/exec_test.go
app/vmselect/promql/timeseries.go

Updated sorting allows to get the order of series in result similar or equal
to what Prometheus returns.
The change is needed for compatibility reasons.

app/vmselect: make sorting for query result similar to Prometheus

---

app/vmselect/promql/aggr.go
app/vmselect/promql/exec_test.go
app/vmselect/promql/rollup.go
app/vmselect/promql/rollup_test.go
app/vmselect/promql/transform.go

The `quantile` func was previously calculated by https://github.com/valyala/histogram
package. The result of such calculation was always a real value corresponded to
requested quantile. While in Prometheus implementation interpolation is used.
Such difference may result into discrepency in output between Prometheus and
VictoriaMetrics.
This commit adds a Prometheus-like `quantile` function. It also used by other
functions which depend on it, such as `quantiles`, `quantile_over_time`, `median` etc.
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1625

app/vmselect: `quantile` func compatiblity with Prometheus

---

app/vmselect/promql/rollup.go

The removed fast path optimisations weren't consistent with
`quantile` function behaviour and results into discrepancy.
Specifically, results didn't match in cases when:
* 0 < phi > 1;
* values contain only one element.

app/vmselect: rm `quantile_over_time` fast-path optimisations

---

app/vmselect/promql/rollup.go

The change affects `count/stddev/stdvar_over_time` funcs and makes
them to return NaN instead of zero when there is no datapoints
in a time window.
This is needed for improving compatibility with Prometheus.

app/vmselect: return NaN instead of 0 for empty value sets

---

app/vmselect/promql/rollup.go

The fix will always return zero if received set of items consists of one
element only, which also means no deviation.

app/vmselect: always return zero for `stddev` func if there is only one value

---

app/vmselect/promql/rollup.go

Adjustment results into discrepancy between Prometheus and VM on time windows
smaller than scrape interval.

app/vmselect: disable time-window adjustment for `min/max_over_time`

---

app/vmselect/promql/exec_test.go
app/vmselect/promql/rollup_test.go

It appeared, that `testRowsEqual` NaN comparison was incorrect.
The fix caused some tests to fail. Please see the change and
tests updated.

app/vmselect: fix `testRowsEqual` func NaN checks

---

app/vmselect/promql/binary_op.go
app/vmselect/promql/exec_test.go

The fix makes the binary comparison func to check for NaNs
before executing the actual comparison. This prevents VM
to return values for non-existing samples for expressions
which contain bool comparisons. Please see added test
for example.
-----------------------
Please note, the added tests will work only with https://github.com/VictoriaMetrics/VictoriaMetrics/pull/1666 patch.

app/vmselect: fix binary comparison func

---

README.md
docs/README.md
docs/Single-server-VictoriaMetrics.md

The relative link won't work for github-docs website,
so we're changing it to absolute link.

docs: make link to logos zip absolute

---

dashboards/clusterbytenant.json
dashboards/victoriametrics.json
dashboards/vmagent.json

Template vars may contain regexp when `all` is selected (.*) or when multiple values are selected (foo|bar).
So they must be passed to regexp filters.

dashboards: consistently use regexp filters for template vars

---

docs/vmalert.md

Describe remoteWrite.url is used to persist rules and alerts state info,
and add an additional paragraph explaining the separation between
-remoteRead.url and -datasource.url.
Fixes #1810.

docs/vmalert.md: document vmalert url flags a bit more cleanly

---

lib/backup/actions/util.go
lib/backup/s3remote/s3.go

In my case, i'm using aliyun oss for s3 and it must be need to me use virtual-hosted style URL.
And this PR just add flag for change `sess.Config.WithS3ForcePathStyle(true)` to `sess.Config.WithS3ForcePathStyle(fs.S3ForcePathStyle)`.
Thanks any review.  
I had really try to use flag of S3ForcePathStyle and it's working for me. 
like:  
```shell
(app/vmbackup)
go run main.go ... -dst=s3://smt-vmbackup/20211110 -s3ForcePathStyle=false

Add flag of S3ForcePathStyle

---

lib/promscrape/scraper.go

If the promscrape.dropOriginalLabels flag is turned on, it will result in duplicate target crawling. This is because originalLabels is always nil. 
Thanks bentol for pointing this out. https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1664#issuecomment-940605503
result:
Related issues:  #1830

Fix duplicate crawl targets

---

app/vmalert/README.md
app/vmalert/main_test.go
app/vmalert/manager.go
app/vmalert/manager_test.go
app/vmalert/notifier/init.go

For a long time, notifier.Addr flag was required. The assumption was that vmalert will
be always used for alerting. However, practice shows that some users need only
recording rules. In this case, requirement of notifier.Addr is ambiguous.
The change verifies if loaded config contains recording or alerting rules and
if there are corresponding flags set. This is true for initial config load
and hot reload.

vmalert: make notifier.Addr optional

---

app/vmalert/main.go

Previously, vmalert would print an err message and set vmalert_config_last_reload_successful=0
only once during a hot reload of a bad config. Such behaviour may result into non noticed
event of a bad config reload attempt
Now, it continues to print error messages and keep vmalert_config_last_reload_successful state
until successful attempt will be made or config state will be rolled back to prev state.

vmalert: continue to print errors for bad config during hot reload

---

lib/backup/actions/restore.go
lib/backup/common/part.go

it should fix download restoration for backups.
When calculating parts diff, old key wasn't able to match srcParts, even if some part chunks was downloaded.

removes FileSize from backup part key

---

.github/workflows/check-licenses.yml
.github/workflows/main.yml
app/vmalert/README.md

The bump was required for `vmalert` package.
`vmalert` docs now also contain an updated description.

ci: bump go version to 1.17

---

app/vmalert/README.md
app/vmalert/alerting.go
app/vmalert/config/config.go
app/vmalert/config/config_test.go
app/vmalert/config/testdata/rules0-good.rules
app/vmalert/config/testdata/rules2-good.rules
app/vmalert/datasource/datasource.go
app/vmalert/datasource/init.go
app/vmalert/datasource/vm.go
app/vmalert/datasource/vm_graphite_api.go
app/vmalert/datasource/vm_prom_api.go
app/vmalert/datasource/vm_test.go
app/vmalert/group.go
app/vmalert/main.go
app/vmalert/manager.go
app/vmalert/recording.go
app/vmalert/web.qtpl
app/vmalert/web.qtpl.go
app/vmalert/web_types.go

The new group field `params` allows to configure custom HTTP URL params
per each group. These params will be applied to every request before
executing rule's expression. Hot config reload is also supported.
Field `extra_filter_labels` was deprecated in favour of `params` field.
vmalert will print deprecation log message if config file contains
the deprecated field.
`params` fields are supported by both Prometheus and Graphite datasource types.

vmalert: introduce additional HTTP URL params per-group configuration

---

app/vmalert/alerting.go
app/vmalert/alerting_test.go

Service labels like `alertname` or `alertgroup` were attached
after template expanding for `labels` section. Because of this,
labels `alertname` or `alertgroup` weren't available for templating
in `labels` section of alert's definition.
This commit changes the order of labels attaching and adds a test
for verifying these labels availability.
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1921

vmalert: update the order of service labels attaching

---

app/vmalert/datasource/vm_prom_api.go
app/vmalert/datasource/vm_test.go

When using `vmalert` with older Prometheus versions, the passed
`step=2m` may be parsed by Prometheus with an err: "cannot parse \"2m0s\" to a valid duration".
In order to improve compatibility vmalert will always convert step duration to seconds.
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1943

vmalert: always convert `step` value to seconds for better compatibility

---

app/vmalert/main.go

The purpose of `replay` mode is to backfill results of recording
or alerting rules. So `remoteWrite.url` should be required.
Otherwise, process can fail on attempt to send data.

vmalert: check if remoteWrite is configured for replay mode

---

.github/workflows/check-based-on-master.sh
.github/workflows/check-based-on-master.yml

This check will prevent merge commits that are not `git rebase`-d on the latest `master`. 
This check will not prevent squash commits, nor commits directly to master.

Add .github/workflows/check-based-on-master

---

app/vmselect/main.go

Grafana expects `data` in response to be a slice and logs an err
if it is not:
```
err="[]v1.ExemplarQueryResult: decode slice: expect [ or n, but found , error found in #0 byte of ...||..., bigger context ...||..."
```
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1999

vmselect: update /query_exemplars placeholder

---

.github/workflows/check-rebased.sh
.github/workflows/check-rebased.yml

Same as PR #1991, but taking into account that base branch is not necessarily `master`.
It will prevent merging in a branch that's not based on its base branch HEAD, leading to streamlined history.
Note it will not prevent squash commits, nor commits directly to base branch.
Also takes into account (prevents) intermediate merges from base into current branch -- let's see if we want it or not.

Add check-rebased Github action

---

app/vmctl/flags.go
app/vmctl/influx.go
app/vmctl/main.go
app/vmctl/opentsdb.go
app/vmctl/prometheus.go
app/vmctl/utils.go
app/vmctl/vm/vm.go

On import process interruption `vmctl` now prints the max and min timestamps of:
* last failed batch if import ended with error;
* last sent batch if import was cancelled by user.
To get more details for each timeseries in batch user needs to specify `--verbose` flag.
The change does not relate to `vm-native` mode, since `vmctl` has no control over
transferred data in this mode.
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1236

vmctl: improve logging during import cancels/errors

---

app/vmctl/README.md
app/vmctl/flags.go
app/vmctl/limiter/limiter.go
app/vmctl/limiter/writer.go
app/vmctl/main.go
app/vmctl/vm/vm.go
app/vmctl/vm_native.go

The new flag `vm-rate-limit` defines data transfer speed limit
in bytes per second. Rate limiting is not applied if flag is omitted.
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1405

vmctl: add option to rate limit data transfer speed

---

app/vmalert/group.go

vmalert has `vmalert_remotewrite_errors_total` metric but doesn't have `vmalert_remotewrite_total`
Current MR fixes it so now it's possible to generate error rate SLO for "remote_write"

add vmalert_remotewrite_total metric

---

lib/promscrape/discovery/dockerswarm/tasks.go
lib/promscrape/discovery/dockerswarm/tasks_test.go

See #2038 for details. Fixed `__address__` field name on line 124 and removed it from commonLabels to avoid overwriting.

Fix for #2038: Make correct __address__ value for dockerswarm promscrape

---

app/vmui/packages/vmui/src/components/Legend/Legend.tsx
app/vmui/packages/vmui/src/components/Legend/legend.css
app/vmui/packages/vmui/src/utils/uplot/series.ts
app/vmui/packages/vmui/src/utils/uplot/types.ts

Added the ability to copy label="value" when clicking on pairs in the legend ([task card](https://github.com/VictoriaMetrics/VictoriaMetrics/projects/2#card-64915508))

vmui: copy pairs on click in legend

---

Makefile

Update version of golangci-lint from v1.43.0 to v1.44.0 in Makefile.
See https://github.com/golangci/golangci-lint/releases/tag/v1.44.0 .

Update version of golangci-lint

---

app/vmalert/notifier/init.go

This would make addresses `http://localhost:9093` and `http://localhost:9093/`
both to result into `http://localhost:9093/api/v2/alerts`.

vmalert: remove trailing slash for static notifier addresses

---

docs/operator/api.MD

A small PR adding some missing links to the Kubernetes API docs for `v2beta2.MetricSpec` and `v2beta2.HorizontalPodAutoscalerBehavior` in the EmbeddedHPA API docs.

Added missing links in EmbeddedHPA API docs

---

lib/promscrape/discovery/gce/gce.go
lib/promscrape/discovery/gce/gce_test.go

Previously, `gce_sd_config` shows `zone` as `{}` instead of the content of the configuration, as shown in this test result before implementation:
```
--- FAIL: TestMarshallingSDConfigWithZoneYAML (0.00s)
[...]/VictoriaMetrics/lib/promscrape/discovery/gce/gce_test.go:25: unexpected marshal:
got 
project: test-project
zone: {}
want
project: test-project
zone:
- zone-a
- zone-b
FAIL
FAIL	github.com/VictoriaMetrics/VictoriaMetrics/lib/promscrape/discovery/gce	1.049s
FAIL
```
This pull requests implements `Marshaler` interface on `ZoneYAML` so zones may be displayed properly.

Show gce sdconfig zone on vmagent:8429/config

---

README.md
app/vmagent/README.md
app/vmauth/README.md
docs/Cluster-VictoriaMetrics.md
docs/README.md
docs/Single-server-VictoriaMetrics.md
docs/vmagent.md
docs/vmauth.md

The change adds `copy text` snippet to code examples
and replaces hostname placeholders with `0.0.0.0`.

docs: make profiling commands more copy-friendly

---

dashboards/victoriametrics.json

The new row Caches adds more visibility for cache utilization by VM.
It replaces the old `Cache size` panel.

dashboards: add row Caches to single node dasbhoard

---

deployment/docker/alerts.yml

Lowering threshold from 50% to 5% will be more sufficient
for discovering un-healthy system state.

alerts: lower the threshold for TooHighSlowInsertsRate

---

app/vmalert/README.md
docs/vmalert.md

This PR will add minimal supported version of AlertManager to vmalert README.md
See https://github.com/VictoriaMetrics/VictoriaMetrics/issues/2236

Added minimal supported version of AlertManager 

---

docs/FAQ.md

InfluxQL is an early (#49) and recurring (#1332) FAQ. It would be honest to clarify this, esp. given that VM does support the InfluxDB line protocol.

Clarify lack of support for InfluxQL

---

docs/CHANGELOG.md

Some of the releases could negatively affect performance for a limited
period of time due to some changes in core. Update details are meant to
warn users about expected changes in peformance after the update.

docs: add update details for some releases

---

lib/writeconcurrencylimiter/concurrencylimiter.go

I found this typo while reading through VictoriaMetrics's source code. I believe the intent to write "thrashing" here.
Awesome project. Cheers!

fix: change thrashing typo

---

lib/storage/index_db.go
lib/storage/index_db_test.go

Proposed fix for issue #2255 - positive empty-match filters (ex. {non_existing_tag_key=~"foobar|"}) should return samples that do not contain the non_existing_tag_key.

Fix for issue #2255 - matchTagFilters for positive empty-match filters

---

Makefile

This PR will update golangci-lint version to latest [v1.45.1](https://github.com/golangci/golangci-lint/tree/v1.45.1)

Update golangci version to latest v1.45.1

---

docs/url-examples.md

Without escaping the part wrapped with `<` `>` chars
won't be rendered properly.

docs: escape chars for /label/values endpoint

---

app/vmalert/README.md
docs/vmalert.md

The API handler was changed in 1.75 but docs
still contain the old address.
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/2366

docs: fix typo in vmalert's API

---

deployment/docker/Makefile

Updated alpine linux base image to the latest v3.15.3 which has fix for [CVE-2018-25032](https://security.alpinelinux.org/vuln/CVE-2018-25032).
See https://alpinelinux.org/posts/Alpine-3.12.11-3.13.9-3.14.5-3.15.3-released.html

Update alpine linux base image to the latest v3.15.3

---

app/vmalert/alerting.go
app/vmalert/alerting_test.go
app/vmalert/group_test.go
app/vmalert/main.go
app/vmalert/manager.go
app/vmalert/notifier/alert.go
app/vmalert/notifier/alert_test.go

To improve compatibility with Prometheus alerting the order of
templates processing has been changed.
Before, vmalert did all labels processing beforehand. It meant
all extra labels (such as `alertname`, `alertgroup` or rule labels)
were available in templating. All collisions were resolved in favour
of extra labels.
In Prometheus, only labels from the received metric are available in
templating, so no collisions are possible.
This change makes vmalert's behaviour similar to Prometheus.
For example, consider alerting rule which is triggered by time series
with `alertname` label. In vmalert, this label would be overridden
by alerting rule's name everywhere: for alert labels, for annotations, etc.
In Prometheus, it would be overridden for alert's labels only, but in annotations
the original …

vmalert: fix labels and annotations processing for alerts

---

app/vmalert/README.md
app/vmalert/notifier/alert.go
app/vmalert/notifier/alert_test.go
app/vmalert/notifier/alertmanager.go
app/vmalert/notifier/alertmanager_request.qtpl
app/vmalert/notifier/alertmanager_request.qtpl.go
app/vmalert/notifier/alertmanager_test.go
app/vmalert/notifier/config.go
app/vmalert/notifier/config_watcher.go
app/vmalert/notifier/init.go
app/vmalert/notifier/testdata/consul.good.yaml
app/vmalert/notifier/testdata/static.good.yaml

Before, relabeling for notifier configured via file was supported
only for target labels disocvered via SD.
WIth this change, specified relabeling config will be also applied
to labels of sent alerts.

vmalert: support relabeling for alert labels sent via notifier

---

lib/promscrape/config.go
lib/promscrape/scraper.go

it must improve user expirience and simplify clustering scrapers.
it must allow to use vmagent cluster with distroless images
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/2359

lib/promscrape: allows to use k8s pod name as clusterMemberNum

---

.github/dependabot.yml

The change disables versions autopupdate for vmui package.
The change has no impact on security updates, which have a separate,
internal limit of ten open pull requests.
See https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#open-pull-requests-limit

github/dependabot.yml: disable versions update for vmui

---

app/vmalert/Makefile
app/vmalert/README.md
app/vmalert/notifier/config.go
app/vmalert/notifier/config_test.go
app/vmalert/notifier/config_watcher.go
app/vmalert/notifier/init.go
app/vmalert/notifier/testdata/dns.good.yaml
app/vmalert/notifier/testdata/mixed.good.yaml
docs/vmalert.md

https://github.com/VictoriaMetrics/VictoriaMetrics/issues/2460
Config example:
```
dns_sd_configs:
- names:
- cloudflare.com
type: 'A'
port: 9093
relabel_configs:
- source_labels: [__meta_dns_name]
replacement: '${1}'
target_label: dns_name
```
Result in UI:

vmalert: add DNS service discovery

---

lib/promscrape/config.go

This change fixes incorrect marshalling for ScrapeConfig
it affects http endpoint and ScrapeConfig checksum.
With omitempty, custom Marshaller is not called if field is not a pointer.
Previously this issue happened at vmalert

lib/promscrape: removes omitempty for ScrapeConfig

---

.github/workflows/check-licenses.yml
.github/workflows/main.yml
.github/workflows/wiki.yml

Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Signed-off-by: naveensrinivasan <172697+naveensrinivasan@users.noreply.github.com>

chore: Set permissions for GitHub actions

---

lib/promscrape/config.go
lib/promscrape/discovery/kubernetes/api_watcher.go

replaces internStringsMap generic map with sync.Map - it greatly reduces lock contention
concurrently reload scrape work for api watcher - each object labels added by dedicated CPU
changes can be tested with following script https://gist.github.com/f41gh7/6f8f8d8719786aff1f18a85c23aebf70

lib/promscrape: reduce latency for k8s GetLabels

---

app/vmui/packages/vmui/src/utils/default-server-url.ts

Fixes double slash bug in queries:
`http://example.com/prometheus//api/v1/label/__name__/values`

vmui: fix default server path

---

app/vmctl/influx.go

Do not assume the db label to be the last one and also
make sure we are not skipping it and everything afterwards.
Breaking the loop would cause following labels to be empty.

app/vmctl: fix empty/skipped labels after db label

---

app/vmstorage/main.go

The switch suppose to allow setting `d`, `w`, `y` duration units.

vmstorage: switch to rich duration parser for flag `snapshotsMaxAge`

---

app/vmui/packages/vmui/src/state/common/reducer.ts
app/vmui/packages/vmui/src/utils/time.ts

Fixed:
- the selected relative time range is reset to the previous one on the graph when new query is entered.
- when clicking on Prometheus line during graph editing in Grafana, vmui doesn't show the graph until explicit click on the graph tab.
the issues mentioned [here](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/2402#issuecomment-1115817302) and [here](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/2402#issuecomment-1115830648)

vmui: prevent reset relative time

---

app/vmctl/flags.go
app/vmctl/influx.go
app/vmctl/main.go

Make it possible to migrate timeseries without changing labels
at all, including not adding the now optional 'db' label.

app/vmctl: add flag to skip adding the InfluxDB 'db' label

---

app/vmctl/flags.go
app/vmctl/influx.go
app/vmctl/main.go

Make it possible to migrate timeseries while restoring the
original timeseries name previously written from Prometheus
to InfluxDB v1 via remote_write.
Fixes: https://github.com/VictoriaMetrics/vmctl/issues/8

app/vmctl: add flag to handle Prometheus remote_write to InfluxDB

---

Makefile

This PR will update golangci-lint version to latest [v1.46.0](https://github.com/golangci/golangci-lint/tree/v1.46.0)

Update golangci version to latest v1.46.0

---

Makefile

This PR will update golangci-lint version to latest [v1.46.1](https://github.com/golangci/golangci-lint/releases/tag/v1.46.1)

Update golangci version to latest v1.46.1

---

app/vmalert/README.md
docs/PerTenantStatistic.md
docs/operator/quick-start.MD
docs/vmalert.md

For liquid text processor double braces `{{` `}}`
are special chars for templating.
Since we use them in some of our docs with different purpose,
we must escape them to avoid syntax errors from liquid.
For escaping curly braces we use bult-in plugin which helps
to enclose sections of text via `{% raw %}` and `{% endraw %}`.
This approach prevents liquid syntax errors and makes render correct.

docs: fix liquid syntax errors

---

app/vmagent/remotewrite/client.go
lib/awsapi/config.go
lib/promscrape/discovery/ec2/api.go

This adds the ability to utilize sigv4 signing for all AWS services not
just "aps". When the newly introduced property "service" is not set it
will default to "aps".
Some words about the reasoning behind this PR:
We are running VictoriaMetrics in an EKS cluster in AWS and would like to use API gateway for authentication. To sign requests for the API gateway the "service" needs to be "execute-api". However vmAgent hard codes it to be "aps.
this PR extends functionality added by #1287

Add ability to sign requests for all AWS services

---

app/vmalert/notifier/config_watcher.go

I tried to use `notifier.config` and found that in my case alert relabeling is not working.
`notifier.config`:
```
scheme: "http"
static_configs:
- targets: ["localhost:5555"]
alert_relabel_configs:
- action: "replace"
source_labels: ["__name__"]
regex: ".*"
target_label: "some_label"
replacement: "som_value"
```
It does not work because unlike for `consul_sd_configs` and `dns_sd_configs` for `static_configs` AlertManager initializes with `parsedRelabelConfigs` instead of `parsedAlertRelabelConfigs`.

Bug fix: use "parsedAlertRelabelConfigs" instead of "parsedRelabelConfigs" in AlertManager initialization

---

dashboards/victoriametrics.json

Using metric `vm_concurrent_queries` in relation to `vm_concurrent_select_capacity`
is incorrect. Switching to `vm_concurrent_select_current` in `Concurrent selects` panel.

dashboards: use `vm_concurrent_select_current` instead of `vm_concurrent_queries`

---

lib/storage/partition.go

Workers count for merges affects the max part size during merges. Such behaviour
protects storage from running out of disk space for scenario when all workers
are merging parts with the max size.
This works very well for most cases. But for systems where high number of CPUs
is allocated for vmstorage components this could significantly impact the max
part size and result in more unmerged parts than expected.
While checking multiple production highly loaded setups it was discovered that
`max_over_time(vm_active_merges{type="storage/big}[1h]}"` rarely exceeds 2,
and `max_over_time(vm_active_merges{type="storage/small}[1h]}"` rarely exceeds 4.
The change in this commit limits the max value for concurrency accordingly.

lib/storage: limit max mergeConcurrency value for systems with high number of CPUs

---

app/vmalert/remotewrite/remotewrite.go
app/vmalert/remotewrite/remotewrite_test.go

When vmalert does remote-write, the content is compressed with snappy, but the header does not explicitly state this.
I suggest adding Content-Encoding Header to remote-write requests to support proper decoding in server implementation.
References: 
* https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Encoding
* https://datatracker.ietf.org/doc/html/rfc2616#section-14.11

Add Content-Encoding Header to remote-write request

---

lib/promscrape/scraper.go

The change updates histogram for registering SD update duration
only SD is considered as `active`. SD is active if at least
one scraper for this SD has started.
This change supposed to reduce metrics cardinality produced
by duration histogram which gets updated even if SD isn't configured.
See https://github.com/VictoriaMetrics/VictoriaMetrics/issues/2671

vmagent: update SD duration histogram metric if SD is active

---

app/vmalert/remotewrite/remotewrite.go
app/vmalert/remotewrite/remotewrite_test.go

* Add `Content-Type` header to vmalert's remote-write request
* Add `X-Prometheus-Remote-Write-Version` to vmalert's remote-write request
* (Out of scope) `User-Agent` would be out of the scope because adding this would require discussion of what information to include in the User-Agent, and the function input could be changed.
Ref:
* https://github.com/VictoriaMetrics/VictoriaMetrics/issues/2686
* https://github.com/VictoriaMetrics/VictoriaMetrics/pull/2685
* https://github1s.com/prometheus/prometheus/blob/HEAD/storage/remote/client.go#L198-L201

Add headers compliant with Prometheus's remote-write format

---

dashboards/victoriametrics.json

The change adds 6 extra panels, 2 panels per each component.
Panel 1 shows the total CPU usage by the component (summary of all instances).
Panel 2 shows the total CPU usage % by the component (summary of all instances).
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/2696

dashboards: add cpu usage panels per each component type

---

deployment/docker/alerts.yml

{level!="info"} - can lead to some unnecessary spam in case of slow queries.
{level="error"} - will alert only on  "error"

Changed the level type in alerts.yml for TooManyLogs alert

---

lib/mergeset/part_header.go

https://github.com/VictoriaMetrics/VictoriaMetrics/issues/2757

bugfix: assignment blocksCount  before the comparison in part_header.go

---

docs/url-examples.md

Adds verbose flag and description for curl that will return output status code `HTTP/1.1 204 No Content`. It should help users to understand what expect while they delete metrics.

url-examples: added curl output after deleting metrics

---

app/vmselect/netstorage/netstorage.go
docs/CHANGELOG.md

Metrics `vm_partial_results_total` and `vm_requests_total` serving
the similar purpose, but contain inconsistent set of labels.
This change updates `vm_partial_results_total` labels to be consistent
with `vm_requests_total`.
The change breaks backward compatibility with assumption that
`vm_partial_results_total` wasn't widely used, since it is
not documented and absent in the alerts and dashboards.

vmselect: make `vm_partial_results_total` consistent

---

app/vmalert/tpl/footer.qtpl
app/vmalert/tpl/footer.qtpl.go
app/vmalert/tpl/header.qtpl
app/vmalert/tpl/header.qtpl.go

Using relative path breaks assets loading on alert view page.

vmalert: use absolute path for assets

---

lib/promscrape/scraper.go

I faced the issue with vmagent -promscrape.configCheckInterval option - its not working, at least with scrape_configs config part - any changes at relabel_configs or job addition\removal not loaded into runtime config, but in log i see messages that config was updated successfully
i tested locally and this fix works for me, now config really updates
commit that brings this bug cbfc7b7c924c5ebfa28fa1ffaa368b74cc105618
vmagent working version v1.68.0, broken since v1.69.0

lib/promscrape: fix vmagent tickerCh reload behaviour

---

app/vmalert/README.md
app/vmalert/main.go
app/vmalert/main_test.go
app/vmalert/tpl/footer.qtpl
app/vmalert/tpl/footer.qtpl.go
app/vmalert/tpl/header.qtpl
app/vmalert/tpl/header.qtpl.go
app/vmalert/utils/links.go
app/vmalert/web.go
app/vmalert/web.qtpl
app/vmalert/web.qtpl.go
app/vmalert/web_test.go
app/vmalert/web_types.go
docs/CHANGELOG.md
docs/vmalert.md

Deprecate alert's status link `/api/v1/<groupID>/<alertID>/status` in favour of
`api/v1/alerts?group_id=<group_id>&alert_id=<alert_id>"`.
The change was needed for simplifying logic in vmselect for proxying vmalert's requests.
The old alert's status link will be still supported for a few versions but will be removed in the future.
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/2825

vmalert: deprecate alert's status link

---

app/vmui/packages/vmui/src/api/query-range.ts

Update query for ```JSON``` and ```Table``` tabs. This fix will use instant query like it described in
https://prometheus.io/docs/prometheus/latest/querying/api/#instant-queries
Related issue:
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/2781

vmui: fix query for json and table tabs

---

app/vmselect/main.go

* remove trailing `/` from requests
* redirect to vmalert's home page when `/vmalert` is requested.

vmselect: cover special cases for vmalert's routing in cluster version

---

app/vmalert/web.go
app/vmalert/web_test.go
app/vmselect/main.go

* remove trailing `/` from requests
* redirect to vmalert's home page when `/vmalert` is requested.

vmselect: cover special cases for vmalert's routing in single-node version

---

deployment/docker/docker-compose.yml

See https://grafana.com/blog/2022/06/14/grafana-9.0-release-oss-and-cloud-features

deployment/docker/docker-compose.yml: update Grafana from v8.5.1 to v9.0.2 for VictoriaMetrics Single 

---

deployment/docker/docker-compose.yml

See https://grafana.com/blog/2022/06/14/grafana-9.0-release-oss-and-cloud-features

deployment/docker/docker-compose.yml: update Grafana from v8.5.1 to v9.0.2 for VictoriaMetrics Cluster 

---

app/vmselect/promql/rollup.go

The change allows to specify default value for `getScrapeInterval`
function when actual interval can't be calculated.
Before the change, function were returning `maxSilenceInterval` (5m)
in such cases, which may be not correct for instant queries processing.
The specific scenario where using `maxSilenceInterval` caused issues
is the following:
1. Series becomes stale;
2. Client (in this case vmalert) continues to request series every 15s;
3. Database returns empty results as expected;
4. But at some specific moment of time database returns datapoints from `now()-5m`,
because lookback window was extended to `maxSilenceInterval`.

promql: return `step` as scrapeInterval when it can't be calculated

---

lib/mergeset/merge.go

There was a linter error
```receiver name bh should be consistent with previous receiver name h for bsrHeap```
Made consistent recievers names

lib/mergeset: fix linter error

---

lib/mergeset/encoding.go

I modify a little code in method Less of inmemoryBlock. In this method, I guess Valialkin want to optimize the comparison between items with suffix, but it does not work. So I modify it and make it work now, please review, thanks.

fix inmemoryBlock's Less method

---

app/vmagent/remotewrite/client.go
dashboards/vmagent.json
deployment/docker/alerts.yml

The new metric `vmagent_remotewrite_queues` exports a static value of
number of configured remote write queus. This metric is useful to
calculate total saturation per each configured URL with given number
of queues. See corresponding changes to vmagent alerts and dashboard.

vmagent: expose metric `vmagent_remotewrite_queues`

---

Makefile

See https://github.com/golangci/golangci-lint/releases/tag/v1.47.1

Update golangci-lint version to latest v1.47.1

---

app/vmselect/promql/transform.go

if all timeseries value equal zero in [here](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/cluster/app/vmselect/promql/transform.go#L543) and xspre can not match inf in [here](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/cluster/app/vmselect/promql/transform.go#L567), 
this code will panic.

vmselect: fix vmrangeBucketsToLE func may panic when ts value equal zero

---

Makefile
deployment/docker/Makefile

`docker-scan` based on native `docker scan` functionality that use snyk.io, see https://docs.docker.com/engine/scan/
`docker-scan` will start after user run `make publish-release` and will call to build `BASE_IMAGE`  that will be scanned for vulnerabilities. If vulnerabilities are found, the release process will be terminated.

deployment/docker/Makefile: added docker-scan

---

README.md
docs/README.md
docs/Single-server-VictoriaMetrics.md

In 3 different README.md files there is a typo which have to be fixed:
"HA **paris**" to "HA **pairs**"

Docs:  Fix typo from "HA paris" to "HA pairs"

---

lib/auth/auth.go
lib/auth/auth_test.go

Implement test for NewToken function which parse token string and return token object.
There was a problem with type convertion
```golang
accountID, err := strconv.Atoi(tmp[0])
token.AccountID = uint32(accountID)
```
in that situation when we parse value as `int` and convert it to `uint32` value like `4294967297` will be converted to `1` so it would be incorrect behavior of the function

lib/auth: add tests for NewToken function

---

.github/workflows/check-licenses.yml
.github/workflows/main.yml

Some new dependencies contain generics, so we bump go version for CI.
--------------------
See https://github.com/VictoriaMetrics/VictoriaMetrics/runs/7720327151?check_suite_focus=true

workflows: bump go version

---

app/vmalert/README.md
app/vmalert/alerting.go
app/vmalert/datasource/init.go
app/vmalert/remoteread/init.go
docs/vmalert.md

vmalert can be successfully used with datasources
compatible with Prometheus HTTP API. So we remove comments or
notes in Readme which are saying opposite.

vmalert: remove notions of vmalert being compatible with VM only

---

lib/promrelabel/config_test.go

follow-up after 68c4ec9472bba3011c7f70a526a4ae6d99410be5

lib/promrelabel: fix expected test result

---

app/vmalert/web.go

Sorting will produce deterministic output
of grops on the page.

vmalert: sort groups at `/alerts` page

---

docs/CHANGELOG.md
lib/storage/partition.go

Returning nil error when storage is in RO mode results
into excessive loops and function calls which could
result into CPU exhaustion. Returning an err instead
will trigger delays in the for loop and save some resources.
-------------------------
CPU pprof results from node potentially affected by this:
```
ROUTINE ======================== github.com/VictoriaMetrics/VictoriaMetrics/lib/storage.(*partition).partsMerger in github.com/VictoriaMetrics/VictoriaMetrics/lib/storage/partition.go
57.33s     97.91s (flat, cum) 93.44% of Total
.          .    941:func (pt *partition) partsMerger(mergerFunc func(isFinal bool) error) error {
.       70ms    946:   for {
40.88s     76.52s    947:           err := mergerFunc(isFinal)
580ms      640ms …
```

lib/storage: prevent excessive loops when storage is in RO

---

app/vmalert/datasource/init.go
app/vmalert/main.go
app/vmalert/remoteread/init.go
app/vmalert/remotewrite/init.go

Other components, such as `vmagent`, mark these flags as sensitive and
hide them from the `/metrics` endpoint by default. This commit adds
similar handling to the `vmalert` component, hiding them by default, to
prevent logging of secrets inappropriately.
Showing of these values is controlled by an additional flag.
Follow up to https://github.com/VictoriaMetrics/VictoriaMetrics/pull/2947

vmalert: mark some url flags as sensitive

---

app/vmselect/main.go
app/vmselect/prometheus/prometheus.go
app/vmselect/promql/eval.go
app/vmselect/promql/exec.go

vmselect: introduce UserReadableError type of error
When read query fails, VM returns rich error message with
all the details. While these details might be useful
for debugging specific cases, they're usually too verbose 
for users. 
Introducing a new error type `UserReadableError` is supposed
to allow to return to user only the most important parts
of the error trace. This supposed to improve error readability
in web interfaces such as VMUI or Grafana.
The full error trace is still logged with the full context
and can be found in vmselect logs.
----------------------
**Examples**
The following error:
```
error when executing query="(node_filesystem_avail_bytes * 100) / node_filesystem_size_bytes < 10 and ON (instance, device, …
```

vmselect: simplify errors returned to user for instant and range handlers

---

deployment/docker/docker-compose.yml

see more at https://grafana.com/blog/2022/08/16/grafana-9.1-release/

deployment/docker-compose.yml: bump Grafana version to latest 9.1.0

---

lib/storage/partition.go

The change is based on the feedback from users on github.
Thier examples show, that limit of 8 sometimes become a
bottleneck. Users report that without limit concurrency
can climb up to 15-20 merges at once.
See https://github.com/VictoriaMetrics/VictoriaMetrics/pull/2673#issuecomment-1218185978

lib/storage: bump max merge concurrency for small parts to 15

---

app/victoria-metrics/main_test.go

Signed-off-by: Cosrider <cosrider7@gmail.com>
io/ioutil ReadFile 
// Deprecated: As of Go 1.16, this function simply calls os.ReadFile.
VictoriaMetrics is currently using go 1.17.

app/victoria-metrics: replace ioutil package with os package

---

app/vmagent/opentsdbhttp/request_handler.go

Let opentsdb http insert request support tenantId:projectId specified in the url like:
`http://vmagent:4242/insert/1000/opentsdb/api/put`
Without the change, the request always writes data into tenant 0 instead of 1000.

[vmagent] make opentsdb insert url support multitenant

---

app/vmctl/influx.go
app/vmctl/opentsdb.go
app/vmctl/prometheus.go
app/vmctl/vm_native.go

Fix `vmctl` breaking terminal in case of exit due to an error

vmctl: fix progress bar not being stopped on error during import process

---

app/vmselect/promql/exec_test.go
app/vmselect/promql/transform.go
docs/CHANGELOG.md
docs/MetricsQL.md

Fixed panic if user defines incorrect param for `histogram_quantiles` function. 
It can happens if second param would be not a number from range [0..1]. 
Related issue: https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3026

vmselect/promql: fix panic in histogram_quantiles function

---

lib/promscrape/config.go

Some tools generate `ServiceMonitor` resources with uppercase "HTTP" and "HTTPS" schemes. Victoria can and should support those monitors.

Support "HTTP" and "HTTPS" schemes

---

deployment/docker/Makefile

bump version of Alpine linux to latest 3.16.2
see https://alpinelinux.org/posts/Alpine-3.13.12-3.14.8-3.15.6-3.16.2-released.html

deployment/docker/Makefile: bump version of Alpine linux to latest 3.16.2

---

deployment/docker/Makefile

VictoriaMetrics Cluster: bump version of Alpine linux to latest 3.16.2
see https://alpinelinux.org/posts/Alpine-3.13.12-3.14.8-3.15.6-3.16.2-released.html

cluster: deployment/docker/Makefile: bump version of Alpine linux to latest 3.16.2

---

app/vmselect/prometheus/prometheus.go

when call the prometheus/api/v1/label/\_\_name\_\_/values very, very many times when vmstorage -retentionPeriod is long time to set，when query time  not specified,start defalut is 0 very bad ，so modify default start values

api  prometheus/api/v1/label/__name__/values default start time let vmstorage cpu will be very high

---

app/vmselect/prometheus/prometheus.go
app/vmselect/promql/eval.go

Updated error messages when user is using flags like `-search.maxPointsPerTimeseries` and `-search.maxPointsSubqueryPerTimeseries`.
User will be able to see which flag must be updated.
Related issue: https://github.com/VictoriaMetrics/VictoriaMetrics/issues/2922#issuecomment-1230518416

vmselect/{promql, prometheus}: show flag names which user can update in error message

---

app/vminsert/main.go
app/vmselect/main.go

If user defines equal addresses in `-storageNode` flag vminsert or vmselect will show error.
Related issue: https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3076

app/{vmselect, vminsert}: fails with error when user defines equal addresses in the `-storageNodes` flag

---

deployment/docker/README.md
deployment/docker/docker-compose.yml

When run `docker-compose up -d` **vminsert** will run on random generated port in OS and it can't be reached from curl/etc - see the screenshot below:
This PR will fix this issue.

deployment/docker/docker-compose: expose port for vminsert

---

.github/workflows/check-licenses.yml
.github/workflows/main.yml
Makefile
README.md
app/vmagent/README.md
app/vmalert/README.md
app/vmauth/README.md
app/vmbackup/README.md
app/vmctl/README.md
app/vmrestore/README.md
docs/vmagent.md
docs/vmalert.md
docs/vmauth.md
docs/vmbackup.md
docs/vmctl.md
docs/vmrestore.md
go.mod

The reason is to cover vulnerability GO-2022-0969
Found in: net/http@go1.18.5
Fixed in: net/http@go1.19.1
More info: https://pkg.go.dev/vuln/GO-2022-0969

bump Go version to 1.19.1

---

app/vmctl/README.md
docs/vmctl.md

In the documentation there is no mentions about `influx-skip-database-label`. Added it in the place where user can have questions

app/vmctl: add description about `influx-skip-database-label` flag

---

app/vmalert/alerting.go
app/vmalert/datasource/datasource.go
app/vmalert/datasource/vm.go
app/vmalert/datasource/vm_test.go
app/vmalert/helpers_test.go
app/vmalert/recording.go
app/vmalert/rule.go
app/vmalert/tpl/header.qtpl
app/vmalert/tpl/header.qtpl.go
app/vmalert/utils.go
app/vmalert/utils_test.go
app/vmalert/web.qtpl
app/vmalert/web.qtpl.go

The change adds an example of `curl` command to the Rule's page. The command is generated for each recorded state. It is supposed user can just copy&execute the command to see what was returned to vmalert.
----------------------------

vmalert: print example of `curl` command for rule's state

---

app/vmalert/alerting.go
docs/CHANGELOG.md

Previously, Annotations were evaluated only:
1. On alert creating.
2. On alert's value change.
This is premature optimization. It was assumed that since annotations could contain only text with alert's labels or value - there is no need in spending resources to re-compile Annotations.
Later, template function `query` was added, which can execute arbitrary queries and return different results on every evaluation. So if it was used in annotations, it would be executed only on init or value change.
Another case when optimization caused an issue - annotations hot reload. In this case, annotations of the active alert won't change even if Rule's annotations were changed.
This fix enables Annotations re-evaluation on each iteration to resolve issues above. It would have some impact on …

vmalert: always re-evaluate Annotations

---

dashboards/victoriametrics-cluster.json
dashboards/victoriametrics.json
dashboards/vmagent.json
dashboards/vmalert.json

dashboards/vmalert: 
* apply consistent formatting across panels;
* adapt resource usage panels for multiple selected jobs/instances;
* show vmalert version in Stats section.
dashboards/vmagent: 
* apply consistent formatting across panels;
* add panels for showing number of samples ingested
or scraped;
* adapt resource usage panels for multiple selected jobs/instances;
* add adhoc variable;
* display vmagent's version in Stats.
dashboards/single:
* apply consistent formatting across panels;
* add extra panels to Performance for displaying
`vm_rows_read_per_query`, `vm_rows_scanned_per_query`,
`vm_rows_read_per_series` and `vm_series_read_per_query` metrics.
dashboards/cluster:
* apply consistent formatting across panels;
* make resource usage panels per component more detailed;
* add …

Dashboards

---

app/vmalert/config/config.go

Now vmalert will print the following messages on duplciates:
```
"recording rule \"record\"; expr: \"up == 1\"; labels: summary={{ value|query }}" is a duplicate within the group "test"
"alerting rule \"alert\"; expr: \"up == 1\"; labels: description={{ value|query }}" is a duplicate within the group "test"
```
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3127

vmalert: prodvide more details on duplicates

---

deployment/docker/docker-compose-cluster.yml
deployment/docker/docker-compose.yml

This PR will remove tag `latest` and set `v1.81.2` tag version in docker-compose files for VictoriaMetrics Single node and Cluster version.

Adds version tag for docker containers

---

deployment/docker/docker-compose-cluster.yml

Cluster components always have `-cluster` suffix. The change fixes incorrect image tag in docker-compose manifest.

deployment/docker: fix image versions for cluster components

---

app/vmalert/datasource/init.go
docs/CHANGELOG.md

Change default value for command-line flag `datasource.queryStep` from `0s` to `5m`. Param `step` is added by vmalert to every rule evaluation request sent to datasource. Before this change, `step` was equal to group's evaluation interval by default. Param `step` for instant queries defines how far VM can look back for the last written data point. The change supposed to improve reliability of the rules evaluation when evaluation interval is lower than scraping interval.

vmalert: set default value for `datasource.queryStep` to `5m`

---

dashboards/victoriametrics-cluster.json
dashboards/victoriametrics.json

Panel `Index size` showed itself impractical for users. So replcaing it with `Active series` panel.
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/776#issuecomment-1255823734

dashboards: replace `Index size` panel with `Active series`

---

app/vmselect/promql/rollup.go
app/vmselect/promql/rollup_test.go

The workaround was introduced to fix https://github.com/VictoriaMetrics/VictoriaMetrics/issues/962. However, it didn't prove itself useful. Instead, it is recommended using `increase_pure` function.
Removing the workaround makes VM to produce accurate results when calculating `delta` or `increase` functions over slow-changing counters with vary intervals between data points.

vmselect/rollup: rm workaround for slow-changing counters

---

lib/backup/gcsremote/gcs.go

Addresses #3147 
Configures GCS retry policy.
AWS SDK uses default retryer configuretion if there is no custom one defined according to [documentation](https://pkg.go.dev/github.com/aws/aws-sdk-go/aws#Config), so is not needed to customize configuration there.

vmbackup: configure retries for GCS remote FS

---

app/vmalert/alerting.go
app/vmalert/alerting_test.go
app/vmalert/config/testdata/rules/rules2-good.rules

According to Ruler specification, only labels returned within time series should be available for use in annotations.
For long time, vmalert didn't respect this rule. And in PR https://github.com/VictoriaMetrics/VictoriaMetrics/pull/2403 this was fixed for the sake of compatibility. However, this resulted into users confusion, as they expected all configured and extra labels to be available - https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3013
This fix allows to use extra labels in Annotations. But in the case of conflicts the original labels (extracted from time series) are preferred.

vmalert: allow using extra labels in annotations

---

app/vmselect/promql/exec_test.go
app/vmselect/promql/transform.go
docs/CHANGELOG.md

VictoriaMetrics doesn't return empty series (with all NaN values) to the user. But such series are filtered after transform functions. It means `limit_offset` will account for empty series as well.
For example, let's consider following data set:
```
time series:
foo{label="1"} NaN, NaN, NaN, NaN // empty series
foo{label="2"} 1, 2, 3, 4
foo{label="3"} 4, 3, 2, 1
```
When user requests all series for metric `foo` the empty series will be filtered out:
```
/query=foo:
foo{label="v2"} 1, 2, 3, 4
foo{label="v3"} 4, 3, 2, 1
```
But `limit_offset(1, 1, foo)` is applied to original series, not filtered yet. So it will return `foo{label="v2"}` (skips the first in list)
```
/query=limit_offset(1, 1, foo):
foo{label="v2"} 1, 2, 3, 4
```
Expected result would be to apply `limit_offset` to already …

app/vmselect: ignore empty series for `limit_offset`

---

docs/vmagent.md

docs/vmagent.md: fix typo

---

lib/backup/s3remote/s3.go

Changes error checking to fix support of alternative S3 providers (tested with Minio)
404 error returned by Minio is wrapped into generic `smithy.OperatonError` instead of AWS `types.NoSuchKey`
The only way to check for this specific error is to check error message.
Since this error message is also present in default AWS message this PR changes validation to only check error message to unify error checking.

lib/backup/s3remote: fix error checking for alternative S3 providers

---

.gitignore
Makefile

The stored backups would help to identify docs corruption but aren't needed for commiting. So `.tmp` backup files are also git-ignored.

docs: when modifying docs in place allow storing backups

---

docs/guides/guide-vmcluster-multiple-retention-setup.md

While reading through the docs the implementation details had different formatting for storageNode. This standardizes them and adds a link to the retention docs.

Multi retention standardization of docs

---

lib/backup/s3remote/s3.go

it should fix an error with region detection for bucket, if AWS_REGION env var is not set
```
VictoriaMetrics/app/vmbackupmanager/main.go:101 cannot create originFS: cannot initialize connection to s3: cannot determine region for bucket "qa-vmstorage-backups": operation error S3: HeadBucket, failed to resolve service endpoint, an AWS region is required, but was not found
```

lib/backup: set s3 default region to us-west-2

---

app/vmselect/promql/transform.go

With v1.81.2-cluster
If two target have the same `le` value but different string, like this:
target_01: `test_metric{le="1"}` and `test_metric{le="5"}`
target_02: `test_metric{le="1.0"}` and `test_metric{le="5.0"}`
It will not properly calculate `histogram_quantile(0.95, sum(rate(test_metric)) by (le))`.
ql1: `sum(rate(test_metric)) by (target_name, le)`
```json
{
"status": "success",
"isPartial": false,
"data": {
"resultType": "vector",
"result": [
{
"metric": {
"target_name": "target_01",
"le": "1"
},
"value": [
1665523482,
"10.103333333333333"
]
},
{
"metric": {
"target_name": "target_01",
"le": "5"
},
"value": [
1665523482,
"10.103333333333335"
]
},
{
"metric": {
"target_name": "target_01",
"le": "0.1"
},
"value": [
1665523482,
"10.103333333333335"
]
},
{
"metric": {
"target_name": …
```

BUGFIX: properly calculate histogram_quantile with the same value and different string le

---

docs/guides/k8s-monitoring-via-vm-cluster.md

Fix will remove not needed extra spaces in helm command.

k8s-monitoring-via-vm-cluster.md: removed extra spaces

---

app/vmalert/remotewrite/remotewrite.go
docs/CHANGELOG.md

The message about dropped data still remains at `error` level. The change supposed to make log message more clear about how serious it is.

vmalert: lower severity level for RW retries

---

app/vmalert/README.md
app/vmalert/main.go
app/vmalert/main_test.go
docs/CHANGELOG.md
docs/vmalert.md

Escape query params when `external.alert.source` is used
Related issue: https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3139

vmalert: escape query params if external alert source defined

---

.github/workflows/codeql-analysis.yml

This PR adds to setup specific Go version and should fix [failed builds](https://github.com/VictoriaMetrics/VictoriaMetrics/actions/runs/3329416205/jobs/5506603245) 
see https://github.com/github/codeql-action/issues/1059

.github/workflows/codeql-analysis.yml: specifically setting the Go version

---

deployment/docker/docker-compose-cluster.yml
deployment/docker/docker-compose.yml

This PR will update version of VictoriaMetrics components in docker-compose files for Cluster and Single node

docker-compose: bump version of container tags for VictoriaMetrics components

---

README.md
docs/README.md
docs/Single-server-VictoriaMetrics.md

It slightly clarified information about the `api/v1/admin/tsdb/delete_series` API. I have added a description that this API doesn't support query range params like `start` and `end`. And if the user will use it all the time series will be deleted.

docs: clarify information about usage of the `api/v1/admin/tsdb/delete_series` API

---

app/vmctl/main.go

The change disables initing the `-version` flag in new `urfave/cli/v2` update. The `-version` flag conflicts with the identical flag from `lib/buildinfo` and causes panic.
See https://github.com/VictoriaMetrics/VictoriaMetrics/pull/3299

vmctl: fix panic on start

---

README.md
app/vminsert/main.go
app/vmselect/main.go
docs/Cluster-VictoriaMetrics.md

Current doc uses strong "must" which confuses users. Also, there is no explanation why this value "must" be used.
Rephrased to use weaker phrase and added explanation for value advised by default.

docs/{vminsert,vmselect}: clarify flag description for `clusternativeListenAddr`

---

lib/storage/storage.go
lib/storage/storage_test.go

This is to fix https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3309
It might happen that `updateCurrHourMetricIDs` stores metric from previous hour (previous day) in `s.currHourMetricIDs`. This happens when `s.pendingHourEntries` has any entries on the first run in the hour. This (as described in the issue) may have catastrophic consequences on per-day index creation.
This change splits `s.pendingHourEntries` into two sets - one for odd hours, one for even (since we only need two for buckets when hour changes). Then, in case of `s.currHourMetricIDs` rotation, it adds entries from `(hour-1)%2` bucket to `s.prevHourMetricIDs` and entries from `hour%2` bucket to new `s.currHourMetricIDs`. Under all other cases it works the same.
One more change is to parametrise …

Fix issue-3309 - currHourMetricIDs shouldn't contain metrics from prev hour

---

app/vmui/packages/vmui/src/components/Legend/Legend.tsx

Closes #3289
Changes graph label legend format from `label:value` to `label="value"`

vmui: change graph legend label format

---

app/vmui/packages/vmui/src/components/CustomPanel/CustomPanel.tsx

Closes #2814
Shows query tracing in json view, if enabled.

vmui: show tracing in json view

---

lib/protoparser/opentsdb/parser.go
lib/protoparser/opentsdb/parser_test.go

According to http://opentsdb.net/docs/build/html/api_telnet/put.html "At least one tag pair must be present".
However, in VictoriaMetrics datamodel tags aren't required. This could be confusing for users. Allowing accept lines without tags seems to do no harm.
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3290

protoparser/opentsdb: allow lines without tags

---

app/vmui/packages/vmui/src/components/Views/TableView/TableView.tsx
app/vmui/packages/vmui/src/styles/components/table.scss
app/vmui/packages/vmui/src/utils/metric.ts

Closes #3241
Adds support for a compact table view showing labels in a single cell instead of split by columns.

vmui: add compact table view

---

app/vmagent/remotewrite/remotewrite.go
deployment/docker/alerts-vmagent.yml
docs/CHANGELOG.md
lib/promscrape/scraper.go

Expose `vm_relabel_config_*` and `vm_promscrape_config_*` metrics for tracking relabel and scrape configuration hot-reloads.
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3345

vmagent: expose metrics for tracking config state

---

dashboards/victoriametrics-cluster.json
deployment/docker/alerts-cluster.yml

The purpose of the update is to make the dash more usable for large installations with many instances. Panels which showed metrics per-instance (Mem, CPU) now are showing metrics per-job or min/max/avg aggregations in % instead. This supposed to help immediately to identify resource shortage and remain usable for small and big installations.
For cases when detailed info is needed, to the bottom of the dashboard a new row `Drilldown` was added. Panels like Mem or CPU now contain a `data-link` named `Drilldown` (cis shown on line click) which takes user to more detailed panel.
The change list is the following:
* bump Grafana version to 9.1.0;
* replace old "Graph" panel with "TimeSeries" panel;
* improve Uptime panel to show number of instances per job;
* show % usage of Mem and CPU instead …

dashboards: cluster dashboard update

---

dashboards/clusterbytenant.json
dashboards/operator.json
dashboards/victoriametrics-cluster.json
dashboards/victoriametrics.json

* some unexpected DS UIDs were removed;
* remove predefined datasource for `clusterbytenant` in favour of datasource variable `ds`.

dashboards: cleanup & remove artifacts

---

app/vmagent/main.go
app/vmagent/pushgateway/request_handler.go

An initial implementation of the pushgateway protocol to vmagent.
The pushgateway protocol supports a few more things that are not covered in this PR (like adding [base64 label values](https://github.com/prometheus/pushgateway#url)) but this implementation adds the most basic features.
Maybe solves https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1415?
It adds a new endpoint to `vmagent` (`/api/v1/pushgateway`) where prometheus time series can be posted following the [URL format](https://github.com/prometheus/pushgateway#url) of pushgateway.
Didn't expand the docs as I'm unsure this will be merged (I decided to give it a try nonetheless 😅 ), but I'll be happy to include this in the docs if you think there's a chance this will be merged.
Tested with the example provided in the …

Adding pushgateway basic capabilities to vmagent

---

dashboards/victoriametrics-cluster.json

The change list is the following:
* bump Grafana version to 9.2.6;
* remove artifacts in data links.

dashboards: update VM cluster dash

---

dashboards/vmagent.json

The change list is the following:
* bump Grafana version to 9.2.6;
* add version change annotations;
* switch to per-job panels instead of per-instance;
* add drilldown option for resource usage panels.
---------------
See on playground https://play-grafana.victoriametrics.com/d/G7Z9GzMGz2

dashboards: update vmagent dash

---

dashboards/victoriametrics.json
deployment/docker/alerts.yml

The change list is the following:
* bump Grafana version to 9.2.6;
* replace old "Graph" panel with "TimeSeries" panel;
* show % usage of Mem and CPU additionally to of absolute values;
* `Caches` row was removed. All needed info for caches is now part of `Troubleshooting`;
* add Annotations for Alert triggers. Not all alerts are supposed to be displayed on the dashboard, but only those with label `show_at: dashboard`. See `alerts.yml` change.

dashboards: update VM single dash

---

app/vmalert/group.go
docs/CHANGELOG.md

See https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3418

vmalert: properly pass headers during the restore procedure

---

dashboards/victoriametrics-cluster.json

Fixes a missing `&` char in data link for ETA panel on cluster dashboards. Without `&` char it generates wrong link when click on Drilldown menu.

dashboards: fix typo in data link

---

app/vmalert/datasource/vm_prom_api.go
app/vmalert/datasource/vm_test.go
docs/CHANGELOG.md

The recent change in modifying default value
of `datasource.queryStep` flag resulted in situation where replay mode was always running queries with
step=`datasource.queryStep`. When it should always use rule's evaluation interval.
The fix is related not to replay mode only, but
for all Range requests. Now step param is set
individually for each mode.

vmalert: fix replay step param

---

Makefile

Newer version of openssl changed output format which breaks symbol number based parsing.
Previous version output(`OpenSSL 1.1.1n  15 Mar 2022`):
```
(stdin)= 790da16b24f4f8e1cc1389defa3ee51a6602473b
```
Newer version(`OpenSSL 3.0.7 1 Nov 2022`):
```
SHA1(stdin)= 7db3104e62c38b114da52f41a7d7f00c1d46b6e9
```
Splitting space by resolves this for both versions.

make: make openssl output parsing symbol number agnostic

---

app/vmalert/datasource/datasource.go
app/vmalert/datasource/vm_prom_api.go
app/vmalert/datasource/vm_prom_api_test.go
app/vmalert/datasource/vm_test.go

Method `metrics()` now pre-allocates slices for labels and results from query responses. This reduces number of allocations on the hot path for instant requests.

vmalert: reduce allocations for Prometheus resp parse

---

app/vmui/packages/vmui/src/components/Main/Autocomplete/Autocomplete.tsx
app/vmui/packages/vmui/src/utils/query-string.ts

- correct encode query in URL (#3444)
- remove prevent nav by up/down keys for multi-line query (#3445)
- multi-line queries are left as is when sent and put into the URL.

vmui: fix multi-line query

---

app/vmagent/datadog/request_handler.go
app/vminsert/datadog/request_handler.go
lib/protoparser/datadog/parser.go
lib/protoparser/datadog/parser_test.go

For some reason that I don't understand, the `datadog-agent` (at least v7) removes the `device` tag from the `Tags` field and adds it as it's own field in the Series object - as far as I can tell, this is not mentioned in the [datadog documentation to submit metrics (check v1)](https://docs.datadoghq.com/api/latest/metrics/#submit-metrics).
In the `datadog-agent` code, you can see the `device` tag being removed from the `Tags` field [in here](https://github.com/DataDog/datadog-agent/blob/0ada7a97fed6727838a6f4d9c87123d2aafde735/pkg/metrics/series.go#L84-L105).
What this PR does is to add what is in the device field value as a label.

Datadog - Add device as a tag if it's present as a field in the series object

---

app/vmalert/group.go
app/vmalert/group_test.go
docs/CHANGELOG.md

By mistake, in 0989649ad041d5984f83fac6e2c76dd3b92af19a the error for remote write failures wasn't returned to user.
This change fixes it.

vmalert: correctly return error for RW failures

---

deployment/docker/docker-compose-cluster.yml
deployment/docker/docker-compose.yml

see https://grafana.com/blog/2022/11/29/grafana-security-release-new-versions-with-high-severity-security-fix-for-cve-2022-31097/

deployment/docker: bump Grafana version to v9.2.7

---

deployment/docker/alerts.yml

Alert `RequestErrorsToAPI` could be permanently triggered due to mistakes in clients configuration. However, such requests are unlikely to cause VM health state change. So there is no need in displaying this alert because there will be no correlation caused by it.

alerts: remove `show_at` label for RequestErrorsToAPI alert

---

dashboards/victoriametrics.json

Those data links were copy&paste artifact from cluster version and aren't needed on the dash.

dashboards: remove DataLinks from single version

---

app/vmalert/alerting.go
app/vmalert/recording.go
app/vmalert/rule.go
app/vmalert/web.qtpl
app/vmalert/web.qtpl.go

http.Request was used as a part of state struct
for generating the curl command when viewing the rule's state changes.
It appears, that holding a reference is far more expensive than generating the curl command immediately.
On the test with 40k rules, this change reduces memory and CPU usage by 50%.

vmalert: do not hold pointer to http.Request

---

dashboards/victoriametrics-cluster.json
dashboards/victoriametrics.json
dashboards/vmalert.json

The new annotation is hidden by default and suppose to show component `short_version` label change on the panels.

dashboards: add VersionChange annotation

---

app/vmbackup/README.md
app/vmbackup/main.go
app/vmrestore/README.md
app/vmrestore/main.go
docs/vmbackup.md
docs/vmrestore.md

Azure Blob Storage terminology uses term `container` to name entity called a `bucket` in different cloud providers.
In order to make it simpler for users to understand what is required to use in URL this PR updates documentation to use Azure term for this.
Related: #3463

app/{vmbackup/vmrestore}: update path example to use Azure terminology

---

lib/backup/azremote/azblob.go

Azure API limits copying of files larger than 256M in a sync mode, this PR implements using async mode for parts copy.
Fixes  #3477

lib/backup/azremote: fix copying for parts larger than 256M by using async copy

---

dashboards/victoriametrics-cluster.json

Previously, $job_select, $job_storage and $job_insert didn't respect the $job filter. This change updates the variable queries to account for set $job variable.

dashboards: respect $job var in sub-vars for cluster dash

---

README.md
app/vmselect/prometheus/prometheus.go
app/vmselect/prometheus/prometheus_test.go
docs/CHANGELOG.md
docs/Cluster-VictoriaMetrics.md
docs/README.md
docs/Single-server-VictoriaMetrics.md

support overriding of `-search.latencyOffset` value via URL param `latency_offset`.
See https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3481

vmselect: support overriding of `-search.latencyOffset`

---

lib/logger/json-fields.go
lib/logger/logger.go

Closes #2348
Adds support for renaming json fields in logs through `--loggerJsonFields` such as:
```
--loggerJsonFields ts:time,level:lvl,msg:message
```

lib/logger: support for renaming json fields

---

app/vmui/packages/vmui/src/components/Configurators/AdditionalSettings/AdditionalSettings.tsx
app/vmui/packages/vmui/src/components/Configurators/StepConfigurator/StepConfigurator.tsx
app/vmui/packages/vmui/src/pages/CustomPanel/hooks/useSetQueryParams.ts
app/vmui/packages/vmui/src/utils/time.ts

- Save step to URL params only when overriding step
- By default, the step is set from the URL, if it is not there, then it is calculated automatically
- Step resets when changing duration (zoom in/out or  change time range)
- Change step rounding: 
* if `step > 100` then rounds up to an integer multiple of 10
* if `step between 10 and 100` then rounds up to an integer multiple of 5
* if `step between 0.01 and 1`  then rounds up to a float to thousandths multiple of 5
* if `step < 0.01` then rounds up to a float to thousandths
<br/>
- #3510
- #3513

vmui: step

---

.github/ISSUE_TEMPLATE/bug_report.md
README.md
app/vmagent/README.md
app/vmalert/README.md
app/vmselect/prometheus/expand-with-exprs.qtpl
app/vmselect/prometheus/expand-with-exprs.qtpl.go
deployment/docker/alerts-cluster.yml
deployment/docker/alerts-vmagent.yml
deployment/docker/alerts-vmalert.yml
docs/Cluster-VictoriaMetrics.md
docs/README.md
docs/Single-server-VictoriaMetrics.md
docs/guides/k8s-monitoring-via-vm-cluster.md
docs/guides/k8s-monitoring-via-vm-single.md
docs/vmagent.md
docs/vmalert.md

Old links to Grafana dashboards start returning 404, example https://grafana.com/dashboards/1860. 
This PR changes dashboards to a new formark
fix https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3532

update links to grafana dashboards

---

lib/snapshot/snapshot.go

Currently, in case 401 error will be returned error message will be:
```
unexpected status code returned from ""; expecting 401; got 200;
```

lib/snapshot: fix error message format for failed HTTP request

---

lib/promscrape/client.go

when scraping metrics in _normal_ mode (i.e. not in streamparse mode), the body response size is only checked before decompressing it, which, given the high compressibility of the prometheus metrics text-based representation, potentially permits to try parsing a `/metrics` endpoint 100x larger than the the configured `maxScrapeSize` (thereby potentially crashing `vmagent` for example)
This behaviour is inconsistent with the streamparse mode (details here https://github.com/VictoriaMetrics/VictoriaMetrics/pull/3527), where the `net.http/Client` correctly reports decompressed size

fix(promscrape): check MaxScrapeSize after gzip decompression

---

app/vmselect/prometheus/prometheus.go

There is no need to manually call `queryDuration.UpdateDuration(startTime)`, because `defer queryDuration.UpdateDuration(startTime)` is executed at the beginning of the function(L660).

app/vmselect/prometheus: no need manually call queryDuration.UpdateDuration

---

app/vmui/packages/vmui/src/components/Chart/ChartTooltip/ChartTooltip.tsx

Fixed title be improperly updated in the tooltip when hovering graph lines. 
- #3530

vmui: fix title in the graph tooltip

---

app/vmalert/README.md
app/vmalert/notifier/init.go
docs/vmalert.md

Stress the importance of specifying of all Alertmanager URLs in vmalert's `-notifier.url` or `notifier.config` if it runs in cluster mode.
See https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3547

vmalert: mention specifics of Alertmanager HA mode

---

app/vmctl/flags.go

Signed-off-by: yanggang <gang.yang@daocloud.io>
/kind cleanup
supplement the omission flag hint for the ```Step Const```
```
app/vmctl/stepper/split.go
```

Fix vmctl command hint for vm-native-step-interval

---

app/vmbackup/main.go

Signed-off-by: yanggang <gang.yang@daocloud.io>
/kind cleanup
There is type ```azblob``` missing.

Fix flag help message for the backups types.

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/feature_request.yml

`render: plain text` makes fields not formattable and prevents
from pasting screenshots.

github: rm `plaintext` render

---

lib/promscrape/config.go
lib/promscrape/targetstatus.go

In case there is a flag `--promscrape.dropOriginalLabels` set to `true` and either:
- resulting labels are empty:
```go
if labels.Len() == 0 {
// Drop target without labels.
droppedTargetsMap.Register(originalLabels, swc.relabelConfigs)
return nil, nil
}
```
-  `__address__` label is empty:
```go
if len(address) == 0 {
// Drop target without scrape address.
droppedTargetsMap.Register(originalLabels, swc.relabelConfigs)
return nil, nil
}
```
`Register` will be called with `nil` argument which will lead to panic during hashing.
Fixes  #3580

lib/promscrape/targetstatus: fix crash during droppedTarget registration

---

dashboards/backupmanager.json
dashboards/clusterbytenant.json
dashboards/operator.json
dashboards/victoriametrics-cluster.json
dashboards/victoriametrics.json
dashboards/vmalert.json

I got "Failed to upgrade legacy queries Datasource $ds was not found" in Grafana on operator dashboard.
It's datasource variable was incorrectly named `datasource`.
I also took the liberty and made the rest of the dashboards have homogeneous datasource-variable names and selections, matching vmagent dashboard - which have worked fine for me.

dashboards: fix operator datasource variable

---

.golangci.yml
Makefile

Lint via golangci-lint using revive. This replaces golint, which is now deprecated and archived.
Delegate errcheck to golangci-lint as well. This allows better control over errcheck as opposed to direct invocation, particularly when excluding a package or directory from checking (not done in this PR but coming).

Lint and errcheck using golangci-lint

---

README.md
app/vmagent/README.md
docs/CHANGELOG.md
docs/README.md
docs/sd_configs.md
lib/promscrape/config.go
lib/promscrape/discovery/nomad/agent.go
lib/promscrape/discovery/nomad/agent_test.go
lib/promscrape/discovery/nomad/api.go
lib/promscrape/discovery/nomad/nomad.go
lib/promscrape/discovery/nomad/service.go
lib/promscrape/discovery/nomad/service_test.go
lib/promscrape/discovery/nomad/watch.go
lib/promscrape/scraper.go

Add `nomad_sd_configs` support for service discovery.
Closes https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3367
Here's an example file:
```
global:
scrape_interval: 10s
scrape_configs:
- job_name: "prom_nomad"
nomad_sd_configs:
- server: "localhost:4646"
tags:
- metrics
```
This is the result it produces:
The labels are similar to what is exported here: https://prometheus.io/docs/prometheus/latest/configuration/configuration/#nomad_sd_config

lib/promscrape: add Prometheus-compatible service discovery for Nomad

---

lib/promscrape/client.go
lib/promscrape/discovery/azure/api.go
lib/promscrape/discovery/azure/machine.go
lib/promscrape/discovery/azure/nic.go
lib/promscrape/discovery/consul/api.go
lib/promscrape/discovery/consul/watch.go
lib/promscrape/discovery/http/api.go
lib/promscrape/discoveryutils/client.go

Using native http client allows using context to cancel requests after discovery stop.
Fixes #3468.

lib/promscrape/discoveryutils: switch to native http client from fasthttp

---

lib/promscrape/discoveryutils/client.go

Fixes timeout usage to use Read timeout since context sets limit for the whole request lifecycle.

lib/promscrape/discoveryutils: use correct timeout for blocking requests

---

docs/CHANGELOG.md
lib/promscrape/discovery/gce/instance.go

lib/promscrape/discovery/gce: fix crash in case instance does not have any labels set

---

app/vmctl/flags.go
app/vmctl/main.go
app/vmctl/remoteread/remoteread.go
app/vmctl/utils/tls.go
docs/CHANGELOG.md

Added flag to remote read protocol, which skip tls verification when connecting to remote read address to perform read from.
Related issue: https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3590

app/vmctl: Add insecure skip verify flag for remote read protocol

---

docs/CHANGELOG.md
lib/promscrape/discovery/dockerswarm/api.go
lib/promscrape/discovery/dockerswarm/dockerswarm.go
lib/promscrape/discovery/dockerswarm/network.go
lib/promscrape/discovery/dockerswarm/nodes.go
lib/promscrape/discovery/dockerswarm/services.go
lib/promscrape/discovery/dockerswarm/tasks.go

Discovery filters were applied to all objects. For object-specific filters like `desired-state` for `task` that leaded to failure during discovery of labels as same filters were applied when fetching services and nodes.
This PR changes logic to pass filter only to the discovery target, so that all other services will be fetched without filters.
Related issue https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3579

lib/promscrape/discovery/dockerswarm: fix discovery filters being applied to all objects

---

app/vmctl/remote_read_test.go
app/vmctl/testdata/servers_integration_test/remote_read_server.go
app/vmctl/testdata/servers_integration_test/remote_write_server.go

1. Implemented remote write server, which helps to implement tests for other supported protocols
2. Implemented remote read server with the mock storage, which helps to check stream mode
3. Implemented integration tests for remote read protocol.
Related issue: https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3419

app/vmctl: add remote read protocol integration tests

---

docs/CHANGELOG.md
lib/promscrape/scrapework.go

It correctly suppresses scrape errors and adds correct context for err msg

/lib/promscrape: use correct err logger for scrape unmarshalling

---

.github/workflows/codeql-analysis.yml

We have limited amount of time used by Github CI runners and JS analysis accounts for a half of it.
Since JS represents only a small fraction of the codebase and is solely maintained by one person - I suggest disabling the CodeQL check in order to save CI runners time.

ci: disable JS codeQL check

---

lib/fs/fs_solaris.go
lib/fs/fs_unix.go

Since `fs.mustGetFreeSpace()` requires a path anyway, this PR changes it from `unix.Fstatfs()` to `unix.Statfs()` (Solaris: `unix.Fstatvfs()` => `unix.Statvfs()`).
Measured around 3.5x faster, and from 3 allocs down to 1 alloc, which seems reasonable going from 3 syscalls down to 1 syscall.

lib/fs: use `unix.Statfs()` / `unix.Statvfs()` when using a path

---

app/vmbackup/main.go
lib/snapshot/snapshot.go

This prevents vmbackup from leaking passwords into logs like shown below.
2023-01-11T15:00:01.050Z        info    VictoriaMetrics/lib/logger/flag.go:12   build version: vmbackup-20221214-211706-tags-v1.85.1-0-g09a70d3e9
2023-01-11T15:00:01.050Z        info    VictoriaMetrics/lib/logger/flag.go:13   command-line flags
2023-01-11T15:00:01.050Z        info    VictoriaMetrics/lib/logger/flag.go:20     -dst="fs:///vm-backups/latest"
2023-01-11T15:00:01.050Z        info    VictoriaMetrics/lib/logger/flag.go:20     -snapshot.createURL="http://user:super_sercret123@victoriametricspshot/create"
2023-01-11T15:00:01.050Z        info    VictoriaMetrics/lib/logger/flag.go:20     -storageDataPath="/storage"
2023-01-11T15:00:01.050Z        info    VictoriaMetrics/app/vmbackup/main.go:53 Snapshot create …

app/vmbackup: prevent password leaks

---

.github/workflows/main.yml

so with my change introduced in https://github.com/VictoriaMetrics/VictoriaMetrics/pull/3670 we now trigger build only if after tests are successful. However github actions for such job uses default branch.
This changes fixes this so that build job will use same commit as the test job that triggered build
see here for more details
https://blog.pother.ca/github-actions-workflow_run-event/

CI: checkout correct branch for build step

---

lib/awsapi/config.go

Switch to the actual API version `2016-11-15`,
since the old version doesn't provide access to all the fields which implementation expects.
For example, old API missing `zone_id` field
in `DescribeAvailabilityZonesResponse` response.
See https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3700

discover/ec2: bump API version

---

Makefile

This PR will add GOARCH=386 builds to build and package VictoriaMetrics and vmtools binaries in *.tar.gz release archives.
see https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3661

Adds i386 architecture 

---

app/vmbackup/main.go
docs/CHANGELOG.md

vmbackup was creating 2 snapshtos due to wrong URL being used for deleting snapshot.
This PR fixes delete URL usage.
Related issue  #3735

app/vmbackup: fix deleting snapshot after backup completion

---

app/vmselect/netstorage/netstorage.go
docs/CHANGELOG.md

In case of multi-level setup with `replicationFactor` set to value higher than 1 responses from some nodes would be dropped. Dropping response will also close `Tracer` before netstorage will retry request causing `NewChild` being called on closed `Tracer`.
This PR changes usage of `qt` to create retry `Tracer` based on `Tracer` which was created locally, this helps to ensure `Tracer` cannot  be closed outside of function execution flow.
Related  #3734

fix: vmselect multi-level setup panic

---

lib/storage/partition.go
lib/storage/partition_search.go
lib/storage/storage_test.go

previously historical data backfilling may trigger force merge for previous month every hour it consumes cpu, disk io and decrease cluster performance. Following commit fixes it by applying deduplication for InMemoryParts

lib/storage: fixes finalDedup for backfilled data

---

.github/workflows/codeql-analysis-js.yml
.github/workflows/codeql-analysis.yml
.github/workflows/main.yml
.github/workflows/nightly-build.yml
deployment/docker/builder/Dockerfile

- fix nightly build (docker scan allows only 10 for free, but with auth in Snyk opensource scan is free)
- enable fast cancel for jobs if there are new commits into same branch or PR, to avoid unnecessary builds
- enabled caching for `/gocache-for-docker` which lead to build speedup

CI: speedup build by 2.4x. restore nightly build

---

docs/Cluster-VictoriaMetrics.md

This is an attempt to make it a bit clearer to the user that the cluster version ingestion URLs are different from the standalone ones.  I have also changed the order of the list items to make it a bit clearer and hopefully stop the user simply inferring that `/prometheus/api/v1` is only related to Prometheus data.

Clarifications between standalone/cluster ingestion endpoints

---

lib/promscrape/discovery/nomad/watch.go

url.Values is an uninitialized map.
Stack trace:
```
panic: assignment to entry in nil map
goroutine 102 [running]:
net/url.Values.Set(...)
net/url/url.go:896
github.com/VictoriaMetrics/VictoriaMetrics/lib/promscrape/discovery/nomad.newNomadWatcher(0xc0001e6820, 0xc?, {0xc00019d7c8, 0x7}, {0xc00002a12d, 0x6})
github.com/VictoriaMetrics/VictoriaMetrics/lib/promscrape/discovery/nomad/watch.go:50 +0x85
github.com/VictoriaMetrics/VictoriaMetrics/lib/promscrape/discovery/nomad.newAPIConfig(0xc000301000, {0x7ffcb7290c55, 0xf})
github.com/VictoriaMetrics/VictoriaMetrics/lib/promscrape/discovery/nomad/api.go:93 +0x40f
github.com/VictoriaMetrics/VictoriaMetrics/lib/promscrape/discovery/nomad.getAPIConfig.func1()
github.com/VictoriaMetrics/VictoriaMetrics/lib/promscrape/discovery/nomad/api.go:33 …
```

fix: panic in nomad watcher because of nil map

---

app/vmui/packages/vmui/src/pages/PredefinedPanels/hooks/useFetchDashboards.ts

Only show local dashboards if no dashboards are specified through the `--vmui.customDashboardsPath` flag.
#3740

vmui: hide the local dashboards

---

dashboards/victoriametrics-cluster.json

`avg` can be affected by just one outlier, which may lead to false conclusions. `median` is supposed to reflect reality better by leveling outliers out.

dashboards: use `median` instead of `avg`

---

lib/protoparser/opentsdb/streamparser.go

Timestamp conversion applies correctly when using -opentsdbHTTPListenAddr flag but does not correctly apply when using -opentsdbListenAddr (it always multiplies milliseconds timestamp by 1000). Fixing this.

fixed opentsdbListenAddr timestamp conversion

---

app/vmagent/prometheusimport/request_handler.go
app/vminsert/prometheusimport/request_handler.go
lib/promscrape/scrapework.go
lib/protoparser/prometheus/stream/streamparser.go
lib/protoparser/prometheus/stream/streamparser_test.go

`lib/protoparser/prometheus` is used by various applications, such as `app/vmalert`. The recent change to the
`lib/protoparser/prometheus` package introduced a new dependency of `lib/writeconcurrencylimiter` which exposes some metrics. Because of the dependency, now all applications which have this dependency also expose these metrics.
Creating a new `lib/protoparser/prometheus/stream` package helps to remove these metrics from apps which use `lib/protoparser/prometheus` as dependency.
See https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3761

lib/protoparser/prometheus: move `streamparser` to subpackage

---

app/vmalert/main.go
docs/vmalert.md

since this [commit](https://github.com/VictoriaMetrics/VictoriaMetrics/commit/11ae1ae92432731989bfe8af1bd7e4e7384719fc), maxResolveDuration should be 4 times of groupInterval by default instead of 3.

[fix]fix vmalert maxResolveDuration flag note

---

app/vmagent/remotewrite/pendingseries_test.go

Add tolerance interval to comparing block size for VictoriaMetrics remote write in TestPushWriteRequest

Fix TestPushWriteRequest for remotewriteprotocol for pure-test (with native zstd)

---

lib/promscrape/client.go

Implements cancelling in-flight requests for `fasthttp.HostClient`.
Related #3747

lib/promscrape: fix cancelling in-flight scrape requests during configuration reload

---

app/vmselect/promql/exec_test.go
app/vmselect/promql/transform.go
docs/CHANGELOG.md

From now on, `interpolate` function fills only intermediate gaps and doesn't extrapolate the trailing empty values at the beginning and at the end of the time series, what corresponds to its description in the [documentation](https://docs.victoriametrics.com/MetricsQL.html#interpolate).
The previous behavior can be achieved by using the functions `keep_next_value` and `keep_last_value`.
[issue #3816](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3816).

fix interpolate function for filling only intermediate gaps (#3816)

---

lib/promscrape/discovery/azure/api.go

Fixes #3830.
While testing VMAgent inside [Azure Container Apps](https://learn.microsoft.com/en-us/azure/container-apps/overview) together with Azure service discovery using Managed Identity I noticed I was not able to get a token from the [IMDS](https://learn.microsoft.com/en-us/azure/virtual-machines/linux/instance-metadata-service?tabs=windows) endpoint.
During investigation I noticed a few issues.
- The endpoint used in these resources requires a newer API version and a different auth header.
- Solution I used is the same as [Azure Go SDK utilizes](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/azidentity/managed_identity_client.go#L120) which is checking for the environment variable `IDENTITY_HEADER`, and adding the correct API version and header if it is set.
- If using …

Azure Service Discovery - Fix token fetch for Container Apps/App Services

---

lib/fs/fs.go
lib/mergeset/table.go
lib/storage/partition.go

Dirs with `.must-remove.` marker are scheduled for deletion and will be removed.
Including those into snapshots could lead to sporadic errors during snapshot as file will be deleted shortly after `os.Readdir` was performed.
See  #3858

lib/{fs,mergeset,storage}: skip `.must-remove.` dirs when creating snapshot

---

app/victoria-metrics/Makefile

Added `victoria-metrics-linux-s390x` to allow single node builds for `s390x` platform.
Leaving other packaging options at the moment, as on this platform, they're mostly going to be built from/with container images hosted within the company as a base, and not alpine.

Option to build for s390x (Linux on IBM Z)

---

app/vmctl/main.go

Enabled version flag, because the [issue](https://github.com/urfave/cli/issues/1560) was fixed 

app/vmctl: enable version flag

---

app/vmctl/influx/influx.go
docs/CHANGELOG.md

When we try to import data from influx db a retention policy autogen can have no data in the measurement and at this moment vmctl struggles to import the data.
skip field keys for measurement when a measurement has no data in the retention policy
Related issue: https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3837

app/vmctl: skip series if measurement not found

---

docs/CHANGELOG.md
lib/promscrape/scraper.go

Previously, metrics were initialized but never updated which leaded to false-positive alerts and could confuse users.

lib/promscrape: correctly register `vm_promscrape_config_*` metrics

---

app/vmctl/README.md
app/vmctl/flags.go
app/vmctl/remoteread/remoteread.go
docs/vmctl.md

When a user tries to migrate a huge amount of data via remote read protocol, he can experience context timeout because the server does not respond in time.
To prevent this situation increased the default timeout from the 30s to 5min.
Added importing tips, fixed typo

app/vmctl: Increase http request timeout made by remote read client, add importing tips

---

app/vmalert/group.go
app/vmalert/group_test.go
app/vmalert/helpers_test.go
app/vmalert/manager.go

When group's update() or close() method is called, the group still need to wait for its current evaluation to finish. Sometimes, evaluation could take a significant amount of time which slows configuration update or vmalert's graceful shutdown.
The change interrupts current evaluation in order to speed up the graceful shutdown or config update procedures.

vmalert: cancel in-flight requests on group's update or close

---

docs/vmctl.md

Small fix for vmctl docs to add missing supported value for vm-native-step-interval

doc: vmctl vm-native-step-interval supported values

---

app/victoria-metrics/main.go
app/vmauth/main.go
docs/CHANGELOG.md
lib/netutil/tcplistener.go

it may occur if non proxy protocol message received by tcp server. Listener Accept method must return only non-recoverable errors. https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3335

lib/netutil: fixes panic at proxy protocol

---

.github/workflows/check-licenses.yml
.github/workflows/codeql-analysis.yml
.github/workflows/main.yml
.github/workflows/nightly-build.yml
app/vmui/Dockerfile-web
deployment/docker/Makefile
docs/CHANGELOG.md
snap/local/Makefile

upgrade Go builder from Go1.20.1 to Go1.20.2
See the list of issues addressed in Go1.20.2 here (https://github.com/golang/go/issues?q=milestone%3AGo1.20.2+label%3ACherryPickApproved).

security: bump go version to 1.20.2

---

app/vmctl/README.md
docs/vmctl.md

Added recommendation when users try to backfill data with overlapping time ranges for destination storage.

app/vmctl: update importing tips when migrating data with overlapping time range

---

lib/storage/storage.go

io.EOF shouldn't be returned from this function. It breaks all search API logic and may result in empty query results.

lib/storage: correctly handle io.EOF error for pre-fetched metrics

---

lib/vmselectapi/server.go

after vmselect api refactoring it wasn't possible to disable response cache. This patch restores correct behavior for rpc.disableCompression flag

lib/vmselectapi: fixes regression for disable compression setting

---

docs/CHANGELOG.md
lib/storage/metric_name.go

Currently, too long value can be discovered by using `vm_too_long_label_values_total` metric, but it does not provide a way to find exact metric and label which was truncated.  This makes it hard to debug and properly fix source of too long label values.
Log message example:
```
2023-03-13T17:20:44.416Z        warn    VictoriaMetrics/lib/storage/metric_name.go:484     truncated label value as it exceeds configured maximal label value length: max 3, actual 22;truncated label: __name__; original labels: {__name__="scrape_timeout_seconds",instance="localhost:8429",job="sel"}; either reduce the label value length or increase -maxLabelValueLen=3;
```

lib/storage: log original labels set when label value is truncated

---

app/vmalert/config/config.go
app/vmalert/config/fs.go
app/vmalert/config/log/logger.go
app/vmalert/config/log/logger_test.go
app/vmalert/main.go

The change is mostly required for ENT version of vmalert, since it supports object-storage for config files. Reading data from object storage could be time-consuming, so vmalert emits logs to track the progress.
However, these logs are mostly needed on start or on manual config reload. Printing these logs each time `rule.configCheckInterval` is triggered would too verbose. So the change allows to control logs emitting during config reloads.
Now, logs are emitted during start up or when SIGHUP is receieved. For periodicall config checks logs emitted by config pkg are suppressed.

vmalert: support logs suppressing during config reloads

---

docs/CHANGELOG.md
lib/netutil/tcplistener.go

Previosly every error was logged. With configured TCP health checks at load-balancer or kubernetes, vmauth spams a lot of false positive error message into logs

lib/netutil: log only parsing errors for proxy-protocol

---

app/vmalert/web.qtpl
app/vmalert/web.qtpl.go

This should help users to see that Group's name is clickable and used for anchoring.

vmalert: add anchor char to Group's link

---

docs/CHANGELOG.md
lib/envtemplate/envtemplate.go
lib/envtemplate/envtemplate_test.go

allowed using dashes and dots in environment variables names for templating config files with envtemplate (#3999)

allowed using dashes and dots in environment variables names

---

app/vmselect/promql/transform.go
app/vmselect/promql/transform_test.go

There is a bug here where if you have a single bucket like:
`foo{vmrange="4.084e+02...4.642e+02"} 2 123`
The expected output is three le encoded buckets like:
```
foo{le="4.084e+02"} 0 123
foo{le="4.642e+02"} 2 123
foo{le="+Inf"} 2 123
```
This correctly encodes the start and end of the vmrange. If however, the input contains the previous bucket, and that bucket is empty then you only get the end le and +Inf out currently, i.e:
```
foo{vmrange="7.743e+05...8.799e+05"} 5 123
foo{vmrange="6.813e+05...7.743e+05"} 0 123
```
results in:
```
foo{le="8.799e+05"} 5 123
foo{le="+Inf"} 5 123
```
This causes issues when you go to compute a quantile because this means that the assumed lower bound of the buckets is 0 and this we interpolate between 0->end rather than the vmrange start->end as …

app/vmselect: Fix le buckets when adjacent vmrange is empty

---

app/vmselect/netstorage/tmp_blocks_file.go

With non-posix compliant systems it's not possible to remove unclosed files.

app/vmselect: properly remove temp files at windows system

---

app/vmalert/notifier/alert.go
docs/CHANGELOG.md

Replace empty labels with "" instead of `"<no value>"` during templating, as Prometheus does.
See https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4012

vmalert: use `missingkey=zero` for templating

---

app/vmctl/README.md
docs/vmctl.md

Adds URL examples for different migration paths, currently documentation only mentions that it is required to follow URL format but that confuses users a lot.

docs/vmctl: add examples of URLs used for migration in different modes

---

lib/storage/storage.go

I have enabled the [unusedwrite](https://github.com/golang/tools/blob/master/gopls/doc/analyzers.md#unusedwrite) check of golsp and it has alerted me that a `pmr` object was copied but the original `pmr` was not properly reset. However, since a new `pendingMetricRow` object was created directly when calling `pmrs` `append` below, it did not have any actual impact.
Based on this code logic, I suspect that the intention was to reuse the `pendingMetricRow` object, so I have made modifications to the code and submitted a pull request. Please inform me if my understanding is incorrect.

lib/storage: fix reuse pendingMetricRow

---

docs/operator/api.md

Looks like the original document has moved to the https://kubernetes.io/docs/concepts/containers/images/#referring-to-an-imagepullsecrets-on-a-pod. Alternatively, it could be that https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/ describes the meaning of the parameter in more detail.
(Strangely I got only 6 change lines, while there are at least 8 pod resources on this page?)

Fix reference to the imagepullsecrets description

---

docs/operator/api.md

It seems that VMServiceScrape description was c-n-p from vmselect one into all other resources.

Fix cut-n-paste error

---

docs/CHANGELOG.md
lib/backup/actions/backup.go

This makes it easier to understand exact point in time which is included in this backup.

lib/backup/actions: store metadata(creation and completion time) in backup files

---

docs/Articles.md

"How do We Keep Metrics for a Long Time in VictoriaMetrics" article is referenced twice in "Third-party articles and slides about VictoriaMetrics" section

Removed duplicate third-party article reference

---

docs/CHANGELOG.md
lib/httpserver/httpserver.go

This handler will instruct search engines that indexing is not allowed for the content exposed to the internet. This should help to address issues like #4128 when instances are exposed to the internet without authentication.

lib/httpserver: add handler to serve `/robots.txt` and deny search indexing

---

app/vmalert/datasource/vm.go
app/vmalert/datasource/vm_test.go
docs/CHANGELOG.md

Retry failed read request on the closed connection one more time. This may improve rules execution reliability when connection between vmalert and datasource closes unexpectedly.

vmalert: retry datasource requests with EOF or unexpected EOF errors

---

app/vmui/packages/vmui/src/components/Configurators/GlobalSettings/TenantsConfiguration/TenantsConfiguration.tsx
app/vmui/packages/vmui/src/components/Configurators/GlobalSettings/TenantsConfiguration/hooks/useFetchAccountIds.ts
app/vmui/packages/vmui/src/utils/tenants.ts
docs/CHANGELOG.md

The list of tenants will be displayed if either of the following conditions is met:
- the `useTenantID` flag is set to `true`.
- the `serverUrl` contains tenantID, for example, `/select/<tenantID>/,` and there is more than one tenant in the response.
#4160

vmui: fix bug where tenant list was not displayed

---

app/vmagent/README.md
app/vmagent/remotewrite/remotewrite.go
docs/vmagent.md
lib/persistentqueue/persistentqueue.go
lib/persistentqueue/persistentqueue_test.go

Show a warning message if the user specified flag `--remoteWrite.maxDiskUsagePerURL` is lower than 500MB. 
Update documentations.
Related issue: https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4195

app/vmagent,lib/persistentqueue: show warning message if `--remoteWrite.maxDiskUsagePerURL` flag lower than 500MB

---

deployment/docker/alerts-vmalert.yml

RecordingRulesNoData could be firing for some very normal reasons - like no metrics source are being scraped at this time but rules are preloaded.
Therefore, it better to mark such alert as 'info', as suggest by some guides, as there could be likely no point to notify regarding this alert.
https://monitoring.mixins.dev/
```
info for alerts that do not require any action by itself but mark something as “out of the ordinary”. Those alerts aren’t usually routed anywhere, but can be inspected during troubleshooting.
```

Decrease severity to info for RecordingRulesNoData

---

app/vmalert/main.go
app/vmalert/templates/template.go
docs/CHANGELOG.md

Templating of `-external.alert.source` is not expected to have access to the query. It was causing runtime error when query function was passed as nil. 
See: #4181

app/vmalert: return an error when using `query` function in `-external.alert.source` flag

---

lib/protoparser/opentsdbhttp/stream/streamparser.go

fix https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4204

vminsert: fix unlimited reader when parsing opentsdb request

---

lib/streamaggr/streamaggr.go
lib/streamaggr/streamaggr_test.go

Samples with timestamps lower than `now - aggregation_interval` are likely to be written via backfilling and should not be used for calculation of aggregation. 
See #4068

lib/streamaggr: discard samples with timestamps outside of aggregation interval

---

app/vmalert/web.go
app/vmalert/web_test.go
docs/CHANGELOG.md

Properly return empty slices instead of nil for `/api/v1/rules` and `/api/v1/alerts` API handlers.
This improves compatibility with Grafana.
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4221

vmalert: fix API to return non-nil values

---

docs/CHANGELOG.md
lib/promscrape/discovery/kubernetes/endpoints.go
lib/promscrape/discovery/kubernetes/endpoints_test.go

Sets `__meta_kubernetes_endpoints_name` and `__meta_kubernetes_namespace` labels to all ports of pod. Prometheus sets those labels to all ports in pod (https://github.com/prometheus/prometheus/blob/0ab95536115adfe50af249d36d73674be694ca3f/discovery/kubernetes/endpoints.go#L267C15-L269) even if port is not matching any service. 
See: #4154

lib/promscrape/discovery/kubernetes: add common labels to all ports discovered from endpoints

---

app/vmselect/main.go

When `-search.maxConcurrentRequests` is reached, vmselect puts request in the queue. It is expected, that requests in the queue will be processed as soon as it would be enough capacity to do so.
However, it could happen that while request was waiting its turn, the client could have already cancel it (close the connection, or just close the tab with UI). In this case, we should de-queue such requests to avoid spending extra resources on them.

vmselect: exit early from queue on context cancel

---

lib/backup/actions/util.go
lib/backup/s3remote/s3.go

Adds a new flag to `vmbackup` which allows users to specify the StorageClass they wish to use for objects stored in AWS S3
Addresses: https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4164

Add s3StorageClass to s3remote

---

lib/promscrape/discovery/kubernetes/endpoints.go
lib/promscrape/discovery/kubernetes/endpointslice.go
lib/promscrape/discovery/kubernetes/pod.go

Add `__meta_kubernetes_endpoints_name`, `__meta_kubernetes_endpoints_label_<labelname>` and `__meta_kubernetes_endpoints_labelpresent_<labelname>`  labels for all targets discovered from ports not assigned to endpoint. Previously, ports not matched by `Service` did not have this label. See [[this issue](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4154)]

Add endpoint labels for pod targets

---

lib/storage/storage.go

previously during sync for mutable and immutable cache parts, link for hotEntry with current date may be not properly updated it corrupts cache for backfilling metrics and increased cpu load

lib/storage: properly update link for entry at dateMetricID cache
