.travis.yml, Makefile, README.md
Basic integration with travis, lint, test + coverage
=> [ci-ci] enable ci

dashboards/victoriametrics.json, deployment/docker/provisioning/dashboards/victoriametrics.json
=> Dashboard update

dashboards/vminsert.json, dashboards/vmselect.json, dashboards/vmstorage.json
This PR is adding basic Grafana dashboards for VM cluster.
=> Adding Grafana dashboards for VM cluster

dashboards/victoriametrics.json
=> Add CPU usage panel; rename `Go runtime` to `Resource usage`

dashboards/victoriametrics.json
Add version requirements to description in order to provide proper versioning on grafana.com
=> Add versioning to dashboard description

package/rpm/README.md, package/rpm/victoriametrics-rpm.spec, package/rpm/victoriametrics.service
Add my service and spec files.
@kmansoft 
I think need union service file with:
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/43
https://github.com/VictoriaMetrics/VictoriaMetrics/pull/116#issuecomment-513813922
=> Add package/rpm/

.gitignore, app/victoria-metrics/Makefile, package/package_rpm.sh
Package as RPM right from the makefile
Uses same .service file as DEB packaging.
=> RPM packaging

package/deb/prerm, package/package_deb.sh
1) stop the service in pre-rm 2) reload services in post-rm
=> deb packaging fixes

deployment/k8s/helm/victoria-metrics/templates/vminsert-service-monitor.yaml, deployment/k8s/helm/victoria-metrics/templates/vmselect-service-monitor.yaml, deployment/k8s/helm/victoria-metrics/templates/vmstorage-service-monitor.yaml
This produced invalid YAML before.
=> Don't render extraLabels in ServiceMonitor if they are not given

app/victoria-metrics/main_test.go, app/victoria-metrics/testdata/prometheus/basic.json, app/victoria-metrics/testdata/prometheus/case-sensitive-regex.json
Part of https://github.com/VictoriaMetrics/VictoriaMetrics/issues/187
covers https://github.com/VictoriaMetrics/VictoriaMetrics/issues/161
=> add test for regex flags

README.md
`victoria-mertrics` -> `victoria-metrics` in helm commands.
=> Update README.md - Fix helm command typos

app/victoria-metrics/main_test.go, app/victoria-metrics/testdata/graphite/basic.json, app/victoria-metrics/testdata/influxdb/basic.json, app/victoria-metrics/testdata/opentsdb/basic.json, app/victoria-metrics/testdata/opentsdbhttp/basic.json, app/victoria-metrics/testdata/opentsdbhttp/multi_line.json, app/victoria-metrics/testdata/prometheus/basic.json, app/victoria-metrics/testdata/prometheus/case-sensitive-regex.json, app/victoria-metrics/testdata/prometheus/duplicate-label.json, app/victoria-metrics/testdata/prometheus/match-series.json
Part of https://github.com/VictoriaMetrics/VictoriaMetrics/issues/187
cover:
- https://github.com/VictoriaMetrics/VictoriaMetrics/issues/155
- https://github.com/VictoriaMetrics/VictoriaMetrics/issues/172
=> Add regression test for duplicated labels and serias

app/victoria-metrics/main_test.go, app/victoria-metrics/testdata/graphite/comparison-not-inf-not-nan.json, app/victoria-metrics/testdata/graphite/not-nan-as-missing-data.json
Part of https://github.com/VictoriaMetrics/VictoriaMetrics/issues/187
cover:
- https://github.com/VictoriaMetrics/VictoriaMetrics/issues/153
- https://github.com/VictoriaMetrics/VictoriaMetrics/issues/150
=> Add regression test for query api

README.md
Provide info about defaults in readme
=> Improve documentation a little bit

lib/storage/storage.go
1. don't return error generated during handling invalid rows, just log it
Error makes vmstorage quit the loop of reading packets and close the connection with vminsert. Consequently vminsert fails in writing the next packet to this connection and reroutes it to the next vmstorage. This makes the cluster unstable if a tenant inserts many data points out of date.
=> warns during rows addition

go.mod, go.sum, vendor/github.com/klauspost/compress/huff0/compress.go, vendor/github.com/klauspost/compress/huff0/huff0.go, vendor/github.com/klauspost/compress/zstd/blockenc.go, vendor/github.com/klauspost/compress/zstd/enc_dfast.go, vendor/github.com/klauspost/compress/zstd/fse_encoder.go, vendor/github.com/klauspost/compress/zstd/zstd.go, vendor/modules.txt
=> #215: update klauspost/compress lib

dashboards/victoriametrics.json
**concurrent inserts**:
**rows ignored:**
If there are any other panels you think are missing just let me know.
=> Update single-version dashboard with new panels

dashboards/victoriametrics.json, deployment/docker/docker-compose.yml, deployment/docker/provisioning/datasources/datasource.yml
=> #224: add slow_queries, on-going merges and merge speed panels

dashboards/victoriametrics.json
add description, churn rate panel, storage.ingestion rate panel
=> Dahsboard upd

dashboards/victoriametrics.json
=> Add churn rate panel to dashboard

app/victoria-metrics/test/parser.go, app/vmselect/prometheus/prometheus.go, lib/backup/common/part.go, lib/fastnum/fastnum.go, lib/fs/fs.go, lib/storage/storage.go, lib/storage/storage_test.go
Few simple mistakes from https://goreportcard.com/report/github.com/VictoriaMetrics/VictoriaMetrics
=> fix misspelled words

dashboards/victoriametrics.json
* fix vm_cache_miss_total => vm_cache_misses_total
* add dashboard links
=> add links and fix cache metric name

dashboards/victoriametrics.json
=> #251 - add Logging rate panel to single version dashboard

dashboards/victoriametrics.json
=> #251 - add Logging rate panel to cluster dashboard

README.md
=> README.md: adds link to Grafana dashboard for clustered version

README.md
This PR was based on following discussion: https://victoriametrics.slack.com/archives/CGZF1H6L9/p1576884626010600
=> Update Prometheus configuration in README

dashboards/victoriametrics.json
Fix names of graphs accordingly to metric
=> Fix current/max graphs

dashboards/victoriametrics.json
* use bits/s for network usage panels;
* improve description for `Pending datapoints` panel;
#292 #299
=> Cluster dashboard

dashboards/victoriametrics.json
=> Single dashboard

README.md
As discussed in #311 here is a proposal about readme/env vars. Feel free to ask modifications. Once settled, I will update and PR the cluster readme as well.
=> Readme envvars

README.md
=> add envvars details on cluster readme

app/vmalert/main.go, app/vmalert/rule.go, app/vmalert/web.go
* populate apiALert object with additional fields
* return all active alerts, not only firing
=> Extend web responses for alerts:

app/vmalert/main.go, app/vmalert/rule.go, app/vmalert/web.go
```
vmalert_alerts_fired_total 3
vmalert_alerts_sent_total 12
vmalert_execution_duration_seconds_sum 0.184914401
vmalert_execution_duration_seconds_count 8
vmalert_execution_duration_seconds{quantile="0.5"} 0.00414202
vmalert_execution_duration_seconds{quantile="0.9"} 0.037640631
vmalert_execution_duration_seconds{quantile="0.97"} 0.124209756
vmalert_execution_duration_seconds{quantile="0.99"} 0.124209756
vmalert_execution_duration_seconds{quantile="1"} 0.124209756
vmalert_execution_errors_total 0
vmalert_execution_total 8
vmalert_iteration_duration_seconds_sum 0.194009614
vmalert_iteration_duration_seconds_count 4
vmalert_iteration_duration_seconds{quantile="0.5"} 0.009826371
vmalert_iteration_duration_seconds{quantile="0.9"} 0.166711371 …
```
=> Vmalert metrics

app/vmbackup/main.go, app/vmbackup/snapshot/snapshot.go, app/vmbackup/snapshot/snapshot_test.go
Resolves: https://github.com/VictoriaMetrics/VictoriaMetrics/issues/422
=> app/vmbackup: added ability to create and delete snapshots during backup

app/vmalert/rule.go
Ref https://github.com/VictoriaMetrics/VictoriaMetrics/issues/434
=> fix: fix vmalert template label not complete bug

app/vmagent/main.go
add promscrap config reload suppport via http endpoint `/-/reload`
=> feat(vmagent): add promscrap config reload suppport via http

dashboards/victoriametrics.json
=> Avoid ugly y-label for rows inserted

lib/promrelabel/relabel.go, lib/promscrape/config.go, lib/protoparser/prometheus/parser.go
=> different behavior as how prometheus deal with labels.

app/vmalert/main.go, app/vmalert/notifier/alert.go, app/vmalert/notifier/alert_test.go, app/vmalert/notifier/template_func.go, app/vmalert/rule.go, app/vmalert/testdata/dir/rules0-good.rules
Add expr to variables, add query and path escape functions. Address #488
=> vmalert - add expr to variables, add escape functions

dashboards/victoriametrics.json
The change contains two updates:
* fix Datapoints panel query #551;
* add datasource selector.
=> dashboard: update single-version dashboard.

dashboards/victoriametrics.json
Fix "Bytes per point" panel query #551.
=> dashboard: update cluster-version dashboard.

lib/storage/partition.go
=> lib/storage: set big/small merge concurrency

app/vmalert/main.go, app/vmalert/main_test.go
address https://github.com/VictoriaMetrics/VictoriaMetrics/issues/586
=> vmalert fix nil transport when http

app/vmagent/README.md
vmagent README.md troubleshooting section updated to help out with duplicated targets detection
=> vmagent README.md update

app/vmselect/prometheus/util.qtpl, app/vmselect/prometheus/util.qtpl.go
Sometimes the query range api response is not a valid json.
But I remember that vm didn't return empty results before, so the bug wasn't triggered. Is there a recent logic change that returns a empty result?
=> fix empty response template

dashboards/vmagent.json
* reference datasource variable instead of datasource name;
* change unit from `bytes` to `bits/s` for Network panel.
=> vmagent: update grafana dashboard

dashboards/victoriametrics.json, deployment/docker/docker-compose.yml, deployment/docker/prometheus.yml, deployment/docker/provisioning/datasources/datasource.yml
* replace Prometheus with vmagent in docker compose env;
* cluster dashboard: exclude vmagent from job list;
* cluster dasbhoard: reference datasource var instead of datasource name.
=> deployment/docker: replace Prometheus with vmagent

app/vmauth/main.go
401 Unauthorize HTTP error added to trigger browser credentials pop-up promt [RFC 7235 https://developer.mozilla.org/en-US/docs/Web/HTTP/Authentication]
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/680
=> 401 Unauthorize HTTP error added

dashboards/victoriametrics.json
=> use Y-min 0 on Grafana dashboard graphs

dashboards/victoriametrics.json, dashboards/vmagent.json
See listed commits for the changelog.
=> Single dashboards update

app/vmalert/group.go
spread load of rule evaluation by group
=> feat: spread load of rule evaluation by group when starting new groups

README.md
=> document `minScrapeInterval` semantics

dashboards/victoriametrics.json
Make vm dashboard more multi tenant by default
=> Add account id to datapoints ingestion rate

lib/storage/index_db.go
Related issue https://github.com/VictoriaMetrics/VictoriaMetrics/issues/781
The code probably looks like this, but I don't know how to test the performance of this strategy in a real-world environment.
=> add filter to getMetricIDs

README.md, app/vmbackup/README.md, app/vmrestore/README.md
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/381
with minio and configuration file examples.
=> update vmbackup/vmrestore README usage

app/vmalert/README.md, app/vmalert/datasource/init.go
Address https://github.com/VictoriaMetrics/VictoriaMetrics/issues/795
=> vmalert: make maxIdleConnections configurable for datasource HTTP client

app/vmalert/README.md
Address https://github.com/VictoriaMetrics/VictoriaMetrics/issues/830
=> vmalert: update docs to highlight the state restore requirements;

lib/promscrape/discovery/openstack/api.go
=>  fixes openstack api endpoint with suffix trim

CHANGELOG.md, app/vmbackup/main.go
Fixes https://github.com/VictoriaMetrics/VictoriaMetrics/issues/856
=> vmbackup fix panic when no origin fs given

lib/promscrape/config.go, lib/promscrape/config_test.go
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/835
=> adds leading forward slash check for scrapeURL path

lib/promscrape/client.go
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/864
regression after body reuse improvements
=> fixes panic at scrape error body formating,

dashboards/victoriametrics.json
The new panel suppose to help to estimate the time needed to run out of free
disk space.
Thx to @belm0 @hekmon
=> dashboard: add `Storage full ETA` panel

lib/logger/logger.go
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/905
=> Adds log suppression per caller

app/vminsert/main.go
=> Spelling mistakes

dashboards/victoriametrics.json
=> dashboard: incorporate dedup rate into storage ETA

README.md
=> Update carbonapi link in readme

dashboards/victoriametrics.json
https://grafana.com/grafana/dashboards/11176/revisions
=> dashboard: release to grafana.com

app/vmagent/remotewrite/client.go, lib/flagutil/array.go, lib/flagutil/array_test.go
ArrayDuration and ArrayBool flags,
makes sendTimeout and tlsInsecure configurable per remoteWriteURL
=> adds new Array Flags

app/vmalert/notifier/init.go
fixes issue with notifier insecure setting, now its possible to use notifier.tlsInsecureSkipVerify multiple time.
=> changes vmalert notifier flag,

app/vmselect/prometheus/prometheus.go
https://github.com/VictoriaMetrics/helm-charts/issues/89
=> fixes panic

docs/vmagent.md
Add remote_write.url format for clustered version
=> Doco vmagent fix

README.md
=> change carbonapi link

app/vmalert/README.md, docs/vmalert.md
Follow-up for https://github.com/VictoriaMetrics/VictoriaMetrics/pull/1050
=> vmalert: mention `-datasource.appendTypePrefix` in README

lib/promscrape/discovery/dockerswarm/services.go
fixes improper usage of host network services
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1028
=> fixes dockerswarm

deployment/docker/base/Dockerfile
NOTE clean up local cache with docker rmi local/base:1.1.1-alpine_3.13.1-alpine_3.13.1
=> adds zoneinfo to base docker image,

dashboards/victoriametrics.json
Same as https://github.com/VictoriaMetrics/VictoriaMetrics/pull/1072 but for cluster
=> Add `Labels limit exceeded` panel to dashboard

docs/Quick-Start.md
I made an effort to not change anything substantive.
=> Native speaker edits.

docs/CaseStudies.md
Do we have the dates that each of these were written so that can be added next to each brand?
=> Alphabetized names and added "native speaker" spin.

app/vmagent/README.md
The changes in this patch were ported from https://github.com/VictoriaMetrics/VictoriaMetrics.github.io/pull/1
Shout out to @dereksfoster99 for his work!
=> Vmagent docs upd

lib/promscrape/client.go, lib/promscrape/discoveryutils/client.go
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1116
=> Changes tlsConfig init for proxy connections

app/vmagent/README.md, app/vmagent/main.go, app/vminsert/main.go, docs/vmagent.md
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1124
=> adds fake response for telegraph queries

lib/ingestserver/graphite/server.go, lib/ingestserver/influx/server.go, lib/ingestserver/opentsdb/server.go, lib/netutil/udp.go
with flag -enableUDP6  https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1131
=> Adds udp6 support for ingest servers

dashboards/victoriametrics.json
* add panel `Open FDs` for file descriptors metrics;
* add panel `Disk writes/reads` to show the real read/write
load on storage layer;
* add stats panel to show available CPUs, memory and disk space.
=> dashboard: update cluster node dashboard

app/vmselect/graphite/metrics_api.go
it should be able mitigate crash if label value contains *,[ or { symbols
=> changes metricsFind api

lib/promscrape/discovery/consul/service_node.go, lib/promscrape/discovery/consul/service_node_test.go, lib/promscrape/discovery/consul/watch.go
according to prometheus discovery.
It should mitigate issue with case sensetive services
https://github.com/hashicorp/consul/issues/5707
=> changes consul_service label value

lib/promscrape/discovery/kubernetes/api_watcher.go
Signed-off-by: Megrez Lu <lujiajing1126@gmail.com>
Fix access to nil `*url.URL` pointer, since there is no nil check in [`URL.String()`](https://github.com/golang/go/blob/776d8d387c262d3dd159f7868b3c04fb0f617865/src/net/url/url.go#L811-L816)
=> fix access to nil *url.URL

docs/vmctl.md
Added explanation that vmctl do not make snapshot from Prometheus when run migration data
=> Added some explanation to vmctl docs

app/vmalert/alerting.go, app/vmalert/alerting_test.go, app/vmalert/datasource/datasource.go, app/vmalert/datasource/init.go, app/vmalert/datasource/vm.go, app/vmalert/datasource/vm_test.go, app/vmalert/group.go, app/vmalert/group_test.go, app/vmalert/helpers_test.go, app/vmalert/main.go, app/vmalert/manager.go, app/vmalert/manager_test.go, app/vmalert/recording.go, app/vmalert/recording_test.go, app/vmalert/remoteread/init.go, app/vmalert/rule.go
it allows to changes some parametrs based on rule setting
for instance - alert type, tenant for cluster version or event endpoint url.
=> changes vmalert Querier with per rule querier

lib/storage/partition.go
=> adds stalePartsRemover

app/vmalert/recording.go
duplicates map helps to determine wheter extra labels has overriden
labels which make time series unique. It was using a sorted hashed
labels sequence as a key. But hashing algorithm could have collisions,
so it is more convenient to not use hashing at all.
Log message for recording rules duplicates was improved as well.
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1293
=> vmalert: use stringified label keys for duplicates map in recording rules

app/vmbackup/main.go, app/vmrestore/README.md, docs/vmrestore.md
app/{vmbackup,vmrestore},docs/vmrestore.md: typo fix: vbackup -> vmbackup
=> typo fix: vbackup -> vmbackup

.github/ISSUE_TEMPLATE/bug_report.md
The main changes are:
* ask for Grafana's dashboard screenshots;
* ask only for non-default cmd-line flags;
* explicitly ask about logs;
=> update the issue template

lib/promscrape/discovery/digitalocean/digitalocean.go, lib/promscrape/discovery/digitalocean/digitalocean_test.go
adds test for digitalocean sd
must fix https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1367
=> fixes DO service discovery labels

README.md, app/vmagent/README.md, docs/Single-server-VictoriaMetrics.md, docs/vmagent.md, lib/promscrape/config.go, lib/promscrape/discovery/http/api.go, lib/promscrape/discovery/http/api_test.go, lib/promscrape/discovery/http/http.go, lib/promscrape/discovery/http/http_test.go, lib/promscrape/discoveryutils/client.go, lib/promscrape/scraper.go
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1392
=> adds http_sd

dashboards/victoriametrics.json
* move panel `Disk writes/reads` to `Resource usage` row
* rename row `storage` to `vmstorage`
* remove cumulative display for `Storage ETA` panel
=> dashboard: several minor fixes

dashboards/victoriametrics.json
=> dashboard: move panel `Disk writes/reads` to `Resource usage` row

lib/promscrape/targets_response.qtpl, lib/promscrape/targets_response.qtpl.go
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1422
=> fixes /targets button style

app/vmalert/notifier/alert.go
=> Performance optimization

deployment/docker/alerts.yml
Once change approved, the follow-up PR for cluster version will be opened.
=> Alerts single update

app/vmui/packages/vmui/src/components/Home/Configurator/TimeSelector.tsx
just delete garbled code in vmui as shown below:
=> delete garbled code

app/vmui/packages/vmui/src/components/Home/HomeLayout.tsx, app/vmui/packages/vmui/src/state/common/reducer.ts, app/vmui/packages/vmui/src/utils/default-server-url.ts
- Fixed layout error on big query ( #1497 )
- Fixed layout when updating the chart
- Added server address by default ( #1506 )
=> vmui: fix layout and add server url by default

README.md
Make "number of open files" recomendation not only Prometheus specific to avoid
confusion for users who does not use Prometheus.
=> docs: update "number of open files" tuning recommendation

.github/dependabot.yml
add dependency chekcs for
- ruby (for docs)
- gomod for monorepo
- npm for vmui
- gomod go small webserver in  vmui
=> Dependencies check

app/vmselect/prometheus/prometheus.go
Before, metric `vm_request_duration_seconds` was update only on successful
attempts which could be misleading. For example, timeout errors on netstorage
request may be not accounted in the metric and won't be visible on dashboards.
Using `defer` statement to update the metric after query arguments validation
may improve the situation.
=> vmselect: update `vm_request_duration_seconds` value when request fails

dashboards/victoriametrics.json, dashboards/vmagent.json, deployment/docker/alerts.yml, deployment/docker/docker-compose.yml
=> Single dashboards upd

lib/netutil/conn_pool.go
reset deadline before we put it back to pool.
=> reset deadline, fix #1562.

app/vmalert/web.qtpl, app/vmalert/web.qtpl.go
=> vmalert: display extra filter labels in UI

app/vmalert/README.md, app/vmalert/datasource/init.go, app/vmalert/datasource/vm.go, app/vmalert/datasource/vm_test.go, app/vmalert/remoteread/init.go, app/vmalert/remotewrite/init.go, app/vmalert/remotewrite/remotewrite.go
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1608
=> vmalert: support bearer token for datasource, remotewrite and remoteread

docs/Articles.md
https://abiosgaming.com/press/high-cardinality-aggregations/
=> docs: add "Choosing a Time Series Database for High Cardinality Aggrgations" article

app/vmalert/datasource/init.go, app/vmalert/remoteread/init.go, app/vmalert/remotewrite/init.go, app/vmalert/utils/auth.go
=> vmalert: create basic auth config only if args aren't empty

app/vmagent/influx/request_handler.go, app/vmagent/main.go, app/vmagent/prometheusimport/request_handler.go, app/vmagent/promremotewrite/request_handler.go, app/vmagent/vmimport/request_handler.go, app/vminsert/promremotewrite/request_handler.go, app/vminsert/vmimport/request_handler.go, lib/protoparser/promremotewrite/streamparser.go, lib/protoparser/vmimport/streamparser.go
adds InsertHandlerForReader apis to vmagent
=> changes protoparser apis for accepting reading from io.Reader

app/vmctl/README.md
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1637
=> app/vmctl: fix misleading comment about cluster version for native mode

deployment/docker/Makefile, deployment/docker/builder/Dockerfile
adds gcc and musl-dev to builder container
=> moves prod images build into alpine container with musl

lib/promscrape/discovery/openstack/auth.go
must fix https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1655
=> changes auth validation for openstack

app/vmagent/promremotewrite/request_handler.go, app/vmagent/remotewrite/client.go, app/vmagent/remotewrite/remotewrite.go
adds auth.Token to promremotewrite InsertHandlerReader
changes remoteWrite client constructor, allows to use multiple remoteWriteUrl schemes, like kafka://
changes url path concatenation for tenant remoteWrite
=> changes vmagent api

docs/guides/k8s-monitoring-via-vm-single.md
metric_ralabel_configs -> metric_relabel_configs
=> fix: typo metric_relabel_configs

deployment/docker/Makefile
See this https://alpinelinux.org/posts/Alpine-3.14.3-released.html
=> Bumped Alpine linux version to the latest

deployment/docker/Makefile
See https://alpinelinux.org/posts/Alpine-3.15.0-released.html
=> Bumped Alpine linux version to 3.15.0

app/vmui/packages/vmui/src/components/Home/Configurator/useFetchQuery.ts, app/vmui/packages/vmui/src/state/common/reducer.ts, app/vmui/packages/vmui/src/utils/storage.ts
=> vmui: remove saving the last query to local storage

app/vmui/packages/vmui/src/components/Home/Configurator/DisplayTypeSwitch.tsx, app/vmui/packages/vmui/src/state/common/reducer.ts, app/vmui/packages/vmui/src/utils/query-string.ts
=> vmui: store display type in URL

app/vmalert/README.md, docs/vmalert.md
Commit changes images width and order in topologies section
for better readability.
=> vmalert: adjust topologies docs in README

docs/MetricsQL.md
* simplify sentences;
* fix typo.
=> docs: update `MetricsQL`.`Subquery` section description

dashboards/vmagent.json, deployment/docker/alerts.yml
=> Dashboards vmagent updates

app/vmselect/promql/rollup.go
issues:[describe](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1962)
so i add changes_prometheus、delta_prometheus、increase_prometheus ,
see  changes_prometheus likes:
see increase_prometheus likes：
delta_prometheus same as increase_prometheus
=> add Prometheus semantics function :changes_prometheus、delta_prometheus、increase_prometheus

dashboards/victoriametrics.json, deployment/docker/alerts.yml
=> Dashboards vmsingle

dashboards/victoriametrics.json
=> Dashboards cluster

dashboards/vmagent.json
=> dashboards/vmagent: fix cached datasource uid

dashboards/victoriametrics.json
In this PR we migrate from deprecated old table panel in Grafana to a new one.
Thanks to @Aleksey_G_Belov
=> dashboards: migrate from old table panel in cluster dashboard

docs/guides/getting-started-with-vm-operator.md
=> docs: Correct config URL

docs/FAQ.md
* Added missing articles.
* Changed minus characters to long dashes.
* Rephrased some words.
* Corrected grammar mistakes.
* Set correct possessive apostrophes.
* "setup" -> "set up"
* "no need in" -> "no need for"
* "comparing" -> "compared"
* "less" -> "fewer"
* "additionally" -> "in addition to"
=> Proofread FAQ.md

README.md, docs/README.md, docs/Single-server-VictoriaMetrics.md
=> docs: update retention docs with additional details

README.md, app/vmbackup/README.md, docs/FAQ.md, docs/README.md, docs/Single-server-VictoriaMetrics.md, docs/vmbackup.md
=> docs: Correct some urls in the docs

app/vmui/packages/vmui/src/components/Home/Views/TableView.tsx
Added sortable columns in table ([task card](https://github.com/VictoriaMetrics/VictoriaMetrics/projects/2#card-64915536))
=> vmui: add sortable columns

docs/operator/api.MD
correct VMAgentStatus description from VMAlert to VMAgent.
=> Correct VMAgentStatus description

docs/FAQ.md
Added description to FAQ about how downsampling and deduplication will work at the same time.
=> FAQ update

lib/mergeset/table_search.go, lib/storage/partition_search.go, lib/storage/table.go, lib/storage/table_search.go
optimized code ,because only the first error,so no need var errors []error
=> optimized code 

app/vmui/packages/vmui/src/utils/uplot/series.ts
Changed logic setting free fields for legend.
#2115
=> vmui: fix hangs when querying

app/vmalert/README.md, app/vmalert/notifier/init.go
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1567
=> vmalert: add support of `-notifier.basicAuth.passwordFile` flag for notifiers

README.md, docs/README.md, docs/Single-server-VictoriaMetrics.md
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/2151
=> docs: add Storage section to docs

app/vmalert/web.go, app/vmalert/web.qtpl, app/vmalert/web.qtpl.go
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/2167
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1783
=> vmalert: fix bug with relative links in UI

docs/CHANGELOG.md, lib/promscrape/discovery/kubernetes/endpoints.go, lib/promscrape/discovery/kubernetes/endpoints_test.go, lib/promscrape/discovery/kubernetes/endpointslice.go
now it must take in account all pods that belong to the discovered endpoint and endpointslice
adds simple test for endpoints
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/2134
=> fixes service discovery for kubernetes

lib/promscrape/discovery/openstack/api.go, lib/promscrape/discovery/openstack/instance.go
explicit use configuration parametr instead of conditional add
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/2182
=> fixes all_tenants query option usage for openstack service discovery

lib/httpserver/httpserver.go
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/2171
=> Adds server certificate reload for lib/http

lib/promscrape/config.go, lib/promscrape/scraper.go
=> match fileSDCheckInterval with prometheus file_sd_config default

lib/promscrape/targetstatus.qtpl, lib/promscrape/targetstatus.qtpl.go
`Uncaught TypeError: Cannot read properties of null (reading 'style')`
=> vmagent: fix js error on CollapseAll/ExpandAll buttons click

app/vmalert/config/testdata/rules2-good.rules, app/vmalert/main.go, app/vmalert/notifier/alert.go, app/vmalert/notifier/alert_test.go, app/vmalert/notifier/init.go
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/2193
=> vmalert: support `$externalLabels` and `$externalURL` in templates

docs/guides/getting-started-with-vm-operator.md, docs/guides/k8s-monitoring-via-vm-cluster.md
This PR contains new version of Grafana dashboards for guides.
=> Update revisions of dashboards

dashboards/victoriametrics.json
=> dashboards: update the threshold for slow inserts % on the dashboard

README.md, docs/README.md, docs/Single-server-VictoriaMetrics.md
How to delete time series url don't jump
=> Correct URL:How to delete time series

app/vminsert/influx/request_handler.go
That would be great if we can override this tag name via the command line parameter because currently, we patch VM insert every release.
=> Add -influxDBLabel parameter

README.md, app/vmstorage/main.go, docs/CHANGELOG.md, docs/README.md, docs/Single-server-VictoriaMetrics.md, lib/mergeset/part.go, lib/storage/storage.go
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1940
=> lib: allow to configure cache size by type

docs/url-examples.md
=> Update URL examples

docs/README.md
- clarify the retention time units
- clarify "indefinite" retention based on #633
- drive-by English improvements
=> docs: clarify Retention, improve English

app/vmalert/README.md, docs/vmalert.md
Hello,
Just a small typo, nothing fancy.
Best
EDIT: Align comment
=> docs(vmalert): typo in path

app/vmalert/README.md, app/vmalert/datasource/init.go, app/vmalert/datasource/vm_test.go, app/vmalert/notifier/alertmanager.go, app/vmalert/notifier/alertmanager_test.go, app/vmalert/notifier/init.go, app/vmalert/remoteread/init.go, app/vmalert/remotewrite/init.go, app/vmalert/utils/auth.go, docs/vmalert.md
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1824
=> Issue-1824: added flags and different auth types support

app/vmalert/README.md, app/vmalert/alerting.go, app/vmalert/datasource/init.go, app/vmalert/datasource/vm_prom_api.go, app/vmalert/group.go, app/vmalert/manager.go, app/vmalert/notifier/template_func.go, app/vmalert/recording.go, app/vmalert/rule.go, app/vmalert/web.go, app/vmalert/web.qtpl, app/vmalert/web.qtpl.go, app/vmalert/web_test.go, app/vmalert/web_types.go
See the compliance doc here https://github.com/prometheus/compliance/blob/main/alert_generator/specification.md
=> Vmalert compliance improvements

docs/CHANGELOG.md
=> docs: add update note to v1.75.0 release note

app/victoria-metrics/main.go
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/2323
=> issue-2323: Fixed Incorrect Content-Type header 'text/plain' for root path

docs/CHANGELOG.md
Warn about memory issue introduced in releases 1.73 - 1.74
=> docs: update release notes

app/vmalert/alerting.go, app/vmalert/alerting_test.go, app/vmalert/datasource/datasource.go, app/vmalert/datasource/vm.go, app/vmalert/datasource/vm_test.go, app/vmalert/group.go, app/vmalert/group_test.go, app/vmalert/helpers_test.go, app/vmalert/notifier/alert.go, app/vmalert/recording.go, app/vmalert/recording_test.go, app/vmalert/remotewrite/remotewrite.go, app/vmalert/rule.go, app/vmalert/utils.go, app/vmalert/web_test.go
=> Vmalert compliance 2

app/vmalert/group.go
Executor recently gain field for storing previously sent series.
Since the same executor object can be used in multiple goroutines,
the access to this field should be serialized.
=> vmalert: protect executor's field from concurrent access

docs/operator/quick-start.MD
=> fix object selectors link

app/vmui/packages/vmui/src/utils/uplot/helpers.ts
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/2409
9
=> vmui: fixed yaxis labels

app/vmctl/main.go
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/2322
=> vmctl: Return non zero error code if validation or subcommand fails

README.md, lib/httpserver/httpserver.go, lib/httpserver/httpserver_test.go
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/2404
=> lib/httpserver: added tlsCipherSuites flag

.github/workflows/codeql-analysis.yml
Add pre-generated workflow definition for GitHub's CodeQL code scanning.
=> Add GitHub workflow for code scanning

app/vmselect/main.go
it should fix an compability error with grafana 8.5 prometheus datasource
https://github.com/grafana/grafana/pull/46771
=> app/vmselect: adds API /api/v1/status/buildinfo

app/vmalert/README.md, app/vmalert/replay.go
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1761
=> vmalert: added disableProgressBar flag which disable progressbar

app/vmalert/notifier/alert.go
Function `ValidateTemplates`, used on the vmalert startup,
is supposed to check whether used templates and functions
in loaded rules are correct. The function was parsing
and executing loaded templates.
However, rules may contain functions which can't be executed
without values (label values or query results), like `slice`.
Because of this, validation for completely valid expression
`{{ slice $labels.job 9 }}` will fail since `$labels.job`
is empty during validation.
This PR updates `ValidateTemplates` function to only parse
templates without executing them.
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/2514
=> vmalert: do not execute templates during validation

lib/promscrape/client.go
standard http client accepts multiple http status codes as redirect
it should fix issue with incorrect redirects
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/2482
=> lib/promscrape: adds correct http status codes for redirect

app/vmselect/main.go
It allows to visualization for alerting rules at grafana
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1739
=> app/vmselect: adds proxy for rules API

dashboards/victoriametrics.json
=> dashboards: bump version requirement for cluster dashboard

app/vmctl/README.md, docs/vmctl.md
=> vmctl: add tip about safety flags during for native data export

app/vmalert/alerting.go, app/vmalert/group.go
=> Vmalert fix bugs in alerting evaluation

app/vmctl/opentsdb.go, app/vmctl/opentsdb/opentsdb.go
=> vmctl: make linter happy

app/vmalert/group.go, app/vmalert/group_test.go
Rules executor within group tracks series sent to remote write
in order to mark them as stale if they had disappeared in next
evaluation round.
The executor uses rules ID as a key to identifies series which belong to rule.
On config reload, executor remains active but the set of rules could change.
Hence, we need to properly cleanup the tracker for rules which has been disappeared
on config reload.
=> vmalert: properly cleanup stale series tracker on rules update

app/vmalert/README.md, docs/CHANGELOG.md, docs/vmalert.md
=> vmalert: follow-up after 0ac1cdfff59f6285ed4750c2cb030587cd8b0f65

app/vmalert/README.md, docs/vmalert.md
=> vmalert: fix readme formatting

app/vmui/packages/vmui/src/components/CustomPanel/Configurator/DisplayTypeSwitch.tsx, app/vmui/packages/vmui/src/state/common/reducer.ts
the issues mentioned https://github.com/VictoriaMetrics/VictoriaMetrics/issues/2402#issuecomment-1115830648
=> vmui: support display type from prometheus url

app/vmui/packages/vmui/src/App.tsx, app/vmui/packages/vmui/src/state/common/StateContext.tsx, app/vmui/packages/vmui/src/utils/query-string.ts
Added the ability to customize url params for individual pages
=> feat: setup url params by route

app/vmctl/README.md
* Updated vmctl documentation (migration from OpenTSDB section)
=> Updated vmctl documentation (migration from OpenTSDB section)

app/vmalert/datasource/vm_prom_api.go
=> vmalert: remove a line added for debug

docs/keyConcepts.md
=> docs: fix a typo of mentioning scrape support for vmselect

docs/vmctl.md
=> docs: follow-up after 4b3eb40658f3c31c2d4329f75e8b947b86ade4ec

app/vmalert/group.go
The new metric shows the configured evaluation interval per group.
Metric updates its value when group's interval is changed during
hot reload.
The new metric can be used to estimate how close group
is to start missing evaluation rounds. The following query
will show the % of used time by the group to evaluate all rules
before the next round:
```
(max(vmalert_iteration_duration_seconds{quantile="0.99"}) / vmalert_iteration_interval_seconds) * 100
```
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/2618
=> vmalert: add new metric `vmalert_iteration_interval_seconds`

app/vmalert/README.md, docs/vmalert.md
=> vmalert: mention how to build a custom image

app/vmctl/README.md, docs/vmctl.md
=> docs: mention guide for migrating from inlfux in vmctl readme

README.md, docs/README.md, docs/Single-server-VictoriaMetrics.md
=> docs: update single version docs by adding extra links and formatting

app/vmalert/README.md, docs/vmalert.md
Signed-off-by: lihaowei <haoweili35@gmail.com>
=> fix: docs minor change

app/vmalert/notifier/alert.go
Signed-off-by: lihaowei <haoweili35@gmail.com>
close #2654
=> chore: remove duplicated code

lib/promauth/config.go, lib/promscrape/discovery/kubernetes/api.go, lib/promscrape/discovery/kubernetes/api_test.go, lib/promscrape/discovery/kubernetes/kubernetes.go, lib/promscrape/discovery/kubernetes/testdata/kubeconfig_basic.yaml, lib/promscrape/discovery/kubernetes/testdata/kubeconfig_cert.yaml, lib/promscrape/discovery/kubernetes/testdata/kubeconfig_token.yaml
=> support kubeconfig

app/vmalert/README.md, app/vmalert/alerting.go, app/vmalert/alerting_test.go, app/vmalert/config/config.go, app/vmalert/group.go, app/vmalert/recording.go, app/vmalert/recording_test.go, app/vmalert/replay.go, app/vmalert/rule.go, docs/vmalert.md, lib/logger/logger.go
Signed-off-by: lihaowei <haoweili35@gmail.com>
=> feat: rule limit

dashboards/clusterbytenant.json
=> dashboards: update cluster by tenant dashboard

app/vmui/packages/vmui/src/components/CustomPanel/Configurator/Query/QueryConfigurator.tsx, app/vmui/packages/vmui/src/state/common/reducer.ts, app/vmui/packages/vmui/src/utils/query-string.ts
=> vmui: fix relative time and query params

docs/guides/migrate-from-influx.md
Mention `-search.maxStalenessInterval` flag and its effect on query engine.
=> docs: migrating from influx

README.md, docs/Cluster-VictoriaMetrics.md, docs/README.md, docs/Single-server-VictoriaMetrics.md
=> docs: reduce free disk recommendation from 30% to 20%

app/vmalert/group.go, app/vmalert/group_test.go, app/vmalert/helpers_test.go, app/vmalert/notifier/init.go, app/vmalert/utils/err_group.go, app/vmalert/utils/err_group_test.go
=> Vmalert notifiers

README.md, app/vmalert/README.md, docs/MetricsQL.md, docs/README.md, docs/Single-server-VictoriaMetrics.md, docs/url-examples.md, docs/vmalert.md
=> docs: reference links from key concepts

app/vmalert/README.md, docs/vmalert.md
Adds verbose flag and description for vmalert How to configure the rule when downsampling.
=> supplement vmalert downsampling docs

app/vmalert/README.md, docs/vmalert.md
=> docs: follow-up for 197d3cdd7488dfff1f1030409bec9ed91fc602e0

docs/BestPractices.md
Update https://docs.victoriametrics.com/BestPractices.html as requested in https://github.com/VictoriaMetrics/VictoriaMetrics/issues/2749
=> Adds a list of supported architectures

dashboards/victoriametrics.json
* add assisted merges panel https://github.com/VictoriaMetrics/VictoriaMetrics/issues/2754
* add mem panel per each component
* remove lines filling for some panels for clarity
=> dashboards: update cluster dashboard

app/vmalert/alerting.go, app/vmalert/alerting_test.go
=> vmalert: make `__name__` available for templating in alerts

docs/Troubleshooting.md
Follow-up after a4d9388ecb2f7bd2e81f3955efc0937272a64e19
=> docs: update Troubleshooting guide

dashboards/vmagent.json
* remove lines filling
* filter series with zero values
* update descriptions
=> dashboards: small visual tweaks for vmagent's dashboard

app/vmalert/README.md, docs/vmalert.md
=> docs: mention deduplication issue for HA vmalert topology

app/vmstorage/main.go, lib/storage/storage.go
Add indicator to monitor index rotation date.
=> add next retention metric

app/vmagent/remotewrite/client.go
This fixes a typo I introduced in pr #2604
=> fix typo introduced in pr #2604

lib/awsapi/config.go
=> fix assume role when running in ECS.

docs/FAQ.md
- adds links for OpenBSD ports
- adds info about prebuilt binaries for FreeBSD and OpenBSD in release page
=> docs: faq update

app/vmselect/promql/eval.go
=> vmselect: return correct error for second part of expression

app/vmui/packages/vmui/src/components/CustomPanel/Configurator/Time/TimeSelector.tsx
=> vmui: change the z-index of the datepicker

app/vmalert/README.md, app/vmalert/alerting.go, app/vmalert/config/config.go, app/vmalert/config/config_test.go, app/vmalert/config/testdata/dir/rules6-bad.rules, app/vmalert/config/testdata/rules/rules2-good.rules, app/vmalert/datasource/datasource.go, app/vmalert/datasource/init.go, app/vmalert/datasource/type.go, app/vmalert/datasource/vm.go, app/vmalert/datasource/vm_test.go, app/vmalert/group.go, app/vmalert/manager.go, app/vmalert/recording.go, app/vmalert/web.qtpl, app/vmalert/web.qtpl.go, app/vmalert/web_types.go, docs/CHANGELOG.md, docs/vmalert.md, lib/promauth/config.go
See https://github.com/VictoriaMetrics/VictoriaMetrics/issues/2860
=> vmalert: allow configuring custom headers per group

app/vmalert/alerting.go, app/vmalert/config/config.go, app/vmalert/config/config_test.go, app/vmalert/config/types.go, app/vmalert/datasource/datasource.go, app/vmalert/datasource/init.go, app/vmalert/datasource/vm.go, app/vmalert/datasource/vm_test.go, app/vmalert/group.go, app/vmalert/manager.go, app/vmalert/manager_test.go, app/vmalert/recording.go, lib/pushmetrics/pushmetrics.go
=> vmalert: remove dependency on datasource pkg from config

README.md
Hello,
Nothing fancy, just a missing letter
Best
=> docs(README): just a small typo

README.md, app/vmagent/README.md, docs/README.md, docs/sd_configs.md, docs/vmagent.md, lib/promscrape/config.go, lib/promscrape/discovery/yandexcloud/api.go, lib/promscrape/discovery/yandexcloud/instance.go, lib/promscrape/discovery/yandexcloud/instance_test.go, lib/promscrape/discovery/yandexcloud/resources.go, lib/promscrape/discovery/yandexcloud/yandexcloud.go, lib/promscrape/scraper.go
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1386
=> YC service discovery

app/vmalert/tpl/header.qtpl, app/vmalert/tpl/header.qtpl.go
the doc url should not be joined by `prefix` because it's an abs url.
=> bugfix: fix vmalert navbar url.

dashboards/victoriametrics.json
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/2941
=> dashboards: add `Cache usage %` panel to Caches row

app/vmalert/README.md, app/vmalert/datasource/init.go, app/vmalert/remoteread/init.go, app/vmalert/remotewrite/init.go, docs/CHANGELOG.md, docs/vmalert.md
=> vmalert: follow-up after 28441711e6784dc3e9a75caf4d096452f0d2ea9c

docs/FAQ.md
Added info on how to upgrade or downgrade VictoriaMetrics without downtime to FAQ
Based on reply https://github.com/VictoriaMetrics/VictoriaMetrics/issues/2944#issuecomment-1207502038
=> doc: add upgrade/downgrade without downtime to FAQ

docs/CHANGELOG.md
=> docs: mention default vmalert's behavior change in Update notes

docs/Articles.md
=> docs: add new article link

lib/storage/index_db.go
Fixes `TestSearchTSIDWithTimeRange` test case.
=> lib/storage: fix the search for empty label name

docs/Cluster-VictoriaMetrics.md
added note about resource usage for data re-routing
=> doc: udpate Cluster-VictoriaMetrics

docs/guides/multi-regional-setup-dedicated-regions.md
=> update multi-region guide, specify multi-level vmselect option

app/vmselect/prometheus/prometheus.go
optimize limit param to api/v1/series api endpoint ，reduce unnecessary vmstorage query
=> reduce unnecessary vmstorage query

README.md, docs/README.md, docs/Single-server-VictoriaMetrics.md
Signed-off-by: Craig Rodrigues <rodrigc@crodrigues.org>
=> docs: add https://github.com/VictoriaMetrics/ansible-playbooks to README.md

README.md, docs/README.md, docs/Single-server-VictoriaMetrics.md
Signed-off-by: Craig Rodrigues <rodrigc@crodrigues.org>
=> docs: Add DataDog to list of ingestion methods

docs/keyConcepts.md
=> docs: Update keyConcepts

README.md, docs/README.md, docs/Single-server-VictoriaMetrics.md, docs/url-examples.md
Signed-off-by: Craig Rodrigues <rodrigc@crodrigues.org>
See:
https://github.com/VictoriaMetrics/VictoriaMetrics/blob/9cd8b729b00630bffe301e137d95de12f0e6d2a3/README.md#how-to-send-data-from-datadog-agent
=> docs: Clarify DataDog examples for VictoriaMetrics cluster

dashboards/victoriametrics-cluster.json, docs/PerTenantStatistic.md
moved cluster dashboard to master, to have all dashboards in one place
note: i haven't found any references to this dashboard to update
=> moved cluster dashboard to master

docs/Articles.md
=> docs: add `Monitoring at scale with Victoria Metrics`

app/vmui/packages/vmui/src/components/TopQueries/TopQueries.tsx, app/vmui/packages/vmui/src/components/TopQueries/TopQueryPanel/TopQueryPanel.tsx, app/vmui/packages/vmui/src/components/TopQueries/TopQueryTable/TopQueryTable.tsx, app/vmui/packages/vmui/src/hooks/useFetchTopQueries.ts, app/vmui/packages/vmui/src/types/index.ts
change columns for Top Queries
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/2707#issuecomment-1241121086
=> vmui: change columns for Top Queries

README.md, docs/README.md, docs/Single-server-VictoriaMetrics.md
See: https://github.com/VictoriaMetrics/VictoriaMetrics/blob/d4570d7439bc4904dae11924919e5165d0053115/README.md#single-node-victoriametrics
Signed-off-by: Craig Rodrigues <rodrigc@crodrigues.org>
=> docs: Use headings in DataDog section to make things easier to read

lib/querytracer/tracer.go
=> correction code comments

README.md, docs/Articles.md, docs/Cluster-VictoriaMetrics.md, docs/Quick-Start.md, docs/README.md, docs/Single-server-VictoriaMetrics.md
=> docs: mention VictoriaMetrics Monitoring blog post

app/vmalert/README.md, docs/vmalert.md
=> vmalert: add info about `search.latencyOffset` to Troubleshooting

deployment/marketplace/vultr/Makefile, deployment/marketplace/vultr/README.md, deployment/marketplace/vultr/RELEASE_GUIDE.md, deployment/marketplace/vultr/helper-scripts/vultr-helper.sh, deployment/marketplace/vultr/victoriametrics-single/etc/systemd/system/vmsingle.service, deployment/marketplace/vultr/victoriametrics-single/etc/update-motd.d/99-one-click, deployment/marketplace/vultr/victoriametrics-single/etc/update-motd.d/99-one-click.tpl, deployment/marketplace/vultr/victoriametrics-single/etc/victoriametrics/single/scrape.yml, deployment/marketplace/vultr/victoriametrics-single/etc/victoriametrics/single/victoriametrics.conf, deployment/marketplace/vultr/victoriametrics-single/setup-per-boot.sh, deployment/marketplace/vultr/victoriametrics-single/setup-per-instance.sh, deployment/marketplace/vultr/victoriametrics-single/victoriametrics-single.pkr.hcl, deployment/marketplace/vultr/victoriametrics-single/victoriametrics-single.sh
This PR will add packer config and helper scripts to build a virtual server with VM Single node for https://www.vultr.com/marketplace/categories/#monitoring. It also adds a Makefile and RELEASE_GUIDE.md.
=> Adds packer build for server with VM Single node in vultr.com marketplace

docs/MetricsQL.md
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3114
=> docs: clarify numeric label values for `label_value`

app/vmalert/README.md, docs/vmalert.md
Signed-off-by: panguicai008 <1121906548@qq.com>
=> fix recording typo

app/vmalert/README.md, docs/vmalert.md
=> vmalert: fix misleading line regarding multitenancy

app/vmui/packages/vmui/src/components/CustomPanel/Views/GraphView.tsx, app/vmui/packages/vmui/src/hooks/useFetchQuery.ts
- Change series limit logic (avoid unnecessary iteration of the loop)
- Remove spread operators with large arrays
#3240
=> vmui: optimize memory

docs/Makefile, docs/guides/README.md, docs/guides/guide-delete-and-replace-metrics.md, docs/guides/guide-delete-or-replace-metrics.md
Docs: add guide "How to delete and replace metrics"
=> Docs: add guide "How to delete and replace metrics"

app/vmui/packages/vmui/src/components/CustomPanel/Configurator/Settings/GlobalSettings.tsx, app/vmui/packages/vmui/src/components/CustomPanel/Configurator/Settings/ServerConfigurator.tsx, app/vmui/packages/vmui/src/components/CustomPanel/Configurator/Time/ExecutionControls.tsx, app/vmui/packages/vmui/src/components/CustomPanel/Configurator/Time/TimeSelector.tsx, app/vmui/packages/vmui/src/hooks/useFetchQuery.ts, app/vmui/packages/vmui/src/hooks/useFetchTopQueries.ts
- Add button "Refresh dashboard"
- Prevent reset time range when enable auto-refresh
- Remove prevent fetch without changing time range or query
- Apply server URL by down `ENTER` for
=> vmui: minor fixes

README.md, docs/README.md
=> Add link to security page from Readme

.github/workflows/check-licenses.yml, .github/workflows/main.yml, app/vmagent/README.md, app/vmalert/README.md, app/vmauth/README.md, app/vmbackup/README.md, app/vmctl/README.md, app/vmrestore/README.md, app/vmui/packages/vmui/package-lock.json, docs/README.md, docs/Single-server-VictoriaMetrics.md, docs/vmagent.md, docs/vmalert.md, docs/vmauth.md, docs/vmbackup.md, docs/vmctl.md, docs/vmrestore.md
=> bump go version to 1.19.3

lib/promscrape/scrapework_test.go
I see you don't have test on this function, i think this function is important to test because if one personne modify this function or appenLabels or AppendExtraLabels, that can change the return for the labels on Timeseries. it's not perfect but it's a start. 
I start test with same labels in tags, labels and extralbels parameters, with honor false and true.  
x - tags
x - externallabels
x - labels
x - tags + labels
x - tags + externallabels
x - labels + externallabels
x - tags + labels + externallabels
x - tags + labels
x - tags + externallabels
x - labels + externallabels
x - tags + labels + externallabels
=> test(golang): add test to function addRowToTimeseries

app/vmstorage/main.go
This PR fixs the security vulnerability defined by CodeQL: https://github.com/VictoriaMetrics/VictoriaMetrics/security/code-scanning/58
=> app/vmstorage: fix potential file inclusion via variable

deployment/docker/alerts-vmalert.yml
=> vmalert: bump evaluation interval to reasonable 30s

app/vmui/packages/vmui/src/components/Configurators/GlobalSettings/GlobalSettings.tsx, app/vmui/packages/vmui/src/components/Header/Header.tsx, app/vmui/packages/vmui/src/router/index.ts
- Display "Settings" on all pages
- Display "Settings" in app mode (for setting up series limits).
=> vmui: display app settings

lib/storage/storage_test.go
find test case one if never be executed，optimized code
=> test case optimized code

app/vmalert/README.md, docs/vmalert.md
there is no flag `-datasource.disablePathAppend` and datasource actually checking for `-remoteRead.disablePathAppend`
=> vmalert: flag reference update

docs/Cluster-VictoriaMetrics.md
=> docs: fix typo in cluster's README

docs/Articles.md
See https://docs.victoriametrics.com/Articles.html#other-articles
=> docs/Articles.md: fix broken link

app/vmui/packages/vmui/src/components/Chart/ChartTooltip/style.scss
=> vmui: fix tooltip sizing

deployment/docker/README.md
=> deployment: update the README

app/vmui/packages/vmui/src/components/Main/ShortcutKeys/ShortcutKeys.tsx, app/vmui/packages/vmui/src/components/Main/ShortcutKeys/style.scss, app/vmui/packages/vmui/src/pages/CustomPanel/QueryConfigurator/QueryConfigurator.tsx
=> vmui: select a single query by clicking the `eye` icon with `Ctrl`

dashboards/vmagent.json
=> dashboards: add non-default flags panel for vmagent

lib/promscrape/discovery/azure/machine.go, lib/promscrape/discoveryutils/client.go
=> lib/promscrape/discovery/azure: remove API server from URL returned by azure

app/vmui/packages/vmui/src/components/Configurators/QueryEditor/QueryEditor.tsx, app/vmui/packages/vmui/src/components/Main/Autocomplete/Autocomplete.tsx
Fix query run when a selection from autocomplete by "enter"
https://github.com/VictoriaMetrics/VictoriaMetrics/pull/3471#issuecomment-1347662927
=> vmui: fix query select from autocomplete

.github/workflows/nightly-build.yml, Makefile, deployment/docker/Makefile
Closes #1578
Schedules a nightly build of `master` branch at 2:48am to be published with a tag `:nightly`
=> Nightly builds at 2:48am

.github/workflows/nightly-build.yml
Resolves issue with missing `docker scan` plugin.
=> Fix issue with missing docker scan

app/vmui/packages/vmui/src/hooks/useFetchQuery.ts, docs/CHANGELOG.md
=> vmui: fix wrong legend when queries are hidden

README.md
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3495
=> docs: fix the image link

docs/CHANGELOG.md, docs/CaseStudies.md, docs/Cluster-VictoriaMetrics.md, docs/README.md, docs/Single-server-VictoriaMetrics.md, docs/vmanomaly.md
=> fix broken links

app/victoria-metrics/main_test.go, app/victoria-metrics/test/parser_test.go, app/victoria-metrics/testdata/graphite/subquery-aggregation.json
=> tests: attempt to fix flaky graphite test

.github/workflows/main.yml
=> run checks only for master/cluster branches

app/vmbackupmanager/README.md
Signed-off-by: yanggang <gang.yang@daocloud.io>
/kind cleanup
fix typo for json values.
=> fix typo for json values.

docs/guides/understand-your-setup-size.md
=> Add Understand Your Setup Size Guide

.github/workflows/nightly-build.yml
This PR should fix issue with Nightly Builds, see https://github.com/VictoriaMetrics/VictoriaMetrics/actions/runs/3826493032/jobs/6510329100#step:5:38.
=> .github/workflows/nightly-build.yml: added dockerhub login

lib/mergeset/table.go, lib/storage/storage.go, lib/storage/table.go
See https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3578
=> vmstorage: add more context to the flock acquiring msg

app/vmagent/README.md, docs/vmagent.md
=> vmagent: add minimal scrape file exampe for vmagent quick start

app/vmselect/prometheus/prometheus.go
=> app/vmselect: fix typo

dashboards/victoriametrics-cluster.json
See https://github.com/VictoriaMetrics/VictoriaMetrics/commit/c63755c316b71630d2f090e3ff7f2fbd36f9cccc#diff-bba263a473e7fbc9d0fde075ebef6b3d4e32c322ee1210a3e07182292c7723aaR18
=> dasbhoards: fix the tooltip info for 1.86

docs/operator/FAQ.md, docs/operator/VictoriaMetrics-Operator.md, docs/operator/additional-scrape.md, docs/operator/api.md, docs/operator/auth.md, docs/operator/backups.md, docs/operator/configuration_syncronization.md, docs/operator/design.md, docs/operator/high-availability.md, docs/operator/managing-versions.md, docs/operator/quick-start.md, docs/operator/relabeling.md, docs/operator/resources-validation.md, docs/operator/security.md, docs/operator/vars.md, docs/operator/vmalertmanager-configuration.md
=> prepare operator documentation to migration

dashboards/operator.json
=> dashboards: bump operator dash to v9 of Grafana

app/vmui/packages/vmui/src/components/Layout/Header/Header.tsx, app/vmui/packages/vmui/src/components/Layout/Header/style.scss, app/vmui/packages/vmui/src/components/Main/Tabs/TabItem.tsx, app/vmui/packages/vmui/src/components/Main/Tabs/TabItemWrapper.tsx, app/vmui/packages/vmui/src/components/Main/Tabs/Tabs.tsx, app/vmui/packages/vmui/src/components/Main/Tabs/style.scss
- make the nav menu as links (#3596)
- adaptive header for small screens
=> vmui: make nav menu as links

lib/promscrape/scrapework.go
Corresponding issue is: https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3668
=> Try to fix vmagent oom when delete kubernetes clusters from kubernetes_sd_configs

lib/promscrape/scrapework.go, lib/promscrape/scrapework_test.go
Stale series are sent when there is a difference between current and previous scrapes. Those series which disappeared in the current scrape are marked as stale and sent to the remote storage.
Sending stale series requires memory allocation and in case when too many series disappear in the same it could result in noticeable memory spike. For example, re-deploy of a big fleet of service can result into excessive memory usage for vmagent, because all the series with old pod name will be marked as stale and sent to the remote write storage.
This change limits the number of stale series which can be sent at once, so memory usage remains steady.
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3668 https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3675
Signed-off-by: hagen1778 …
=> lib/promscrape: limit number of sent stale series at once

docs/CHANGELOG.md
=> discover/ec2: follow-up after e2b4ab838425676d8b581dee495d8ff42cf69028

app/vmagent/README.md, docs/sd_configs.md, docs/vmagent.md
=> docs: specify the time window for `series_limit`

docs/Cluster-VictoriaMetrics.md, docs/Quick-Start.md
This PR will add:
* security section to https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html 
* Security recommendation section to https://docs.victoriametrics.com/Quick-Start.html
See https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3674
=> Improving docs by adding additional security sections

deployment/docker/docker-compose-cluster.yml
See https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3767
=> fixed wrong vmstorage port number

app/vmalert/README.md, app/vmalert/main.go, app/vmalert/replay.go, docs/vmalert.md
=> vmalert: update docs

docs/managed-victoriametrics/how-to-monitor-k8s.md
there were some issues in guide with numbered list. should be fine now
=> docs: update formatiing for k8s monitoring with Managed VictoriaMetrics

docs/CHANGELOG.md
https://github.com/VictoriaMetrics/VictoriaMetrics/pull/3784/commits/2e4bfcce6399e1f18ff104af8550e68018827ec4
=> docs: follow-up after 2e4bfcce6399e1f18ff104af8550e68018827ec4

docs/Quick-Start.md
Hello,
Just started to read [Quick start](https://docs.victoriametrics.com/Quick-Start.html) and did some notes :)
Thank you!
=> Possibly spelling in the Quick start

docs/managed-victoriametrics/README.md, docs/managed-victoriametrics/how-to-monitor-k8s.md, docs/managed-victoriametrics/overview.md, docs/managed-victoriametrics/quickstart.md, docs/managed-victoriametrics/user-managment.md
Changes:
- use Readme as an index
- move the old Readme to the Overview page
- add sorting for every page
=> change docs for VictoriaMetrics Managed

docs/CHANGELOG.md
=> follow-up after d1cbc35cf6010204c7267a3d3a5c9d0412a29e90

app/vmalert/README.md, docs/keyConcepts.md, docs/vmalert.md
=> docs: improve troubleshooting docs for vmalert

app/vmui/packages/vmui/src/components/Layout/Header/Header.tsx, app/vmui/packages/vmui/src/pages/CardinalityPanel/hooks/useSetQueryParams.ts, app/vmui/packages/vmui/src/pages/CustomPanel/hooks/useSetQueryParams.ts, app/vmui/packages/vmui/src/pages/ExploreMetrics/hooks/useSetQueryParams.ts, app/vmui/packages/vmui/src/pages/PredefinedPanels/hooks/useSetQueryParams.ts, app/vmui/packages/vmui/src/pages/TopQueries/hooks/useSetQueryParams.ts, app/vmui/packages/vmui/src/pages/TracePage/index.tsx, app/vmui/packages/vmui/src/utils/query-string.ts
Change the query parameter update to the `useSearchParams` method provided by `react-router-dom`.
=> vmui: change query params update

app/vmagent/remotewrite/client.go, app/vmalert/datasource/vm.go, app/vmalert/notifier/alertmanager.go, app/vmalert/remotewrite/remotewrite.go, app/vmctl/remoteread/remoteread.go, app/vmctl/vm/vm.go, app/vmselect/prometheus/prometheus_test.go, app/vmselect/searchutils/searchutils_test.go, lib/awsapi/config.go, lib/awsapi/sign.go, lib/promauth/config_test.go, lib/promscrape/discovery/gce/api.go, lib/promscrape/discovery/kubernetes/api_watcher.go, lib/promscrape/discovery/openstack/api.go, lib/promscrape/discovery/yandexcloud/api.go, lib/protoparser/common/extra_labels_test.go
Use http constants to replace numbers
=> chore: Use http constants to replace numbers

app/vmui/packages/vmui/src/components/Layout/Layout.tsx, app/vmui/packages/vmui/src/pages/CustomPanel/QueryConfigurator/QueryConfigurator.tsx, app/vmui/packages/vmui/src/pages/CustomPanel/index.tsx
- Show the error "Please enter a valid Query and execute it" only after executing the query.
- Add support for links with old query params.
=> vmui: show query error

.github/ISSUE_TEMPLATE/question.yml
checkboxes do not support markdown(
=> github: fix validation errors

docs/operator/high-availability.md
Added info about `%SHARD_NUM%` placeholder to HA-section of operator doc. Added example of podAntiAffinity for vmagent.
issue: https://github.com/VictoriaMetrics/operator/issues/592
pr: https://github.com/VictoriaMetrics/operator/pull/598
=> added doc for %SHARD_NUM% placeholder support in vmagent specification for operator (VictoriaMetrics/operator#598)

app/vmctl/README.md, docs/CHANGELOG.md, docs/vmctl.md
=> docs: follow up after 4b136abff8fef02f670d63e7de7ac0cab73f0b9e

README.md, docs/README.md, docs/Single-server-VictoriaMetrics.md
See:
https://github.com/VictoriaMetrics/VictoriaMetrics/blob/2ac2f410121bb0306d5ddaae4caf6c6db39dedfa/README.md#install
For rendered version of this PR
=> docs: move installation methods further up in README

app/vmalert/group.go, app/vmalert/manager.go
Each group in vmalert starts with an artifical delay to avoid
thundering herd problem. For some groups with high evaluation
intervals, the delay could be significant.
If during this delay user will remove the group from the config
and hot-reload it - vmalert will have to wait until the delay
ends. This results into slow config reloading and UI hang.
The change moves the start-delay logic back to the group's
`start` method. Now, group can immediately exit from the
delay when `group.close()` method is called.
=> app/vmalert: do not wait for group start on removal

app/vmui/packages/vmui/src/components/Main/Select/MultipleSelectedValue/MultipleSelectedValue.tsx, app/vmui/packages/vmui/src/components/Main/Select/Select.tsx, docs/CHANGELOG.md
Fixes the issue where the selected value is not displayed in the selector in desktop version.
=> vmui: fix display of selected value in the selector

docs/operator/vmalertmanager-configuration.md
https://github.com/VictoriaMetrics/operator/issues/592
=> Documentation about `templates` field of vmalertmanager spec

app/vmui/packages/vmui/src/api/query-range.ts, docs/CHANGELOG.md
=> vmui: remove send step param for instant queries

app/vmctl/testdata/servers_integration_test/remote_write_server.go, app/vmctl/vm_native_test.go
I have Implemented integration tests for the backfilling process by [native bynary protocol](https://docs.victoriametrics.com/vmctl.html#native-protocol). 
=> app/vmctl: integration test for native protocol

app/vmselect/promql/timeseries_test.go
@valyala thank you for the proper fix of #3927 in 0af9e2b69340b068590f36f41e53261c1046fe11.
This PR augments the tests to ensure proper alignment of the `[]float64` and `[]int64` (to prevent eventual regression in the future).
I think the code currently works, because new `[]byte` allocation in Go are currently 16 byte aligned (at least according to https://blog.chewxy.com/2016/07/25/on-the-memory-alignment-of-go-slice-values/).
However the [Language Specification](https://go.dev/ref/spec#Size_and_alignment_guarantees) does not guarantee such an alignment for `[]byte` slices, so this may break in the future.
The added test should help catch such issue.
=> app/vmselect/promql: add test to ensure 8-byte alignment

deployment/docker/alerts-health.yml
See https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3502#issuecomment-1358374954
=> alerts: add `TooManyTSIDMisses` alerting rule

app/vmalert/notifier/alert.go, app/vmalert/notifier/alert_test.go, app/vmalert/notifier/init.go, app/vmalert/notifier/init_test.go, app/vmalert/remotewrite/init_test.go, app/vmalert/templates/template_test.go, app/vmalert/web_test.go
=> Vmalert tests

app/vmctl/terminal/terminal.go, app/vmctl/terminal/unix.go, app/vmctl/terminal/unix_bsd.go, app/vmctl/terminal/windows..go
=> app/vmctl: follow up after aed59b90298a6b5e44ffea4543a6aa3b9e402e65

app/vmui/packages/vmui/src/components/Chart/Legend/LegendItem/LegendItem.tsx, app/vmui/packages/vmui/src/components/Main/TextField/style.scss, app/vmui/packages/vmui/src/hooks/useFetchQuery.ts, app/vmui/packages/vmui/src/pages/CustomPanel/QueryConfigurator/QueryConfigurator.tsx, app/vmui/packages/vmui/src/pages/CustomPanel/index.tsx, docs/CHANGELOG.md
- fix display errors for each query
- when there is an error in one of the queries, the others will still be displayed.
- #3987
=> vmui: display errors for each query

app/vmselect/promql/eval.go
This PR reduces lock contention caused by increased parallelism for `evalRollup*` functions evaluation because of
work stealing implemented at https://github.com/VictoriaMetrics/VictoriaMetrics/commit/53d871d0b173242c8f4ce13defd81abb861c358a.
On systems with high number of CPUs better parallelism and using locks to merge results of computation leaded to contentions and caused higher CPU usage than in prior versions.
See #3966 for more details and results of these optimizations.
=> app/vmselect/promql: use lock-less approach to gather results of parallel processing for `evalRollup*` funcs

lib/filestream/filestream_windows.go, lib/fs/fs_windows.go, lib/storage/part_header.go, lib/storage/partition.go, lib/storage/table.go
it should improve performance for file reading at https://github.com/VictoriaMetrics/VictoriaMetrics/issues/70
=> lib/fs: adds memory map for windows

app/vmui/packages/vmui/src/components/Configurators/GlobalSettings/GlobalSettings.tsx, app/vmui/packages/vmui/src/components/Configurators/GlobalSettings/LimitsConfigurator/LimitsConfigurator.tsx, app/vmui/packages/vmui/src/components/Configurators/GlobalSettings/ServerConfigurator/ServerConfigurator.tsx, app/vmui/packages/vmui/src/components/Configurators/GlobalSettings/Timezones/style.scss, app/vmui/packages/vmui/src/components/Configurators/GlobalSettings/style.scss, app/vmui/packages/vmui/src/components/Configurators/ThemeControl/ThemeControl.tsx, app/vmui/packages/vmui/src/hooks/useFetchQuery.ts
=> vmui: add apply button to the settings popup

lib/storage/partition_test.go
=> lib/storage: remove unused code

app/vmalert/README.md, app/vmalert/main.go, docs/vmalert.md
=> app/vmalert: update Grafana URLs to match latest format

deployment/docker/docker-compose-cluster.yml, deployment/docker/docker-compose.yml
=> deployment/docker: update Grafana URLs to match latest format

app/vmui/packages/vmui/src/components/Chart/GraphTips/contants/tips.tsx, app/vmui/packages/vmui/src/components/Main/ShortcutKeys/ShortcutKeys.tsx, app/vmui/packages/vmui/src/components/Main/ShortcutKeys/constants/keyList.tsx, app/vmui/packages/vmui/src/components/Main/ShortcutKeys/style.scss
- correct the description of shortcut keys
- add a hotkey to call up the modal window for shortcut keys (`Cmd` + `/` for macOS or `F1` for other platforms.)
- refactor the component for the list of shortcut keys.
=> vmui: correct the description of shortcut keys

app/vmui/packages/vmui/src/hooks/useFetchQuery.ts, app/vmui/packages/vmui/src/utils/default-server-url.ts, app/vmui/packages/vmui/src/utils/uplot/heatmap.ts
- hide empty buckets from the graph
- change the logic of histogram detection
- correct display of errors when there are hidden queries 
=> vmui: heatmap fixes

lib/storage/storage.go
fix https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4094
=> lib/storage: fix sort pendingDateMetrics

docs/Makefile, docs/guides/understand-your-setup-size.md
- added info about metric `vm_vminsert_metrics_read_total`,
- small doc refactoring
- and added make-command for running docs in docker.
issue #4172
=> doc improvements (#4172)

docs/CHANGELOG.md
=> changelog for issue #4083

deployment/docker/alerts-health.yml
relax job filter in health alerts to allow jobs created by VMOperator
=> relax job filter to allow jobs created by VMOperator

docs/CHANGELOG.md, lib/memory/memory.go
=> max value for `memory.allowedPercent` changed from 200 to 100 (#4171)

app/vmalert/config/config.go, app/vmalert/config/config_test.go, app/vmalert/config/fs.go, app/vmalert/config/url.go, app/vmalert/main.go
fix https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3352
=> vmalert: support reading rule from http url

README.md, docs/Quick-Start.md, docs/README.md, docs/Single-server-VictoriaMetrics.md
Added information about VictoriaMetrics datasource plugin and how to install it
=> docs: Add information about datasource plugin

lib/storage/index_db.go, lib/storage/index_db_test.go, lib/storage/storage.go
The new index substitutes global MetricName=>TSID index used for locating TSIDs on ingestion path.
For installations with high ingestion and churn rate, global MetricName=>TSID index can grow enormously making
index lookups too expensive. This also results into bigger than expected cache growth for indexdb blocks.
New per-day index supposed to be much smaller and more efficient. This should improve ingestion speed and reliability during re-routings in cluster.
The negative outcome could be occupied disk size, since per-day index is more expensive comparing to global index.
=> lib/storage: introduce per-day MetricName=>TSID index

lib/storage/index_db.go
=> [fix]fix lint check

app/vmctl/testdata/servers_integration_test/remote_write_server.go
In the import handler, we are using `stream.Parse` function. This function runs callback in the goroutines, so we have a situation when two goroutines write to the same slice simultaneously. To prevent this situation, I added mutex. 
To check that all tests work well, I have run this script
```bash
for i in {1..1000}; do go test -run Test_vmNativeProcessor_run || echo TESTS WAS FAILED; done
```
=> app/vmctl: fix vm-native tests

app/vmalert/tpl/header.qtpl, app/vmalert/tpl/header.qtpl.go, app/vmalert/utils/links.go, docs/CHANGELOG.md
Properly form path to static assets in WEB UI
if `http.pathPrefix` set.
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4349
=> vmalert: properly form assets address if httpPrefix set

app/vmselect/netstorage/netstorage.go
fix https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4364
=> vmselect:fix init sn take too much time

app/vmalert/datasource/vm.go, app/vmalert/datasource/vm_test.go
=> app/vmalert: fix datasource.roundDigits Parameter

app/vmalert/Makefile, app/vmalert/datasource/vm.go
https://github.com/VictoriaMetrics/VictoriaMetrics/pull/4341/commits/7a9ae9de0d2221cf7759e49ebcde0a06508b0f68
=> app/vmalert: follow-up after 7a9ae9de0d2221cf7759e49ebcde0a06508b0f68

lib/promauth/config.go, lib/promscrape/client.go, lib/promscrape/config.go, lib/promscrape/discovery/azure/api.go, lib/promscrape/discovery/azure/machine_test.go, lib/promscrape/discovery/consul/api.go, lib/promscrape/discovery/consulagent/api.go, lib/promscrape/discovery/digitalocean/api.go, lib/promscrape/discovery/docker/api.go, lib/promscrape/discovery/dockerswarm/api.go, lib/promscrape/discovery/eureka/api.go, lib/promscrape/discovery/http/api.go, lib/promscrape/discovery/kuma/api.go, lib/promscrape/discovery/nomad/api.go, lib/promscrape/discoveryutils/client.go, lib/promscrape/discoveryutils/client_test.go, lib/promscrape/scrapework.go, lib/promscrape/testdata/prometheus.yml
fix https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4283
=> vmagent:scrape config support enable_http2

docs/CHANGELOG.md
https://github.com/VictoriaMetrics/VictoriaMetrics/pull/4418/commits/a6a7795b9e1f210d614a2c5f9a3016b97ded4792
=> docs/changelog: mention a6a7795b9e1f210d614a2c5f9a3016b97ded4792 change

docs/operator/api.md
the links to the Kubernetes documentation have changed the version from v1.22 to v1.27
=> docs/api corrected broken links to Kubernetes documentation 

lib/mergeset/table.go
https://github.com/VictoriaMetrics/VictoriaMetrics/pull/4449/commits
=> lib/mergeset: add comment for how mustBeDeleted field should be used 

README.md, docs/README.md, docs/Single-server-VictoriaMetrics.md
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4446
=> docs: mention errors processing for /api/v1/import API

docs/_includes/extra/script.js
Added scroll to the selected element in the sidebar menu. 
=> docs: add scroll to the selected element

docs/CHANGELOG.md
https://github.com/VictoriaMetrics/VictoriaMetrics/pull/4571/commits/9da638aa665d5e27462e5fef0e53dfaca31fdbb3
=> docs: follow-up after 9da638aa665d5e27462e5fef0e53dfaca31fdbb3

app/vmselect/netstorage/netstorage.go
follow up https://github.com/VictoriaMetrics/VictoriaMetrics/pull/4538
=> vmselect: fix result collect count

docs/keyConcepts.md
Followup for https://github.com/VictoriaMetrics/VictoriaMetrics/commit/b67bd156d59775d93251f0f00dabb76766d9b8c0
=> doc: fix image src after b67bd156

docs/stream-aggregation.md
=> added info about using stream aggregation as statsd alternative (#4600)

docs/stream-aggregation.md
=> fixed typo

docs/CHANGELOG.md, go.mod, go.sum, vendor/github.com/cheggaaa/pb/v3/pool_win.go, vendor/github.com/cheggaaa/pb/v3/pool_x.go, vendor/modules.txt
The problem was fixed via this issue: https://github.com/cheggaaa/pb/issues/207
Related issue: https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4555
=> app/vmctl: fix issue with adding many seconds

app/vmui/packages/vmui/src/components/Layout/Footer/Footer.tsx
Added link to [MetricsQL](https://docs.victoriametrics.com/MetricsQL.html) in the footer.
#4562
=> vmui: add link to MetricsQL

app/vmctl/README.md, docs/vmctl.md
Addresses https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4624
=> vmctl: mention replicationFactor during migration

README.md, app/victoria-metrics/main.go, app/vlselect/logsql/logsql.go, app/vlstorage/main.go, app/vmagent/README.md, app/vmalert/README.md, app/vmauth/README.md, app/vmbackup/README.md, app/vmbackupmanager/README.md, app/vmgateway/README.md, app/vmrestore/README.md, docs/Cluster-VictoriaMetrics.md, docs/README.md, docs/Single-server-VictoriaMetrics.md, docs/VictoriaLogs/README.md, docs/vmagent.md, docs/vmalert.md, docs/vmauth.md, docs/vmbackup.md, docs/vmbackupmanager.md, docs/vmgateway.md, docs/vmrestore.md, lib/bytesutil/internstring.go, lib/envflag/envflag.go, lib/memory/memory.go, lib/netutil/tcplistener.go
https://github.com/VictoriaMetrics/VictoriaMetrics/pull/4613/commits/aec4b5db81b3595aee4593c426e7ed6375882d55
=> docs: follow-up after aec4b5db81b3595aee4593c426e7ed6375882d55

app/vlinsert/loki/loki_protobuf.go
Loki uses default labels format without "or" operator. This format can't create a list of LabelFilters, so only first set of LabelFilters should be used.
=> app/vlinsert/loki: fix compatibility with latest MetricsQL lib

docs/CHANGELOG.md, docs/stream-aggregation.md, lib/streamaggr/histogram_bucket.go, lib/streamaggr/increase.go, lib/streamaggr/streamaggr.go, lib/streamaggr/total.go
=> allow configuring staleness interval in stream aggregation (#4667)

app/vmselect/promql/active_queries.go, docs/CHANGELOG.md
Change the response to valid json for active queries
Fixed this bug: https://github.com/VictoriaMetrics/VictoriaMetrics/pull/4676#issuecomment-1663203424
=> vmui: change the response for active queries

app/vmctl/README.md, docs/vmctl.md
Follow up after: https://github.com/VictoriaMetrics/VictoriaMetrics-enterprise/commit/5aed369132b3e38d85bb29709b23d861503d9ff0
Signed-off-by: dmitryk-dk d.kozlov@victoriametrics.com
=> add migration guide from Promscale

lib/logstorage/storage.go
=> lib/logstorage: add nil check for ptwHot.pt

lib/logstorage/storage.go
- Set `ptwHot` to nil when the partition pointed by ptwHot is dropped.
- Set `ptwHot` to nil when close Storage.
=> lib/logstorage: Optimize ptwHot to nil

app/vlinsert/loki/loki.go
Some log shippers verify health of Loki before pushing, adding this endpoint will make it easier to configure such shippers.
See: https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4762
=> app/vlinsert/loki: add handler for healthcheck endpoint

app/vmauth/README.md, app/vmauth/auth_config.go, app/vmauth/auth_config_test.go, app/vmauth/example_config.yml, app/vmauth/main.go, app/vmauth/target_url.go, app/vmauth/target_url_test.go, docs/CHANGELOG.md, docs/vmauth.md
=> vmauth: added ability to set and remove response headers (#4825)

app/vmui/packages/vmui/src/hooks/useFetchQuery.ts, docs/CHANGELOG.md
- Fix the bug causing render looping when switching to heatmap.
- Fix flickering when switching to the heatmap.
=> vmui: fix render heatmap

README.md, docs/CHANGELOG.md, docs/README.md, docs/Single-server-VictoriaMetrics.md
- added changelog entry
- documented requirements for `dedup.minScrapeInterval` and `downsampling.period` being multiples of each other
=> docs: add changelog entry for downsampling.period and dedup.minScrapeInterval verification

lib/storage/partition.go
for fix https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4987
=> lib/storage: remove ForceMergeAllParts internal loop

app/vmselect/graphite/render_response.qtpl, app/vmselect/graphite/render_response.qtpl.go
0/0 = NaN
123/0 = +Inf
Fixes #3783
=> app/vmselect: return +Inf as null in graphite render api

README.md, docs/README.md, docs/Single-server-VictoriaMetrics.md
Address: https://github.com/VictoriaMetrics/VictoriaMetrics/issues/5076
=> doc: mention InfluxDB v2 HTTP API support

lib/logstorage/datadb.go
It was added in order to limit number of goroutines performing assisted merges during ingestion. It turned out that blocking ingestion goroutines lower ingestion performance and limits overall ingestion around 40k items per seconds because of lock contention. Removing parts merge sync.Cond allows to remove lock contention at write path and significantly improves write performance.
See: https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4775
=> lib/logstorage/datadb: remove parts merge cond

README.md, docs/README.md, docs/Single-server-VictoriaMetrics.md
Use service configuration example from https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3781#issuecomment-1424671624
=> docs: add example service configuration for windows

app/vmui/packages/vmui/package-lock.json, app/vmui/packages/vmui/package.json, app/vmui/packages/vmui/src/hooks/useFetchQuery.ts, app/vmui/packages/vmui/src/hooks/useFetchQueryOptions.tsx, app/vmui/packages/vmui/src/hooks/useStateSearchParams.ts, app/vmui/packages/vmui/src/pages/CustomPanel/QueryConfigurator/QueryConfigurator.tsx, app/vmui/packages/vmui/src/pages/CustomPanel/QueryConfigurator/style.scss
Update all the dependencies to their latest versions
=> vmui: update dependencies

docs/CaseStudies.md
=> docs/CaseStudies: update usecase info

app/vmui/packages/vmui/src/components/Configurators/AdditionalSettings/AdditionalSettings.tsx, app/vmui/packages/vmui/src/components/Main/ShortcutKeys/constants/keyList.tsx
Changed autocomplete hotkey to `Alt/Option + A`
ref: #5253
=> vmui: fix autocomplete hotkey

app/vmalert/README.md, docs/vmalert.md
Please see discussion here https://github.com/VictoriaMetrics/VictoriaMetrics/issues/5279
=> docs/vmalert: clarify deduplication recommendations for HA setup

app/vlinsert/elasticsearch/elasticsearch.go
PR for issue: https://github.com/VictoriaMetrics/VictoriaMetrics/issues/5065
=> app/vlinsert/elasticsearch: add _stream fields logs

docs/guides/guide-vmanomaly-vmalert.md, docs/vmanomaly.md
- versions upgrade, 
- config change
- minor text change
=> Guide - vmanomaly v1.7.0 changes

README.md, docs/README.md, docs/Single-server-VictoriaMetrics.md, docs/url-examples.md
=> docs: explicitly mention "delete_series" endpoint accepts any HTTP method

app/vmui/packages/vmui/src/components/Configurators/QueryEditor/QueryEditor.tsx, app/vmui/packages/vmui/src/components/ExploreMetrics/ExploreMetricsHeader/ExploreMetricsHeader.tsx
Add autofocus to input for desktop version. 
- Ref: #5479
=> vmui: add autofocus to inputs

docs/anomaly-detection/CHANGELOG.md, docs/anomaly-detection/README.md, docs/anomaly-detection/components/monitoring.md
- add 1.8.0 notes to changelog
=> add 1.8.0 notes to changelog

Makefile
=> Follow up after https://github.com/VictoriaMetrics/VictoriaMetrics/pull/5685

app/vmauth/main.go
for use case when only one backend is available - if we get an error from the retry_status_codes list, but cannot execute retry, we increment vmauth_user_request_backend_errors_total as well
=> vmauth: fix `vmauth_user_request_backend_errors_total` metric 

deployment/docker/vmanomaly/vmanomaly-integration/docker-compose.yml, deployment/docker/vmanomaly/vmanomaly-integration/vmanomaly_guide_dashboard.json, docs/anomaly-detection/Overview.md, docs/anomaly-detection/guides/guide-vmanomaly-vmalert.md
- version 1.9.1 update in guide and overview
- grafana dashboard viz flag
=> version 1.9.1 update, dashboard viz flag

app/vmui/packages/vmui/src/components/Configurators/QueryEditor/QueryEditor.tsx
Fixed https://github.com/VictoriaMetrics/VictoriaMetrics/pull/5681#issuecomment-1912822226
Refs: #5470 and #5667
=> vmui: fix `Enter` key in query field 

README.md, docs/README.md, docs/Single-server-VictoriaMetrics.md, docs/VictoriaLogs/data-ingestion/README.md, docs/VictoriaLogs/querying/README.md
=> Change ndjson links to https://jsonlines.org/ as original one was hacked

lib/httputils/duration.go
=> [lib/httputils] fixed error message for getting zero duration (#5795)

deployment/docker/vmanomaly/vmanomaly-integration/docker-compose.yml, deployment/docker/vmanomaly/vmanomaly-integration/vmanomaly_config.yml, docs/anomaly-detection/CHANGELOG.md, docs/anomaly-detection/Overview.md, docs/anomaly-detection/components/README.md, docs/anomaly-detection/components/models.md, docs/anomaly-detection/components/scheduler.md, docs/anomaly-detection/guides/guide-vmanomaly-vmalert.md
- v1.11 doc updates
- fix dead links
=> docs: vmanomaly v1.11.0 updates

app/victoria-metrics/main_test.go, app/victoria-metrics/testdata/csv/basic.json, app/victoria-metrics/testdata/csv/with_extra_labels.json, app/vmselect/prometheus/export.qtpl, app/vmselect/prometheus/export.qtpl.go, docs/CHANGELOG.md, lib/protoparser/csvimport/parser_test.go
=> changes export/csv timestamp formato for rfc3339

docs/CaseStudies.md
We want to add our experience and solution on VictoriaMetrics
=> add xiaohongshu in Case studies

app/vmalert/config/testdata/rules/kube-good.rules
Hi @zekker6, it's me the guy in the PR https://github.com/VictoriaMetrics/VictoriaMetrics/pull/5947
I messed with the context of git in the last PR. I tried to resign all unsigned commit but I realize that I use different machine to perform the commit so it messed up.
I created this new PR to simplify the solution.
Thank you for your help.
=> feat: include cluster info in alert CPUThrottlingHigh

docs/anomaly-detection/guides/guide-vmanomaly-vmalert.md
- link to docker deployment file
=> docs/vmanomaly: fix 404 links in guide

app/vmagent/main.go, app/vmagent/opentelemetry/request_handler.go, app/vminsert/main.go, app/vminsert/opentelemetry/request_handler.go, docs/CHANGELOG.md, lib/protoparser/opentelemetry/firehose/parser.go
Fixed AWS Firehose HTTP destination response
=> app/{vmagent,vminsert}: fixed firehose response

docs/anomaly-detection/components/models.md
just a small PR with following typo/links corrections and term formatting alignment
=> docs/vmanomaly: typos fix

lib/promscrape/client.go
=> lib/promscrape/config: fix missing timeout for http client

.github/PULL_REQUEST_TEMPLATE/pull_request_template.md, CONTRIBUTING.md
This PR is based on @tenmozes changes from https://github.com/VictoriaMetrics/VictoriaMetrics/tree/pr-template
Updates:
- set up PR template with information about requirements to the contribution
- update contributing doc to include mandatory requirements to the contribution
=> [docs][github] Update contributing information

app/vmalert/notifier/alertmanager.go, docs/CHANGELOG.md
=> vmalert: support any status code from the range 200-299 from alertmanager as successful

deployment/docker/victorialogs/fluentbit-docker/docker-compose.yml
see also https://fluentbit.io/announcements/v3.0.0/
=> deployment/docker/victorialogs/fluentbit-docker/docker-compose.yml: update fluentbit version from v2.1.4 to v3.0.2

deployment/docker/Makefile
Updated package targets in a same manner, how it's done for publish ones in https://github.com/VictoriaMetrics/VictoriaMetrics/commit/7958f3886467aef1a386e3111136f1d3c59f7149
=> updated makefile package-* targets

deployment/docker/alerts.yml
=> minor grammatical fixes in alert descriptions

docs/MetricsQL.md
=> docs: added information about difference between default_rollup and last_over_time

app/vmagent/remotewrite/pendingseries_test.go, app/vmctl/opentsdb/opentsdb.go, docs/stream-aggregation.md
=> chore: remove redundant words

docs/anomaly-detection/FAQ.md, docs/anomaly-detection/README.md
More explicit [vmanomaly FAQ](https://docs.victoriametrics.com/anomaly-detection/faq/index.html), based on common Q&A from recent communications with users
- :heavy_check_mark: My change adheres [VictoriaMetrics contributing guidelines](https://docs.victoriametrics.com/contributing/).
=> docs/vmanomaly: improve FAQ

docs/MetricsQL.md
=> docs/metricsql: fix typo in link

dashboards/vm/vmagent.json, dashboards/vmagent.json, deployment/docker/alerts-vmagent.yml, deployment/docker/docker-compose-cluster.yml, deployment/docker/docker-compose-victorialogs.yml, deployment/docker/docker-compose.yml, deployment/docker/vm-datasource/docker-compose-cluster.yml, deployment/docker/vm-datasource/docker-compose.yml, docs/CHANGELOG.md
Added streaming aggregation section to vmagent dashboards
Added alert for streaming aggregation and deduplication flush timeouts
Removed deprecated compose versions from compose files
=> vmagent: updated dashboard and alert for stream aggregation

deployment/docker/alerts-vmalert.yml
Fixes https://github.com/VictoriaMetrics/VictoriaMetrics/issues/6439
=> removed exclusion of recording label in alert expression, which is utilized in alert annotations

docs/MetricsQL.md
=> Small fix in MetricsQL.md

dashboards/operator.json
Corrected spelling mistake in the operator json to be "working" instead of "wokring"
- [ x ] My change adheres [VictoriaMetrics contributing guidelines](https://docs.victoriametrics.com/contributing/).
=> updating operator dashboard chart to be titled working instead of wokring

app/vminsert/relabel/relabel.go
* fixes linter error
* simplify code a bit
* fixes bug with incorrectly set configSuccess metric. It was not set to 1 in case of config rollback
=> follow-up after 77f22fdb8d31d30dab76ec00afa06d2823d462c4

docs/guides/getting-started-with-opentelemetry.md
=> docs/guides/otel-guide: update sentence to make it less obscure

docs/CHANGELOG.md, lib/backup/s3remote/s3.go
properly use credsFilePath flag value
fixes #6353
=> lib/backup/s3remote: fixed credsFilePath flag

app/vmalert/notifier/alertmanager.go, docs/CHANGELOG.md
=> fix VMAlert oauth2 error

app/vmalert-tool/unittest/testdata/rules.yaml, app/vmalert-tool/unittest/unittest.go, docs/CHANGELOG.md
address https://github.com/VictoriaMetrics/VictoriaMetrics/issues/6500
=> vmalert-tool: exit normally when no rule is defined under rule group

app/vmui/packages/vmui/src/constants/footerLinks.ts, app/vmui/packages/vmui/src/layouts/Footer/Footer.tsx, app/vmui/packages/vmui/src/layouts/LogsLayout/LogsLayout.tsx
Update the links in the footer for logs: [LogsQL](https://docs.victoriametrics.com/victorialogs/logsql/) and [Documentation](https://docs.victoriametrics.com/victorialogs/)
=> vmui/logs: update footer links

.github/workflows/benchmark.yml, app/victoria-logs/multiarch/Dockerfile, app/victoria-metrics/multiarch/Dockerfile, app/vmagent/multiarch/Dockerfile, app/vmalert-tool/multiarch/Dockerfile, app/vmalert/multiarch/Dockerfile, app/vmauth/multiarch/Dockerfile, app/vmbackup/multiarch/Dockerfile, app/vmctl/multiarch/Dockerfile, app/vmrestore/multiarch/Dockerfile, app/vmui/Dockerfile-web, deployment/docker/Makefile, deployment/docker/base/Dockerfile
optionally build vmagent image for benchmark
needed for https://github.com/VictoriaMetrics/ops/pull/1297
=> build image for vmagent streamaggr benchmark

app/vmui/packages/vmui/package-lock.json, app/vmui/packages/vmui/src/hooks/useFetchQuery.ts, app/vmui/packages/vmui/src/hooks/useFetchQueryOptions.tsx, app/vmui/packages/vmui/src/hooks/useStateSearchParams.ts, app/vmui/packages/vmui/src/pages/CustomPanel/QueryConfigurator/QueryConfigurator.tsx
1. Updated `package-lock.json` to resolve [Dependabot alerts](https://github.com/VictoriaMetrics/VictoriaMetrics/security/dependabot).
2. Updated types to align with the latest `Preact` update.
=> vmui: update package-lock.json

.github/workflows/codeql-analysis-js-ts.yml
Enables CodeQL TypeScript analysis.
=> Update CodeQL: run analysis for both JavaScript and TypeScript

dashboards/clusterbytenant.json
=> update statistic by tenant dashboard, fix billing disk usage pie panel

dashboards/vm/vmagent.json, dashboards/vmagent.json
=> vmagent-dashboard: update streaming aggregation panels

README.md, docs/Cluster-VictoriaMetrics.md, docs/Single-server-VictoriaMetrics.md, docs/stream-aggregation.md
=> docs: fix typos

docs/anomaly-detection/components/models.md
Fixed Custom Model guide according to newer `vmanomaly` versions
=> docs/vmanomaly:custom model guide fix

app/vmui/packages/vmui/src/pages/ExploreLogs/ExploreLogs.tsx, app/vmui/packages/vmui/src/pages/ExploreLogs/ExploreLogsBarChart/ExploreLogsBarChart.tsx, app/vmui/packages/vmui/src/pages/ExploreLogs/hooks/useFetchLogHits.ts, app/vmui/packages/vmui/src/pages/ExploreLogs/hooks/useFetchLogs.ts, docs/VictoriaLogs/CHANGELOG.md
Add a spinner to the bar chart 
#6558
=> vmui/logs: add spinner to bar chart

docs/managed-victoriametrics/alertmanager-setup-for-deployment.md
=> vmcloud: fixed image paths for cloud alertmanager docs

docs/managed-victoriametrics/alertmanager-setup-for-deployment.md
=> vmcloud: fixed images in cloud alertmanager docs

docs/anomaly-detection/CHANGELOG.md
Add patch note v1.13.3 to CHANGELOG doc page for `vmanomaly`
=> docs/vmanomaly - v1.13.3 patch notes

app/vmui/packages/vmui/src/pages/ExploreLogs/ExploreLogs.tsx, app/vmui/packages/vmui/src/pages/ExploreLogs/ExploreLogsBarChart/ExploreLogsBarChart.tsx, app/vmui/packages/vmui/src/pages/ExploreLogs/hooks/useFetchLogs.ts
This PR changes `/select/logsql/query` and `/select/logsql/hits` to execute sequentially
Fixed https://github.com/VictoriaMetrics/VictoriaMetrics/issues/6558#issuecomment-2219298984
=> vmui/logs: switched requests to sequential execution

docs/Articles.md, docs/BestPractices.md, docs/Cluster-VictoriaMetrics.md, docs/ExtendedPromQL.md, docs/FAQ.md, docs/MetricsQL.md, docs/Quick-Start.md, docs/README.md, docs/Release-Guide.md, docs/Single-server-VictoriaMetrics.md, docs/Troubleshooting.md, docs/goals.md, docs/guides/migrate-from-influx.md, docs/keyConcepts.md, docs/relabeling.md, docs/sd_configs.md, docs/stream-aggregation.md, docs/url-examples.md, docs/vmagent.md, docs/vmalert.md, docs/vmauth.md, docs/vmbackup.md, docs/vmctl.md, docs/vmgateway.md, docs/vmrestore.md
Replaced global http links in docs with relative markdown ones
=> replaced global http refs with relative markdown ones

docs/VictoriaLogs/CHANGELOG.md, docs/VictoriaLogs/LogsQL.md
=> fixed victorialogs relative links

docs/anomaly-detection/CHANGELOG.md
- Doc updates on v1.14.1 - v1.14.2 of `vmanomaly`
- [Changelog](https://docs.victoriametrics.com/anomaly-detection/changelog/) page
=> docs/vmanomaly - changelog upd v1.14.1-v1.14.2

lib/backup/s3remote/s3.go
Fixes a few typos in errors in lib/backup/s3remote package.
=> lib/backup/s3remote: fix typos

README.md, docs/README.md, docs/Single-server-VictoriaMetrics.md
updates
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/5810
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/2969
=> docs: mention graphite incompatibilities

docs/Quick-Start.md
=> docs: fix typo in quick start guide

docs/data-ingestion/vmagent.md, docs/guides/multi-regional-setup-dedicated-regions.md
fixed yaml header in a guide doc, that causes hugo build error
=> fixed docs build

docs/anomaly-detection/CHANGELOG.md, docs/anomaly-detection/components/models.md, docs/anomaly-detection/components/reader.md
vmanomaly - release v1.15.1 updates to docs:
- changelog page
- reader page (new arguments docs)
- typos & fixes
=> docs: vmanomaly - release v1.15.1

docs/anomaly-detection/CHANGELOG.md, docs/anomaly-detection/components/README.md, docs/anomaly-detection/components/models.md, docs/anomaly-detection/components/reader.md
typos fix & clarity improvement of vmanomaly docs after v1.15.1 release
=> docs/vmanomaly - typos fix & clarity

app/vmui/packages/vmui/src/components/Table/TableSettings/TableSettings.tsx, app/vmui/packages/vmui/src/components/Table/TableSettings/style.scss, app/vmui/packages/vmui/src/hooks/useSortedCategories.ts, app/vmui/packages/vmui/src/pages/ExploreLogs/ExploreLogsBody/TableLogs.tsx, docs/VictoriaLogs/CHANGELOG.md
fix #6668, just add **select all** and "unselect all" func.
https://github.com/user-attachments/assets/0c31385b-def0-4618-aa9c-5ba4bb6f56c3
=> Table tab select all

docs/anomaly-detection/CHANGELOG.md, docs/anomaly-detection/components/models.md
update vmanomaly docs to forthcoming release v1.15.2
=> docs: vmanomaly - release v1.15.2

docs/anomaly-detection/components/reader.md
small update to `data_range` parameter in uppermost config conversion example
=> docs: vmanomaly - reader page update

docs/anomaly-detection/CHANGELOG.md
changelog updates to v1.15.3 patch of `vmanomaly`
=> docs/vmanomaly - changelog update to v1.15.3

docs/anomaly-detection/CHANGELOG.md
release notes for 1.15.4 patch
=> docs: vmanomaly - release notes for 1.15.4

docs/anomaly-detection/Overview.md
Updated model list in Anomaly Detection Overview
=> docs/vmanomaly: updated model list in Overview

docs/anomaly-detection/CHANGELOG.md
docs: vmanomaly - v1.15.5 patch notes
=> docs: vmanomaly - v1.15.5 patch notes

docs/guides/guide-delete-or-replace-metrics/README.md
Adds a link to the API example section that describes how to delete metrics on VM Single.
=> docs/guides/guide-delete-or-replace-metrics/README.md: adds a link to the API examples

docs/anomaly-detection/CHANGELOG.md, docs/anomaly-detection/components/monitoring.md, docs/anomaly-detection/components/reader.md, docs/anomaly-detection/components/writer.md
release notes for patches 1.15.6 - 9
=> docs/vmanomaly - release notes v1.15.[6-9]

docs/Quick-Start.md
Describe steps to run VictoriaMetrics Single node or Cluster on VictoriaMetrics Cloud
=> quickstart: describe steps to run VM on VM Cloud

docs/vmalert.md
Add mentions of VictoriaMetrics Cloud to the documentation of vmalert where this info is helpful to a user.
=> vmalert docs: mention VM Cloud where it can be helpful to a user

app/vmalert/rule/group_timing_test.go, lib/streamaggr/streamaggr_timing_test.go
=> bug: fix slice init length

dashboards/victoriametrics-cluster.json, dashboards/vm/victoriametrics-cluster.json
Correct the spelling error of 'vminsert' in the dashboards.
=> dashboards: typo fix

docs/LTS-releases.md
=> docs: clarify why 1.102.1 was publicly available

deployment/docker/docker-compose-victorialogs.yml, deployment/docker/vm-datasource/docker-compose-cluster.yml, deployment/docker/vm-datasource/docker-compose.yml
Upgraded victoriametrics and victorialogs data source versions.
=> deployment: upgrade datasource versions

docs/changelog/CHANGELOG.md, lib/storage/index_db.go
follow up https://github.com/VictoriaMetrics/VictoriaMetrics/commit/4ecc370acb541447739e4c2c72e2d7179a650bd9
=> lib/storage: fix metric `vm_object_references{type="indexdb"}`

deployment/docker/victorialogs/fluentbit-ha-single-node/README.md, deployment/docker/victorialogs/fluentbit-ha-single-node/auth.yml, deployment/docker/victorialogs/fluentbit-ha-single-node/compose.yml, deployment/docker/victorialogs/fluentbit-ha-single-node/fluent-bit.conf, deployment/docker/victorialogs/logstash-ha-single-node/README.md, deployment/docker/victorialogs/logstash-ha-single-node/auth.yml, deployment/docker/victorialogs/logstash-ha-single-node/compose.yml, deployment/docker/victorialogs/logstash-ha-single-node/logstash.yml, deployment/docker/victorialogs/logstash-ha-single-node/pipeline.conf, deployment/docker/victorialogs/vector-ha-single-node/README.md, deployment/docker/victorialogs/vector-ha-single-node/auth.yml, deployment/docker/victorialogs/vector-ha-single-node/compose.yml, deployment/docker/victorialogs/vector-ha-single-node/vector.yaml, docs/VictoriaLogs/README.md
=> victorialogs: add HA example for logstash and fluentbit

app/vmui/packages/vmui/src/layouts/LogsLayout/ControlsLogsLayout.tsx, docs/VictoriaLogs/CHANGELOG.md
=> vmui/logs: add auto refresh

deployment/docker/victorialogs/fluentbit-ha-single-node/README.md, deployment/docker/victorialogs/fluentbit/README.md
Fix a typo; `filebeat.yml` -> `fluent-bit.conf`
=> docs: typo filebeat -> fluent-bit

deployment/docker/docker-compose-victorialogs.yml, deployment/docker/vm-datasource/docker-compose-cluster.yml, deployment/docker/vm-datasource/docker-compose.yml
Updated grafana plugins to the latest releases 
=> deployment/docker: update grafana datasources to the latest version

docs/CONTRIBUTING.md, docs/README.md
The change supposed to have more practical recommendations and reflect the real processes for maintaining the project.
=> docs: update CONTRIBUTING.md with practical requirements

app/vmalert/main.go, docs/vmalert.md
The change should help users to understand what happens on labels conflict.
=> app/vmalert: mention labels conflict resolution strategy

deployment/docker/victorialogs/fluentd/Dockerfile, deployment/docker/victorialogs/fluentd/compose.yml, deployment/docker/victorialogs/fluentd/elasticsearch/fluent.conf, deployment/docker/victorialogs/fluentd/jsonline/fluent.conf, deployment/docker/victorialogs/fluentd/loki/fluent.conf
Use fluentd logging driver in examples to have enriched data in VictoriaLogs
=> Fluentd changed input type in examples

app/vmselect/prometheus/prometheus.go, app/vmstorage/servers/vmselect.go, docs/Cluster-VictoriaMetrics.md, lib/storage/index_db.go, lib/storage/storage.go, lib/storage/storage_test.go
This is the cluster version for #7091
=> Introduce a flag for limiting the number of time series to delete (cluster version)

docs/victoriametrics-cloud/support.md
=> docs: cloud add support page

docs/README.md
=> docs: add note that otel is not using streaming parsing

deployment/docker/vmanomaly/vmanomaly-integration/docker-compose.yml, docs/anomaly-detection/CHANGELOG.md, docs/anomaly-detection/FAQ.md, docs/anomaly-detection/Overview.md, docs/anomaly-detection/QuickStart.md, docs/anomaly-detection/components/models.md, docs/anomaly-detection/guides/guide-vmanomaly-vmalert/README.md
doc updates for vmanomaly v1.16.0
=> docs/vmanomaly - release 1.16.0 docs

deployment/docker/vmanomaly/vmanomaly-integration/docker-compose.yml, docs/anomaly-detection/components/models.md, docs/anomaly-detection/guides/guide-vmanomaly-vmalert/README.md
update `vnanomaly` versions in examples
=> docs/vmanomaly - update versions in examples

deployment/docker/vmanomaly/vmanomaly-integration/docker-compose.yml, docs/anomaly-detection/CHANGELOG.md, docs/anomaly-detection/components/models.md, docs/anomaly-detection/guides/guide-vmanomaly-vmalert/README.md
`vmanomaly` patch release 1.16.1 updates
=> docs/vmanomaly: patch release 1.16.1

README.md
Fix https://github.com/VictoriaMetrics/VictoriaMetrics/issues/7155.
Some anchors became invalid after https://github.com/VictoriaMetrics/VictoriaMetrics/commit/58e667c89511ea86a22b88b6a1379bb342b8dd01. This PR fixed them.
=> fix: [doc] fixed anchor in readme

docs/anomaly-detection/FAQ.md, docs/anomaly-detection/Overview.md, docs/anomaly-detection/QuickStart.md
fix of typos and improper version references in code snippets of example usage
=> docs/vmanomaly: fix example snippets

lib/promscrape/client_test.go
This PR fixes #7062 
For hijacked connections, one has to read from the connection buffer, but still write directly to the connection. Otherwise, when reading directly from such connections, the first byte may be lost. This, in turn corrupts the ClientHello TLS handshake message and when the backend server receives it, it closes the connection and reports the following error in the log:
```
http: TLS handshake error from 127.0.0.1:33150: tls: first record does not look
like a TLS handshake
```
The first byte may be lost because underlying HTTP request handler may read it from the connection and put it into the buffer. As the result, subsequent connection reads won't see that byte.
-   See: https://github.com/golang/go/issues/27408
-   The fix is taken from : …
=> lib/promscrape: Fix TestClientProxyReadOk flaky test

docs/anomaly-detection/CHANGELOG.md, docs/anomaly-detection/components/reader.md, docs/anomaly-detection/components/writer.md
docs for `vmanomaly`, updated after release 1.16.2
=> docs/vmanomaly: release 1.16.2

docs/victoriametrics-cloud/api.md, docs/victoriametrics-cloud/audit-logs.md, docs/victoriametrics-cloud/support.md
=> docs: add audit logs page for Cloud

docs/FAQ.md, docs/Quick-Start.md, docs/victoriametrics-cloud/alertmanager-setup-for-deployment.md, docs/victoriametrics-cloud/overview.md, docs/victoriametrics-cloud/quickstart.md, docs/vmalert.md
=> docs: replace cloud url to be consistent with the other ones

docs/VictoriaLogs/data-ingestion/Vector.md
=> docs: fix typo in docs/VictoriaLogs/data-ingestion/Vector.md

docs/stream-aggregation.md
This PR is based on https://github.com/VictoriaMetrics/VictoriaMetrics/pull/6777. The differences are the following:
* it keeps backward compatibility for links
* it re-structures only original document file
* it adds #common-mistakes section, re-phrased
=> docs: update stream aggregation docs

docs/victoriametrics-cloud/quickstart.md
Fixed button name in the cloud docs
=> docs/victoriametrics-cloud: fix button description

app/vmui/packages/vmui/package-lock.json, app/vmui/packages/vmui/src/utils/uplot/series.ts
=> vmui: update dependencies npm 

dashboards/victoriametrics-cluster.json, dashboards/victoriametrics.json, dashboards/vm/victoriametrics-cluster.json, dashboards/vm/victoriametrics.json, docs/VictoriaLogs/README.md
See [our playground](https://play-grafana.victoriametrics.com/d/oS7Bi_0Wz_vm/victoriametrics-cluster-vm?orgId=1&var-ds=P996FABE17B5F6D1E&var-job=All&var-job_insert=All&var-job_select=All&var-job_storage=All&var-instance=All) for reference.
=> fix doc and dashboard description about pending datapoints

docs/VictoriaLogs/README.md
=> docs/victoria-logs: fix typo

docs/VictoriaLogs/README.md
Fixed VictoriaLogs HA examples references in docs
=> docs/victorialogs: fixed HA examples links

docs/Cluster-VictoriaMetrics.md, docs/FAQ.md
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/7212
=> docs: make all statement of active time series consistent

deployment/docker/README.md, deployment/docker/alerts-vlogs.yml, deployment/docker/docker-compose-victorialogs.yml, deployment/docker/prometheus-victorialogs.yml, docs/VictoriaLogs/CHANGELOG.md, docs/VictoriaLogs/README.md
=> vlogs: added basic alerts

dashboards/vm/vmagent.json, dashboards/vmagent.json
Fix vmagent monitoring chart descriptions
- [x ] My change adheres [VictoriaMetrics contributing guidelines](https://docs.victoriametrics.com/contributing/).
=> Fix vmagent monitoring chart descriptions

deployment/docker/vmanomaly/vmanomaly-integration/docker-compose.yml, docs/anomaly-detection/CHANGELOG.md, docs/anomaly-detection/FAQ.md, docs/anomaly-detection/Overview.md, docs/anomaly-detection/QuickStart.md, docs/anomaly-detection/guides/guide-vmanomaly-vmalert/README.md
docs/vmanomaly: release 1.17.1
=> docs/vmanomaly: release 1.17.1

docs/Cluster-VictoriaMetrics.md, docs/README.md, docs/vmagent.md, docs/vmalert.md, docs/vmauth.md, docs/vmbackup.md, docs/vmgateway.md, docs/vmrestore.md
Changed highlight style for cmd flags
=> docs: updated cmd flags highlight style

docs/README.md
=> Fix "loosing" typo in README.md

deployment/docker/vmanomaly/vmanomaly-integration/docker-compose.yml, docs/anomaly-detection/CHANGELOG.md, docs/anomaly-detection/FAQ.md, docs/anomaly-detection/Overview.md, docs/anomaly-detection/QuickStart.md, docs/anomaly-detection/components/models.md, docs/anomaly-detection/components/reader.md, docs/anomaly-detection/guides/guide-vmanomaly-vmalert/README.md
docs/vmanomaly - release 1.18.0
=> docs/vmanomaly - release 1.18.0

lib/logstorage/block.go
=> chore: fix function name

docs/CaseStudies.md
- made small typo fix in case studies
=> fix typo in adsterra case study

docs/Single-server-VictoriaMetrics.md
"Single version" is unclear, since VM is also a single-executable. I think "single-node" is clearer.
=> Clarify "single" in Single-server-VictoriaMetrics.md

deployment/docker/docker-compose-victorialogs.yml, deployment/docker/vm-datasource/docker-compose-cluster.yml, deployment/docker/vm-datasource/docker-compose.yml
Updated the versions of the data sources to the latest releases
=> deployment/docker: update datasource versions to the latest releases

app/vmui/packages/vmui/src/hooks/useFetchFlags.ts, app/vmui/packages/vmui/src/router/navigation.ts, docs/changelog/CHANGELOG.md
Fix the issue mentioned in https://github.com/VictoriaMetrics/VictoriaMetrics/pull/7088#issuecomment-2391360368
=> vmui: fix the display of the link to vmalert

docs/guides/examples/guide-vmcluster-vmagent-values.yaml, docs/guides/k8s-ha-monitoring-via-vm-cluster/README.md, docs/guides/k8s-monitoring-via-vm-cluster/README.md, docs/guides/k8s-monitoring-via-vm-single/README.md
- updated dependencies versions 
- removed Helm v2 from docs
- fixed VMAgent configuration
=> Updated k8s guides

docs/README.md
=> docs: mention VM version when DS filters became available

deployment/docker/docker-compose-cluster.yml, deployment/docker/docker-compose-victorialogs.yml, deployment/docker/docker-compose.yml, deployment/docker/victorialogs/compose-base.yml, deployment/docker/vmanomaly/vmanomaly-integration/docker-compose.yml, deployment/logs-benchmark/docker-compose.yml, docs/anomaly-detection/guides/guide-vmanomaly-vmalert/README.md, docs/enterprise.md, docs/guides/grafana-vmgateway-openid-configuration/README.md, docs/scrape_config_examples.md
Update references to latest release - v1.106.0.
=> {docker,docs}: update references to latest release

docs/VictoriaLogs/vmalert.md
* fix typos in rules definition. Otherwise, they can't pass validation
* add code types for rendered examples
=> docs: fix typos in vlogs rules examples

deployment/docker/base/Dockerfile
=> deployment/docker/base: Fix the typo that causes InvalidDefaultArgInFrom

dashboards/victorialogs.json
Related issue https://github.com/VictoriaMetrics/helm-charts/issues/1699
=> dashboards/victorialogs: allow multiple values for instance variable

apptest/testcase.go, apptest/tests/key_concepts_test.go, apptest/tests/multilevel_test.go, apptest/tests/sharding_test.go, apptest/vminsert.go, apptest/vmselect.go, apptest/vmsingle.go, apptest/vmstorage.go
* make test suite responisble for stopping apps
* reuse test suite fields to simplify function signatures
=> tests: couple applications and test suit

docs/CaseStudies.md
Update figures for the existing RELEX Oy case study.
=> docs: Update RELEX Oy figures

docs/Cluster-VictoriaMetrics.md, docs/README.md, docs/VictoriaLogs/vmalert.md, docs/sd_configs.md, docs/vmagent.md
=> docs: use `available_from` shortcode for versioning features

deployment/docker/vmanomaly/vmanomaly-integration/docker-compose.yml, docs/anomaly-detection/CHANGELOG.md, docs/anomaly-detection/FAQ.md, docs/anomaly-detection/Overview.md, docs/anomaly-detection/QuickStart.md, docs/anomaly-detection/components/models.md, docs/anomaly-detection/components/monitoring.md, docs/anomaly-detection/components/reader.md, docs/anomaly-detection/guides/guide-vmanomaly-vmalert/README.md
doc updates for vmanomaly v1.18.1
=> docs: vmanomaly - release 1.18.1

deployment/docker/vmanomaly/vmanomaly-integration/docker-compose.yml, docs/anomaly-detection/CHANGELOG.md, docs/anomaly-detection/FAQ.md, docs/anomaly-detection/Overview.md, docs/anomaly-detection/QuickStart.md, docs/anomaly-detection/components/models.md, docs/anomaly-detection/guides/guide-vmanomaly-vmalert/README.md
docs update for `vmanomaly` release 1.18.2
=> docs/vmanomaly - release 1.18.2

deployment/docker/vmanomaly/vmanomaly-integration/docker-compose.yml, docs/anomaly-detection/CHANGELOG.md, docs/anomaly-detection/FAQ.md, docs/anomaly-detection/Overview.md, docs/anomaly-detection/QuickStart.md, docs/anomaly-detection/components/models.md, docs/anomaly-detection/guides/guide-vmanomaly-vmalert/README.md
`vmanomaly` docs update with patch release 1.18.3
=> docs/vmanomaly - patch release 1.18.3

docs/anomaly-detection/README.md
=> Updated vmanomaly product link

docs/vmalert.md
address https://github.com/VictoriaMetrics/VictoriaMetrics/issues/7585
=> doc: clarify rule group type

docs/FAQ.md
=> docs: fixed typo in FAQ

docs/victoriametrics-cloud/audit-logs.md, docs/victoriametrics-cloud/billing.md
=> docs: add cloud billing page

docs/LTS-releases.md
LTS versions are out of date, linking to old releases. This updates them to the latest.
=> docs: Bump LTS versions

docs/vmalert.md
=> doc: add multitenat endpoints usage for vmalert multitenancy

deployment/docker/vmanomaly/vmanomaly-integration/docker-compose.yml, docs/anomaly-detection/CHANGELOG.md, docs/anomaly-detection/FAQ.md, docs/anomaly-detection/Overview.md, docs/anomaly-detection/QuickStart.md, docs/anomaly-detection/components/models.md, docs/anomaly-detection/guides/guide-vmanomaly-vmalert/README.md
docs/vmanomaly - patch release v1.18.6 docs
=> docs/vmanomaly - patch release v1.18.6 docs

deployment/docker/docker-compose-victorialogs.yml
Update victorialogs datasource to the latest release [version](https://github.com/VictoriaMetrics/victorialogs-datasource/releases/tag/v0.9.0) 
=> deployment/docker: update victorialogs datasource versions to the latest releases

deployment/docker/docker-compose.yml
Updated docker.compose.yml, set remotewrite.url to port 8429 so it would correspond to documentation 
=> Changed vmalert --remoteWrite.url to port 8429 (vmagent)

docs/keyConcepts/keyConcepts.md
Update docs to reflect the changes introduced in #7767 to fix #5796
=> Update query docs

docs/Cluster-VictoriaMetrics.md, docs/README.md
=> docs: add missing resource usage limits

app/vmui/packages/vmui/src/components/Configurators/QueryEditor/QueryEditor.tsx, app/vmui/packages/vmui/src/components/Main/TextField/TextField.tsx, docs/VictoriaLogs/CHANGELOG.md, docs/changelog/CHANGELOG.md
Fix cursor reset in query input field. Related issue: https://github.com/VictoriaMetrics/VictoriaMetrics/issues/7288.
=> vmui: fix cursor reset in query input

docs/Release-Guide.md
=> docs/release-guide: add a note about versioning in helm charts and ansible

docs/anomaly-detection/components/README.md, docs/anomaly-detection/components/monitoring.md, docs/anomaly-detection/components/reader.md, docs/anomaly-detection/components/scheduler.md, docs/anomaly-detection/components/writer.md
added deprecated form and available from popups in vmanomaly docs
=> docs/vmanomaly: popup deprecated_from and available_from for all docs

app/vminsert/netstorage/netstorage.go, docs/changelog/CHANGELOG.md
=> vminsert: sort the storage nodes during initialization

docs/README.md
The point of the new section is to highlight publicly available playgrounds for users. All of them were mentioned in other parts of the documentation, but we didn't have all of them in one place before.
=> docs: mention publicly available playgrounds

README.md, docs/README.md
added links to badges and made them clickable at docs.victoriametrics.com
=> updated badges

apptest/tests/key_concepts_test.go, lib/promscrape/discovery/ovhcloud/dedicated_server.go, lib/promutils/time.go
=> chore: fix function name in comment

deployment/docker/victorialogs/datadog-serverless/aws/Dockerfile, deployment/docker/victorialogs/datadog-serverless/aws/compose.yml
recently new datadog extension was released, where custom endpoint configuration was added
=> victorialogs: ugraded datadog extension version in compose to one which supports custom endpoint configuration

docs/anomaly-detection/components/scheduler.md, docs/anomaly-detection/components/writer.md
- fix table rendering on writer and scheduler pages
=> docs/vmanomaly: fix table rendering

docs/changelog/CHANGELOG.md, lib/protoparser/opentelemetry/stream/streamparser.go
To resolve: https://github.com/VictoriaMetrics/VictoriaMetrics/issues/8009
Log the name of unsupported metrics.
=> feat: log the metric name of unsupported metrics

docs/changelog/CHANGELOG.md
=> docs/changelog: port LTS changes, update release date

docs/LTS-releases.md
=> docs/lts-releases: update links to latest releases

deployment/docker/docker-compose-cluster.yml, deployment/docker/docker-compose-victorialogs.yml, deployment/docker/docker-compose.yml, deployment/docker/victorialogs/compose-base.yml, deployment/docker/vmanomaly/vmanomaly-integration/docker-compose.yml, deployment/logs-benchmark/docker-compose.yml
=> deployment/docker: update to v1.109.0

docs/anomaly-detection/guides/guide-vmanomaly-vmalert/README.md, docs/enterprise.md, docs/guides/grafana-vmgateway-openid-configuration/README.md, docs/scrape_config_examples.md
=> docs: update references to v1.109.0

docs/anomaly-detection/components/monitoring.md, docs/anomaly-detection/components/reader.md, docs/anomaly-detection/components/scheduler.md, docs/anomaly-detection/components/writer.md
- fix parameters width in Components section - reader, wtiter, monitoring, scheduler
=> docs/vmanomaly: fix parameters field width

docs/anomaly-detection/components/monitoring.md, docs/anomaly-detection/components/reader.md, docs/anomaly-detection/components/scheduler.md, docs/anomaly-detection/components/writer.md
Fixing column widht in tables for components`sections: reader, writer, monitoring and scheduler
=> docs/vmanomaly: fix column width

deployment/docker/docker-compose-cluster.yml, deployment/docker/docker-compose-victorialogs.yml, deployment/docker/docker-compose.yml, deployment/docker/victorialogs/compose-base.yml, deployment/docker/vmanomaly/vmanomaly-integration/docker-compose.yml
=> deployment/docker: update reference to the latest release - v1.109.1

docs/anomaly-detection/guides/guide-vmanomaly-vmalert/README.md, docs/enterprise.md, docs/guides/grafana-vmgateway-openid-configuration/README.md, docs/scrape_config_examples.md
=> docs: update reference to the latest release - v1.109.1

docs/Release-Guide.md
Release procedure was updated on helm charts side, update documented procedure with up-to-date steps for the release.
=> docs/release-guide: update helm release guide

deployment/docker/vmanomaly/vmanomaly-integration/docker-compose.yml, docs/anomaly-detection/CHANGELOG.md, docs/anomaly-detection/FAQ.md, docs/anomaly-detection/QuickStart.md, docs/anomaly-detection/components/models.md, docs/anomaly-detection/components/reader.md, docs/anomaly-detection/guides/guide-vmanomaly-vmalert/README.md
Updated `vmanomaly` docs to release v1.19.0. Also, slight improvements on other pages, like FAQ
=> docs/vmanomaly: release v1.19.0

deployment/docker/vmanomaly/vmanomaly-integration/docker-compose.yml, docs/anomaly-detection/CHANGELOG.md, docs/anomaly-detection/FAQ.md, docs/anomaly-detection/components/models.md, docs/anomaly-detection/components/reader.md, docs/anomaly-detection/guides/guide-vmanomaly-vmalert/README.md
docs/vmanomaly: release v1.19.1
=> docs/vmanomaly: release v1.19.1

docs/README.md, docs/url-examples.md
Provide `curl` file upload example to csv import related section.
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/8080
=> docs: add curl file upload example to csv import doc

deployment/docker/vmanomaly/vmanomaly-integration/vmanomaly_config.yml, docs/anomaly-detection/Presets.md, docs/anomaly-detection/QuickStart.md, docs/anomaly-detection/components/models.md, docs/anomaly-detection/guides/guide-vmanomaly-vmalert/README.md
- fix formatting in Presets
- change integration guide config according to new format + optimisation of prophet
- minor fixes
=> docs/vmanomaly: format & fix docs

docs/vmagent.md
When using Kafka, it's important to estimate the message rate and size before applying for resources.
This pull request explained why and how to use remote write metrics to do the evaluation.
=> vmagent doc: estimating the message size and rate when using Kafka

app/vmselect/prometheus/prometheus.go, apptest/tests/multitenant_test.go, apptest/vmselect.go, docs/changelog/CHANGELOG.md
See: https://github.com/VictoriaMetrics/VictoriaMetrics/issues/8126
=> app/vmselect/prometheus: fix panic when performing delete with "multitenant" auth token

deployment/docker/docker-compose-victorialogs.yml, deployment/docker/vm-datasource/docker-compose-cluster.yml, deployment/docker/vm-datasource/docker-compose.yml
Upgraded Grafana plugins to the latest versions
=> deployment/docker: upgraded Grafana plugins to the latest versions

docs/Cluster-VictoriaMetrics.md, docs/README.md
Follow-up for https://github.com/VictoriaMetrics/VictoriaMetrics/commit/4574958e2efa540098a1b5e5196faceb76257749
=> docs: add avaialbe_version notion to new -search.maxDeleteDuration

deployment/docker/vmanomaly/vmanomaly-integration/docker-compose.yml, docs/anomaly-detection/CHANGELOG.md, docs/anomaly-detection/FAQ.md, docs/anomaly-detection/QuickStart.md, docs/anomaly-detection/components/models.md, docs/anomaly-detection/guides/guide-vmanomaly-vmalert/README.md
docs/vmanomaly: release v1.19.2 (patch that addresses some of the bugs found in 1.19.0)
=> docs/vmanomaly: release v1.19.2

docs/BestPractices.md, lib/cgroup/cpu.go
See https://github.com/VictoriaMetrics/VictoriaMetrics/issues/7988
=> lib/cgroup: warn users about using fractional CPU quotas

deployment/docker/docker-compose-victorialogs.yml
=> deployment/docker: install VL datasource from marketplace

docs/VictoriaLogs/QuickStart.md
=> docs/victoria-logs/quickstart: use link to docs for chart

docs/Release-Guide.md
=> docs/release-guide: add a note for vmui build

deployment/docker/README.md
Fixed misspelling of the word "components" from "componetns"
=> TYPO: Update README.md

deployment/docker/docker-compose-cluster.yml, deployment/docker/docker-compose-victorialogs.yml, deployment/docker/docker-compose.yml, deployment/docker/victorialogs/compose-base.yml, deployment/docker/vmanomaly/vmanomaly-integration/docker-compose.yml, docs/LTS-releases.md, docs/Quick-Start.md, docs/anomaly-detection/guides/guide-vmanomaly-vmalert/README.md, docs/enterprise.md, docs/guides/grafana-vmgateway-openid-configuration/README.md, docs/scrape_config_examples.md
- Update references to the latest release - v1.110.1
- Update links to the latest LTS releases
=> {docs,deployment}: update references to the latest release

.github/workflows/main.yml
See https://github.com/codecov/codecov-action?tab=readme-ov-file#usage
```
- uses: codecov/codecov-action@v5
with:
files: ./coverage1.xml,./coverage2.xml # optional
```
=> github/workflows: update deprecated field

lib/httpserver/httpserver.go
fix typo for description of flag  -pprofAuthKey
=> docs: [all] fix typo for description of flag  -pprofAuthKey

Makefile, app/vmalert/web_test.go, app/vmauth/target_url_test.go, lib/logstorage/parser.go
See https://github.com/golangci/golangci-lint/releases/tag/v1.64.4
* address linting errors
=> bump golangci-lint to v1.64.4

docs/keyConcepts/keyConcepts.md
Just an extremely nit-picky grammatical fix.
=> Tiny grammatical fix in keyConcepts.md

.github/workflows/docs.yaml
trigger docs pipeline on docs workflow change
=> docs: trigger workflow on pipeline change

.github/workflows/docs.yaml
=> Docs trigger workflow on pipeline change

docs/guides/collecting-openshift-logs-with-victoria-logs/README.md
Based on feedback at: https://github.com/VictoriaMetrics/VictoriaMetrics/pull/8337/files/e4240e61c6093abd700eefbb6dfa03210365a37a#r1961497609
Thanks to @vrutkovs for the feedback.
=> docs/guides: remove unneeded IDs for security context

apptest/vmsingle.go
follow-up for https://github.com/VictoriaMetrics/VictoriaMetrics/commit/855dfb324dbbb792b0257e39841acc08285edced
=> apptest/vmsingle: check for right status code in return

app/vlinsert/elasticsearch/elasticsearch.go, app/vlinsert/main.go, docs/VictoriaLogs/CHANGELOG.md
related issue https://github.com/VictoriaMetrics/VictoriaMetrics/issues/8353
=> vlinsert: accept ES ping requests to endpoint without trailing slash

app/vminsert/prompush/push.go, docs/changelog/CHANGELOG.md
fixes https://github.com/VictoriaMetrics/VictoriaMetrics/issues/8389
=> app/vminsert: enable relabeling for prompush ingestion

docs/changelog/CHANGELOG.md, lib/promscrape/discovery/kubernetes/pod.go, lib/promscrape/discovery/kubernetes/pod_test.go, lib/promscrape/discoveryutils/utils.go, lib/promscrape/discoveryutils/utils_test.go
Fix parsing of IPv6 addresses after discovery. Previously, it could lead to target being discovered and discarded afterwards.
See: https://github.com/VictoriaMetrics/VictoriaMetrics/issues/8374
=> lib/promrelabel/scrape_url: properly parse IPv6 address from __address__ label

docs/README.md
=> docs: fix typo in docs

docs/Release-Guide.md
* move testing step after assets upload
* add LTS build step before testing step
=> docs: update release guide

docs/VictoriaLogs/data-ingestion/Promtail.md
=> docs/victoria-logs/data-ingestion/promtail: fix typo

app/vlinsert/elasticsearch/elasticsearch_test.go, app/vlinsert/insertutils/timestamp.go, app/vlinsert/loki/loki_json.go, app/vlinsert/loki/loki_json_test.go, app/vlinsert/loki/loki_protobuf_test.go, docs/VictoriaLogs/CHANGELOG.md
fixes https://github.com/VictoriaMetrics/VictoriaMetrics/issues/8470
=> app/vlinsert: support floats for elasticseach timestamps

docs/changelog/CHANGELOG.md, lib/streamaggr/avg.go, lib/streamaggr/count_samples.go, lib/streamaggr/count_series.go, lib/streamaggr/histogram_bucket.go, lib/streamaggr/last.go, lib/streamaggr/max.go, lib/streamaggr/min.go, lib/streamaggr/output.go, lib/streamaggr/quantiles.go, lib/streamaggr/rate.go, lib/streamaggr/std.go, lib/streamaggr/sum_samples.go, lib/streamaggr/total.go, lib/streamaggr/unique_samples.go
=> lib/streamaggr: fixed streamaggr panic

docs/README.md
* add version since feature is available
* add cluster endpoint paths
=> docs: update metric names stats description

docs/Cluster-VictoriaMetrics.md, docs/README.md
* move related sections clother to each other
* group related sections within the same section
The intention of the change is to tie related documentation together.
=> docs: re-organize docs

docs/changelog/CHANGELOG.md, lib/protoparser/opentelemetry/pb/logs.go
Fixed an issue where  and  were incorrectly displayed when sent from OpenTelemetry Collector to Victoria Logs
Fixes #8502
=> fix:Fixed an issue where  and  were incorrectly displayed

docs/victoriametrics-cloud/cloud-FAQ.md
This PR adds the dedicated FAQ for VictoriaMetrics Cloud
=> docs/cloud: add FAQ for VM Cloud

.github/workflows/docs.yaml, docs/victoriametrics-cloud/account-management/roles-and-permissions.md, docs/victoriametrics-cloud/get-started/features.md, docs/victoriametrics-cloud/get-started/quickstart.md, docs/victoriametrics/changelog/CHANGELOG_2020.md, docs/victoriametrics/changelog/CHANGELOG_2021.md, docs/victoriametrics/changelog/CHANGELOG_2022.md, docs/victoriametrics/changelog/CHANGELOG_2023.md, docs/victoriametrics/changelog/CHANGELOG_2024.md, docs/victoriametrics/changelog/CHANGELOG_2025.md
- add smaller search weights for changelog content
- remove replace `<details>` tag with collapse shortcode
=> docs: support new docs site version updates

lib/promscrape/scrapework_test.go
It was spotted that the test introduced In https://github.com/VictoriaMetrics/VictoriaMetrics/pull/8515#issuecomment-2741063155 was flaky. This PR fixes it. 
=> vmagent: fix stream parse flaky test

docs/victoriametrics/Articles.md
This PR will add a link to https://helgeklein.com/blog/victoriametrics-long-term-storage-of-home-assistant-data/
- [ x ] My change adheres [VictoriaMetrics contributing guidelines](https://docs.victoriametrics.com/contributing/).
=> docs/Articles.md: add a link to https://helgeklein.com/blog/victoriametrics-long-term-storage-of-home-assistant-data/

lib/logstorage/datadb.go, lib/mergeset/table.go, lib/storage/partition.go
=> chore: minor grammar fix in error messages

.github/workflows/docs.yaml
=> docs: delete old content

docs/victoriametrics/README.md
This change has been requested during code review for #8134. See https://github.com/VictoriaMetrics/VictoriaMetrics/pull/8134#discussion_r1933726927
=> Update series count docs

docs/victorialogs/README.md
=> Fix typo in README

.github/pull_request_template.md
The verb is _adhere to_, see https://en.wiktionary.org/wiki/adhere .
=> docs: fix typo in pull request template

docs/anomaly-detection/CHANGELOG.md
Changelog note about experimental v1.22.0 release that solves deadlock issue on multicore systems by complete parallelization turned off until proper refactor is made to return it back w/o reintroducing the risk of the deadlock in child processes.
P.s. other references and guides were not updated to experimental tag, as long as it has downsides of dropped speed. The links will be updated once we have parallelization properly turned on.
=> docs/vmanomaly - release 1.22.0 - experimental

app/vmui/packages/vmui/src/hooks/useFetchFlags.ts, docs/victoriametrics/changelog/CHANGELOG.md
Fixes incorrect /flags request in vmui when using URL prefixes.
 
 Related issue: #8641 
=> vmui: fix `/flags` API requests to respect custom URL prefixes

docs/victoriametrics/stream-aggregation.md, lib/flagutil/array.go
Follow-up on https://github.com/VictoriaMetrics/VictoriaMetrics/issues/8715 and https://github.com/VictoriaMetrics/VictoriaMetrics/issues/8681#issuecomment-2796127921
=> docs\stream-aggregation: Describe dropping unneeded labels in more details

docs/Makefile
related https://github.com/VictoriaMetrics/vmdocs/issues/129
=> docs: fixed docs-debug target

docs/victoriametrics-cloud/account-management/organizations.md
Here a description of important terms related to Organizations is provided. The intention is to leverage on a good UI design rather than explaining all steps needed to perfomr certain actions.
However, an effort on explaining the meaning of internal states and terms has been done.
=> docs/cloud: add organizations documents

docs/victorialogs/FAQ.md
=> docs: fix typos in victorialogs FAQ.md

docs/victoriametrics-cloud/deployments/README.md, docs/victoriametrics-cloud/deployments/access-tokens.md
=> vmcloud: small fixes in access tokens docs

docs/victoriametrics/Cluster-VictoriaMetrics.md, docs/victoriametrics/README.md
https://github.com/VictoriaMetrics/helm-charts/issues/2153
=> doc: mention distributed chart in HA section

app/vmselect/promql/aggr.go, lib/storage/merge.go
use the built-in max/min to simplify the code
=> refactor: use the built-in max/min to simplify the code

docs/victoriametrics-cloud/integrations/README.md, docs/victoriametrics-cloud/integrations/cloud-alertmanager.md, docs/victoriametrics-cloud/integrations/cloudwatch.md, docs/victoriametrics-cloud/integrations/curl.md, docs/victoriametrics-cloud/integrations/custom-alertmanager.md, docs/victoriametrics-cloud/integrations/grafana.md, docs/victoriametrics-cloud/integrations/kubernetes.md, docs/victoriametrics-cloud/integrations/opentelemetry.md, docs/victoriametrics-cloud/integrations/perses.md, docs/victoriametrics-cloud/integrations/prometheus.md, docs/victoriametrics-cloud/integrations/telegraf.md, docs/victoriametrics-cloud/integrations/vector.md, docs/victoriametrics-cloud/integrations/vmagent.md
A first PR was submitted which contained a nice integration
with code snippets. In this PR, the work is finished by adding
intro text to each section
=> Add text to cloud integrations

docs/victoriametrics-cloud/how-to-monitor-k8s.md
=> docs: updated removed .Values.externalVM to .Values.external.vm parameter in setup instructions

app/vmui/packages/vmui/src/hooks/useDebounceCallback.ts, app/vmui/packages/vmui/src/hooks/useUnmount.ts, app/vmui/packages/vmui/src/pages/ExploreLogs/ExploreLogs.tsx, docs/victorialogs/CHANGELOG.md
Fix logs not updating after query change
Related issue: #8912
=> vmui/logs: fix logs not reloading when query changes

app/vmalert/web.go
Add a link to UI on the welcome page.
=> vmalert: Add link to UI on welcome page.

deployment/docker/compose-vl-cluster.yml, deployment/docker/compose-vl-single.yml
follow up https://github.com/VictoriaMetrics/VictoriaMetrics/commit/4de8113f390e1c1be89a22c59bf5c41069dfbfd3
=> docker-deployment: update vmalert `external.alert.source` flag

docs/victoriametrics/Release-Guide.md
=> docs/Release-Guide.md: Fix formatting and outdated instructions

docs/victoriametrics/Cluster-VictoriaMetrics.md
https://docs.victoriametrics.com/victoriametrics/cluster-victoriametrics/#how-to-delete-time-series doesn't exist.
=> docs: minor fix

Makefile, deployment/docker/Makefile, docs/victoriametrics/changelog/CHANGELOG.md
See https://github.com/VictoriaMetrics/VictoriaMetrics/issues/7336 for the details.
=> make/docker: stop updating `:latest` and `:stable` tags

app/vlogsgenerator/main.go, app/vmctl/vm/vm.go, lib/promrelabel/config.go, lib/promscrape/discoveryutil/client.go, lib/snapshot/snapshot.go
Close the body to avoid leaking goroutines
=> net/http: close the body

app/vmagent/remotewrite/relabel.go, docs/victoriametrics/changelog/CHANGELOG.md
=> app/vmagent: fixed relabel config reloading

app/vlinsert/datadog/datadog.go, deployment/docker/victorialogs/compose-base.yml, deployment/docker/victorialogs/datadog-serverless/aws/Dockerfile, deployment/docker/victorialogs/datadog-serverless/gcp/Dockerfile, docs/victorialogs/CHANGELOG.md
fixes https://github.com/VictoriaMetrics/VictoriaMetrics/issues/8956
=> app/vlinsert: return HTTP 202 on successfully ingested Datadog logs

lib/storage/storage_test.go
The following test produces duplicate per-day index records on a system with 1 CPU even when data inserted sequentially:
```
GOEXPERIMENT=synctest taskset -c 0 go test ./lib/storage -run=TestStorageAddRowsForVariousDataPatternsConcurrently/perDayIndexes/serial/sameBatchMetrics/sameRowMetrics/sameBatchDates/diffRowDates
```
See: #8654
Make this test pass by relaxing got and want data equality requirement if the number of CPUs is 1. This is temporary until one insertion corner case is fixed: https://github.com/VictoriaMetrics/VictoriaMetrics/issues/8948
=> lib/storage: make the test pass on systems with 1 CPU

deployment/docker/victorialogs/datadog-agent/README.md, deployment/docker/victorialogs/datadog-serverless/README.md, deployment/docker/victorialogs/filebeat/README.md, deployment/docker/victorialogs/fluentbit/README.md, deployment/docker/victorialogs/fluentd/README.md, deployment/docker/victorialogs/grafana-alloy/README.md, deployment/docker/victorialogs/grafana-alloy/compose-base.yml, deployment/docker/victorialogs/grafana-alloy/loki/compose.yml, deployment/docker/victorialogs/grafana-alloy/loki/config.alloy, deployment/docker/victorialogs/grafana-alloy/otlp/compose.yml, deployment/docker/victorialogs/grafana-alloy/otlp/config.alloy, deployment/docker/victorialogs/journald/README.md, deployment/docker/victorialogs/logstash/README.md, deployment/docker/victorialogs/opentelemetry-collector/README.md, deployment/docker/victorialogs/promtail/README.md, deployment/docker/victorialogs/telegraf/README.md, deployment/docker/victorialogs/vector/README.md
=> deployment/docker/victorialogs: add grafana alloy setup

docs/victoriametrics-cloud/integrations/cloud-alertmanager.md, docs/victoriametrics-cloud/integrations/cloudwatch.md, docs/victoriametrics-cloud/integrations/curl.md, docs/victoriametrics-cloud/integrations/custom-alertmanager.md, docs/victoriametrics-cloud/integrations/grafana.md, docs/victoriametrics-cloud/integrations/kubernetes.md, docs/victoriametrics-cloud/integrations/opentelemetry.md, docs/victoriametrics-cloud/integrations/perses.md, docs/victoriametrics-cloud/integrations/prometheus.md, docs/victoriametrics-cloud/integrations/telegraf.md, docs/victoriametrics-cloud/integrations/vector.md, docs/victoriametrics-cloud/integrations/vmagent.md
This PR improves integrations docs in 2 areas:
- Background set to white, avoiding issues when changing to dark mode.
- Height set to avoid blank spaces
=> docs/cloud: adapt integrations

docs/victoriametrics-cloud/api.md
=> vmcloud: add info about api go client to the docs

docs/victoriametrics/FAQ.md
Fixed grammatical and phrasing issues in first half of FAQ docs.
=> Fixes first half of FAQ grammar #9072

deployment/docker/vmanomaly/vmanomaly-integration/compose.yml, docs/anomaly-detection/CHANGELOG.md, docs/anomaly-detection/FAQ.md, docs/anomaly-detection/QuickStart.md, docs/anomaly-detection/components/README.md, docs/anomaly-detection/components/models.md, docs/anomaly-detection/components/reader.md, docs/anomaly-detection/components/settings.md, docs/anomaly-detection/guides/guide-vmanomaly-vmalert/README.md
Docs update for vmanomaly v1.23.0 release
=> docs/vmanomaly - release v1.23.0

docs/victorialogs/data-ingestion/Journald.md
=> Fix typo of journald in CLI flag

docs/victorialogs/LogsQL.md
Typo? It's called "fields" pipe, not "field".
=> Update LogsQL.md: "field pipe" typo

deployment/docker/vmanomaly/vmanomaly-integration/compose.yml, docs/anomaly-detection/CHANGELOG.md, docs/anomaly-detection/FAQ.md, docs/anomaly-detection/QuickStart.md, docs/anomaly-detection/components/models.md, docs/anomaly-detection/guides/guide-vmanomaly-vmalert/README.md
Update docs to vmanomaly release v1.23.2
=> docs/vmanomaly: release v1.23.2

deployment/docker/vmanomaly/vmanomaly-integration/compose.yml, docs/anomaly-detection/CHANGELOG.md, docs/anomaly-detection/FAQ.md, docs/anomaly-detection/QuickStart.md, docs/anomaly-detection/components/models.md, docs/anomaly-detection/guides/guide-vmanomaly-vmalert/README.md
Docs update to vmanomaly v1.23.3
=> docs/vmanomaly: release 1.23.3

deployment/docker/vmanomaly/vmanomaly-integration/compose.yml, docs/anomaly-detection/CHANGELOG.md, docs/anomaly-detection/FAQ.md, docs/anomaly-detection/QuickStart.md, docs/anomaly-detection/components/models.md, docs/anomaly-detection/guides/guide-vmanomaly-vmalert/README.md
Patch release doc updates for vmanomaly (v1.24.1)
=> docs/vmanomaly: release v1.24.1

deployment/docker/compose-vl-cluster.yml, deployment/docker/compose-vl-single.yml, deployment/docker/compose-vm-cluster.yml, deployment/docker/compose-vm-single.yml, deployment/docker/vmanomaly/vmanomaly-integration/compose.yml, deployment/logs-benchmark/docker-compose.yml
Fixes https://github.com/VictoriaMetrics/VictoriaMetrics/issues/9207
=> deployment/docker: Update grafana image version due to CVE issue

app/vmalert/main.go, app/vmalert/remotewrite/client.go, app/vmalert/replay.go, app/vmalert/replay_test.go
see https://github.com/VictoriaMetrics/VictoriaMetrics/pull/9265
=> vmalert: fix data race in replay ut

app/vmctl/vm_native.go
See https://github.com/VictoriaMetrics/VictoriaMetrics/issues/9220#issuecomment-3001880833:
```
2025-06-24T17:27:47.062Z      error VictoriaMetrics/app/vmctl/backoff/backoff.go:60 got error: failed to write into "http://vminsert-vmcluster.metrics.svc.cluster.local:8480/insert/0/prometheus": io: read/write on closed pipe on attempt: 1; will retry in 2s
```
This error could happen only if pipe-reader was closed before we tried to write into pipe-writer. But in this case we won't see the error explaining why pipe-reader was closed. In this change, we checking if there was a pipe-reader error before checking pipe-writer error.
The …
=> app/vmctl: print import error before pipe error

.gitignore, Makefile, app/vlagent/Makefile, app/vlagent/README.md, app/vlagent/deployment/Dockerfile, app/vlagent/main.go, app/vlagent/multiarch/Dockerfile, app/vlagent/remotewrite/client.go, app/vlagent/remotewrite/client_test.go, app/vlagent/remotewrite/pendinglogrows.go, app/vlagent/remotewrite/remotewrite.go, apptest/testcase.go, apptest/tests/vlagent_remotewrite_test.go, apptest/vlagent.go, dashboards/vlagent.json, docs/victorialogs/vlagent.md, lib/logstorage/log_rows.go
This commit introduces new component - VictoriaLogs Agent (vlagent).
It accepts logs data via any data ingestion protocol supported by VictoriaLogs and forwards it to the provided remote storages.
=> app: add vlagent component

docs/victorialogs/data-ingestion/Journald.md
Point out a some things to watch out for with the default stream field set and explain what the `_TRANSPORT` field is useful for
=> docs: Update journald ingestion docs regarding suggested fields

app/vmalert/static/css/custom.css, app/vmalert/web.qtpl, app/vmalert/web.qtpl.go, docs/victoriametrics/changelog/CHANGELOG.md
fixes https://github.com/VictoriaMetrics/VictoriaMetrics/issues/9236
=> app/vmalert: removed inline styles from UI, which are not working with recommended CSP

deployment/docker/README.md
Fixes https://github.com/VictoriaMetrics/VictoriaMetrics/issues/9323
=> deployment/docker: add troubleshooting section

README.md
=> docs: add a link to the main, twitter, reddit icon

docs/victoriametrics/README.md
typo_fix_in_readme_vm_rows_ignored_total vs vm_rows_ingored_total
=> Update README.md typo_fix_in_readme_vm_rows_ignored_total

app/vmbackup/main.go, app/vmrestore/main.go, docs/victoriametrics/Troubleshooting.md, docs/victoriametrics/vmbackup.md, docs/victoriametrics/vmbackupmanager.md, docs/victoriametrics/vmrestore.md
Making documentation easier to use following customer issues
=> Adding note for -dst config. Adding additional reference for snapshot troubleshooting for better accessibility

lib/storage/index_db_test.go
=> lib/storage: refactor TestIndexDB

app/vmselect/graphite/metrics_api.go, lib/storage/storage_test.go
Follow-up for https://github.com/VictoriaMetrics/VictoriaMetrics/pull/9399 and https://github.com/VictoriaMetrics/VictoriaMetrics/pull/9357. Should prevent issues on 32-bit platforms.
=> do not depend on platform, use maxInt64 explicilty

lib/storage/storage_test.go
=> issue-7599: revert testStorageRegisterMetricNames

lib/storage/index_db_test.go, lib/storage/index_db_timing_test.go
=> lib/storage: pass timestamp explicitly in tests

lib/storage/partition.go, lib/storage/storage.go, lib/storage/table.go, lib/storage/table_search_test.go
=> lib/storage: add DebugFlush methods for partition/table

lib/storage/storage_test.go
=> lib/storage: refactor TestStorageRotateIndexDB_* tests

lib/storage/storage.go, lib/storage/storage_legacy.go
=> issue-7599: notify rw mode to legacy idbs

docs/victoriametrics/Release-Guide.md
- Split the release process into two steps.
- Add some links 
- Described in more details what should be done to check branches in sync.
- Added some small checks, like running tests, and testing final release on sandbox.
- Changed the order of some actions (like build final image before publish release).]
=> docs/changelog: Enhance the release guide

apptest/tests/legacy_indexdb_test.go
=> issue-7599: apptest: add LegacyDeleteSeries for cluster

.github/workflows/build.yml, .github/workflows/main.yml
=> ci: do not run go actions on UI changes

.golangci.yml, Makefile, app/vmagent/remotewrite/client.go, app/vmagent/remotewrite/client_test.go, app/vmalert-tool/unittest/unittest.go, app/vmalert/notifier/config_watcher.go, app/vmalert/web.go, app/vmctl/stepper/split.go, app/vmselect/prometheus/prometheus.go, apptest/tests/dedup_test.go, apptest/tests/metric_names_stats_test.go, apptest/tests/replication_test.go, apptest/tests/vmagent_remotewrite_test.go, lib/decimal/decimal.go, lib/promscrape/discovery/kubernetes/api_watcher.go, lib/promscrape/discovery/ovhcloud/common.go, lib/promscrape/scrapework_test.go
=> ci: upgrade golangci-lint v1.64.7 -> v2.2.1

deployment/docker/vmanomaly/vmanomaly-integration/compose.yml, docs/anomaly-detection/CHANGELOG.md, docs/anomaly-detection/FAQ.md, docs/anomaly-detection/QuickStart.md, docs/anomaly-detection/README.md, docs/anomaly-detection/components/README.md, docs/anomaly-detection/components/models.md, docs/anomaly-detection/components/monitoring.md, docs/anomaly-detection/components/settings.md, docs/anomaly-detection/guides/guide-vmanomaly-vmalert/README.md
Doc updates to release v1.25.0, including
- config hot reload
- environment variable config placeholders
- cross-linking VM Operator support
- and other connected docs changes
=> docs/vmanomaly: release v1.25.0

deployment/docker/vmanomaly/vmanomaly-integration/compose.yml, docs/anomaly-detection/CHANGELOG.md, docs/anomaly-detection/FAQ.md, docs/anomaly-detection/QuickStart.md, docs/anomaly-detection/components/models.md, docs/anomaly-detection/guides/guide-vmanomaly-vmalert/README.md
update docs with v1.25.2 release
=> docs/vmanomaly: v1.25.2 update

apptest/vmauth.go
Fix flaky integration test `TestSingleVMAuthRouterWithAuth`.
The flakiness is caused by the `vmauth_config_last_reload_success_timestamp_seconds` metric, which reports time with second-level precision.
Update the test to account for this when verifying that the config reloads correctly.
=> apptest: fix flaky single vmauth router with auth test

docs/victoriametrics/README.md, docs/victoriametrics/changelog/CHANGELOG.md, docs/victoriametrics/vmctl/vmctl.md
required for https://github.com/VictoriaMetrics/vmdocs/issues/164
=> docs: exclude files from rendering by hugo

app/vmui/packages/vmui/src/components/ExploreAlerts/BaseAlert/index.tsx, app/vmui/packages/vmui/src/components/ExploreAlerts/BaseAlert/style.scss, app/vmui/packages/vmui/src/components/ExploreAlerts/BaseRule/index.tsx, app/vmui/packages/vmui/src/components/ExploreAlerts/BaseRule/style.scss
reuse codeexample component in vmui alerts page
=> app/vmui: reuse codeexample component in alerts tab

docs/victoriametrics/vmalert.md
=> docs: correct a typo in vmalert.md

app/vmui/packages/vmui/src/components/Main/DatePicker/DateTimeInput/DateTimeInput.tsx, app/vmui/packages/vmui/src/components/Main/Popper/Popper.tsx, app/vmui/packages/vmui/src/components/Main/Switch/style.scss, app/vmui/packages/vmui/src/components/Table/Table.tsx, app/vmui/packages/vmui/src/components/Table/helpers.ts, app/vmui/packages/vmui/src/pages/TopQueries/TopQueryTable/TopQueryTable.tsx, app/vmui/packages/vmui/src/pages/TopQueries/style.scss
`Table` component:
- add `format` property for table column, which allows to apply custom formatting depending on column type
- add `rowClasses` table property, that allows to pass function that allows to customize row css class depending on row value
- add `rowAction` table property, that allows to execute action while clicking on table row
`Popper` component:
- add `classes` to specify additional CSS classes for popper to differentiate from other poppers, since it's mounted to a DOM root
`Switch` component:
- use gap instead of left-margin
`DateTimeInput` component:
- add `dateOnly` property to allow accepting only date in the input
additional fixes:
- fix TopQuery header fields alignment
Please provide a brief description of the changes you made. Be as specific as possible to help …
=> app/vmui: minor main components improvements

docs/victoriametrics/vmauth.md, docs/victoriametrics/vmbackup.md, docs/victoriametrics/vmbackupmanager.md, docs/victoriametrics/vmgateway.md, docs/victoriametrics/vmrestore.md
This pull request consists of the following:
1. Markdown fixes
following https://www.markdownguide.org/basic-syntax/
and https://github.com/markdownlint/markdownlint/blob/main/docs/RULES.md
- Add empty lines after headers or lists
- Remove extra lines between paragraphs
- Remove extra spaces at the end of a line
- Add language to code quote
- Consistent list (dont mix astrixes and dashes on same file, choose one and be consistent in the same file)
- Proper URL links
- Use meaningful context to URLs instead of "here".
2. Concise language
3. Grammar fixes
- removing extra spaces between words
- there are multiple ones but i picked the basic ones that triggered my eye :)
4. Spelling fixes
=> Markdown, grammar and spelling

lib/workingsetcache/cache.go
Follow-up for cea9505bab08bc930c86a7e7c96d6b6f7e5febc6
fastcache.Cache allocates off-heap memory, which must be explicitly
returned back to the pool with Reset method call.
After changed made at commit above, during cache transit from whole to
split mode, it's possible that current cache is referenced by Cache.Get or Cache.Call atomic pointers. It leads to potential memory leaks, since we don't have any memory synchronization for atomic.Pointer.Store calls.
This commit adds `Finalizer` to the `fastcache.Cache` instances.
It properly releases memory, when cache is no reachable.
Related PR https://github.com/VictoriaMetrics/VictoriaMetrics/pull/9769
Please provide a brief description of the changes you made. Be as specific as possible to help others understand the purpose and impact of your …
=> lib/workingsetache:add runtime finalizer to the cache

app/vmalert/rule/alerting.go, app/vmalert/rule/alerting_test.go, docs/victoriametrics/changelog/CHANGELOG.md
=> fix for regression in #9783
