VictoriaMetrics/VictoriaMetrics

deployment/docker/alerts-health.yml, docs/CHANGELOG.md
It appears that 90% usage for anonymous mem usage
is already concerning. So we lowering the threshold to 80%.
=> alerts: update TooHighMemoryUsage threshold

deployment/docker/Makefile
It makes it easier for users who build and self-host images to publish their images without changing tags manually.
=> deployment/docker: allow overriding docker namespace

app/vminsert/common/streamaggr.go, docs/CHANGELOG.md
Without reset, labels duplicates could have been added during stream aggregation.
Since `ctx.Labels` is reused during processing of many series, each series will
add its labels to the context. Even if the same labels were already addeded on prev
iteration. Now, we reset `ctx.Labels` on each iteration to contain so labels from
different series didn't interfere.
This could have cause exceeding of the limit on number of labels per pushed time series.
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4277
=> vminsert: properly reset labels object on aggregation

app/vmalert/alerting.go
Previously, metric `vmalert_alerting_rules_last_evaluation_series_fetched` would be set to 0 for const expressions, because const expression do not match any series. This may result into a confusion: no series were matched but response isn't empty. The change updates the logic behind metric: if no series were matched but there are samples in response - use amount of samples as number of series.
=> vmalert: correctly update seriesFetched metric for const exprs

docs/CHANGELOG.md, lib/protoparser/csvimport/parser.go, lib/protoparser/csvimport/parser_test.go
This PR fixes an issue when parseRows miss  the line even if some metrics can be collected from this line
Related issue: https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4048
=> lib/protoparser: fix skip csv line when metric can be collect from the line

app/vminsert/netstorage/insert_ctx.go
VictoriaMetrics_ProjectID and VictoriaMetrics_AccountID labels. It should help to migrate for new labels vm_account_id vm_project_id without service downtime
=> app/vminsert: allow parsing tenant id from

app/vmalert/manager.go, app/vmalert/web_test.go
The fix addresses a case when vmalert is configured with a group which has `name`, but doesn't have `rules` configured. In this case it still returns a `nil` instead of `[]` slice.
Fixing this via current commit.
See https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4221
=> vmalert: do not return nil `rules` for /api/v1/rules

README.md, docs/README.md, docs/Single-server-VictoriaMetrics.md, docs/guides/migrate-from-influx.md, docs/keyConcepts.md
The update should make understanding of multi-tenancy more clear for influxdb users.
=> docs: mention multi-tenancy in docs

README.md, app/vmagent/README.md, docs/README.md, docs/Single-server-VictoriaMetrics.md, docs/vmagent.md
The purpose of the change is too highlight what HA pair is and how deduplication needs identical labels to be present in raw samples.
See https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4367
=> docs: clarify deduplication docs

app/vmalert/datasource/vm.go, docs/CHANGELOG.md
The storage instance with nil map params was created for remote-read purposes. And before change https://github.com/VictoriaMetrics/VictoriaMetrics/pull/4341/commits/7a9ae9de0d2221cf7759e49ebcde0a06508b0f68 this map was ignored in ApplyParams. Now, it started to be used and vmalert panics in runtime.
The fix properly inits map for at `NewVMStorage` and verifies it is not nil on assignment in `ApplyParams`.
=> vmalert: fix nil map assignment

docs/CHANGELOG.md, lib/promscrape/client.go
Follow-up after
https://github.com/VictoriaMetrics/VictoriaMetrics/commit/72c3cd47eb1120037ceffb2400e54b11c8a0e414
=> app/vmagent: mention `enable_http2` in changelog

lib/promscrape/discoveryutils/client.go
This error may be wrapped in another error, and should normally be tested using `errors.Is(err, net.ErrClosed)`.
=> lib/promscrape/discoveryutils: properly check for net.ErrClosed

README.md, app/vmstorage/main.go, docs/Cluster-VictoriaMetrics.md, docs/README.md, docs/Single-server-VictoriaMetrics.md
We have fatal log messages if the retention period is lower than 1d - `-retentionPeriod cannot be smaller than a day`, but we don't have this clarification in the documentation. In this case, the user can specify `-retentionPeriod` with wrong time duration.
=> docs: clarify `-retentionPeriod` flag usage

dashboards/victoriametrics-cluster.json, dashboards/victoriametrics.json, docs/CHANGELOG.md
[dashboards: update dashboard for single-node version](https://github.com/VictoriaMetrics/VictoriaMetrics/pull/4438/commits/074bd9e016251fe52886b0d79759fdccceb18342) 
* add anonymous mem usage panel;
* add syscall rate panel;
* add location to logs panel;
* update legend for panels to reflect instance name;
* update queries to aggregate per instance.
[dashboards: update dashboard for cluster version](https://github.com/VictoriaMetrics/VictoriaMetrics/pull/4438/commits/4839084b05248a01c5ef4a3a7fcee194258756e4) 
* add syscall rate panel;
* add drilldown to logs panel.
=> Dashboard upd

docs/CHANGELOG.md, lib/promscrape/discovery/consulagent/watch.go
fixed service name detection for consulagent service discovery in case of a difference in service name and service id.
issue: #4390 
more info in this comment: https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4390#issuecomment-1587319848
=> fixed service name detection for consulagent service discovery

app/vmctl/backoff/backoff.go, app/vmctl/backoff/backoff_test.go, docs/CHANGELOG.md
Improved backoff retry policy for `vmctl`. 
`vmctl` should finish retries if the context is canceled.
=> vmctl: finish retries if context canceled

docs/CHANGELOG.md, lib/mergeset/table.go, lib/storage/partition.go
It fixes migrations from versions below v1.90.0.
Previously parts.json was created only after successful merge. But if merge was interruped for some reason (OOM or shutdown), parts.json wasn't created and partitions left after interruped merge weren't properly deleted. Since VM cannot check if it must be removed or not. https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4336
=> lib/storage: creates parts.json on start-up if it not exists.

app/vmui/packages/vmui/src/components/Chart/Heatmap/HeatmapChart/HeatmapChart.tsx, app/vmui/packages/vmui/src/components/Chart/Line/ChartTooltip/ChartTooltip.tsx, app/vmui/packages/vmui/src/components/Chart/Line/Legend/LegendItem/LegendItem.tsx, app/vmui/packages/vmui/src/components/Chart/Line/LineChart/LineChart.tsx, app/vmui/packages/vmui/src/components/Main/Tooltip/Tooltip.tsx, app/vmui/packages/vmui/src/components/Views/GraphView/GraphView.tsx, app/vmui/packages/vmui/src/styles/components/table.scss, app/vmui/packages/vmui/src/utils/uplot/events.ts, app/vmui/packages/vmui/src/utils/uplot/heatmap.ts, app/vmui/packages/vmui/src/utils/uplot/scales.ts, app/vmui/packages/vmui/src/utils/uplot/series.ts, app/vmui/packages/vmui/src/utils/uplot/types.ts, docs/CHANGELOG.md
In the current chart refresh implementation, a memory leak problem has been detected. With each new chart update, memory usage increases even though the chart data remains unchanged. This can lead to degraded performance and, ultimately, application failure.
- Fixed a memory leak associated with chart updates.
- Memory consumption for the chart's legend and tooltips has been optimized.
The comparison shows a noticeable improvement in memory usage. Heap snapshots have been provided, with the current logic shown on the left and the corrected logic on the right.
- query: `flag`
- timerange: `30m`
- limit: `1000` series (for more noticeable growth)
Link to example: [Chart Example](https://play.victoriametrics.com/select/accounting/1/6a716b0f-38bc-4856-90ce-448fd713e3fe/prometheus/graph/#/?g0.e …
=> vmui: memory leak fix

app/vmalert/remotewrite/remotewrite.go, app/vmalert/remotewrite/remotewrite_test.go, docs/CHANGELOG.md
Retry all errors except 4XX status codes while pushing via remote-write
to the remote storage. Previously, errors like broken connection could
prevent vmalert from retrying the request.
=> vmalert: retry all errors except 4XX status codes

lib/vmselectapi/server.go
This is a followup for https://github.com/VictoriaMetrics/VictoriaMetrics/pull/4418 to also handle "connection reset by peer" errors in connection handling logic. 
This error can be triggered just the same as described in original PR: when query was closed on vmselect side and connection has been interrupted.
=> lib/vmselectapi: extend error handling to ignore "reset by peer"

deployment/logs-benchmark/grafana/dashboards/comparison.json
- remove second panel for disk usage. It is not very useful for users and brings more confusion than profit from having it.
- update CPU graph to show number of used CPUs to make it less ambiguous
=> deployment/logs-benchmark: update dashboard

docs/_includes/extra/script.js
Added two scroll params where the `block` is vertical alignment. It will scroll to the element but create and offset to center this element into the viewport
Scroll to the bottom of the page
Scroll to the center of the page.
Scroll to the start of the page.
=> docs: scroll to center of the view port

app/vmauth/README.md, app/vmauth/example_config.yml, app/vmauth/example_config_ent.yml, docs/vmauth.md
It is impossible to run OS vmauth with the provided config. The example of using ip filters should be only a part of docs. All other examples should work seamlessly with OS version.
=> vmauth: rm ip filters from non-ent config example

README.md, docs/Cluster-VictoriaMetrics.md, docs/README.md, docs/Single-server-VictoriaMetrics.md
It is required for periods to be multiplies of each other, but it was not stated clearly in documentation.
Flag description will be updated in a separate PR.
=> docs: clarify downsampling periods requirements

docs/CHANGELOG.md, lib/promutils/time.go, lib/promutils/time_test.go
Unlike prometheus, VictoriaMetrics accepts [format timestamp with four letter as year](https://docs.victoriametrics.com/Single-server-VictoriaMetrics.html#timestamp-formats) in [query APIs](https://docs.victoriametrics.com/#prometheus-querying-api-usage) and in [export APIs](https://docs.victoriametrics.com/#how-to-export-time-series).
We parse time using time.UnixNano which can only store maxInt64, so the valid year is between [1970,2262]
tip: User can't query data by passing timestamp "6000" as "1970-10-01 00:10:00" like prometheus, they should use something like 1970-01-01T10:00:00.
=> fix parse for invalid partial RFC3339 format

app/vmagent/remotewrite/client.go
Error message will be present for any auth error, but message claims an error is about OAuth2 configuration which is confusing.
=> app/vmagent/remotewrite: fix error message for auth config

Makefile
Using this flag eliminates the wrong behavior of the copy-docs function in Arch Linux and its forks, which use https://fishshell.com by default.
Without using '-e' flag echo don't recognized "\n". See example:
```fish
on garuda@VictoriaMetrics on 🌱fix/wrong-copy-docs-behavior 📝 ×12via 🐹 v1.20.5 []
🤍 19:08 󰈺  ❯ git status
On branch fix/wrong-copy-docs-behavior
Changes not staged for commit:
(use "git add <file>..." to update what will be committed)
(use "git restore <file>..." to discard changes in working directory)
modified:   Makefile
modified:   README.md
modified:   docs/README.md
modified:   docs/Single-server-VictoriaMetrics.md
modified:   docs/vmagent.md
modified:   docs/vmalert.md
modified:   docs/vmauth.md
modified:   docs/vmbackup.md
modified:   docs/vmbackupmanager.md
modified: …
```
=> adds '-e' flag for echo in Makefile:copy-docs section

app/vmalert/datasource/vm_prom_api.go, app/vmalert/datasource/vm_test.go, docs/CHANGELOG.md
related with https://github.com/VictoriaMetrics/VictoriaMetrics/pull/4539, only RFC3339 format can cover all-time.
=> vmalert:fix query request using rfc3339 format

app/vmselect/promql/eval.go, docs/CHANGELOG.md
Right now the query result is missing when time is small than 10m(default step is 5m), set minTimestamp to 0 instead of negative when time is small enough.
=> vmselect: fix result in Prometheus query when time is small

README.md, app/vmselect/netstorage/netstorage.go, docs/CHANGELOG.md, docs/Cluster-VictoriaMetrics.md, docs/vmalert.md
vmselect has two logical conditions during request processing when
`-replicationFactor` cmd-line flag is set:
1. If at least `len(storageNodes) - replicationFactor` responded, it could skip
waiting for the rest of nodes to respond. This could lead to problems described
here https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1207.
2. Mark response as partial if less than `len(storageNodes) - replicationFactor` responded
without an error.
The P1 showed itself error-prone and became the main reason why
`-replicationFactor` wasn't recommended to use at vmselect level.
However, this optimization could be still very useful in situations
when there are slow and fast replicas in cluster.
But P2 remains viable and important conditionless.
Hiding P1 behind the feature-flag …
=> vmselect: introduce `search.skipSlowReplicas` cmd-line flag

README.md, app/vmagent/README.md, app/vmalert/README.md, app/vmauth/README.md, app/vmbackup/README.md, app/vmbackupmanager/README.md, app/vmgateway/README.md, app/vmrestore/README.md, docs/Cluster-VictoriaMetrics.md, docs/README.md, docs/Single-server-VictoriaMetrics.md, docs/VictoriaLogs/README.md, docs/vmagent.md, docs/vmalert.md, docs/vmauth.md, docs/vmbackup.md, docs/vmbackupmanager.md, docs/vmgateway.md, docs/vmrestore.md, lib/httpserver/httpserver.go
Currently, it may confuse users whether `httpAuth.*` flags are used by HTTP client or server configuration(see https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4586 for example).
=> docs: make `httpAuth.*` flags description less ambiguous

app/vmctl/README.md, docs/vmctl.md
Removed from the documentation undefined flag `--remote-read-src-check-alive`.
Related issue: https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4552
=> app/vmctl: remove undefined flag from the documentation

Makefile
Adds task to fix imports formatting inplace.
Formats imports into:
- standard library
- external libraries
- local packages based on github.com/VictoriaMetrics/VictoriaMetrics prefix
Note that this PR does not apply new formatting.
=> make: add goimports task

lib/logstorage/datadb.go
This PR fixed panic when test running
```
panic: unaligned 64-bit atomic operation
goroutine 13918 [running]:
runtime/internal/atomic.panicUnaligned()
/opt/hostedtoolcache/go/1.20.6/x64/src/runtime/internal/atomic/unaligned.go:8 +0x2d
runtime/internal/atomic.Xadd64(0xe038224, 0x1)
/opt/hostedtoolcache/go/1.20.6/x64/src/runtime/internal/atomic/atomic_386.s:125 +0x11
github.com/VictoriaMetrics/VictoriaMetrics/lib/logstorage.(*datadb).nextMergeIdx(...)
/home/runner/work/VictoriaMetrics/VictoriaMetrics/lib/logstorage/datadb.go:443
github.com/VictoriaMetrics/VictoriaMetrics/lib/logstorage.(*datadb).mustMergeParts(0xe038200, {0xae460c0, 0xf, 0x10}, 0x0)
/home/runner/work/VictoriaMetrics/VictoriaMetrics/lib/logstorage/datadb.go:350 +0x337 …
```
=> lib/logstorage: fix panic

app/vmalert/group.go, docs/CHANGELOG.md
Need to reset evalTS after modify group interval. Otherwise there could be latency on rule evaluation time all the time when (modifyTS-LastestEvalTS)%NewGroupInterval >0, eg: will have 29m latency below.
=> vmalert: fix evalTS after modify group interval

dashboards/victoriametrics-cluster.json
Using `job=~$job_storage` forces "Cache usage" panel to display only vmstorage caches, but there is a cache peresent at vmselect(`promql/rollupResult`). 
Updated selector to match generic `$job` so that all caches will be displayed with an option to display per-job caches.
=> dashboards/cluster: fix using storage filter for cache usage panel

app/vmselect/main.go, app/vmselect/promql/active_queries.go, app/vmui/packages/vmui/src/App.tsx, app/vmui/packages/vmui/src/api/active-queries.ts, app/vmui/packages/vmui/src/constants/navigation.ts, app/vmui/packages/vmui/src/pages/ActiveQueries/hooks/useFetchActiveQueries.ts, app/vmui/packages/vmui/src/pages/ActiveQueries/index.tsx, app/vmui/packages/vmui/src/pages/ActiveQueries/style.scss, app/vmui/packages/vmui/src/router/index.ts, app/vmui/packages/vmui/src/types/index.ts, docs/CHANGELOG.md, docs/keyConcepts.md
- Added a new page in VMUI to display active queries. 
- The API method `/api/v1/status/active_queries` is used to fetch the data.
- The API method `/api/v1/status/active_queries` has been updated; now it returns data in `JSON` format.
#4598
=> vmui: add Active Queries page

README.md, docs/README.md, docs/Single-server-VictoriaMetrics.md
Explained potential cardinality statistics inaccuracy in the documentation
Related issue: 
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3070
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3528
=> docs: update information about tsdb usage in cluster version

app/vmui/packages/vmui/src/App.tsx, app/vmui/packages/vmui/src/pages/ActiveQueries/index.tsx, app/vmui/packages/vmui/src/types/index.ts, app/vmui/packages/vmui/src/utils/time.ts
- The `id` column has been removed
- The `from`, `to`, and `step` columns have been combined into a single `args` column.
- The `remote_addr` column has been renamed to `client address`.
- The columns have been reordered as follows: `duration`, `client address`, `query`, `args`.
- The table has been sorted in descending order based on the `duration` column.
https://github.com/VictoriaMetrics/VictoriaMetrics/pull/4653#issuecomment-1642888619
=> vmui: improvements for the Active Queries

.github/dependabot.yml
The change disables version updates for repo packages. Please note, security updates should not be affected by the change according to https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#open-pull-requests-limit:
```
open-pull-requests-limit
By default, Dependabot opens a maximum of five pull requests for version updates. Once there are five open pull requests from Dependabot, Dependabot will not open any new requests until some of those open requests are merged or closed.
This option has no impact on security updates, which have a separate, internal limit of ten open pull requests.
```
=> dependabot: disable version update for packages

app/vlinsert/loki/push_request.pb.go
Reduces binary size from 22M to 14M.
Tested with promtail, those changes don't affect logs ingestion.
Thanks to @f41gh7
=> app/vlinsert/loki: manually remove bloat dependecies for generate proto file

app/vmalert/README.md, app/vmalert/unittest/input.go, app/vmalert/unittest/input_test.go, app/vmalert/unittest/testdata/test1.yaml, docs/vmalert.md
unittest input supports `stale` sample
=> vmalert: unittest support stale datapoint

docs/CHANGELOG.md, lib/protoparser/common/extra_labels.go, lib/protoparser/common/extra_labels_test.go
Fixed decoding of label values with slash for pushgateway and prometheus golang client compatibility + added some tests.
Related links:
- issue #4692
- [pushgateway](https://github.com/prometheus/pushgateway/blob/1da09352b953a78ad6aaa47a47414513e78adccf/handler/push.go#L171)
- [prometheus client](https://github.com/prometheus/client_golang/blob/644c80d1360fb1409a3fe8dfc5bad4228f282f3b/prometheus/push/push.go#L353)
=> fixed label values decoding for pushgateway compatibility

app/vmalert/README.md, app/vmalert/main.go, app/vmalert/main_test.go, docs/CHANGELOG.md, docs/vmalert.md
Use `-configCheckInterval` command-line flag instead.
=> vmalert: remove deprecated in v1.61.0 `-rule.configCheckInterval`

app/vmctl/stepper/split.go, app/vmctl/stepper/split_test.go, docs/CHANGELOG.md
Added support of the `week` step.
Related issue: https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4738
=> app/vmctl: add support the `week` step for time-based chunks

deployment/docker/Makefile
I am using buildah instead of docker. It's too rare a setup to warrant including it into the makefile, but this little change helps generalize the build process.
=> Remove some repetitions in docker Makefile

.github/workflows/check-licenses.yml, .github/workflows/codeql-analysis.yml, .github/workflows/main.yml, app/vmui/Dockerfile-web, deployment/docker/Makefile, docs/CHANGELOG.md, snap/local/Makefile
The update includes a security fix to the crypto/tls package, as well as bug fixes to the assembler and the compiler.
See the list of issues addressed in Go1.20.7 here: https://github.com/golang/go/issues?q=milestone%3AGo1.20.7+label%3ACherryPickApproved
=> security: bump go version from 1.20.6 to 1.20.7

deployment/docker/victorialogs/vector-docker/docker-compose.yml
Vector images don't have `curl` installed, so the healthchecks fail.
```
"Log": [
{
"Start": "2023-08-03T14:41:21.383735348+05:30",
"End": "2023-08-03T14:41:21.46569884+05:30",
"ExitCode": -1,
"Output": "OCI runtime exec failed: exec failed: unable to start container process: exec: \"curl\": executable file not found in $PATH: unknown"
},
]
```
=> fix: remove healthcheck in vector docker-compose

app/vmalert/README.md, docs/vmalert.md
Value of `-dedup.minScrapeInterval` comand-line flag must be higher than `evaluation_interval` in order to make sure that only one sample on each evaluation will be left after deduplication. 
Moreover, value of `-dedup.minScrapeInterval` must be a multiple of vmalert's `evaluation_interval` in order to make sure that samples will be aligned between deduplication window periods.
See: https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4774#issuecomment-1663940811
=> docs: make phrase about dedup and evaluation interval relation less obscure

app/vmalert/main_test.go, app/vmalert/notifier/config_watcher_test.go
fix redundant clean up move introduced by https://github.com/VictoriaMetrics/VictoriaMetrics/pull/4788
=> fix redundant clean up move

app/vmui/packages/vmui/src/App.tsx, app/vmui/packages/vmui/src/constants/navigation.ts
Hide the `Logs Explorer` from the navigation menu for the base application
=> vmui: hide "Logs Explorer" for the base app

app/vmagent/remotewrite/remotewrite.go, app/vminsert/common/insert_ctx.go, docs/CHANGELOG.md
Sync behavior for dropInput and keepInput flags between single-node and vmagent. 
Fix vmagent not respecting dropInput flag and reverse logic for keepInput.
See: https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4804
=> {vmagent/remotewrite,vminsert/common}: fix dropInput and keepInput flags inconsistency

app/vmagent/remotewrite/remotewrite.go
fixed this comment: https://github.com/VictoriaMetrics/VictoriaMetrics/commit/a27c2f37731986f4bf6738404bb6388b1f42ffde#r124737432
=> fixed premature release of the context (after #4247 / #4824)

app/vmauth/README.md, docs/vmauth.md
`vmauth` documentation reported two flags with a wrong case.
PS: there is also some differences in the usage of a leading hyphen in the flags (reload and flags have it, metrics and pprof don't), but I didn't touch that in this patch.
=> Fix typo in `vmauth` docs.

app/vmalert/datasource/vm.go, app/vmalert/datasource/vm_test.go, docs/CHANGELOG.md
Previosly, request retry to datasource re-used existing HTTP request. But if request object was already partially processed (body was read), then retry will be unsuccessful.
The change re-instantinates HTTP request object before retry.
=> vmalert: correctly re-instantinate HTTP req on retries

lib/promscrape/client.go
User agent was not set for native client which resulted in using one provided by Golang.
See: https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4884
=> lib/promscrape/client: make User-Agent consistent between fasthttp and stream client

docs/CHANGELOG.md, lib/promscrape/client.go
Initially, stream parse mode was reading data from response and parsing it on flight. This was causing longer delay to read the whole response and required increasing timeout value to allow data processing while reading. So that https://github.com/VictoriaMetrics/VictoriaMetrics/commit/908e35affd31975bf808effa7072f59197d8d507 increased timeout value to fix this.
But after https://github.com/VictoriaMetrics/VictoriaMetrics/commit/74c00a87623718f9c1a8ecaeab3a6a0febc2db2f response in stream parse mode is saved into memory and then parsed eliminating necessity of having timeout value higher that for usual scrape.
Updates: https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4847
=> lib/promscrape/client: sync timeout for HostClient and http.Client 

lib/promscrape/config.go
follow up https://github.com/VictoriaMetrics/VictoriaMetrics/commit/f1c2508243c2f4d8d6bc546276c41d1b1a12fa2b, fix clusterMembersCount check with default value.
And since the default value for `clusterMemberNum` is "0" instead of nothing, I presume we consider single scraper as a one node cluster, thus `clusterMembersCount` default value should be "1" instead of "0".
=> fix clusterMembersCount check

app/vmselect/main.go, docs/CHANGELOG.md
Such requests must be rejected as not found since vmselect does not support multitenant endpoint.
See: https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4910
=> app/vmselect: fix panic when using `/select/multitenant` endpoint

app/vlstorage/main.go, app/vmstorage/main.go, lib/flagutil/duration.go, lib/flagutil/duration_test.go, lib/storage/index_db_test.go, lib/storage/index_db_timing_test.go, lib/storage/storage.go, lib/storage/storage_test.go, lib/storage/table_test.go
I had a bug incorrectly using `.Msec`, when converting it to time.Duration.
Added flagutil.Duration() which eliminates the possibility of incorrectly using the `.Msec`.
=> Add flagutil.Duration to avoid conversion bugs

deployment/docker/README.md, deployment/docker/docker-compose.yml, deployment/docker/fluent-bit.conf, deployment/docker/victorialogs/filebeat-docker/docker-compose.yml, deployment/docker/victorialogs/filebeat-syslog/docker-compose.yml, deployment/docker/victorialogs/fluentbit-docker/docker-compose.yml, deployment/docker/victorialogs/fluentbit-docker/fluent-bit.conf, deployment/docker/victorialogs/logstash/docker-compose.yml, deployment/docker/victorialogs/promtail/docker-compose.yml, deployment/docker/victorialogs/vector-docker/docker-compose.yml
- added VictoriaLogs to main docker-compose file
- removed outdated comments
- added `path` to fluentbit stream fields
Previously, stream only contained `stream` field which stands for `stdout` or `stderr`. This leads to performance in case this configuration will be used.
=> deployment/docker: add VictoriaLogs

docs/CHANGELOG.md, lib/vmselectapi/server.go
it breaks cluster communication, since vmselect incorrectly reads request buffer, leaving unread data on it https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4932
=> lib/vmselectapi: do not send empty label names for labelNames request

app/vlinsert/insertutils/common_params.go, app/vlinsert/insertutils/flags.go, docs/VictoriaLogs/CHANGELOG.md, docs/VictoriaLogs/README.md
Adding limit on ingestion allows to avoid issues like this one https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4762 Such issues are often caused by misconfigurtion on log persing/ingestion side and preventing such rows from being ingested allows to avoid performance implications created by storing such log rows.
=> app/vlinsert: add flag to limit amount of fields per line

docs/CHANGELOG.md, lib/promscrape/discovery/kubernetes/api_watcher.go
goroutine which was polling k8s API had no execution control. This leaded to leaking goroutines during config reload.
See: https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4850
cc: @hagen1778 vmalert is using `lib/*` Consul and DNS implementations of service discovery and not affected by this.
=> lib/promscrape/discovery/kubernetes: fix leaking api watcher

docs/CHANGELOG.md, lib/backup/common/part.go
appliedRetention.txt can be modified in place, so it should be always copied just the same as parts.json
Updates: https://github.com/victoriaMetrics/victoriaMetrics/issues/5005
=> lib/backup: fix issue with inconsistent copying of appliedRetention.txt

app/vmbackup/README.md, app/vmbackupmanager/README.md, docs/vmbackup.md, docs/vmbackupmanager.md
- updated headers structure to make it easier to search for some specific content in navigation menu
- added examples for different authentication options
- linked vmbackupmanager to the same documentation to make it clear that same options are applied
Updates: https://github.com/VictoriaMetrics/VictoriaMetrics/issues/5023
=> docs/vmbackup: update docs for different authentication options

docs/VictoriaLogs/CHANGELOG.md, lib/logstorage/block.go, lib/logstorage/block_stream_merger.go, lib/logstorage/rows.go
Fixes panic during background merge when resulting block would contain more columns than maxColumnsPerBlock. Buffered data will be flushed and replaced by the next block.
See: https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4762
=> lib/logstorage: prevent from panic during background merge

README.md, docs/README.md, docs/Single-server-VictoriaMetrics.md
Updated documentation regarding retention filter usage if the duration is set lower than the `-retentionPeriod` flag value.
Related issue: https://github.com/VictoriaMetrics/VictoriaMetrics/issues/5086
=> docs: add clarification of the retention filter usage

docs/enterprise.md, docs/vmanomaly.md
- added information about new `-license` flags
- added more details about how to run enterprise binaries
=> docs/enterprise: add info about license flags 

docs/enterprise.md, docs/vmanomaly.md
Fixes rendering of values expressions - `{{ $labels.job }}` at https://docs.victoriametrics.com/enterprise.html#monitoring-license-expiration
=> docs/enterprise: fix rendering of example alert

docs/VictoriaLogs/CHANGELOG.md, docs/VictoriaLogs/FAQ.md, docs/VictoriaLogs/LogsQL.md, docs/VictoriaLogs/QuickStart.md, docs/VictoriaLogs/README.md, docs/VictoriaLogs/Roadmap.md, docs/VictoriaLogs/data-ingestion/Filebeat.md, docs/VictoriaLogs/data-ingestion/Fluentbit.md, docs/VictoriaLogs/data-ingestion/Logstash.md, docs/VictoriaLogs/data-ingestion/Promtail.md, docs/VictoriaLogs/data-ingestion/README.md, docs/VictoriaLogs/data-ingestion/Vector.md, docs/VictoriaLogs/keyConcepts.md, docs/VictoriaLogs/querying/README.md
we need to use relative links, otherwise it's impossible to have more than one env with documentation
=> docs victorialogs use relative links

lib/storage/storage.go
follow up https://github.com/VictoriaMetrics/VictoriaMetrics/commit/fe8cc573d1d839d84e7d71949bca0b7f16f8faf8, seems to be a test code merged by mistake.
Which failed the [test](https://github.com/VictoriaMetrics/VictoriaMetrics/actions/runs/6528888299/job/17725766359?pr=5153)(vmalert-tool unittest can be a good e2e implementation for vm))
=> lib/storage: fix ingesting stale point

README.md, deployment/docker/Makefile
These makefile changes allow building VictoriaMetrics via podman in either rootful or rootless mode.  Due to the use of buildx, production builds are not supported.
=> deployment/docker: Support building images via podman

lib/stringsutil/stringsutil.go
We have failed test on master branch.
```
--- FAIL: TestFormatLogMessage (0.00s)
logger_test.go:24: unexpected result; got
"foo: abcde, \"foo bar baz\", xx"
want
"foo: a..e, \"f..z\", xx"
```
if failed because maxArgs maxLen <= 4 in the  `LimitStringLen` in that case we always will return the income string but in the test we limit the maxLen by value 4
```
f("foo: %s, %q, %s", []interface{}{"abcde", fmt.Errorf("foo bar baz"), "xx"}, 4, `foo: a..e, "f..z", xx`)
=> lib/stringsutil: fix failing test

app/vmui/packages/vmui/src/components/Table/helpers.ts, app/vmui/packages/vmui/src/pages/ExploreLogs/ExploreLogs.tsx, app/vmui/packages/vmui/src/pages/ExploreLogs/ExploreLogsBody/ExploreLogsBody.tsx, app/vmui/packages/vmui/src/pages/ExploreLogs/ExploreLogsBody/style.scss, app/vmui/packages/vmui/src/pages/ExploreLogs/ExploreLogsHeader/ExploreLogsHeader.tsx
- Fixed sorting by time in the table. #5300
- Added error output when executed without an entered query
- Added messages (`No logs found` / `Run query to see logs`) when no logs are present.
=> vmui: ui logs enhancements

lib/logstorage/storage_search.go
solve the issue: #4856 
Steps to reproduce：
1. Set up a clean VictoriaLogs instance
2. Execute the provided script to generate test data:
```shell
#!/bin/bash
for i in {0..3000}; do
log="{\"log\": {\"level\": \"info\", \"message\": \"hello world\"}, \"date\": \"0\", \"foo\": \"bar\", \"stream\": \"stream$i\"}"
echo $log >> logs.json
done
```
3. Import the test data into VictoriaLogs instance
`curl -X POST -H 'Content-Type: application/stream+json' --data-binary @logs.json 'http://localhost:9428/insert/jsonline?_stream_fields=stream&_time_field=date&_msg_field=log.message'`
4. Execute the provided script to identify the stream that cannot be queried.
```shell
#!/bin/bash
for i in {0..3000}; do
query='_stream:{stream="stream'$i'"}'
response=$(curl -s …
```
=> lib/logstorage: fix streamID and tenantID search (#4856)

docs/Cluster-VictoriaMetrics.md
=> docs/dns-srv-typo-fix: replace `dns+src` with `dns+srv`

app/vmselect/promql/eval.go
app/vmselect/promql/eval.go:evalAggrFunc shunts evaluation of AggrFuncExpr over rollupFunc over MetricsExpr to an optimized path. `tryGetArgRollupFuncWithMetricExpr()` checks whether expression can be shunted, but it re-creates the AggrFuncExpr with the single MetricExpr argument which is wrong when the aggregation function has more than one argument. This results in queries like `sum(aggr_over_time("avg_over_time",m))` failing with error message
> expecting at least 2 args to "aggr_over_time"; got 1 args; expr: "aggr_over_time(m)"
while the analogous query `sum(avg_over_time(m))` executes successfully. This fix removes the unnecessary mangling.
=> Fix sum(aggr_over_time) 'got 1 args' error (#3028)

app/vmui/packages/vmui/src/hooks/useFetchQuery.ts, app/vmui/packages/vmui/src/types/index.ts
To reproduce, point serverUrl to a wrong URL that returns an HTTP error without "errorType"
=> VMUI: Handle unknown query error response type

README.md, docs/Cluster-VictoriaMetrics.md, docs/README.md, docs/Single-server-VictoriaMetrics.md, docs/VictoriaLogs/README.md, docs/vmagent.md
Removed all default value fro the `maxConcurrentInserts` flag from the all documentation. There was different values for this flag. But at that moment it calculates depends on `2*cgroup.AvailableCPUs()` available CPU
Related issue: https://github.com/VictoriaMetrics/VictoriaMetrics/issues/5488
=> docs: remove default value from the `maxConcurrentInserts` flag

app/vmselect/promql/rollup.go
It is unclear why there are two identical fns `rollupDefault` and `rollupDistinct`. Dropping one of them.
-------------------
Related to https://github.com/VictoriaMetrics/VictoriaMetrics/issues/5499
=> app/vmselect: drop `rollupDefault` function as duplicate

docs/keyConcepts.md
Described information in the Key Concepts about the label value where the when the value converts to the `float64`
Related issue: https://github.com/VictoriaMetrics/VictoriaMetrics/issues/5485
=> docs: clarify information about values

app/vmui/packages/vmui/src/components/Chart/Line/LegendAnomaly/LegendAnomaly.tsx, app/vmui/packages/vmui/src/pages/ExploreAnomaly/ExploreAnomaly.tsx, app/vmui/packages/vmui/src/pages/ExploreAnomaly/hooks/useFetchAnomalySeries.ts, app/vmui/packages/vmui/src/types/uplot.ts, app/vmui/packages/vmui/src/utils/color.ts, app/vmui/packages/vmui/src/utils/uplot/series.ts
This pull request introduces support for IsolationForest and similar models that output only `y` and `anomaly_score`. Key features include:
1. Visualizing `y` Metric: Display of the `y` metric.
2. Highlighting Anomalies: Anomalies (where `anomaly_score` > 1) are marked in red for quick identification.
=> vmui/vmanomaly: add support models that produce only `anomaly_score`

docs/operator/resources/vmalertmanager.md
The link text of AlertManager API docs was set to `VMAlert` instead of `VMAlertmanager`
=> Docs: fix link text for alertmanager under custom resources

Makefile
`cat /proc/cpuinfo` doesn't work on MacOS, this command (`getconf`) should work on both MacOS and Linux
=> Make a makefile work on a MacOS and Linux

lib/flagutil/array.go
Add "how to insert comma inside value" instruction to flag description, should help users with question like https://github.com/VictoriaMetrics/VictoriaMetrics/issues/5626
=> add inserting comma inside value instruction to flag description

app/vmalert/rule/alerting.go, app/vmalert/rule/alerting_test.go
The change is to set `ActiveAt` timestamp of created alerts to the execution timestamp instead of the actual timestamp when rule was executed. The change is justified by alert generator specification: https://github.com/prometheus/compliance/blob/main/alert_generator/specification.md#pending-state-conditions:
"evaluation time when the alert is first created is referred to as ActiveAt for that alert".
The change also fixes flaky test `TestAlertingRule_Exec` which has dependency on the actual timestamps, which resulted into inaccurate test states:
https://github.com/VictoriaMetrics/VictoriaMetrics/actions/runs/7608452967/job/20717699688
=> vmalert: set `ActiveAt` to evaluation timestamp

lib/logstorage/storage_search.go
Maybe the block search in the `searchByTenantIDs` method should exit the same as in `searchByStreamIDs`. When `scheduleBlockSearch` returns false, there is no need to traverse subsequent data.
=> lib/logstorage: proper exit during block search

lib/storage/raw_row.go
Previously, block header timestamps were not initialized. This fix allows relying on part header timestamps information when checking if deduplication for block is required.
=> lib/storage/raw_row: properly initialize TS for tmp blocks

app/vmalert/static/js/custom.js, app/vmalert/web.qtpl, app/vmalert/web.qtpl.go
At my company we run hundreds of alerts in different groups and to search for them in the vmalert UI sometimes is tough task.  
I'm proposing here a filter at UI level by Group or Rule names and by Labels. The idea is just to show Groups that match its name with the filter and hide the others. For Rule name, I want to filter them and show theirs groups and already show the rules row opened. For labels, I want to filter by its key or its value.
Example:
No filter applied:
Filter by group name `1abc`:
Just changing the query to `2abc`:
Now, changing to filter by rule name and querying `1234`:
Changing the query to `5678`:
Changing the query to `service1` which is a value of a label:
Changing the query to `raw_name=alert_cba`:
Other case:
- Any blank filter will show all groups
- Every new …
=> add filter by group or rule name to vmalert ui

deployment/docker/vm-datasource/docker-compose-cluster.yml, deployment/docker/vm-datasource/docker-compose.yml
Currently the docker-compose examples for loading `victoriametrics-datasource` uses 2 environment variables:
-  `GF_ALLOW_LOADING_UNSIGNED_PLUGINS`
- `GF_DEFAULT_APP_MODE`
I believe both of the env vars are trying to achieve the same thing. 
- `GF_DEFAULT_APP_MODE` disables code signing for all plugins -
- `GF_ALLOW_LOADING_UNSIGNED_PLUGINS` intends to disable code signing for just `victoriametrics-datasource`. 
In my opinion, keeping the scope narrowed to just `victoriametrics-datasource` would be preferable in this case.
Unfortunately `GF_ALLOW_LOADING_UNSIGNED_PLUGINS` is misspelled. According to [grafana docs](https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#override-configuration-with-environment-variables), the format is supposed to be …
=> deployment/docker: clean up loading of victoriametrics-datasource

docs/README.md
=> docs: CSV RFC3339 format uses server timezone

lib/storage/partition.go
This PR is fiixing the problem with data aligning 
```
--- FAIL: TestIndexDBRepopulateAfterRotation (0.09s)
panic: unaligned 64-bit atomic operation [recovered]
panic: unaligned 64-bit atomic operation
```
Please check the tests on master branch 
=> lib/storage: fix aligning

deployment/docker/docker-compose-cluster.yml, deployment/docker/docker-compose.yml, deployment/docker/vmanomaly/vmanomaly-integration/docker-compose.yml
This commit will bump alertmanager version from v0.25.0 to the latest v0.27.0 for docker-compose files of VictoriaMetrics Single/Cluster/vmanomaly
see https://github.com/prometheus/alertmanager/releases/tag/v0.27.0
=> docker-compose: bump alertmanager version from v0.25.0 to the latest v0.27.0 

lib/logstorage/parser.go, lib/logstorage/stream_filter.go
We meet a panic when typing in an invalid regex with the stream filter. I think it can be avoided at the `ParseQuery`.
reproduce:
logsql: `_stream: {path=~"*debug.log"}`
```
panic: BUG: cannot parse regexp "*debug.log": error parsing regexp: missing argument to repetition operator: `*`
goroutine 5112 [running]:
github.com/VictoriaMetrics/VictoriaMetrics/lib/httpserver.handlerWrapper.func1()
github.com/VictoriaMetrics/VictoriaMetrics/lib/httpserver/httpserver.go:289 +0x5b
panic({0x845320?, 0xc001002740?})
runtime/panic.go:770 +0x132
github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.logMessage({0x8c006c, 0x5}, {0xc004a89650, 0x69}, 0x4)
github.com/VictoriaMetrics/VictoriaMetrics/lib/logger/logger.go:301 +0xa74
github.com/VictoriaMetrics/VictoriaMetrics/lib/logger.logLevelSkipframes(0x1, …
```
=> lib/logstorage: avoid panic when parsing regex with stream filter

lib/bytesutil/bytesutil.go
Benchmark test results (To Unsafe Bytes2 here is after I optimized it)
```bash
go test -bench='ToUnsafeBytes' ./lib/bytesutil/ -benchtime=10s
goos: darwin
goarch: arm64
pkg: github.com/VictoriaMetrics/VictoriaMetrics/lib/bytesutil
BenchmarkToUnsafeBytes-8        1000000000               2.974 ns/op    8069.32 MB/s           0 B/op          0 allocs/op
BenchmarkToUnsafeBytes2-8       1000000000               2.721 ns/op    8819.26 MB/s           0 B/op          0 allocs/op
PASS
ok      github.com/VictoriaMetrics/VictoriaMetrics/lib/bytesutil        6.458s
```
In addition, I also tried to rewrite ToUnsafeString, from the benchmark test results (here ToUnsafeString2 is after I optimized it) will become a little bit slower, I do not know if this change is OK, because I did not submit it …
=> lib/bytesutil: Optimize ToUnsafeBytes to make it leaner, more standards-compliant and slightly faster

app/vmui/Dockerfile-build
**Problem:**
When attempting to execute the `make vmui-build` command on macOS, the process fails with an `npm` error related to permissions. Specifically, the error message is as follows:
```
npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /.npm
npm ERR! errno -13
npm ERR! Your cache folder contains root-owned files, due to a bug in
npm ERR! previous versions of npm which has since been addressed.
npm ERR! To permanently fix this problem, please run:
npm ERR!   sudo chown -R 501:20 "/.npm"
```
This issue arises because `npm` attempts to access a cache directory that has incorrect ownership, leading to a permission denied error.
**Solution:**
To resolve this issue, an environment variable `NPM_CONFIG_CACHE` is introduced. This change specifies a custom location for the npm cache …
=> vmui: fix permission issue for `make vmui-build` command

README.md, docs/README.md, docs/Single-server-VictoriaMetrics.md
It is confusing for cluster users to find that VMUI is available at vmselect as it is only mentioned in the list of URLs. Explicit mention of vmselect URL in docs will make it easier to discover.
=> docs: explicitly mention VMUI is available in cluster

app/vmctl/main.go
The parameters ca-file and key file to TLSConfig() got interchanged. 
Fixed it in this PR
=> Vmctl: Error in Vmnative protocol

app/vlselect/logsql/sort_writer.go, docs/VictoriaLogs/CHANGELOG.md
=> app/vlselect: follow-up for 0514091948cf8e00e42f44318c0e5e5b63b6388f

app/vmselect/prometheus/prometheus.go
`GetDeadlineForLabelsAPI` exists but is unused. It seems like it was intended to be used here and just got over looked. My LabelAPI requests were running for multiple minutes on end which led me here.
=> Use GetDeadlineForLabelsAPI for LabelAPI requests

docs/CHANGELOG.md, lib/storage/partition.go, lib/storage/table.go
This is required to avoid crashes during graceful shutdown in case background merge is in progress.
See: https://github.com/VictoriaMetrics/VictoriaMetrics/issues/5944
=> lib/storage/table: wait for merges to be completed when closing a table

README.md, docs/Cluster-VictoriaMetrics.md, docs/README.md, docs/Single-server-VictoriaMetrics.md
Described `timeout` query argument фтв its impact on the execution time of requests.
=> docs: describe timeout query argument

docs/operator/resources/vmalert.md
* fix docs/operator/resources/vmalert.md,Change VMRUle to VMRule in the second subheading.
=> docs: fix a typo in docs/operator/resources/vmalert.md

docs/managed-victoriametrics/alertmanager-setup-for-deployment.md
There was a typo in the `curl` usage
=> docs: fix typo in the curl command

app/vmauth/auth_config.go, app/vmauth/auth_config_test.go, app/vmauth/target_url.go, app/vmauth/target_url_test.go, docs/CHANGELOG.md, docs/vmauth.md
Support regex matching when routing incoming requests based on HTTP query args via `src_query_args` option at `url_map`.
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/6070
=> app/vmauth: support regex matching in `src_query_args`

app/vmui/packages/vmui/src/components/Main/Select/Select.tsx, docs/CHANGELOG.md
**Problem:**
In `Select` component, user-entered values disappear if the user tabs out without selecting from the dropdown list.
**Solution:**
Implemented retention of the user-entered value in the `Select` component if it matches an option from the list upon blur.
=> vmui: preserve select value on blur if it matches list

app/vmalert/rule/group_test.go
There was a sleep statement in the test, waiting for Group to perform a couple of evaluation. But looks like
it worked unreliable for some CI tests like the one below https://github.com/VictoriaMetrics/VictoriaMetrics/actions/runs/8718213844/job/23915007958?pr=6115
This commit changes the sleep statement on a function that waits for a specific number of evaluations. It should make this test faster in general case, and more reliable for slow environemnts.
=> app/vmalert: make `TestGroupStart` more reliable

deployment/docker/Makefile, deployment/docker/builder/Dockerfile, docs/Release-Guide.md
Added x86_64 libraries to allow building cross-platform images on arm64
=> {deployment/docker}: allow cross-platform building on arm64 platform

deployment/docker/docker-compose-cluster.yml, deployment/docker/docker-compose-victorialogs.yml, deployment/docker/docker-compose.yml, deployment/docker/vmanomaly/vmanomaly-integration/docker-compose.yml, deployment/logs-benchmark/docker-compose.yml, deployment/marketplace/digitialocean/one-click-droplet/files/etc/update-motd.d/99-one-click
Step 17:
> Bump VictoriaMetrics version at deployment/docker/docker-compose.yml and at deployment/docker/docker-compose-cluster.yml.
from https://docs.victoriametrics.com/release-guide/
=> deployment: bump to 1.101.0

dashboards/victoriametrics.json, dashboards/vm/victoriametrics.json, docs/CHANGELOG.md
Allowing to select multiple instance IPs makes it much easier to view metrics for longer periods of time in dynamic environments such as Kubernetes. In k8s update will also cause IP to change making it harder to use dashboard to check the status.
See: https://github.com/VictoriaMetrics/VictoriaMetrics/issues/5869
=> dashboards/victoria-metrics-single: allow selecting multiple instance values

lib/mergeset/table.go, lib/mergeset/table_test.go
Add test to cover the code path with overflowing shards buffers and triggering merge to partition.
This test covers the code path which leaded to https://github.com/VictoriaMetrics/VictoriaMetrics/issues/5959
=> lib/mergeset: improve test coverage

app/vmagent/remotewrite/pendingseries.go, app/vmagent/remotewrite/pendingseries_test.go, lib/prompb/prompb.go, lib/prompb/prompb_test.go, lib/prompbmarshal/prompbmarshal_test.go, lib/prompbmarshal/types.pb.go, lib/promscrape/client.go, lib/promscrape/scrapework.go, lib/promscrape/scrapework_test.go, lib/protoparser/prometheus/parser.go, lib/protoparser/prometheus/parser_test.go, lib/protoparser/prometheus/parser_timing_test.go
This code adds Exemplars to VMagent and the promscrape parser adhering to OpenMetrics Specifications.  This will allow forwarding of exemplars to Prometheus and other third party apps that support OpenMetrics specs.
=> Exemplar support

README.md, app/vmagent/main.go, app/vmagent/statsd/request_handler.go, app/vminsert/main.go, app/vminsert/statsd/request_handler.go, docs/README.md, docs/Single-server-VictoriaMetrics.md, docs/stream-aggregation.md, docs/vmagent.md, lib/ingestserver/statsd/server.go, lib/protoparser/statsd/parser.go, lib/protoparser/statsd/parser_test.go, lib/protoparser/statsd/parser_timing_test.go, lib/protoparser/statsd/stream/streamparser.go, lib/protoparser/statsd/stream/streamparser_test.go
In this PR I added compatibility with [statsd protocol](https://github.com/b/statsd_spec) with tags to be able to send metrics directly from statsd clients to vmagent or directly to VM.
For example its compatible with [statsd-instrument](https://github.com/Shopify/statsd-instrument) and [dogstatsd-ruby](https://github.com/DataDog/dogstatsd-ruby) gems
Related issues: #5052, #206, #4600
=> Statsd protocol compatibility

app/vmui/Dockerfile-web, deployment/docker/Makefile, deployment/logs-benchmark/docker-compose-elk.yml, deployment/logs-benchmark/docker-compose-loki.yml, docs/CHANGELOG.md
upgrade from go 1.22.2 to 1.22.3 to include security fixes. Also see:
- https://go.dev/doc/devel/release
- https://github.com/golang/go/issues?q=milestone%3AGo1.22.3+label%3ACherryPickApproved
=> chore: [deployment] upgrade from go 1.22.2 to 1.22.3 to include security fixes

docs/CHANGELOG.md, lib/streamaggr/streamaggr_test.go, lib/streamaggr/total.go
Set correct suffix `<output>_prometheus` for aggregation outputs `increase_prometheus` and `total_prometheus`
Before, outputs `total` and `total_prometheus` or `increase` and `increase_prometheus` had the same suffix.
- [ * ] My change adheres [VictoriaMetrics contributing guidelines](https://docs.victoriametrics.com/contributing/).
=> lib/streamaggr: set correct suffix `<output>_prometheus`

app/victoria-metrics/Makefile, app/vmagent/Makefile, app/vmalert/Makefile, app/vmauth/Makefile, app/vmbackup/Makefile, app/vmctl/Makefile, app/vmrestore/Makefile
Added makefile rule for `GOARCH=loong64` to support building all VictoriaMetrics components on the `loongarch64` platform.
=> Add build support for loong64

app/vmui/packages/vmui/src/utils/default-server-url.ts
This PR for ui vmanomaly eliminates URL parameters to automatically use the default server URL, simplifying URLs like:
From http://localhost:3000/#/?g0.expr=vm_blocks... to http://localhost:3000
From http://localhost:3000/select/0/vmui/#/?g0.expr=vm_blocks... to http://localhost:3000/select/0/vmui/ etc.
=> vmui/vmanomaly: fix default server url

app/vmui/packages/vmui/src/components/ExploreAnomaly/AnomalyConfig.tsx, app/vmui/packages/vmui/src/components/ExploreAnomaly/style.scss, app/vmui/packages/vmui/src/components/Main/Spinner/Spinner.tsx, app/vmui/packages/vmui/src/pages/CustomPanel/QueryConfigurator/QueryConfigurator.tsx, app/vmui/packages/vmui/src/pages/ExploreAnomaly/ExploreAnomaly.tsx
This pull request adds a button to the vmanomaly ui that opens a modal window for viewing and downloading the config file.
=> vmui/vmanomaly: add download config button

app/vmagent/remotewrite/relabel.go, app/vmagent/remotewrite/remotewrite.go, docs/CHANGELOG.md, docs/vmagent.md
Removed deprecated `-remoteWrite.multitenantURL` flag to simplify global stream aggregation
=> app/vmagent: removed deprecated -remoteWrite.multitenantURL flag support

lib/streamaggr/rate.go, lib/streamaggr/streamaggr_timing_test.go
=> lib/streamaggr: added rate_sum and rate_avg to benchmarks, lint fix

README.md, app/vmagent/main.go, app/vmagent/remotewrite/remotewrite.go, app/vmagent/statsd/request_handler.go, app/vminsert/common/streamaggr.go, app/vminsert/main.go, app/vminsert/statsd/request_handler.go, docs/README.md, docs/Single-server-VictoriaMetrics.md, docs/vmagent.md, lib/protoparser/statsd/parser.go, lib/protoparser/statsd/parser_test.go, lib/protoparser/statsd/stream/streamparser.go, lib/protoparser/statsd/stream/streamparser_test.go
* adds datadog extensions for statsd:
- multiple packed values (v1.1)
- additional types distribution, histogram
* adds type check and append metric type to the labels with special tag name `__statsd_metric_type__`. It simplifies streaming aggregation config.
* updates docs
=> follow-up for c6c5a5a18695ab5f0be1f68bbb63bf90f6f15657

app/vmalert-tool/unittest/input.go
every time function **parseInputValue** execute, these regexp are initialized. which situation reduce the performance.
=> optimise regex

app/vmui/packages/vmui/src/pages/ExploreLogs/hooks/useFetchLogs.ts, docs/VictoriaLogs/CHANGELOG.md
change time range limitation from `_time` in the expression to `start` and `end` query args.
=> vmui/logs: change time range to `start` and `end` query args

docs/anomaly-detection/components/scheduler.md
Fix date parameters names in vmanomaly backtest scheduler component documentation.
=> docs/vmanomaly: backtest parameter fix

README.md, app/vmselect/main.go, docs/Cluster-VictoriaMetrics.md
Update wording to highlight that cache is not persistent if flag is value is empty. Previously, it was not clear if cache is not used at all or just not persistent.
=> app/vmselect: update flag description

app/vmui/Dockerfile-web, deployment/docker/Makefile, docs/CHANGELOG.md
fixes: CVE-2023-42366, CVE-2023-42363, CVE-2024-4603, CVE-2024-2511, CVE-2024-24788, CVE-2024-24787
=> Update base Alpine image to 3.20.0 to avoid security risks 

app/vmagent/remotewrite/streamaggr.go
use GetOptionalArg instead of index to fallback to a first argument if index is absent for remotewrite.streamaggr.config
=> app/vmagent: fixed streamaggr args

deployment/docker/Makefile, docs/CHANGELOG.md
Scratch based images will be using a separate tag: "(version)-scratch" and will be built for the same architecture as regular images.
This is useful for environments with higher security standards. In this case using alpine as base layer requires updating images more frequently in order to get the latest updates for the base image, even in case the user did not need to update VictoriaMetrics version.
Tested that scratch images work for:
- vmagent - enterprise with kafka and opensource
- cluster
- single-node
No issues observed so far.
cc: @tenmozes 
=> deployment/docker: add scratch-based images

docs/CHANGELOG.md
Update CHANGELOG to include go version change introduced in 43cf2216811c24d008f9c417339d14513c93c734
Also see:
- https://go.dev/doc/devel/release
- https://github.com/golang/go/issues?q=milestone%3AGo1.22.4+label%3ACherryPickApproved
=> docs: [deployment] update CHANGELOG.md to include go version change 1.22.4

app/vmauth/main.go, docs/CHANGELOG.md, docs/vmauth.md
* adds idleConnTimeout flag, which must reduce probability of `broken pipe` and `connection reset` errors.
* one-time retry trivial network requests for the same backend
=> app/vmauth: adds idleConnTimeout flag, retry trivial errors

lib/protoparser/opentelemetry/firehose/http.go
All user input should be sanitized before rendering. This should prevent possible attacks. See https://github.com/VictoriaMetrics/VictoriaMetrics/security/code-scanning/203
=> lib/protoparser/opentelemetry/firehose: escape requestID before returning it to user

docs/anomaly-detection/Overview.md, docs/anomaly-detection/components/models.md
Fix 404 relative img links for v1.13.0 update of vmanomaly docs
=> docs/vmanomaly - fix 404 img links & remove outdated models

docs/CHANGELOG.md, lib/flagutil/duration.go, lib/flagutil/duration_test.go
use maxMonths limit for parsed duration flag value
fixes #6330 
=> lib/flagutil: use month limit for duration flag for parsed duration assessment

docs/anomaly-detection/Presets.md, docs/anomaly-detection/components/models.md
Added config example for `min_dev_from_expected` arg; also, small styling fixes and alignments
=> docs/vmanomaly - add config example for min_dev arg

app/vmui/packages/vmui/src/api/logs.ts, app/vmui/packages/vmui/src/api/types.ts, app/vmui/packages/vmui/src/components/Chart/BarHitsChart/BarHitsChart.tsx, app/vmui/packages/vmui/src/components/Chart/BarHitsChart/TooltipBarHitsChart.tsx, app/vmui/packages/vmui/src/components/Chart/BarHitsChart/hooks/useBarHitsOptions.ts, app/vmui/packages/vmui/src/components/Chart/BarHitsChart/style.scss, app/vmui/packages/vmui/src/constants/logs.ts, app/vmui/packages/vmui/src/constants/palette.ts, app/vmui/packages/vmui/src/pages/ExploreLogs/ExploreLogs.tsx, app/vmui/packages/vmui/src/pages/ExploreLogs/ExploreLogsBarChart/ExploreLogsBarChart.tsx, app/vmui/packages/vmui/src/pages/ExploreLogs/ExploreLogsBarChart/style.scss, app/vmui/packages/vmui/src/pages/ExploreLogs/ExploreLogsBody/ExploreLogsBody.tsx, app/vmui/packages/vmui/src/pages/ExploreLogs/GroupLogs/GroupLogs.tsx, app/vmui/packages/vmui/src/pages/ExploreLogs/GroupLogs/GroupLogsItem.tsx, app/vmui/packages/vmui/src/pages/ExploreLogs/GroupLogs/style.scss, app/vmui/packages/vmui/src/pages/ExploreLogs/hooks/useFetchLogHits.ts, app/vmui/packages/vmui/src/pages/ExploreLogs/hooks/useFetchLogs.ts, app/vmui/packages/vmui/src/utils/uplot/axes.ts, app/vmui/packages/vmui/src/utils/uplot/bars.ts, docs/VictoriaLogs/CHANGELOG.md
- Added a bar chart displaying the number of log entries over a time range.
#6404
- When `_msg` is empty, all fields are displayed in a single line.
- Added double quotes when copying pairs: `key: "value"`.
- Minor style adjustments.
=> vmui/logs: add bar chart

dashboards/vm/vmalert.json, dashboards/vmalert.json
`vmalert_iteration_total` series number is 4 time less than `vmalert_iteration_duration_seconds`, queries will be lighter.
=> vmalert-dashboard: replace variable query metric

app/vmalert-tool/unittest/unittest.go
g.ExecOnce() shouldn't be failed at all. If it fails, it might be bug or something wrong with tmp vm datasource, exit immediately.
=> vmalert-tool: exit immediately when rule group execute failed

docs/managed-victoriametrics/README.md, docs/managed-victoriametrics/alerting-vmalert-managed-victoria-metrics.md, docs/managed-victoriametrics/alertmanager-setup-for-deployment.md, docs/managed-victoriametrics/overview.md, docs/managed-victoriametrics/quickstart.md, docs/managed-victoriametrics/setup-notifications.md, docs/managed-victoriametrics/user-managment.md
With the recent release of Managed VictoriaMetrics users are able to create and execute Alerting & Recording rules and send notifications via hosted Alertmanager.
So, we're publishing Alertmanager configuration docs for Managed VictoriaMetrics.
=> Publish Alertmanager configuration docs for Managed VictoriaMetrics

docs/anomaly-detection/QuickStart.md
- Fixed config example in QuickStart vmanomaly docs for 1.13 version compatibility
=> docs/vmanomaly:quickstart example fix

app/vmui/packages/vmui/src/pages/ExploreLogs/ExploreLogs.tsx, app/vmui/packages/vmui/src/pages/ExploreLogs/ExploreLogsBarChart/ExploreLogsBarChart.tsx, app/vmui/packages/vmui/src/pages/ExploreLogs/ExploreLogsBody/ExploreLogsBody.tsx, app/vmui/packages/vmui/src/pages/ExploreLogs/hooks/useFetchLogHits.ts, app/vmui/packages/vmui/src/pages/ExploreLogs/hooks/useFetchLogs.ts, docs/VictoriaLogs/CHANGELOG.md
- Fixed the update of the relative time range when `Execute Query` is clicked
- Optimized server requests: now, if an error occurs in the `/query` request, the `/hits` request will not be executed.
#6345 (duplicates: #6440, #6312)
=> vmui/logs: fix the update of the relative time range

app/vmagent/remotewrite/remotewrite.go, app/vmagent/remotewrite/remotewrite_test.go, app/vmagent/remotewrite/streamaggr.go, app/vminsert/common/streamaggr.go, dashboards/vm/vmagent.json, dashboards/vmagent.json, docs/CHANGELOG.md, lib/promrelabel/if_expression.go, lib/streamaggr/deduplicator.go, lib/streamaggr/deduplicator_test.go, lib/streamaggr/deduplicator_timing_test.go, lib/streamaggr/histogram_bucket.go, lib/streamaggr/rate.go, lib/streamaggr/streamaggr.go, lib/streamaggr/streamaggr_test.go, lib/streamaggr/streamaggr_timing_test.go, lib/streamaggr/total.go
- added stale metrics counters for input and output samples
- added labels for aggregator metrics => `name="{rwctx}:{aggrId}:{aggrSuffix}"`
- rwctx - global or number starting from 1
- aggrid - aggregator id starting from 1
- aggrSuffix - <interval>_(by|without)_label1_label2_labeln
e.g: `name="global:1:1m_without_instance_pod"`
=> lib/streamaggr: added stale samples metric, added metrics labels

app/vmalert/main.go, deployment/docker/docker-compose-cluster.yml, deployment/docker/docker-compose.yml, docs/vmalert.md
The change adds a new docs section with examples on how source can be overriden. It should address questions like https://github.com/VictoriaMetrics/VictoriaMetrics/issues/6536
While there, fix the example in `external.alert.source` cmd-line flag.
=> app/vmalert: add examples for `source` override

.github/workflows/build.yml, .github/workflows/main.yml
This PR is aimed to change the currently in place configuration of running Go related jobs for code changes that don't contain actual Go files ([example 1](https://github.com/VictoriaMetrics/VictoriaMetrics/pull/6517/checks) - 2m32s , [example 2](https://github.com/VictoriaMetrics/VictoriaMetrics/pull/6543/checks) - 4m11s).
In order to do that the `build` workflow was extracted from Go related workflow (now it doesn't require lint as a `need` step -- let me know if it's something we want to keep). It will run upon the same triggers as before the change.
The `main` workflow now will be triggered by `**.go` pattern only and contains lint/test steps that are relevant for Go file changes.
I expect this PR + https://github.com/VictoriaMetrics/VictoriaMetrics/pull/6540 to improve CI minutes …
=> Optimize CI workflows

docs/README.md, docs/Single-server-VictoriaMetrics.md, docs/stream-aggregation.md
recently added custom `promtextmetric` and `influxtextmetric` prismjs plugins to vmdocs to convert this
to this
=> Code tooltip updates

docs/vmbackup.md
Add a note to clarify usage of azure credentials when multiple credentials are available.
The user is required to specify AZURE_CLIENT_ID as otherwise Azure API will return an error: "Multiple user assigned identities exist, please specify the clientId / resourceId of the identity in the token request"
=> docs/vmbackup: add a note for azure identity

docs/vmagent.md
Improve documentation to help: https://github.com/VictoriaMetrics/VictoriaMetrics/issues/6670
Currently, the documentation of Kafka Integration did not describe:
- How to switch between different remote write protocols in producer side and consumer side.
This pull request adds those information.
=> docs: [vmagent] Add docs for remote write protocol control in Kafka integration

app/vmauth/main.go, app/vmauth/main_test.go, docs/CHANGELOG.md
Change response code to 502 to align it with behaviour of other existing reverse proxies. Currently, the following reverse proxies will return 502 in case an upstream is not available: nginx, traefik, caddy, apache.
=> app/vmauth: change response code when all backend are not available

app/vmui/Dockerfile-web, deployment/docker/Makefile, docs/CHANGELOG.md
See https://www.alpinelinux.org/posts/Alpine-3.20.1-released.html
>including security fix for:
OpenSSL CVE-2024-5535
=> security: upgrade base docker image (Alpine) from 3.20.1 to 3.20.2

.gitignore, docs/VictoriaLogs/CHANGELOG.md, docs/VictoriaLogs/FAQ.md, docs/VictoriaLogs/QuickStart.md, docs/VictoriaLogs/Roadmap.md, docs/VictoriaLogs/keyConcepts.md
After breadcrumb was added to docs.victoriametrics.com there's no need to specify parent page name in a title
Also added vmdocs to gitignore to avoid committing it
=> docs: removed redundant 'VictoriaLogs' from title

app/vmui/packages/vmui/src/components/Configurators/GlobalSettings/GlobalSettings.tsx, app/vmui/packages/vmui/src/components/Configurators/GlobalSettings/style.scss, app/vmui/packages/vmui/src/components/Configurators/LogsSettings/MarkdownParsing/SwitchMarkdownParsing.tsx, app/vmui/packages/vmui/src/components/Main/Icons/index.tsx, app/vmui/packages/vmui/src/components/Table/Table.tsx, app/vmui/packages/vmui/src/components/TraceQuery/TracingsView.tsx, app/vmui/packages/vmui/src/contexts/AppContextProvider.tsx, app/vmui/packages/vmui/src/pages/ExploreLogs/ExploreLogs.tsx, app/vmui/packages/vmui/src/pages/ExploreLogs/ExploreLogsBody/ExploreLogsBody.tsx, app/vmui/packages/vmui/src/pages/ExploreLogs/ExploreLogsBody/TableLogs.tsx, app/vmui/packages/vmui/src/pages/ExploreLogs/ExploreLogsHeader/ExploreLogsHeader.tsx, app/vmui/packages/vmui/src/pages/ExploreLogs/GroupLogs/GroupLogs.tsx, app/vmui/packages/vmui/src/pages/ExploreLogs/GroupLogs/GroupLogsItem.tsx, app/vmui/packages/vmui/src/pages/ExploreLogs/GroupLogs/style.scss, app/vmui/packages/vmui/src/state/logsPanel/LogsStateContext.tsx, app/vmui/packages/vmui/src/state/logsPanel/reducer.ts, docs/VictoriaLogs/CHANGELOG.md
<details>
<summary>add a toggle button to the "Group" tab that allows users to expand or collapse all groups at once.</summary>
</details>
<details>
<summary>introduce the ability to select a key for grouping logs within the "Group" tab. </summary>
</details>
<details>
<summary>display the number of entries within each log group.</summary>
</details>
<details>
<summary>move the Markdown toggle to the general settings panel in the upper left corner.</summary>
</details>
=> vmui/logs: improve UI functionality

app/vmagent/main.go, app/vminsert/main.go, docs/CHANGELOG.md, lib/influxutils/influxutils.go
This is useful for clients which validate InfluxDB is available before data ingestion can be started.
See: https://github.com/VictoriaMetrics/VictoriaMetrics/issues/6653
=> app/{vminsert,vmagent}: add healthcheck for influx ingestion endpoints

docs/VictoriaLogs/victorialogs-datasource.md, docs/victoriametrics-datasource.md
https://victoriametrics.slack.com/archives/C05UNTPAEDN/p1722833182319299
Sometimes users may use the wrong (lower) version of Grafana when setting up the VictoriaLogs datasource. 
It would be good to document the requirements of Grafana versions to use VictoriaMetrics/VictoriaLogs datasource.
=> docs: Added grafana version requirement for vm+vl datasorce

app/vlinsert/elasticsearch/elasticsearch.go, docs/VictoriaLogs/CHANGELOG.md
This is needed in order to support standard Elasticsearch output in Logstash pipelines. 
See: https://github.com/VictoriaMetrics/VictoriaMetrics/pull/6660
=> app/vlinsert/elasticsearch: add fake response for logstash requests

docs/CHANGELOG.md, lib/promscrape/config.go, lib/promscrape/config_test.go
By introducing this feature, users will have the ability to customize the sampleLimit parameter on a per-target basis, providing more flexibility and control over the job execution behavior.
=> app/vmagent: read __sample_limit__ from labels (#6665)

app/vmselect/graphite/eval.go, app/vmselect/graphite/render_api.go, docs/CHANGELOG.md
VM has different responses to equivalent queries for MetricsQL and GraphiteQL in case of failed access to one of vmstorage node of the cluster vmstorage nodes. For GraphiteQL, the denyPartialResponse feature is not used, it is always true, which is not always correct (depending on the configuration).
In the PR I have removed the hardcoded denyPartialResponse for GraphiteQL, just like MetricsQL does.
=> fixed using denyPartialResponse for graphite requests

docs/anomaly-detection/components/models.md
Fixing remaining typos and missing words after v.1.15.0 updates
=> docs/vmanomaly: fix typos after v1.15.0

app/vmui/packages/vmui/src/AppAnomaly.tsx, app/vmui/packages/vmui/src/assets/MetricsQL.md, app/vmui/packages/vmui/src/components/ExploreAnomaly/AnomalyConfig.tsx, app/vmui/packages/vmui/src/hooks/useSortedCategories.ts, app/vmui/packages/vmui/src/utils/default-server-url.ts, docs/MetricsQL.md
- fix TS lint
- anomaly: remove /vmui
- anomaly: minor inspections fix
- docs: fix broken links to headings
Initially vmanomaly opened with `/vmui` in serverUrl, remove it.
=> vmui: Fix initial serverUrl for vmanomaly

Makefile, docs/CHANGELOG.md
Forcefully set permissions for release binaries to 1000:1000. This helps to avoid issues such as https://github.com/VictoriaMetrics/VictoriaMetrics/issues/6788 on systems with limitations around UID:GID configuration.
"1000" UID and GID is widely used by linux distributions for the first user in the system.
=> make: reset permissions when creating release archive

docs/guides/getting-started-with-opentelemetry/README.md
Fix broken link on: https://docs.victoriametrics.com/guides/getting-started-with-opentelemetry/index.html#building-the-go-application-instrumented-with-metrics
- https://docs.victoriametrics.com/guides/app.go-collector.example
- https://docs.victoriametrics.com/guides/app.go.example
The valid links **could be**:
- https://docs.victoriametrics.com/guides/getting-started-with-opentelemetry/app.go-collector.example
- https://docs.victoriametrics.com/guides/getting-started-with-opentelemetry/app.go.example
Also went throught `/guides` folder and did not found doc with same issue. Please advice if you know more.
=> docs: fix example links in getting started with OpenTelemetry

lib/storage/storage.go
Reduced the scope of rowsAddedTotal variable from global to Storage.
This metric clearly belongs to a given Storage object as it counts the number of records added by a given Storage instance.
Reducing the scope improves the incapsulation and allows to reset this variable during the unit tests (i.e. every time a new Storage object is created by a test, that object gets a new variable).
This has previously been done in #6663, but that PR is still in review and I need this change for my other PRs that are still in development.
- [ x] My change adheres [VictoriaMetrics contributing guidelines](https://docs.victoriametrics.com/contributing/).
=> Move rowsAddedTotal counter to Storage

docs/VictoriaLogs/keyConcepts.md
The anchor to "Other fields" section should be #other-fields (instead of #other-field)
=> VictoriaLogs/keyConcepts.md: fix broken anchor to #other-fields

docs/guides/getting-started-with-opentelemetry/README.md, docs/url-examples.md
This pull request fixes incorrect URLs in two places:
1. In the OTel guide, which has been corrected in https://github.com/VictoriaMetrics/VictoriaMetrics/pull/6880, but one incorrect URL is still missing.
2. In the URL example, the cache reset endpoint for vmselect / Cluster version is `/internal/resetRollupResultCache`, but it is mistakenly noted as `/select/internal/resetRollupResultCache`, which misguides the user. （introduced in #4468)
=> docs: fix incorrect URLs for resetCache and OTel guide

deployment/docker/alerts-vmalert.yml
Added missing `{` in vmalert rule.
=> typo: added missing '{'

app/vmui/packages/vmui/src/hooks/useFetchQuery.ts, docs/changelog/CHANGELOG.md
change the `/query_range` and `/query` requests method from `GET` to `POST`. See #6288.
=> vmui: change the `query_range` request method from `GET` to `POST`

docs/VictoriaLogs/data-ingestion/opentelemetry.md
By default, the `elasticsearchexporter` in OTel Collector puts the log message under a field other than `_msg` (e.g., `Body`). Without specifying via an HTTP header, those logs may not be queried correctly. See also: https://github.com/VictoriaMetrics/VictoriaMetrics/issues/6785.
This pull request updates the example configuration and notes for the `elasticsearchexporter`.
=> docs: [VictoriaLogs] OTel Collector elasticsearchexporter header note

docs/VictoriaLogs/data-ingestion/Fluentbit.md
removed FluentBit Elasticsearch example from docs as custom headers are not supported by elasticsearch output till https://github.com/fluent/fluent-bit/pull/9416 is merged and released
fixes https://github.com/VictoriaMetrics/VictoriaMetrics/issues/6985
=> docs/victorialogs/data-ingestion: removed FluentBit Elasticsearch from examples

docs/changelog/CHANGELOG.md, lib/flagutil/password_test.go, lib/fs/fscore/fscore.go
Previous commit 201fd6de1eb0dd03cf5c24787d6a550d07b1390a removed trailing space trim from data read from file. But common practice is to remove such trailing space. And it leaded to the authorization errors for the major group of users.
In first place, this change must help to mitigate an issue with kubernetes. When authorization information was read from Secret content.
Changes to the operator was made to mitigate such problem at commit https://github.com/VictoriaMetrics/operator/commit/1cf64358c8dd3963d0233b6c966de149ad7d522c
We could introduce later optional flag for VictoriaMetrics to disable trim space behavior.
Related issues:
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/6986
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/7089 …
=> fscore: rollback trailing space trim

app/vmselect/main.go
vmselect determines the default value of `-search.maxConcurrentRequests` multiplying the number of available CPUs by 2 if and only if the number is small (to be precise <= 4). That leads `-search.maxConcurrentRequests` is decreasing at the edge of these two cases as shown below:
| CPUs | MaxConcurrentRequests | MaxConcurrentRequests (original proposal) | MaxConcurrentRequests (updated proposal) |
|--------|--------|--------|--------|
| 1 | 2 | 2 | 2 |
| 2 | 4 (prev+2) | 4 (prev+2) | 4 (prev+2) |
| 3 | 6 (prev+2) | 6 (prev+2) | 6 (prev+2) |
| 4 | 8 (prev+2) | 8 (prev+2) | 8 (prev+2) |
| 5 | 5 __(prev-3)__ | 9 __(prev+1)__ | 10 __(prev+2)__ |
| 6 | 6 (prev+1) | 10 (prev+1) | 12 (prev+2) |
| 7 | 7 (prev+1) | 11 (prev+1) | 14 (prev+2) |
| 8 | 8 (prev+1) | 12 (prev+1) | 16 (prev+2) |
I propose …
=> vmselect: ensure default -search.maxConcurrentRequests is non-decreasing

app/vmselect/prometheus/prometheus.go
Change the default value of the maxDeleteSeries flag to 1 million. This is a follow up for #7091
=> Change the default value of the maxDeleteSeries flag to 1 million

app/vmstorage/main.go, lib/storage/storage.go, lib/storage/storage_test.go
`vm_rows_ignored_total` metric is a metric for users to signalize about ingestion issues, such as bad timestamp or parsing error.
In commit https://github.com/VictoriaMetrics/VictoriaMetrics/commit/a5424e95b393022090a7996aa92cefe4d29f7311 this metric started to increment each time vmstorage gets NaN. But NaN is a valid value for Prometheus data model and for Prometheus metrics exposition format. Exporters from Prometheus ecosystem could expose NaNs as values for metrics and these values will be delivered to vmstorage and increment the metric.
Since there is nothing user can do with this, in opposite to parsing errors or bad timestamps, there is not much sense in incrementing this metric. So this commit rolls-back `reason="nan_value"` increments.
Please provide a brief description of the …
=> (app|lib)/vmstorage: do not increment `vm_rows_ignored_total` on NaNs

docs/anomaly-detection/components/writer.md
docs/vmanomaly: remove duplicate header in VmWriter docs
=> docs/vmanomaly: remove duplicate header in VmWriter docs

app/vmselect/promql/eval.go
evalInstantRollup could have overreport the number of fetched series if `offset` checks will result into retry. This change updates fetched series only if these checks were successful.
It also adds a comment to another potential place of over-reporting series fetched. It doesn't fix it, because it would require spending extra resources on such a check, while discrepancy in seriesFetched doesn't affect calculations in any way.
Probably related to https://github.com/VictoriaMetrics/VictoriaMetrics/issues/7170
=> app/vmselect/promql: fix seriesFetched update logic

Makefile, app/vminsert/Makefile, app/vmselect/Makefile, app/vmstorage/Makefile, docs/changelog/CHANGELOG.md
Add darwin `amd64` and `arm64` builds for cluster binaries build.
=> make: add darwin builds for cluster

deployment/docker/Makefile, docs/README.md, docs/changelog/CHANGELOG.md, docs/vmagent.md, lib/promauth/config.go, lib/promscrape/discovery/kubernetes/api_watcher.go, lib/promscrape/scrapework.go
Currently, vmagent always uses a separate `http.Client` for every group watcher in Kubernetes SD. With a high number of group watchers this leads to large amount of opened connections.
This PR adds 2 changes to address this:
- re-use of existing `http.Client` - in case `http.Client` is connecting to the same API server and uses the same parameters it will be re-used between group watchers
- HTTP2 support - this allows to reuse connections more efficiently due to ability of using streaming via existing connections.
See this issue for the details and test results - https://github.com/VictoriaMetrics/VictoriaMetrics/issues/5971
=> vmagent: add support of HTTP2 client for Kubernetes SD

app/vmagent/remotewrite/client.go, app/vmalert/remotewrite/client.go, docs/vmagent.md, docs/vmalert.md
The flags docs mention the flag that does not exist (and never existed). Perhaps that was a typo.
`s/retryMaxInterval/retryMaxTime/g`
=> app/(vmagent,vmalert)/remotewrite/client: Fix flag docs

deployment/docker/alerts-cluster.yml
there's an extra `"` at the end of the dashboard url for this alert; remove it by making the quoting consistent with other alerts in this file.
=> deployment/alerts: fix quoting on DiskRunsOutOfSpace

app/vmalert-tool/unittest/unittest.go, docs/changelog/CHANGELOG.md
address https://github.com/VictoriaMetrics/VictoriaMetrics/issues/6970.
This reduces the hard limit on duration for completing the test when users run vmalert-tool on slow hosts.
=> vmalert-tool: reduce victoriametrics health check interval

app/vmalert-tool/unittest/input.go, app/vmalert-tool/unittest/input_test.go, app/vmalert-tool/unittest/recording.go, docs/changelog/CHANGELOG.md
address https://github.com/VictoriaMetrics/VictoriaMetrics/issues/7224, allow using 
```
exp_samples:
- labels: '{}'
```
for prometheus compatibility.
=> vmalert-tool: add more syntax checks for `input_series` and `exp_samples`

docs/changelog/CHANGELOG.md, lib/storage/search.go
After adding multitenant query feature at v1.104.0, searchQuery wasn't properly unmarshalled at bottom vmselect in multi-level cluster setup. It resulted into empty query responses.
This commit adds fallback to Unmarshal method of SearchQuery to fill TenantTokens. It allows to properly execute search requests
at vmselect side.
Related issue: https://github.com/VictoriaMetrics/VictoriaMetrics/issues/7270
=> lib/storage: properly unmarshal SearchQuery

lib/flagutil/duration.go
`flagutil.Duration` docs state that `m` suffix stands for `minute`, but in fact this suffix is not supported due to ambiguity with `month`
=> clarify `flagutil.Duration` docs

docs/vmbackup.md
Add more detailed information about performing backups for VictoriaMetrics cluster setup. 
More detailed explanation should help to address questions similar to https://github.com/VictoriaMetrics/VictoriaMetrics/issues/7225
=> docs/vmbackup: add information about cluster backups

docs/Troubleshooting.md
When debugging unexpected query results, add reduce_mem_usage=1 param to export query to preserve duplicates.
=> docs/troubleshooting: add reduce_mem_usage=1 to export query

app/vmalert/web_types.go, app/vmalert/web_types_test.go, docs/changelog/CHANGELOG.md
Adds group_name and file fields for recording rules where they were previously left blank.
See issue #7297
=> vmalert: properly set `group_name` and `file` fields for recording rules

app/vmui/packages/vmui/src/pages/ExploreLogs/ExploreLogs.tsx, docs/VictoriaLogs/CHANGELOG.md
Fixes issues with incorrect updating of query and limit fields, and resolves the problem where the display tab resets.
Related issue: #7279 and #7290
=> vmui/logs: fix query and limit update issue

docs/README.md, docs/sd_configs.md, docs/vmagent.md, lib/promscrape/config.go, lib/promscrape/discovery/puppetdb/api.go, lib/promscrape/discovery/puppetdb/api_test.go, lib/promscrape/discovery/puppetdb/mock_puppetdb_server_test.go, lib/promscrape/discovery/puppetdb/puppetdb.go, lib/promscrape/discovery/puppetdb/puppetdb_test.go, lib/promscrape/discovery/puppetdb/resource.go, lib/promscrape/scraper.go
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/5744
Added support for [PuppetDB](https://www.puppet.com/docs/puppetdb/8/overview.html) service discovery.
The following flag is introduced:
```
-promscrape.puppetdbSDCheckInterval duration
Interval for checking for changes in PuppetDB API. This works only if puppetdb_sd_configs is configured in '-promscrape.config' file. See https://docs.victoriametrics.com/sd_configs/#puppetdb_sd_configs for details (default 30s)
```
The service discovery could be config like:
```
scrape_configs:          
- job_name: puppetdb_job 
puppetdb_sd_configs:   
- ...
```
See: [https://docs.victoriametrics.com/sd_configs/#puppetdb_sd_configs](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/c50f1992cd840ffa745911297dada735e00ae1b1/docs/sd_configs. …
=> vmagent: Added support for PuppetDB service discovery

app/vmalert-tool/unittest/unittest.go, docs/vmalert-tool.md
Currently it is not optional option, but if user forgot to set, it defaults to 0, which cause unexpected behavior.
This change sets default = evaluation_interval similar to promtool behavior.
https://prometheus.io/docs/prometheus/2.55/configuration/unit_testing_rules/#test_group
=> Sets default interval for unittest input_series

app/victoria-metrics/testdata/graphite/subquery-aggregation.json
Fix the flaky test by adjusting test data, see #6983.
Test in question: `TestWriteRead/read/graphite2/subquery-aggregation`
Its config (query and data):
```
$ cat app/victoria-metrics/testdata/graphite/subquery-aggregation.json 
{
  "name": "subquery-aggregation",
  "issue": "https://github.com/VictoriaMetrics/VictoriaMetrics/issues/184",
  "data": [
    "forms_daily_count;item=x 1 {TIME_S-1m}",
    "forms_daily_count;item=x 2 {TIME_S-2m}",
    "forms_daily_count;item=y 3 {TIME_S-1m}",
    "forms_daily_count;item=y 4 {TIME_S-2m}"],
  "query": ["/api/v1/query?query=min%20by%20(item)%20(min_over_time(forms_daily_count[10m:1m]))&time={TIME_S-1m}&latency_offset=1ms"],
  "result_query": {
    "status":"success",
    "data":{"resultType":"vector","result":[{"metric":{"item":"x"},"value":["{TIME_ …
```
=> Fix flaky test TestWriteRead/read/graphite/subquery-aggregation

app/vlinsert/loki/loki_json.go, app/vlinsert/loki/loki_json_test.go, docs/VictoriaLogs/CHANGELOG.md
Fix https://github.com/VictoriaMetrics/VictoriaMetrics/issues/7431.
It's now relaxed the validation for the `values` field from `len(row) must be 2` to `len(row) must be >= 2`.
=> VictoriaLogs: fix validation for loki logs with structured metadata

app/vmselect/graphite/eval_test.go, app/vmselect/graphite/transform.go, docs/changelog/CHANGELOG.md
There is an error in the transformRemoveEmptySeries function when xFilesFactor is equal to 0, series are not removed. Judging by the description in the documentation: 
_xFilesFactor follows the same semantics as in Whisper storage schemas. Setting it to 0 (the default) means that only a single value in the series needs to be non-null for it to be considered non-empty, setting it to 1 means that all values ​​in the series must be non-null. A setting of 0.5 means that at least half the values ​​in the series must be non-null._ 
The function must contain a **<=** sign
=> vmselect: Fix graphite function transformRemoveEmptySeries

docs/VictoriaLogs/CHANGELOG.md
Added missing changelog entry for PR
https://github.com/VictoriaMetrics/VictoriaMetrics/pull/5536
=> victorialogs: added missing changelog entry about DataDog support

app/vmauth/auth_config.go, app/vmauth/auth_config_test.go, docs/changelog/CHANGELOG.md
Previously, vmauth could have pick `buMin` as least loaded backend without checking its status. In result, vmauth could have respond to the user with an error even if there were healthy backends. That could happen if healthy backends already had non-zero amount of concurrent requests executing at the moment of least-loaded backend choosing logic.
Steps to reproduce:
1. Setup vmauth with two backends: healthy and non-healthy
2. Execute a bunch of concurrent requests against vmauth (i.e. Grafana dash reload)
3. Observe that some requests will fail with message that all backends are unavailable
Addresses https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3061
Please provide a brief description of the changes you made. Be as specific as possible to help others understand the purpose …
=> app/vmauth: properly check for backend health before leastLoaded policy

docs/Makefile, docs/VictoriaLogs/data-ingestion/DataDogAgent.md, docs/VictoriaLogs/data-ingestion/README.md
added make target, which updates `{{% available_from "#" %}}` shortcode to `{{% available_from "$(PKG_TAG)" %}}` if PKG_TAG matches expression `v.*`. `{{% available_from %}}` shortcode was introduced in https://github.com/VictoriaMetrics/vmdocs/pull/89 to show a reference to a version in a changelog since which a feature was introduced
related issue https://github.com/VictoriaMetrics/VictoriaMetrics/issues/7376
=> added make command for docs version update

docs/VictoriaLogs/FAQ.md
Add FAQs to VictoriaLogs:
- I want to ingest logs without message field, is that possible?
- What if my logs have multiple message fields candidates
Preview: https://github.com/VictoriaMetrics/VictoriaMetrics/blob/docs/VL-FAQ-empty-msg/docs/VictoriaLogs/FAQ.md#i-want-to-ingest-logs-without-message-field-is-that-possible
=> docs: [VictoriaLogs] FAQ add logs without msg field

apptest/tests/key_concepts_test.go, docs/keyConcepts/keyConcepts.md
More key concept tests
-  Verify how the time range points are calculated
-  Vefify that a range query is equivalent to many instant queries
Fix docs accordingly.
=> More key concept tests

docs/vmctl.md
when migrating from cluster to single, the native export API attach `vm_account_id` and `vm_project_id` labels. `--vm-native-disable-binary-protocol` is a workaround to remove them, which is available since v1.93.0 but did not documented in vmctl doc.
See: https://github.com/VictoriaMetrics/VictoriaMetrics/pull/4716
=> vmctl: add docs migrating from cluster to single with --vm-native-disable-binary-protocol

dashboards/vm/vmalert.json, dashboards/vmalert.json, deployment/docker/rules/alerts-vmalert.yml, docs/changelog/CHANGELOG.md
Previously, metrics from groups with the same name but in different files could be mixed in the results.
e.g.  the evaluation time [here](https://grafana.maas.victoriametrics.com/d/LzldHAVnz/victoriametrics-vmalert?orgId=1&var-ds=PE8D8DB4BEE4E4B22&var-job=All&var-instance=All&var-file=%2Fetc%2Fvmalert%2Fconfig%2Fvm-per-tenant-rulefiles-0%2Fmaas-tenant-1011-maas-1011-vm-health.yaml&var-group=All&var-topk=5&editPanel=23) is the total for multiple groups from different tenants.
=> vmalert-dashboard: add `file` label filter to vmalert dashboard panels

docs/VictoriaLogs/data-ingestion/README.md
`VL-Extra-Field` should changed to `VL-Extra-Fields` according to code 
https://github.com/VictoriaMetrics/VictoriaMetrics/blob/02e5fb81c570813799d496e9c7d811d324bcc8ff/app/vlinsert/insertutils/common_params.go#L95
=> fix typos error VL-Extra-Field in docs

app/vmctl/flags.go, app/vmctl/main.go, docs/vmctl.md
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/7521
This PR add **Command-line flags** section to vmctl doc.
=> vmctl: add command-line flag list to doc

app/vmalert/rule/recording_test.go
The order of stale metrics can't be controlled in recording rule, only use two time series then.
=> test: fix flaky ut `TestRecordingRule_Exec`

Makefile
This is a follow-up PR for #7523. Disabling the verbosity in integration tests after confirming that the tests run in both master and cluster branches.
=> Remove -v flag from integration tests

deployment/docker/vm-datasource/docker-compose-cluster.yml, deployment/docker/vm-datasource/docker-compose.yml
Updated victoriametrics-datasource to the newest [release](https://github.com/VictoriaMetrics/victoriametrics-datasource/releases/tag/v0.10.3) version 
=> deployment/docker: update victoriametrics datasource versions to the latest releases

app/vmalert/remoteread/init.go, app/vmalert/rule/alerting.go, app/vmalert/rule/alerting_test.go, docs/VictoriaLogs/vmalert.md, docs/changelog/CHANGELOG.md, docs/vmalert.md
Previously, when the alert got resolved shortly before the vmalert process shuts down, this could result in false alerts.
=> vmalert: fix alert states restoration

app/vmselect/netstorage/netstorage.go, app/vmselect/promql/rollup_result_cache.go, docs/changelog/CHANGELOG.md
This is a follow-up for #7549.  
In multitenant mode cache keys use different authTokens – `nil` for [read](https://github.com/VictoriaMetrics/VictoriaMetrics/pull/7576/files#diff-e0f61d3956b85ae35b3a6275d33b089dca4ccf9be7fc0b77836d970021eeed33R244), `ec.AuthTokens[0]` for [write](https://github.com/VictoriaMetrics/VictoriaMetrics/pull/7576/files#diff-e0f61d3956b85ae35b3a6275d33b089dca4ccf9be7fc0b77836d970021eeed33R266) – it could lead either to panic (if there are no tenants) or to cache miss. 
=> vmselect: fix panic/incorrect tenant in key

app/victoria-metrics/self_scraper.go, app/vmctl/vm_native_test.go, app/vminsert/common/insert_ctx.go, app/vminsert/common/sort_labels.go, app/vminsert/influx/request_handler.go, app/vminsert/relabel/relabel.go, app/vmselect/graphite/tags_api.go, lib/storage/metric_name.go
doing similar changes for both vmagent and vminsert (like one in https://github.com/VictoriaMetrics/VictoriaMetrics/pull/7399) ends up with almost same implementations for each of packages instead of having this shared code in one place. one of the reasons is the same Timeseries and Labels structure from different prompb and prompbmarshal packages. My proposal is to use structures from prompb package only to marshal/unmarshal sent/received data, but for internal transformations use only structures from prompbmarshal package
Another example, where it already can help to simplify code is streaming aggregation pipeline for vmsingle (now it first marshals prompb.Timeseries to storage.MetricRow and then if streaming aggregation or deduplication is enabled it unmarshals all the series back but …
=> refactoring: changed prompb to prompbmarshal everythere where internal series transformations are happening

apptest/model.go, apptest/tests/key_concepts_test.go, apptest/tests/metricsql_test.go, apptest/tests/multitenant_test.go, apptest/vminsert.go, apptest/vmselect.go, apptest/vmsingle.go
This commit adds integration test for multitenant via labels feature - https://docs.victoriametrics.com/cluster-victoriametrics/#multitenancy-via-labels
It also extends current test models in order to:
- accept float timestamps returned from /api/v1/query_range and query api https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/app/vmselect/prometheus/util.qtpl#L43
- accept arbitrary query url params for requests. It simplifies testing for the different VM API extensions
=> apptest: adds cluster test for multitenant API requests

docs/vmalert-tool.md
Fix wrong path to rules_file in vmalert-tool doc
=> docs: fix rule unittest rule_files point to alerts.yaml

docs/vmgateway.md
=> vmgateway: added to documentation a case, when vm_access claim value is of string type

docs/VictoriaLogs/CHANGELOG.md, lib/logstorage/block.go, lib/logstorage/block_stream_writer.go, lib/logstorage/block_test.go, lib/logstorage/block_timing_test.go, lib/logstorage/inmemory_part_test.go
Previously Block columns wasn't properly limited by maxColumnsPerBlock.
And it was possible a case, when more columns per block added than expected.
For example, if ingested log stream has many unuqie fields
and it's sum exceed maxColumnsPerBlock.
We only enforce fieldsPerBlock limit during row parsing, which limits
isn't enough to mitigate this issue. Also it
would be very expensive to apply maxColumnsPerBlock limit during ingestion, since it requires to track all possible field tags combinations.
This commit adds check for maxColumnsPerBlock limit during
MustInitFromRows function call. And it returns offset of the rows and timestamps added to the block.
Function caller must create another block and ingest remaining rows
into it.
Related issue: …
=> lib/logstorage: fixes panic at Block.MustInitFromRows

docs/VictoriaLogs/QuickStart.md
the helm chart being referenced switched from fluentbit to vector in a1aea5d694ff725c350b325205e3372b52242639, so update the docs to match
=> docs/vlogs: replace reference to fluentbit with vector

app/vmalert/config/testdata/dir/rules0-bad.rules, app/vmalert/notifier/alert.go, app/vmalert/notifier/alert_test.go, docs/changelog/CHANGELOG.md
Reusable template can only be defined via `-rule.templates` flag, template defined inside rule annotation shouldn't be reused by others.
=> vmalert: fix possible template overwritten between rule annotations

app/vmui/packages/vmui/src/components/Main/Accordion/Accordion.tsx, docs/changelog/CHANGELOG.md
Prevent accordion from collapsing when selecting text in headers.
Related issue: #7742
=> vmui: prevent accordion collapse on text selection in headers 

docs/changelog/CHANGELOG.md, docs/sd_configs.md, lib/promscrape/discovery/docker/api.go, lib/promscrape/discovery/docker/container.go, lib/promscrape/discovery/docker/container_test.go, lib/promscrape/discovery/docker/docker.go
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/7398
add `match_first_network` support for docker service discovery. 
It uses the first network if the container has multiple networks defined, thus avoiding collecting duplicate targets.
=> vmagent: add match_first_network support for docker sd

lib/storage/dedup_test.go, lib/storage/dedup_timing_test.go
* update misleading comments about preferring NaNs on intervals. NaNs are only preferred on timestamp conflicts
* add conflicting timestamps to the benchmark test. Previously, benchmark wasn't checking the timestamp conflict code branch. The updated results after https://github.com/VictoriaMetrics/VictoriaMetrics/commit/c0fcfd6b97d347ce5c59c9b187edcddefb0f0bbb are the following:
```
benchstat old.txt new.txt
goos: darwin
goarch: arm64
pkg: github.com/VictoriaMetrics/VictoriaMetrics/lib/storage
cpu: Apple M4 Pro
│   old.txt    │               new.txt                │
│    sec/op    │    sec/op     vs base                │
DeduplicateSamples/minScrapeInterval=3s-14               889.7n ± ∞ ¹   904.3n ± ∞ ¹       ~ (p=1.000 n=1) ²
DeduplicateSamples/minScrapeInterval=4s-14 …
```
=> lib/storage: update dedup tests

deployment/docker/rules/alerts-vmanomaly.yml, docs/anomaly-detection/Self-monitoring.md
fixes #7804 by adding alert for missing uptime metric in vmanomaly
=> fixed #7804 Added NoSelfMonitoringMetrics rule

deployment/docker/docker-compose-victorialogs.yml, deployment/docker/provisioning/datasources/victoriametrics-logs-datasource/victoriametrics-logs-datasource.yml
Renamed victorialogs-datasource to victoriametrics-logs-datasource.
We prepared the victorialogs Grafana plugin for sign and updated the plugin ID. This action require to update configs in our ops repository
Please check this [release](https://github.com/VictoriaMetrics/victorialogs-datasource/releases/tag/v0.13.0) and https://github.com/VictoriaMetrics/victorialogs-datasource/pull/161 with changes
=> deployment/docker: rename victorialogs-datasource to victoriametrics-logs-datasource

app/vminsert/common/insert_ctx.go, app/vminsert/common/sort_labels.go, app/vminsert/common/streamaggr.go, app/vminsert/csvimport/request_handler.go, app/vminsert/graphite/request_handler.go, app/vminsert/influx/request_handler.go, app/vminsert/native/request_handler.go, app/vminsert/newrelic/request_handler.go, app/vminsert/opentsdb/request_handler.go, app/vminsert/opentsdbhttp/request_handler.go, app/vminsert/prometheusimport/request_handler.go, app/vminsert/vmimport/request_handler.go, apptest/tests/relabeling_test.go, apptest/vmsingle.go, docs/changelog/CHANGELOG.md
Regression was introduced at 564e6ea024112fdfc65121ae889977aee251f668 after implementing: https://github.com/VictoriaMetrics/VictoriaMetrics/issues/6928
ctx.Labels array could be incorrectly updated and changes to it after relabeling rules can be lost.
E.g. ctx.Labels passed to WriteDataPoint function as slice copy, but results of relabeling only changed an actual slice at ctx.Labels.
This commit replaces implicit relabeling call with explicit `TryPrepareLabels` function.
It also reduces code diffs with cluster version.
related issue:
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/7865
The following checks are …
=> app/vminsert: properly apply relabeling at ingestion

docs/guides/getting-started-with-opentelemetry/README.md, docs/guides/getting-started-with-opentelemetry/app.go.example
* simplify wording
* update styles
* remove extra info about go application details. The details are likely not needed and we didn't have details for rolling-dice app anyway. So keep it simple for consstency and brevity.
* update navigation for simplicity sake
* fix typos
follow-up after https://github.com/VictoriaMetrics/VictoriaMetrics/commit/40b47601d1fb7c96cee49d254a57055081d0f2d0
=> docs: update OTEL guide

docs/CONTRIBUTING.md
Fixed typo in contributing.md (enterpriZe -> enterpriSe in the label name)
=> docs: changed typo in label (enterpriSe instead of enterpriZe)

app/vmctl/influx/influx.go, docs/changelog/CHANGELOG.md
Previously, vmctl expect that tag must exist for each measurement, but it's actually not necessary.
https://github.com/VictoriaMetrics/VictoriaMetrics/blob/f16a58f14c43663ca35093b6583539934bdc6544/app/vmctl/influx/influx.go#L183-L186
This pull request fix it by removing the check. For influx series `measurement1_value1{}`, it will be represented as:
```go
Series{
Measurement: "measurement1",
Field:       "value1",
LabelPairs:  []LabelPair{},
EmptyTags:   []string{},
}
```
and searched by the following query:
```sql
select "value1" from "measurement1"
``` 
=> fix: [vmctl] fix support for influx series without tag

deployment/docker/Makefile
In order for third-party tooling to identify the source repository of
VictoriaMetrics, add the org.opencontainers.image label to the
Dockerfiles. This enables a whole suite of tools that scan container
images to further correlate data with the source code.
The lack of these annotations can be identified using docker:
```shell
docker pull victoriametrics/victoria-metrics
docker inspect victoriametrics/victoria-metrics
```
```jsonc
// ...
"Labels": null
// ...
```
If we try an image that has the annotations, we'll see more output.
```shell
docker pull traefik
docker image inspect traefik
```
```jsonc
// ...
"Labels": {
"org.opencontainers.image.description": "A modern reverse-proxy",
"org.opencontainers.image.documentation": "https://docs.traefik.io",
"org.opencontainers.image.source": …
```
=> Add open containers source label to Dockerfiles

docs/README.md
clarify extra resource is needed when downsampling with filter(s) or retention filter(s) is applied
=> docs: clarify extra resource is needed for downsampling/retention filter

docs/VictoriaLogs/FAQ.md
There has been a question in our public Slack on whether the length limit of a log record is going to be changed. See: https://victoriametrics.slack.com/archives/C05UNTPAEDN/p1736156255119689
This PR documents the max length and explains why it has been chosen. This FAQ section could serve as an answer to more questions like this.
=> Update VictoriaLogs FAQ: add a section about max log record length

app/vmalert/notifier/alertmanager.go, app/vmalert/notifier/alertmanager_request.qtpl, app/vmalert/notifier/alertmanager_request.qtpl.go, app/vmalert/notifier/alertmanager_test.go, docs/changelog/CHANGELOG.md
c7fc0d0d2fa5c56bff5731709c3067532edda386 commit enabled skipping alerts in case there is no labels present for an alert. This made clause which was adding a comma for the JSON list incorrect as it is not possible to determine if the next alert will be skipped or not.
This fix renders all alert labels in advance allowing properly format JSON payload for Alertmanager notification.
See: https://github.com/VictoriaMetrics/VictoriaMetrics/issues/7985
=> app/vmalert/notifier: fix rendering of Alertmanager notification body

app/vmselect/promql/eval.go, docs/changelog/CHANGELOG.md
Since https://github.com/VictoriaMetrics/VictoriaMetrics/commit/44b071296d4bb98a5d425d0350636b4dfdc3c4b9 `evalNumber` function no longer updating MetricName tenancy information. This leads to mismatch in metric names between the query result and evaluated number for all tenants other than 0:0.
For example, query `count(up) or 0` will return different results for tenants 0:0 and 1:1 (assuming up is present for both tenants):
- tenant 0:0 - will only contain result of `count(up)`
- tenant 1:1 - will return both `count(up)` and `0` since metric names will not be matched
This restores setting of tenancy information for metric name for single-tenant queries.
Also see: https://github.com/VictoriaMetrics/VictoriaMetrics/issues/7987
=> app/vmselect/promql:  set tenant information for numbers

app/vmstorage/main.go, docs/Cluster-VictoriaMetrics.md, docs/README.md, lib/logstorage/indexdb.go, lib/mergeset/part.go, lib/mergeset/part_search.go, lib/mergeset/part_search_test.go, lib/mergeset/table.go, lib/mergeset/table_search.go, lib/mergeset/table_search_test.go, lib/mergeset/table_search_timing_test.go, lib/mergeset/table_test.go, lib/storage/block_stream_merger.go, lib/storage/index_db.go, lib/storage/index_db_test.go, lib/storage/merge.go, lib/storage/merge_test.go, lib/storage/merge_timing_test.go, lib/storage/partition.go, lib/storage/search.go, lib/storage/storage.go
Hint allows to choose type of cache to be used for index search:
- in-memory parts are storing recently ingested samples and should use main cache. This improves ingestion speed and cache hit ration for queries accessing recently ingested samples.
- merges of file parts is performed in background, using a separate cache allows avoiding pollution of the main cache with irrelevant entries.
Related issue:
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/7182
=> lib/storage: add a hint for merge about type of parts in merge

app/vmselect/promql/rollup.go, app/vmselect/promql/rollup_test.go, docs/changelog/CHANGELOG.md
When vmselect process a rollup function it fetches all the raw samples on requested `start-end` interval of the query. It then loops through the raw samples, picks the range of the samples based on provided `step` interval and invokes a rollup function for each of the picked ranges of samples.
During this processing, vmselect always populates the `realPrevValue` field with the closest previous raw sample value before the picked range of samples. This `realPrevValue` is used by rollup functions like increase_pure or delta to decide whether the counter change happened or not. For example, we get the counter value == 1. If we've seen this counter before and its value was also 1 - then no change happened. If we didn't see it before, then this counter should have started with value=0 and we …
=> app/vmselect/promql: account for staleness when populating realPrevValue

Makefile, app/vmalert/manager.go, app/vmalert/rule/group.go, app/vmctl/prometheus/prometheus.go, app/vmselect/graphite/aggr.go, app/vmselect/graphite/transform.go, app/vmselect/promql/aggr.go, app/vmselect/promql/rollup.go, lib/protoparser/datadogsketches/parser.go, lib/protoparser/opentelemetry/pb/metrics.go, lib/streamaggr/max.go, lib/streamaggr/min.go
New version has additional checks and reduced resource consumption, so it doesn't timeout for our internal repos.
To make linter happy, I addressed "redefinition of the built-in function" lint error.
=> make: bump golangci-lint to v1.63.4

lib/storage/storage_test.go
Commit eef6943084e3cca6995b8603003de6ca7a25fbf6  added new test functions. Which checks various cases for metricName registration at data ingestion.
Initial dataset size had 4 batches with 100 rows each. It works fine at machines with 5GB+ memory.
But i386 architecture supports only 4GB of memory per process.
Due to given limitations, batch size should be reduced to 3 batches and 30 rows. It keeps the same
test funtionality, but reduces overall memory usage to ~3GB.
=> lib/storage: reduce test suite batch size

app/vmselect/promql/rollup.go, app/vmselect/promql/rollup_test.go
`doInternal` has adaptive staleness detection mechanism. It is calculated using timestamp distance between samples in selected list of samples. It is dynamic because VM can store signals from many sources with different samples resolution. And while it works for most of cases, there are edge cases for rollup functions that are comparing values between windows: increase, increase_pure, delta.
The edge case 1.
There was a gap between series because of the missed scrape or two. In this case staleness will trigger and increase-like functions will assume the value they need to compare with is 0. In result, this could produce spikes for a flappy data - see https://github.com/VictoriaMetrics/VictoriaMetrics/issues/894 This problem was solved by introducing a `realPrevValue` field - …
=> app/vmselect/promql: limit staleness detection for increase/increase_pure/delta

docs/VictoriaLogs/Roadmap.md
Fixes #8019 and adds retention filters to victorialogs roadmap as an enterprise feature
=> added retention filters to Victorialogs roadmap

app/vmui/packages/vmui/web/main.go
Seems `favicon-32x32.png` removed in #6972
Fixes this:
```shell
√ build % go build -x -buildmode="pie" -trimpath -mod="readonly" -modcacherw -ldflags "-linkmode external"
WORK=/var/folders/mj/r83hky151tzbqsvml0hxts_w0000gn/T/go-build2937230855
main.go:13:12: pattern favicon-32x32.png: no matching files found
```
=> vmui: web: fixed favicon name

app/vmui/packages/vmui/src/components/LogsConfigurators/GroupLogsConfigurators/GroupLogsConfigurators.tsx, app/vmui/packages/vmui/src/components/LogsConfigurators/GroupLogsConfigurators/style.scss, app/vmui/packages/vmui/src/components/Main/Accordion/Accordion.tsx, app/vmui/packages/vmui/src/components/Main/Modal/Modal.tsx, app/vmui/packages/vmui/src/components/Main/Select/style.scss, app/vmui/packages/vmui/src/constants/logs.ts, app/vmui/packages/vmui/src/hooks/useClickOutside.ts, app/vmui/packages/vmui/src/pages/ExploreLogs/GroupLogs/GroupLogs.tsx, app/vmui/packages/vmui/src/pages/ExploreLogs/GroupLogs/GroupLogsFieldRow.tsx, app/vmui/packages/vmui/src/pages/ExploreLogs/GroupLogs/GroupLogsHeader.tsx, app/vmui/packages/vmui/src/pages/ExploreLogs/GroupLogs/GroupLogsHeaderItem.tsx, app/vmui/packages/vmui/src/pages/ExploreLogs/GroupLogs/GroupLogsItem.tsx, app/vmui/packages/vmui/src/pages/ExploreLogs/GroupLogs/style.scss, docs/VictoriaLogs/CHANGELOG.md
This PR introduces improvements for the `Group view` tab:
1. **Reduced text size and improved styles**  
Related issue: #7479
<details>  
<summary>Demo UI</summary>  
</details>  
2. **Added the ability to select a field to display instead of `_msg`**  
You can select fields to display in the field list or in the settings
Related issue: #7419
<details>  
<summary>Demo UI</summary>  
</details>
3. **Added date format customization**  
<details>  
<summary>Demo UI</summary>  
</details>  
4. **Added an option to display log messages in a single line**  
<details>  
<summary>Demo UI</summary>  
</details>  
5. **Added an option to display group labels in a single line**  
<details>  
<summary>Demo UI</summary>  
</details> 
7. **Settings indicator for modified defaults**  
A red marker is …
=> vmui/logs: improvements to grouped view in logs 

docs/changelog/CHANGELOG.md, lib/protoparser/opentelemetry/stream/streamparser.go, lib/protoparser/opentelemetry/stream/streamparser_test.go, lib/protoparser/opentelemetry/stream/streamparser_timing_test.go
Despite requirement in OpenTelemetry spec that histograms should contain sum, [OpenTelemetry collector promremotewrite translator](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/37c8044abfaace7077a18a643d70057aa475fe65/pkg/translator/prometheusremotewrite/helper.go#L222) and [Prometheus OpenTelemetry parsing](https://github.com/prometheus/prometheus/blob/d52e689a20da7aa248291f0c0ea86fc4b8dbb189/storage/remote/otlptranslator/prometheusremotewrite/helper.go#L264) skip only sum if it's absent. Our current implementation drops buckets if sum is absent, which causes issues for users, that are expecting a similar to Prometheus behaviour 
Please provide a brief description of the changes you made. Be as specific as possible to help others understand the purpose and impact …
=> lib/protoparser/opentelemetry: do not drop histogram buckets, when sum is absent

docs/guides/k8s-monitoring-via-vm-single/README.md
As reported by a user, the value in [VictoriaMetrics Single helm chart](https://github.com/VictoriaMetrics/helm-charts/blob/master/charts/victoria-metrics-single/values.yaml#L420) and actual example, should be "enabled", not "enable". This commit fixes it.
=> doc: fix typo in vmsingle k8s monitoring guide

app/vmui/packages/vmui/src/components/Configurators/QueryEditor/QueryEditor.tsx, docs/VictoriaLogs/CHANGELOG.md, docs/changelog/CHANGELOG.md
Fixed an issue where pressing `Enter` did not execute the query, and `Shift+Enter` did not insert a new line.  
- The issue occurred when autocomplete was disabled.  
- This problem affected the query editor in both the VictoriaMetrics UI and VictoriaLogs UI.  
Ref issue: #8058
=> vmui: fix issue with query execution and line breaks in query editor

docs/VictoriaLogs/README.md, docs/vmauth.md
- add example a generic example to vmauth docs
- add an multi-tenancy usage example to VictoriaLogs docs
=> docs/{vmauth,VictoriaLogs}: add examples of using headers per-user

dashboards/victorialogs.json, dashboards/victoriametrics-cluster.json, dashboards/victoriametrics.json, dashboards/vm/victorialogs.json, dashboards/vm/victoriametrics-cluster.json, dashboards/vm/victoriametrics.json, dashboards/vm/vmagent.json, dashboards/vm/vmalert.json, dashboards/vm/vmauth.json, dashboards/vmagent.json, dashboards/vmalert.json, dashboards/vmauth.json
See https://github.com/VictoriaMetrics/VictoriaMetrics/issues/7988
=> dashboards: consistently use `process_cpu_cores_available` for CPU usage

app/vmui/packages/vmui/src/api/types.ts, app/vmui/packages/vmui/src/components/Chart/BarHitsChart/BarHitsTooltip/BarHitsTooltip.tsx, app/vmui/packages/vmui/src/components/Chart/BarHitsChart/BarHitsTooltip/style.scss, app/vmui/packages/vmui/src/components/Chart/BarHitsChart/hooks/useBarHitsOptions.ts, app/vmui/packages/vmui/src/pages/ExploreLogs/hooks/useFetchLogHits.ts, docs/VictoriaLogs/CHANGELOG.md
Restored transparency for bars in the hits chart to improve visibility. Ref issue: #8152
| State  | Preview |
|--------|---------|
| Before | ![image](https://github.com/user-attachments/assets/2f95cdd9-0b39-4420-9bf7-011274eadc86) |
| After  | ![image](https://github.com/user-attachments/assets/9123d8e7-e615-41ab-9193-4c50ce262e7f) |
=> vmui/logs: fix transparency for bars in hits chart

app/vmui/packages/vmui/src/components/Main/CodeExample/CodeExample.tsx, app/vmui/packages/vmui/src/components/Table/Table.tsx, docs/changelog/CHANGELOG.md
Replaced `await navigator.clipboard.writeText` with `useCopyToClipboard` hook.  
See [this pull request](https://github.com/VictoriaMetrics/VictoriaMetrics/pull/7778) for details.
=> vmui: refactor clipboard handling with useCopyToClipboard hook

app/vmselect/promql/binary_op.go, app/vmselect/promql/exec_test.go, docs/changelog/CHANGELOG.md
The change covers various corner cases when using `or` binary operator. See corresponding issues and pull request here to see the cases: https://github.com/VictoriaMetrics/VictoriaMetrics/pull/7770
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/7759 https://github.com/VictoriaMetrics/VictoriaMetrics/issues/7640
=> app/vmselect/promql: fix discrepancies when using `or` binary operator

deployment/docker/rules/alerts-vmagent.yml
Currently the alert descrption considers only one end of the connection (vmagent). While saturation can also be caused by slowness of the receiving components (vminsert, vmstorage). Update the alert description with a brief suggestion to also check the dashboards of these components. 
=> RemoteWriteConnectionIsSaturated alert: add another saturation cause to the alert description

docs/stream-aggregation.md
Fix metric name labels set not being "closed" by `}`.
=> docs/streaming-aggregation: fix typo in metric name

app/vmctl/flags.go, docs/vmctl.md
Explicitly mention that `--vm-rate-limit` is used for each individual worker defined by `--vm-concurrency`.
=> {docs,app/vmctl}: clarify how vm-rate-limit is applied

docs/changelog/CHANGELOG.md, lib/storage/storage.go, lib/storage/storage_test.go
The cardinality limiter in this case does not receive the actual metricID but some other value found in r.TSID.MetricID and is not initialized. Depending on the system and/or go runtime implementation, this value can be 0 or some garbage value (which shouldn't have too wide a range). Thus, there basically no limit for inserted metricIDs.
=> lib/storage: Fix cardinality limiting for cases when insertion takes fast path

app/vmselect/main.go, docs/changelog/CHANGELOG.md
Improves integration with third-party solutions who rely on non-root endpoints (i.e. MinIO) when the vmselect path has been specified in the configured Prometheus URL like: `http://vmselect.:8481/select/0/prometheus`
Comparable change has been done before (b885a3b6e95a9b68db0bba1c2ffa00fdeaab4019), however only takes care of the root path. This means endpoints `-/healthy` and `-/ready` are still not available on full vmselect Prometheus paths, resulting in unsupported path requests.
This change makes these endpoints available on the full paths like: `/select/0/prometheus/-/healthy` and `/select/0/prometheus/-/ready`, thus achieving full Prometheus compatibility for external dependencies.
- https://github.com/minio/console/issues/2829
- …
=> fix(vmselect): expose /-/healthy and /-/ready endpoints on full Prometheus path

app/vmui/packages/vmui/src/components/Configurators/StepConfigurator/StepConfigurator.tsx, app/vmui/packages/vmui/src/components/Configurators/StepConfigurator/style.scss, app/vmui/packages/vmui/src/hooks/useFetchQuery.ts, app/vmui/packages/vmui/src/utils/time.ts, docs/changelog/CHANGELOG.md
Updated default `step` calculation for `Table` and `JSON` views.
- When switching to the `Table` or `JSON` view, the default step is now automatically set to `end - start`, where `end` and `start` correspond to the selected time range.
- If the user has manually set a step value, it will remain unchanged when switching views or changing the time range.
- The UI now explicitly indicates when the step is automatically calculated. 
<details> <summary>Demo</summary>
https://github.com/user-attachments/assets/2540de24-36ed-4764-a047-1c6b48a80ed4
</details>
**Note:** These views use the [`/api/v1/query`](https://docs.victoriametrics.com/keyconcepts/#instant-query) endpoint for instant queries.  
Related issue: #8240
=> vmui: update default step calculation for instant queries

docs/changelog/CHANGELOG.md, lib/protoparser/clusternative/stream/streamparser.go
The `callbackErr` is silently ignored in clusternative parser.
It will now be returned after reading all block metrics. This aligns with other parsers in `lib/protoparser` (not sure if `errors.Join` is needed, as others don't have it, but it provides more information in case of multiple errors).
=> vmstorage: fix silent callback error

app/vmui/packages/vmui/src/components/Configurators/QueryEditor/LogsQL/useFetchLogsQLOptions.tsx, docs/VictoriaLogs/CHANGELOG.md
Fix autocomplete not passing `AccountID` and `ProjectID` headers when fetching suggestions in VictoriaLogs UI.
Related: #8042
=> vmui/logs: fix autocomplete ignoring selected tenant

apptest/tests/vmauth_routing_test.go, docs/changelog/CHANGELOG.md, lib/httpserver/httpserver.go
Commit 68791f9ccc21548d27f1cf04d0b3270be4146b82 introduced regression. It performed basicAuth check before built-in routes. It made impossible to bypass basic authorization with `authKey` param.
This commit fixeds that issue and removes unneeded check. It also adds integration tests for this case.
Related issue:
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/7345
=> lib/httpserver: properly check basic authorization

docs/changelog/CHANGELOG.md, go.mod, go.sum, vendor/github.com/VictoriaMetrics/metricsql/lexer.go, vendor/github.com/VictoriaMetrics/metricsql/parser.go, vendor/github.com/VictoriaMetrics/metricsql/prettifier.go, vendor/modules.txt
See https://github.com/VictoriaMetrics/VictoriaMetrics/issues/7703
=> metricsql: support auto-format (prettify) for expressions that use quoted metric or label names

docs/anomaly-detection/Self-monitoring.md
It looks like when using html image insertion, the path is changed. This commit fixes that by redirecting to the previous dir in path.
=> docs: fix vmanomaly image broken links

docs/victoriametrics-cloud/get-started/quickstart.md
It looks like the version deployed works differently than in local, and some paths are not taken correctly. This commit fixes that by adding absolute paths to the 2 images included in this section.
=> docs/cloud: fix image routes in getstarted

docs/anomaly-detection/Presets.md, docs/anomaly-detection/QuickStart.md
- Fixed 404 links to anomaly score dashboard `.json` file on Github.
- Fixed broken markdown on QuickStart page.
=> docs/vmanomaly: fix 404 in dashboard guide

deployment/docker/rules/alerts-health.yml, docs/changelog/CHANGELOG.md
TooHighQueryLoad should trigger when vmsingle or vmselect can't start processing read queries for last 15min.
=> deployment/rules: add alerting rule `TooHighQueryLoad`

app/vmctl/flags.go, app/vmctl/influx/influx.go, app/vmctl/influx/influx_test.go, docs/changelog/CHANGELOG.md, docs/vmctl.md
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/8259
https://docs.influxdata.com/influxdb/v1/query_language/explore-schema/#run-a-show-series-query-limited-by-time
=> app/vmctl: respect time filter when exploring time series for influxdb

README.md, docs/README.md
Before, badge could have shown the latest build result. Even for open PRs. Now, it shows the latest build result for `master` branch.
See https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/monitoring-workflows/adding-a-workflow-status-badge
=> docs: point github badge to the main action for `master` branch

docs/changelog/CHANGELOG.md, lib/storage/index_db.go
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/8345
Fix the incorrect caching of extMetricsIDs when a query timeout error occurs. This bug can lead to incorrect query results.
=> bug: fix the incorrect caching of extMetricsIDs when a query timeout error occurs

deployment/docker/Makefile
Updated `publish-via-docker` task to push images to multiple registries as defined by `DOCKER_REGISTRIES`. By default, publish pushes images to both docker.io and quay.io. It is possible to choose a single repo by overriding `DOCKER_REGISTRIES`, for example: `DOCKER_REGISTRIES=quay.io make publish-victoria-logs`
Note that `package-via-docker` task is not using multiple registries as there is usually little sense in building same image with different tags for local use.
See: https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4116
=> deployment/docker/make: publish images to multiple repos

app/vmagent/remotewrite/remotewrite_test.go, lib/prompbmarshal/util.go, lib/promscrape/scrapework_test.go, lib/protoparser/prometheus/util.go, lib/streamaggr/deduplicator_test.go, lib/streamaggr/streamaggr_test.go, lib/streamaggr/streamaggr_timing_test.go
`MustParsePromMetrics` imports `lib/protoparser/prometheus`, and this package exposes the following metrics:
```
vm_protoparser_rows_read_total{type="promscrape"}
vm_rows_invalid_total{type="prometheus"}
```
It means every package that uses `lib/prompbmarshal` will start exposing these metrics. For example, vlogs imports `lib/protoparser/common` which uses `lib/prompbmarshal.Label`. And only because of this vlogs starts exposing unrelated prometheus metrics on /metrics page.
Moving `MustParsePromMetrics` to `lib/protoparser/prometheus` seems like the leas intrusive change.
-----------
Depends on another change https://github.com/VictoriaMetrics/VictoriaMetrics/pull/8403
=> lib/prompbmarshal: move MustParsePromMetrics to protoparser/prometheus

docs/Quick-Start.md, docs/README.md
Previous link was incorrectly created by adding repository name to organization link.
All other links are using proper schema.
This is a follow-up for 6ff61a1c.
=> docs: fix link to quay docker image for single-node

app/vlogsgenerator/main.go, app/vlselect/logsql/logsql.go, app/vmalert/templates/template.go, app/vmctl/utils/time.go, lib/httputils/duration.go, lib/httputils/time.go, lib/logstorage/parser.go, lib/promscrape/config.go, lib/promutils/duration.go, lib/promutils/duration_test.go, lib/storage/part_header.go, lib/timeutil/duration.go, lib/timeutil/time.go, lib/timeutil/time_test.go
Since funcs `ParseDuration` and `ParseTimeMsec` are used in vlogs, vmalert, victoriametrics and other components, importing promutils only for this reason makes them to export irrelevant `vm_rows_invalid_total{type="prometheus"}` metric.
This change removes `vm_rows_invalid_total{type="prometheus"}` metric from /metrics page for these components.
=> lib/promutils: move time-related funcs from `promutils` to `timeutil`

docs/README.md
I guess a "downsampling" term is more appropriate than "deduplication" in the downsampling paragraph. 
=> docs/downsampling: fix terminology. replace "deduplication" with "downsample".

app/vmui/packages/vmui/src/pages/DownsamplingFilters/hooks/useDebugDownsamplingFilters.ts, app/vmui/packages/vmui/src/pages/DownsamplingFilters/index.tsx, app/vmui/packages/vmui/src/styles/components/table.scss, docs/changelog/CHANGELOG.md
This PR fixes an issue where the Downsampling filters debug page would get stuck in an infinite loading state when labels had no matches. Now, the case is properly handled.
Related issue: #8339
=> vmui: fix infinite loader on downsampling page

docs/anomaly-detection/QuickStart.md, docs/anomaly-detection/_index.md
Removed VictoriaMetrics prefix from anomaly detection menu items
=> docs: remove VictoriaMetrics prefix from anomaly detection menu items titles

docs/changelog/CHANGELOG.md, lib/promscrape/targetstatus.go
If in the scrape file, I do some magic and manipulate the job name then Prometheus will show scrapePool as the original job name in the targets API, but vmagent will set it to the final value which is wrong. 
example
```
job: consul-targets
...
- source_labels: [ __meta_consul_service ]
regex: (\w+)[_-]exporter
target_label: job
replacement: $1
```
curl to prom API will show
`"scrapePool": "consul-targets",`
vmagent:
`""scrapePool": "node",`
before changes:
```
curl -s 'http://localhost:8429/api/v1/targets' | jq -r '.data.activeTargets[].scrapePool'| sort|uniq
blackbox
pgbackrest
postgres
```
after changes
```
curl -s 'http://localhost:8429/api/v1/targets' | jq -r '.data.activeTargets[].scrapePool'| sort|uniq
blackbox
consul-targets
```
=> fix scrape pool name in targets api

app/vmagent/remotewrite/remotewrite.go, docs/vmagent.md
revert doc change in https://github.com/VictoriaMetrics/VictoriaMetrics/commit/815bad3687a2207ce267ec81099b4e20e9a91cbb and move new content to another section.
=> vmagent: revert doc change for on-disk persistence and move new content to another section

app/vmui/packages/vmui/src/components/Main/Accordion/Accordion.tsx, docs/VictoriaLogs/CHANGELOG.md
Fix endless group expansion loop.
Related issue: #8347
=> vmui/logs: fix endless group expansion loop bug

app/vmalert/manager.go, app/vmalert/manager_test.go, app/vmalert/rule/alerting.go, app/vmalert/rule/alerting_test.go, app/vmalert/rule/group.go, app/vmalert/rule/recording.go, app/vmalert/web_test.go, app/vmalert/web_types.go, app/vmalert/web_types_test.go, docs/changelog/CHANGELOG.md
1. fix possible data race on group checksum when reload is called concurrently. Before, it didn't affect much but might update the group one more time.
2. remove the unnecessary g.mu.RLock(), as changes to group.ID() indicate that type and interval have changed, and the group is new.
=> vmalert: fix possible data race on group checksum

app/vmalert/main_test.go, app/vmalert/manager.go, app/vmalert/rule/alerting.go, app/vmalert/rule/alerting_test.go, app/vmalert/rule/group.go, app/vmalert/rule/group_test.go, app/vmalert/rule/recording.go, app/vmalert/rule/rule.go, docs/changelog/CHANGELOG.md
address https://github.com/VictoriaMetrics/VictoriaMetrics/issues/8532
~~This pull request also contains https://github.com/VictoriaMetrics/VictoriaMetrics/pull/8540, must be merged after that.~~
Delay the creation of group&rule metrics only before `group.Start()`.
=> vmalert: fix memory leak during rule group updates on reload

docs/guides/getting-started-with-vm-operator/README.md, docs/guides/k8s-monitoring-via-vm-cluster/README.md, docs/guides/k8s-monitoring-via-vm-single/README.md
This pull request update some wording for the k8s guide here:
- [Kubernetes monitoring via VictoriaMetrics Single](https://docs.victoriametrics.com/guides/k8s-monitoring-via-vm-single)
- [Kubernetes monitoring with VictoriaMetrics Cluster](https://docs.victoriametrics.com/guides/k8s-monitoring-via-vm-cluster)
- [Getting started with VM Operator, ](https://docs.victoriametrics.com/guides/getting-started-with-vm-operator)
The change is based on executing the commands in guide and check the output diff.
=> doc: [guide] update k8s vmsingle vmcluster helm and operator guide

docs/victorialogs/CHANGELOG.md, docs/victorialogs/FAQ.md, docs/victorialogs/LogsQL.md, docs/victorialogs/QuickStart.md, docs/victorialogs/Roadmap.md, docs/victorialogs/_index.md, docs/victorialogs/data-ingestion/DataDogAgent.md, docs/victorialogs/data-ingestion/Filebeat.md, docs/victorialogs/data-ingestion/Fluentbit.md, docs/victorialogs/data-ingestion/Fluentd.md, docs/victorialogs/data-ingestion/Journald.md, docs/victorialogs/data-ingestion/Logstash.md, docs/victorialogs/data-ingestion/Promtail.md, docs/victorialogs/data-ingestion/README.md, docs/victorialogs/data-ingestion/Telegraf.md, docs/victorialogs/data-ingestion/Vector.md, docs/victorialogs/data-ingestion/_index.md, docs/victorialogs/data-ingestion/opentelemetry.md, docs/victorialogs/keyConcepts.md, docs/victorialogs/querying/_index.md, docs/victorialogs/vmalert.md
replace /VictoriaLogs aliases to /victorialogs as generated directories are anyway renamed to victorialogs before deployment
need to merge this PR immediately after https://github.com/VictoriaMetrics/vmdocs/pull/116
=> docs: update /VictoriaLogs path in hugo to /victorialogs

app/vmagent/remotewrite/pendingseries.go
Fixes golangci-lint issues introduced in https://github.com/VictoriaMetrics/VictoriaMetrics/commit/98f1e32e39f743e5e128f18096b6bd925c7d2898
```
--- a/app/vmagent/remotewrite/pendingseries.go
+++ b/app/vmagent/remotewrite/pendingseries.go
@@ -202,7 +202,7 @@ func (wr *writeRequest) copyTimeSeries(dst, src *prompbmarshal.TimeSeries) {
// Pre-allocate memory for labels.
labelsLen := len(wr.labels)
-	wr.labels = slicesutil.SetLength(wr.labels, labelsLen + len(labelsSrc))
+	wr.labels = slicesutil.SetLength(wr.labels, labelsLen+len(labelsSrc))
labelsDst := wr.labels[labelsLen:]
// Pre-allocate memory for byte slice needed for storing label names and values.
@@ -212,7 +212,7 @@ func (wr *writeRequest) copyTimeSeries(dst, src *prompbmarshal.TimeSeries) {
neededBufLen += len(label.Name) + …
```
=> vmagent/remotewrite: fix golangci-lint code style issue

app/vmauth/main.go, docs/victoriametrics/changelog/CHANGELOG.md
Currently, requests failing due to network timeout would receive "200 OK" while producing a warning log message about the timeout. This behaviour is confusing and might produce unexpected issues as it is not possible to retry errors properly.
Change this to return "502 Bad Gateway" response so that error can be handled by the client.
See: https://github.com/VictoriaMetrics/VictoriaMetrics/issues/8621
Config for testing:
```
unauthorized_user:
url_prefix: "http://example.com:9800"
```
Before the change:
```
*   Trying 127.0.0.1:8427...
* Connected to 127.0.0.1 (127.0.0.1) port 8427
* using HTTP/1.x
> HEAD /api/v1/query HTTP/1.1
> Host: 127.0.0.1:8427
> User-Agent: curl/8.12.1
> Accept: */*
>
* Request completely sent off
/* NOTE: 30 seconds timeout passes */
< HTTP/1.1 200 OK
HTTP/1.1 200 …
```
=> app/vmauth: return non-OK response for timeouts and request cancellation

app/vmagent/remotewrite/client.go, apptest/testcase.go, apptest/tests/vmagent_remotewrite_test.go, apptest/vmagent.go, apptest/vmsingle.go, docs/victoriametrics/changelog/CHANGELOG.md, lib/encoding/util.go, lib/encoding/util_test.go, lib/protoparser/promremotewrite/stream/streamparser.go
Improve remote write handling in vmagent by setting the `Content-Encoding` header based on the actual request body, rather than relying on configuration.
- Detects Zstd compression via the Zstd magic number.
- Falls back to Snappy if Zstd is not detected.
- Persistent queue may now contain mixed-encoding content.
- Add basic vmagent integration tests
Follow up on https://github.com/VictoriaMetrics/VictoriaMetrics/issues/5301, https://github.com/VictoriaMetrics/VictoriaMetrics/pull/5344 and https://github.com/VictoriaMetrics/VictoriaMetrics/commit/12cd32fd75706969f972a328e8583ca1da9e68c3.
Extracted from https://github.com/VictoriaMetrics/VictoriaMetrics/pull/8462
=>  vmagent/remotewrite: set content encoding header based on actual body

docs/victoriametrics/changelog/CHANGELOG.md, lib/backup/s3remote/s3.go
Previously, if ProfileName is set to empty value (as default). AWS s3 lib ignored any profile config defined with `-configProfilePath`.
This commit correctly configure client options and set profile name only if it's set to non-empty value.
Related issue:
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/8668
=> lib/backup/s3: properly set ProfileName

docs/victoriametrics/changelog/CHANGELOG.md, lib/writeconcurrencylimiter/concurrencylimiter.go
Under heavy load, vmagent's wirte concurrency limiter
(https://github.com/VictoriaMetrics/VictoriaMetrics/blob/2ab53acce487924a49fd5484ac4a90f484cf9fb8/lib/writeconcurrencylimiter/concurrencylimiter.go#L111) queues incoming requests. If a client's timeout is shorter than the wait time in the
queue, the client may close the connection before vmagent starts
processing it. When vmagent then tries to read the request body, it
encounters an ambiguous `unexpected EOF` error
(https://github.com/VictoriaMetrics/VictoriaMetrics/issues/8675).
This commit adds more context to such errors to help users diagnose and
resolve
the issue when it's related to vmagent's own load and queuing behavior.
Possible user actions include:
- Lowering `-insert.maxQueueDuration` below the client's timeout.
- …
=> lib/writeconcurrencylimiter: add some hints to unexpected EOF error message.

app/vmselect/netstorage/netstorage.go, app/vmselect/prometheus/tsdb_status_response.qtpl, app/vmselect/prometheus/tsdb_status_response.qtpl.go, apptest/model.go, apptest/tests/metric_names_stats_test.go, apptest/vmselect.go, docs/victoriametrics/README.md, docs/victoriametrics/changelog/CHANGELOG.md, lib/storage/index_db.go, lib/storage/index_db_test.go, lib/storage/metricnamestats/tracker.go, lib/storage/storage.go, lib/vmselectapi/server.go
This commit adds new fields - `requestsCount` and `lastRequestTimestamp` to series count be metric names stats.
It allows to display an additional stats at explore cardinality page. Stats will only be added if `storage.trackMetricNameStats` flag is set.
This change requires an update to RPC protocol in order to properly
marshal data.
In addition, this commit adds integration tests to TSDB stats API.
Related issue:
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/6145
=> lib/storage: enhance TSDB status response

app/vmui/packages/vmui/src/components/LogsConfigurators/GroupLogsConfigurators/style.scss, app/vmui/packages/vmui/src/components/Table/TableSettings/style.scss, app/vmui/packages/vmui/src/layouts/Header/style.scss, app/vmui/packages/vmui/src/pages/ExploreLogs/ExploreLogsBody/ExploreLogsBody.tsx, app/vmui/packages/vmui/src/pages/ExploreLogs/ExploreLogsBody/style.scss, app/vmui/packages/vmui/src/pages/ExploreLogs/GroupLogs/GroupLogs.tsx, docs/victorialogs/CHANGELOG.md
- Fix mobile layout on the VictoriaLogs page
- Fix width of groups settings modal
- Fix width of table settings modal
=> app/vmui: fix mobile layout on the VictoriaLogs page, fix width of groups and table settings modal

docs/victoriametrics/changelog/CHANGELOG.md, lib/protoparser/protoparserutil/compress_reader.go
The write concurrency limiter in ReadUncompressedData was previously removed in
https://github.com/VictoriaMetrics/VictoriaMetrics/commit/22d1b916bfc4d9f3da47a40c5e13ec093d781135 to avoid suboptimal behavior in certain scenarios. However, follow-up reports—including issue
https://github.com/VictoriaMetrics/VictoriaMetrics/issues/8674 and production feedback from VictoriaMetrics Cloud—indicated a noticeable degradation in performance after its removal.
To mitigate these regressions, this commit reintroduces the concurrency limiter. A long-term, more optimal solution will be explored separately in issue https://github.com/VictoriaMetrics/VictoriaMetrics/issues/8728.
TODO:
=> lib/protoparser/protoparserutil: Restore write concurrency limiter in ReadUncompressedData due to performance regressions

apptest/tests/vmagent_remotewrite_test.go, apptest/vmagent.go
Before the change, the vmagent integration tests created their directory and files inside apptest/tests.
After the change, vmagent is instructed to store all files in a real temporary directory, which is automatically deleted after the tests complete.
=> vmagent: use tmp dir in integrations tests

app/vmui/packages/vmui/src/components/Chart/BarHitsChart/hooks/useBarHitsOptions.ts, docs/victorialogs/CHANGELOG.md
Related issue: #8409 
Added 0 label to the Y axis on VictoriaLogs chart.
=> app/vmui/logs: add 0 label to the Y axis

app/vmalert/remotewrite/client.go
On shutdown, rw client printed two log messages about shutting down and how many series it flushed on shut down.
This commit removes these log messages for the following reasons:
1. These messages were printed for each `client.cc`, which is set to x2 of available CPUs. This behavior generated a lot of useless logs on shutdown.
2. Number of flushed series on shutdown doesn't matter to the user.
Instead, it now prints only two log messages: when shutdown starts and when it ends:
```
^C2025-04-22T07:37:11.932Z      info    VictoriaMetrics/app/vmalert/main.go:189 service received signal interrupt
2025-04-22T07:37:11.932Z        info    VictoriaMetrics/app/vmalert/remotewrite/client.go:152   shutting down remote write client: flushing remained series
2025-04-22T07:37:11.933Z        info …
```
=> app/vmalert/remotewrite: rm noisy shutdown logs

app/vmalert/config/config.go, app/vmalert/notifier/config.go, lib/awsapi/sign_test.go, lib/promauth/config_test.go
Fixes which are required in order to build FIPS-compliant binaries. These changes were originally added for enterprise version and synced to opensource for consistency and easier maintenance.
- consistently use `hash/fnv` at `app/vmalert` when calculating checksums. Usage of md5 is not allowed in FIPS mode.
- increase encryption keys size used in testing in order to allow tests to successfully run in FIPS mode
=> fix: compatibility for FIPS builds

deployment/docker/victorialogs/logstash/Dockerfile, deployment/docker/victorialogs/logstash/elasticsearch/pipeline.conf
1. When I used the opensearch plugin in the reference example, I found a bug that caused memory exhaustion and stopped working. There is a similar issue in the opensearch community: https://github.com/opensearch-project/logstash-output-opensearch/issues/186, @chadmyers raised this issue, but it has not been fixed yet. It has been verified that the elasticsearch plugin does not have this problem.
2. In the vmlogs logstash docking example, it is consistent with the official document's example of using the elasticsearch plugin. https://docs.victoriametrics.com/victorialogs/data-ingestion/logstash/
The following checks are **required**:
=> app/vmlogs: Replace elasticsearch plugin with opensearch plugin of logstash

app/vmui/packages/vmui/src/components/Chart/Line/Legend/hooks/useGroupSeries.ts, docs/victoriametrics/changelog/CHANGELOG.md
Hide identical series in the legend on the Raw Query page when deduplication is disabled.
Related issue: #8688
=> vmui: hide duplicate legend items in Raw Query

app/vmui/packages/vmui/src/components/Main/Button/style.scss, app/vmui/packages/vmui/src/pages/ExploreLogs/ExploreLogsHeader/ExploreLogsHeader.tsx, app/vmui/packages/vmui/src/pages/ExploreLogs/ExploreLogsHeader/style.scss, docs/victorialogs/CHANGELOG.md
Fixes oversized `Query History` button on mobile in logs UI.
Related issue: #8788 
=> vmui/logs: fix oversized `Query History` button on mobile

app/vmui/packages/vmui/src/components/Chart/BarHitsChart/BarHitsChart.tsx, app/vmui/packages/vmui/src/components/Chart/BarHitsChart/BarHitsLegend/BarHitsLegend.tsx, app/vmui/packages/vmui/src/components/Chart/BarHitsChart/BarHitsPlot/BarHitsPlot.tsx, app/vmui/packages/vmui/src/components/Chart/BarHitsChart/hooks/useBarHitsOptions.ts, docs/victorialogs/CHANGELOG.md
Related issue: #8557, #8558 
Fix zoom behavior on VictoriaLogs chart. The problem was that after zooming, the chart was recreated and the cursor position on the graph was lost, so further zooming occurred relative to the zero position. So to fix this problem:
- removed unnecessary dependencies from useEffect to avoid recreating the chart;
- moved the chart with the legend to a separate component to optimize the code when the graph is hidden;
- also this PR contains changes from [this PR](https://github.com/VictoriaMetrics/VictoriaMetrics/pull/8718), which preserve zoom selection on autorefresh 
=> app/vmui/logs: fix zoom behavior on VictoriaLogs chart

lib/storage/index_db.go, lib/storage/storage.go
Reuse indexdb/indexSearch if possible - reduce pressure on atomic counters
Before:
```
GOMAXPROCS=20 ./storage-test -test.v -test.run ^$ -test.bench ^BenchmarkStorageAddRows$ 2> /dev/null
goos: linux
goarch: amd64
pkg: github.com/VictoriaMetrics/VictoriaMetrics/lib/storage
cpu: Intel(R) Xeon(R) Gold 6230R CPU @ 2.10GHz
BenchmarkStorageAddRows
BenchmarkStorageAddRows/1
BenchmarkStorageAddRows/1-20                    	  305073	      3713 ns/op	   0.27 MB/s	     581 B/op	       0 allocs/op
BenchmarkStorageAddRows/10
BenchmarkStorageAddRows/10-20                   	  121305	     10187 ns/op	   0.98 MB/s	    1458 B/op	       0 allocs/op
BenchmarkStorageAddRows/100
BenchmarkStorageAddRows/100-20                  	   14506	     83855 ns/op	   1.19 MB/s	   12309 B/op	       0 allocs/op …
```
=> Reuse indexdb/indexSearch

deployment/docker/rules/alerts-vmagent.yml, docs/victoriametrics/changelog/CHANGELOG.md
The new rule should notify user when there is a job with 0 configured or discovered targets, which is usually a sign of misconfiguration.
=> deployment/rules: add alerting rule `ScrapePoolHasNoTargets` to vmagent

lib/storage/index_db_test.go, lib/storage/search_test.go, lib/storage/search_timing_test.go, lib/storage/storage_test.go, lib/storage/storage_timing_test.go
These were added while working on paritition index (#8134). Submitting the separately in order to:
1. Make sure partition index will not break anything and
2. Be able to compare performance before and after swiching to parition index.
=> lib/storage: Add more unit tests and benchmarks

app/vmagent/remotewrite/relabel.go, app/vmagent/remotewrite/remotewrite.go, app/vminsert/common/streamaggr.go, app/vminsert/relabel/relabel.go, docs/victoriametrics/changelog/CHANGELOG.md
all `*_last_reload_successful` metrics are set to 1 even when respective configuration is not defined, besides stream aggregation and scraping. PR initialises config reload related metrics only when respective configuration is set
fixes https://github.com/VictoriaMetrics/helm-charts/issues/2119
=> init config reload related metrics only when configuration is defined

docs/victoriametrics/Quick-Start.md
`latest` seem to confuse users with `:latest` tag
see https://github.com/VictoriaMetrics/VictoriaMetrics/issues/7336#issuecomment-2849382265
Replacing it with `newest` word, which is how dockerhub sorts the tags in its UI at https://hub.docker.com/r/victoriametrics/victoria-metrics/tags
=> docs/victoriametrics/quickstart: avoid using word `latest`

app/victoria-logs/main.go, app/victoria-metrics/main.go, app/victoria-metrics/main_test.go, app/vmagent/main.go, app/vmalert/main.go, app/vmauth/main.go, app/vmbackup/main.go, app/vmrestore/main.go, lib/httpserver/httpserver.go
This addresses that todo in the codebase, and updates all callsites to the new signature.
=> lib/httpserver: move ServeWithOpts to Serve

app/vmauth/main.go
This functionality was broken in https://github.com/VictoriaMetrics/VictoriaMetrics/commit/0e313e53557f01046e3162abb33ef361ccf4a243
Was caught by integration tests:
```
--- FAIL: TestSingleVMAuthRouterWithInternalAddr (5.00s)
vmauth_routing_test.go:148: Could not start vmauth: could not extract some or all regexps from stderr: ["pprof handlers are exposed at http://(.*:\\d{1,5})/debug/pprof/"]
```
=> app/vmauth: expose built-in handlers if `-httpInternalListenAddr` is specified

app/vmui/packages/vmui/src/api/tsdb.ts, app/vmui/packages/vmui/src/pages/ExploreLogs/ExploreLogs.tsx, docs/victorialogs/CHANGELOG.md
Fixes UI freeze in logs timeline after repeated zooming and panning.
The issue was caused by excessive query requests triggered during fast timeline interactions. Added debounce to limit the frequency of requests, similar to the approach used in vmui for metrics.
Related issue: #8655
=> vmui/logs: fix freeze on timeline zoom

docs/anomaly-detection/CHANGELOG.md, docs/anomaly-detection/components/scheduler.md
Update /anomaly-detection/ docs according to release `v1.22.1`
P.s. The links in guides and quickstarts were not intentionally set to v1.22.1 until we fully restore parallelization in forthcoming releases and mark it as a go-to release everywhere
=> docs/vmanomaly: release v1.22.1

go.mod, go.sum, vendor/github.com/prometheus/common/config/headers.go, vendor/github.com/prometheus/common/model/alert.go, vendor/github.com/prometheus/common/model/labels.go, vendor/github.com/prometheus/common/model/metric.go, vendor/github.com/prometheus/common/promslog/slog.go, vendor/github.com/prometheus/prometheus/config/config.go, vendor/github.com/prometheus/prometheus/model/labels/labels_common.go, vendor/github.com/prometheus/prometheus/model/relabel/relabel.go, vendor/github.com/prometheus/prometheus/storage/remote/write_handler.go, vendor/github.com/prometheus/prometheus/util/logging/file.go, vendor/modules.txt
Version with the latest changes from prometheus/common have been released as v0.303.1 so builds are no longer failing.
=> deps: remove pin for prometheus/prometheus

app/vmui/packages/vmui/package.json, app/vmui/packages/vmui/src/components/Configurators/QueryEditor/LogsQL/useFetchLogsQLOptions.tsx, app/vmui/packages/vmui/src/hooks/useTenant.ts, app/vmui/packages/vmui/src/pages/ExploreLogs/hooks/useFetchLogHits.ts, app/vmui/packages/vmui/src/pages/ExploreLogs/hooks/useFetchLogs.ts, app/vmui/packages/vmui/src/utils/default-server-url.ts, app/vmui/packages/vmui/vite.config.ts
Added npm command `npm run start:logs:playground` to run VictoriaLogs UI with playground env.
=> app/vmui: add command to run VictoriaLogs with playground env

lib/storage/index_db.go, lib/storage/storage.go
Replace dateMetricIDCache with a simplified one for metricsIDs
=> use separate data structure for metricIDs

lib/storage/storage.go, lib/storage/storage_test.go
In common case search requests will cover only one partition - no need for concurrency and synchronization.
Commands to run benchmark
```
BRANCH=$(git branch --show-current); GOEXPERIMENT=synctest GOOS=linux GOARCH=amd64 go test -c -o ~/work/tasks/issue-7599/benchmarks/bin/amd64/$BRANCH github.com/VictoriaMetrics/VictoriaMetrics/lib/storage
OUT=amd64-amd-epyc-7702/ BINARY=issue-7599_speedup_search_and_merge BENCHMARK=BenchmarkStorageSearchMetricNames_VariousTimeRanges; ./bin/amd64/$BINARY -test.count 6 -test.run ^$ -test.bench ^$BENCHMARK$ -test.cpuprofile $OUT/$BINARY-$BENCHMARK.cpu -test.mutexprofile $OUT/$BINARY-$BENCHMARK.mutex 1> $OUT/$BINARY-$BENCHMARK.log 2>/dev/null
```
Tested on two machines:
```
amd64-intel-xeon-6230R benchstat …
```
=> issue-7599: Optimize common cases on read path

docs/victoriametrics/changelog/CHANGELOG.md, lib/promauth/config.go, lib/promauth/config_test.go
Fix #8931 
Details is described in the issue above
=> fix auth header always get the same hash thus causing config changes not apply

docs/victoriametrics/changelog/CHANGELOG.md
Add a note to skip the latest releases, because of the bug in vmagent. Fixed in https://github.com/VictoriaMetrics/VictoriaMetrics/pull/8941
=> changelog: add advice to skip affected versions

dashboards/victoriametrics-cluster.json, dashboards/victoriametrics.json, dashboards/vm/victoriametrics-cluster.json, dashboards/vm/victoriametrics.json, deployment/docker/rules/alerts-cluster.yml, deployment/docker/rules/alerts.yml, docs/victoriametrics/changelog/CHANGELOG.md
enhance alerting rule `DiskRunsOutOfSpaceIn3Days` and `NodeBecomesReadonlyIn3Days` to account for [deduplication](https://docs.victoriametrics.com/#deduplication) and [indexDB](https://docs.victoriametrics.com/#indexdb) when calculating disk consumption rate.
And try bring the `Storage full ETA` panel back.
=> alerts: improve disk full estimation

docs/guides/understand-your-setup-size/README.md, docs/victoriametrics-cloud/alerting-vmalert-victoria-metrics-cloud.md, docs/victoriametrics-cloud/alertmanager-setup-for-deployment.md, docs/victoriametrics-cloud/deployments/README.md, docs/victoriametrics-cloud/deployments/tiers-and-types.md, docs/victoriametrics-cloud/how-to-monitor-k8s.md
As planned, we are adding a more structured way of explaining deployments and tiers.
In this PR the following changes are added:
- The previous tiering section is moved under the deployments placeholder
- Explanations for users to pick single or cluster 
- Explanations for different parameters
- Re-styling of the docs to look more appealing
- Reorder some hanging docs so the sections are more clearly presented to the users
=> Docs/cloud: complete deployments section

deployment/docker/compose-vm-cluster.yml
vmalert auto adds `/api/v1/write` if `remoteWrite.disablePathAppend` is not specified
=> deployment-docker: fix vmalert `-remoteWrite.url` arg

docs/victoriametrics/stream-aggregation.md
MetricsQL code was in wrong place - moved it 5 lines higher
=> docs: changed typo in histogram_bucket - metricsQL query was in wrong place

app/vmselect/prometheus/query_range_response.qtpl, app/vmselect/prometheus/query_range_response.qtpl.go, docs/victoriametrics/changelog/CHANGELOG.md
Previously, querying with disabled tracking would lead to loading nil value of execution duration. `qs.SeriesFetched` does not need similar handling as it uses atomic.Int64 and has default value anyway.
See: https://github.com/VictoriaMetrics/VictoriaMetrics/issues/8973
=> app/vmselect/prometheus: prevent panic when querying with disabled query stats tracking

lib/storage/index_db.go, lib/storage/index_db_test.go, lib/storage/index_db_timing_test.go, lib/storage/storage.go
This PR partially reverts #8851.
Fresh indexSearch/tableSearch must perform expensive block reading since there is no saved state in underlying partSearches. indexSearch reuse allows amortized this.
=> Issue 7599: reuse indexSearch instances again

app/vmalert-tool/unittest/unittest.go, docs/victoriametrics/changelog/CHANGELOG.md
When multiple users run tests on the same instance, the first user creating a folder will own the testStoragePath, which can lead to issues accessing this folder for other users. This change will allow us to create unique folders per user. 
```
% ls -ld /usr/tmp/vmalert-unittest/
drwxr-xr-x 2 some_user users 4096 May 12 17:22 /usr/tmp/vmalert-unittest/
...
2025-05-20T13:56:16.488Z        panic   lib/fs/fs.go:132        FATAL: cannot create directory: mkdir /usr/tmp/vmalert-unittest/1747749376488491648: permission denied
panic: FATAL: cannot create directory: mkdir /usr/tmp/vmalert-unittest/1747749376488491648: permission denied
```
=> fix for multiple users running tests (testStoragePath ownership issue)

docs/victorialogs/CHANGELOG.md, lib/logstorage/datadb.go, lib/logstorage/partition.go
Fixes [#8873](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/8873).
Automatically recover missing `parts.json` files on startup. VictoriaLogs now scans existing part directories and recreates missing `parts.json` files instead of crashing. This aligns with VictoriaMetrics' approach.
=> vlstorage: automatically recover missing parts.json files on startup

deployment/logs-benchmark/source_logs/download.sh
When downloading archives for benchmarks, an error appears saying that the archive was placed in a new path. 
The error could have been prevented by providing the `-L (--location)` flag that would tell curl to follow the redirect, so in addition to updating the paths, this flag was added.
=> deployment/logs-benchmark: fix URLs to benchmark data

docs/victorialogs/README.md, docs/victoriametrics/Cluster-VictoriaMetrics.md, docs/victoriametrics/README.md, docs/victoriametrics/vmagent.md, docs/victoriametrics/vmalert.md
follow up https://github.com/VictoriaMetrics/VictoriaMetrics/commit/b9f080321c23ddb128457856bb4e4a7e23b37031
=> fix cmd-line flag default values in description

apptest/testcase.go
This change reduces integration tests time from 90s to 30s:
1. before https://github.com/VictoriaMetrics/VictoriaMetrics/actions/runs/15321154610/job/43105211053?pr=9048#step:5:2
2. after https://github.com/VictoriaMetrics/VictoriaMetrics/actions/runs/15324035886/job/43114340500#step:5:2
=> apptest: run tests in parallel to imrpove testing speed

app/vmui/packages/vmui/src/components/Configurators/QueryEditor/LogsQL/utils/sort.test.ts, app/vmui/packages/vmui/src/components/Configurators/QueryEditor/LogsQL/utils/sort.ts, app/vmui/packages/vmui/src/components/LogsConfigurators/GroupLogsConfigurators/GroupLogsConfigurators.tsx, app/vmui/packages/vmui/src/components/Table/TableSettings/TableSettings.tsx, app/vmui/packages/vmui/src/pages/ExploreLogs/ExploreLogsBody/views/TableView/TableView.tsx, app/vmui/packages/vmui/src/pages/ExploreLogs/GroupLogs/GroupLogs.tsx, docs/victorialogs/CHANGELOG.md
* UI now respects the `sort by` pipe in queries — if it's present, the order returned by the server is preserved. Related issue: #8660.
* If no `sort by` pipe is used, logs are reversed on the client to show the newest entries first (since VictoriaLogs returns them in ascending time order — [see this in the code](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/app/vlselect/logsql/logsql.go#L1047)).
* Removed redundant client-side time-based sorting logic.
Additionally:
* Log record fields are now sorted alphabetically in UI selectors such as **Group by field**, **Display fields**, and **Customize columns**. Related issue: #8438.
=> vmui/logs: add sort pipe handling

app/vminsert/netstorage/netstorage.go, app/vmselect/netstorage/netstorage.go, app/vmselect/prometheus/prometheus.go, lib/netutil/netutil.go, lib/netutil/netutil_test.go
Previously, address was always parsed as "host:port" and added port if it was missing. This leaded to hard to understand errors in case address was provided in "http://host:port" format.
Improve error validation in order to provide more precise error message in case of invalid address format.
See: https://github.com/VictoriaMetrics/VictoriaMetrics/issues/9029
Previous error message: `cannot dial storageNode "http://localhost:8488": dial tcp4: address http://localhost:8488: too many colons in address` and vminsert continue running.
Current error message: `cannot normalize -storageNode="http://localhost:8480": invalid address "http://localhost:8480"; expected format: host:port` and vminsert exists with error status code.
=> app/netstorage: improve validation for address provided at storageNode

app/vlstorage/netselect/netselect.go, docs/victorialogs/CHANGELOG.md
Set missing `Authorization` header when querying a storage node and Basic Auth is enabled.
See: #9080 
=> app/vlselect: set missing Authorization header

lib/netutil/netutil.go, lib/netutil/netutil_test.go
Properly check index returned by `strings.Index`, previously it was ignoring a case where "/" would be at the beginning of the string.
This is a follow-up for 00712b18
=> lib/netutil/netutil: fix strings index check

Makefile, apptest/testcase.go, apptest/tests/backup_restore_test.go, apptest/vmbackup.go, apptest/vmrestore.go, apptest/vmsingle.go, apptest/vmstorage.go
This PR adds a basic backup/restore test for vmsingle and vmcluster. A more sophisticated was originally added to the partition index PR (#8134) and was aimed to test backup/restore when switching back and forth between legacy and partition index. During the code review it was decided that it would be good to have a separate test as well since legacy code will be removed in future and so will the test.
=> apptest: Add basic backup/restore integration test

.github/workflows/main.yml
Currently, some PRs have a failed CI due to low code coverage reported by Codecov. However, the team typically ignore this and relies on other quality indicators such as thorough code reviews.
This change configures Codecov to continue posting coverage reports without marking the build as failed.
It also helps reduce confusion for external contributors, who might otherwise feel pressured to add unnecessary tests just to satisfy Codecov requirements (for example https://github.com/VictoriaMetrics/VictoriaMetrics/pull/9002#discussion_r2111651046).
=> .github/workflows: allow codecov to report without failing CI build

docs/victoriametrics/vmctl.md
Users try to migrate from systems like Thanos or Prometheus using `vmctl` and `promtheus` migration protocol, with questions about the problems when they try to specify the snapshot, but `vmctl` shows `0` series to be found for migration.
This issue happens because users specify the block folder instead of the snapshot folder.
Added clarification about snapshot structure and its appearance with multiple blocks inside.
=> docs/vmctl: add information about the prometheus snapshot folder structure

app/vmui/packages/vmui/src/components/LogsConfigurators/GroupLogsConfigurators/GroupLogsConfigurators.tsx, app/vmui/packages/vmui/src/components/Main/Icons/index.tsx, app/vmui/packages/vmui/src/components/ScrollToTopButton/ScrollToTopButton.tsx, app/vmui/packages/vmui/src/components/ScrollToTopButton/style.scss, app/vmui/packages/vmui/src/hooks/useLocalStorageBoolean.test.ts, app/vmui/packages/vmui/src/hooks/useLocalStorageBoolean.ts, app/vmui/packages/vmui/src/pages/ExploreLogs/ExploreLogsBody/views/LiveTailingView/LiveTailingSettings.tsx, app/vmui/packages/vmui/src/pages/ExploreLogs/ExploreLogsBody/views/LiveTailingView/LiveTailingView.tsx, app/vmui/packages/vmui/src/pages/ExploreLogs/ExploreLogsBody/views/LiveTailingView/style.scss, app/vmui/packages/vmui/src/pages/ExploreLogs/ExploreLogsBody/views/LiveTailingView/useLiveTailingLogs.ts, app/vmui/packages/vmui/src/pages/ExploreLogs/ExploreLogsBody/views/LiveTailingView/utils.ts, app/vmui/packages/vmui/src/pages/ExploreLogs/GroupLogs/GroupLogsFields.tsx, app/vmui/packages/vmui/src/pages/ExploreLogs/GroupLogs/GroupLogsItem.tsx, app/vmui/packages/vmui/src/pages/ExploreLogs/GroupLogs/style.scss, app/vmui/packages/vmui/src/utils/storage.ts
Related issue: #9130 
- add `ScrollToTopButton` component for better navigation UX and integrate it into Live Tailing view;
- replace log throttling logic with the new `LogFlowAnalyzer` utility for enhanced performance state tracking;
- enhance `GroupLogsItem` with a copy-to-clipboard feature, which allows to copy only one log object; 
- update styles for better responsiveness and aesthetics;
- change raw json view into expandable view in the live tailing tab by default and keep the value of this setting in the local storage, it became possible thanks to [this issue](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/9130#9083).
Short demo: 
https://github.com/user-attachments/assets/351133a7-f3ef-41ad-b23d-cc12f030a357
=> app/vmui/logs: improve usability of the live tailing tab

app/vlinsert/datadog/datadog.go, app/vlinsert/elasticsearch/elasticsearch.go, app/vlinsert/internalinsert/internalinsert.go, app/vlinsert/journald/journald.go, app/vlinsert/jsonline/jsonline.go, app/vlinsert/loki/loki_json.go, app/vlinsert/loki/loki_protobuf.go, app/vlinsert/opentelemetry/opentelemetry.go
The 'select' HTTP request duration metric is currently implemented as a summary, while the 'insert' HTTP request duration uses a histogram. 
All time series under the same metric name must use the same metric type. Using the summary type for this metric is preferable, as it significantly reduces the number of unique time series generated. While summaries have the limitation of not supporting accurate aggregation across multiple instances or paths, this trade-off is more manageable than dealing with a high-cardinality explosion caused by histograms.
=> vlogs: fix inconsistent type for HTTP request duration metric

lib/logstorage/storage_search.go
The `DataBlock` contains structs with string fields, and while the original comment mentioned not holding references to `br`, it wasn't immediately clear that this also applies to fields like strings within the data.
This change clarifies that the `writeBlockResultFunc` must not retain references to any part of `br`, including its fields. This makes it explicit that even seemingly safe types like strings must be copied if needed.
=> lib/logstorage: clarify comment on writeBlockResultFunc usage constraints

app/vmalert/config/types.go, app/vmalert/web.go, app/vmalert/web.qtpl, app/vmalert/web.qtpl.go, app/vmalert/web_test.go, app/vmalert/web_types.go, docs/victoriametrics/changelog/CHANGELOG.md, docs/victoriametrics/vmalert.md
added /api/v1/notifiers endpoint and `datasource_type` query argument for `/api/v1/rules` and `/api/v1/alerts` API endpoints to filter groups and rules by datasource type. required for https://github.com/VictoriaMetrics/VictoriaMetrics/pull/8989
fixes https://github.com/VictoriaMetrics/VictoriaMetrics/issues/8537
=> app/vmalert: added `/api/v1/notifiers` endpoint and datasource_type query argument filter for `/api/v1/rules` and `/api/v1/alerts` endpoints

docs/victorialogs/LogsQL.md
The example in the VictoriaLogs docs (Comments section) is currently missing an aggregate function in the `stats` pipe:
```logsql
error                       # find logs with `error` word
| stats by (_stream) logs # then count the number of logs per `_stream` label
| sort by (logs) desc     # then sort by the found logs in descending order
| limit 5                 # and show top 5 streams with the biggest number of logs
```
However, `stats by (_stream) logs` is invalid syntax - `logs` is interpreted as a function name, which causes a parsing error.
This fix replaces it with a valid version using `count()`:
```logsql
| stats by (_stream) count() as logs
```
Without `count()`, the query fails with:
```
cannot parse 'stats' pipe: unknown stats func "logs"
```
=> victorialogs/docs: fix invalid stats example in "Comments" section

docs/anomaly-detection/components/writer.md
as noticed @f41gh7 in [operator PR](https://github.com/VictoriaMetrics/operator/pull/1427#discussion_r2164171944)
vm writer `import_json_path` became deprecated starting [v1.19.2](https://github.com/VictoriaMetrics/vmanomaly/commit/cc2cd0e084a9e431d0f5ea1b82ed33123cff9547). Adding this information to docs
=> docs/anomaly-detection: mark import_json_path as deprecated

lib/mergeset/encoding.go
It appears the `lib/mergeset.Item` violates the 3rd rule https://pkg.go.dev/unsafe#Pointer
> (3) Conversion of a Pointer to a uintptr and back, with arithmetic.
> 
> Unlike in C, it is not valid to advance a pointer just beyond the end of its original allocation:
> ```
> // INVALID: end points outside allocated space.
> b := make([]byte, n)`
> end = unsafe.Pointer(uintptr(unsafe.Pointer(&b[0])) + uintptr(n))
> ```
`CGO_ENABLED=0 go test -trimpath -gcflags=all=-d=checkptr -run TestTableAddItemsSerial`
```
fatal error: checkptr: pointer arithmetic result points to invalid allocation
goroutine 42 gp=0x14000082e00 m=6 mp=0x14000080808 [running]:
runtime.throw({0x100278d2a?, 0x100031a90?})
runtime/panic.go:1101 +0x38 fp=0x14000987d00 sp=0x14000987cd0 pc=0x100097268 …
```
=> lib/mergeset: misuse of unsafe.Pointer

app/vmselect/promql/rollup.go, apptest/tests/special_query_regression_test.go, docs/victoriametrics/changelog/CHANGELOG.md
removeCounterResets was operating only using stalenessInterval (when set by user) and didn't account for user-specified [window] in rollup functions. Since in rollup functions MetricsQL could look behind for up to [window] interval - it can capture those datapoints that weren't accounted in removeCounterResets. With this change, we remove resets on stalenessInterval+window interval to avoid this corner case.
Fixes https://github.com/VictoriaMetrics/VictoriaMetrics/issues/8935#issuecomment-2978728661
=> app/vmselect/promql: respect window interval for rollup functions when removing resets

app/vlinsert/insertutil/common_params.go
Add metrics to track the behavior of the message processor:
- `vl_insert_processors_count` tracks the current number of active log message processors.
- `vl_insert_flush_duration_seconds{type="protocol"}` measures the time taken to flush log data from recently parsed logs to the underlying storage system (in-memory buffering, remote storage nodes, or local storage).
Related issue: https://github.com/VictoriaMetrics/VictoriaMetrics/issues/9320
=> VictoriaLogs: add message processor metrics

app/vlstorage/main.go
- `vl_max_disk_space_usage_bytes{path}` reports the configured maximum disk space usage limit for the storage path. It helps to show the limit on the dashboard.
Related issue: https://github.com/VictoriaMetrics/VictoriaMetrics/issues/9320
=> VictoriaLogs: Add metrics to track the retention.maxDiskSpaceUsageBytes flag

lib/storage/index_db_legacy.go, lib/storage/storage.go, lib/storage/storage_legacy.go
`isReadOnly` flag does not prevent writes (which we need to perform in case of deletion), it just [disables background merges](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/2603). In some cases, it could lead to a large number of small parts and hurt performance.
Union of legacy deleted metric ids is already propagated to partitioned indexDBs. We also need to add them to the previous legacy indexDB. 
=> issue-7599: do not force read-only for legacy idbs

app/vlselect/traces/jaeger/jaeger.go, app/vlselect/traces/jaeger/model.go, app/vlselect/traces/jaeger/model_test.go, apptest/tests/otlp_ingestion_test.go
1. Currently user can't filter trace by resource attributes. This pull request enable such capability when user use `resource_attr:` prefix in tag filter of Jaeger query APIs.
2. Fix ref type typo `FOLLOWS_FROM`. This issue affect the visualization in Grafana and Jaeger.
=> VictoriaTraces: Fix ref type typo. Support resource attribute filter

lib/storage/storage_test.go
Initialize storage properly via the constructor function. Extracted from #8134. 
=> lib/storage: use real storage in TestUpdateCurrHourMetricIDs

lib/storage/partition_search_test.go, lib/storage/partition_test.go
Add helper `testCreatePartition` for partition test. Extracted from #8134.
=> lib/storage: add and use testCreatePartition helper

lib/storage/storage_test.go
No-op for master branch, preparation for #8134.
Also move testCountAllMetricIDs() to reduce diff in #8134.
=> lib/storage: use explicit TimeRange{0, math.MaxInt} for all time period search

lib/storage/index_db.go, lib/storage/search.go, lib/storage/storage.go
- Move `prefetchMetricNames`, `SearchMetricNames`, and `SearchLabelValues` from `Storage` to `indexDB`
- Rename `searchLabelValuesWithFiltersOnTimeRange` to `searchLabelValuesOnTimeRange`
- Rename `searchLabelValuesWithFiltersOnDate` to `searchLabelValuesOnDate`
Extracted from #8134.
=> lib/storage: move methods from Storage to indexDB

lib/storage/storage_test.go
Add unit tests that verify filesystem hierarchy of the indexdb after opening the storage and after rotation. The test have been originally added in #8134 but are still applicable to the current version and will also reduce the diff.
=> lib/storage: add TestMustOpenIndexDBTables_*

apptest/tests/legacy_indexdb_test.go
Currently, select data caching is [persistent](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/aaefe469c14dee3484f48c9fe89fd1557124428e/app/vmselect/main.go#L66) for vmsingle and non-persistent ([1](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/664efe4d50bd9ebb3608819e1294b20b89f2ad97/app/vmselect/main.go#L123), [2](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/c677e7e10f3a00e5c4b7bdfdaae553522d1a6892/app/vmselect/promql/rollup_result_cache.go#L81)) for vmselect. It leads to different results because a cache key uses [rollupResultCacheKeyPrefix](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/c677e7e10f3a00e5c4b7bdfdaae553522d1a6892/app/vmselect/promql/rollup_result_cache.go#L514-L513). 
Caching on the search side could hide bugs - it is better to turn …
=> issue-7599: apptest: do not cache search results

Makefile
VictoriaLogs has been moved to a separate repository. Remove remaining vlogs build rules from VictoriaMetrics.
=> Makefile: remove vlogs build targets

dashboards/victorialogs-cluster.json, dashboards/victoriametrics-cluster.json, dashboards/vm/victorialogs-cluster.json, dashboards/vm/victoriametrics-cluster.json
When `$__interval` is small and close to the scrape interval, we start losing some data points, which can cause the sum to show misleading spikes. This change ensures that the minimum interval does not go below 1m to avoid such issues. 
The query works fine for long time ranges, like 7d, 30d, where interval is  bigger than 1m
The query:
```
sum(max_over_time(vm_tcplistener_conns{job=~"$job", instance=~"$instance"}[$__interval])) by(job)
```
Before:
After:
=> dashboards: TCP connections shows spikes on small time ranges

lib/storage/index_db.go, lib/storage/storage.go, lib/storage/table.go
The following renamings were requested in #8134 to be done in a separate PR:
- Rename putTSIDToCache(s) to storeTSIDToCache(s). This is because get/put prefixes are normally reserved for pools and ref counters. This unclear though whether name `getTSIDFromCache` is okay in this context.
- Rename `addPartitionNolock` to `addPartitionLocked`, because the `Locked` suffix is used everywhere else
- Rename deleteMetricIDs to saveDeletedMetricIDs, because no deletion is actually happening. The deleted metric ids are still present in the index. One needs to filter the deleted metric ids out after the retrieval.
=> lib/storage: Minor renamings requested in #8134

app/vmselect/netstorage/netstorage.go, docs/victoriametrics/changelog/CHANGELOG.md
Currently, all errors that occur during the handshake and dial phases (except for timeouts) are retried in [execOnConnWithPossibleRetry](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/0c4062b7276cecb3345197f6aa1181cfab1f2f00/app/vmselect/netstorage/netstorage.go#L2431). However, such errors typically result from network issues or CPU exhaustion on the storage side. In both cases, retrying is unlikely to succeed and may instead contribute to additional, unnecessary load on the system.
This PR disables retries for all errors encountered during the handshake and dial process. The goal is to avoid redundant retry attempts in scenarios where they are unlikely to help and may worsen the underlying problem.
Related to https://github.com/VictoriaMetrics/VictoriaMetrics/issues/9345
The …
=> app/vmselect/netstorage: do not retry "cannot obtain connection from the pool" errors

docs/victoriametrics/Cluster-VictoriaMetrics.md, docs/victoriametrics/FAQ.md
See context here https://www.reddit.com/r/VictoriaMetrics/comments/1mb60ck/ha_setup_on_onprem_cluster/ Apparently, user was confused with inability of VM single-node to run in HA.
=> docs: mention that single-node supports HA in cluster recommendation

app/vmauth/main.go, docs/victoriametrics/changelog/CHANGELOG.md
Commit e77df5d00ba4c95c7156ef5db89909375eb026b7 introduced
unintentional change, which prevents from using httpInternalListenAddr. Which is designed to use with clients that do not support proxy protocol.
Fixes https://github.com/VictoriaMetrics/VictoriaMetrics/issues/9515
=> app/vmauth: properly set useProxyProtocol for httpInternalListenAddr

app/vmui/packages/vmui/src/components/Configurators/GlobalSettings/TenantsConfiguration/TenantsConfiguration.tsx, docs/victoriametrics/changelog/CHANGELOG.md
Previously, the tenant selector was hidden when only one tenant
was returned, making it impossible to run queries in multi-tenant mode.
Now, the selector is always shown as long as at least one tenant exists.
Related issue: #9396
=> vmui: always show tenant selector if tenant list is not empty

apptest/app.go, apptest/testcase.go, apptest/vmagent.go, apptest/vmauth.go, apptest/vmbackup.go, apptest/vmctl.go, apptest/vminsert.go, apptest/vmrestore.go, apptest/vmselect.go, apptest/vmsingle.go, apptest/vmstorage.go
Update tests to only print component output in integration tests if the test case is failing.
An example of pipeline failure: https://github.com/VictoriaMetrics/VictoriaMetrics/actions/runs/16473633711/job/46569913168?pr=9491
=> apptest/tests: only flush component logs on test failure

lib/fs/fs.go, lib/fs/fs_netbsd.go, lib/fs/fs_nix.go, lib/fs/fs_openbsd.go, lib/fs/fs_solaris.go, lib/fs/fs_unix.go, lib/fs/fs_windows.go
Extends the disk space monitoring functionality by adding support for retrieving total disk capacity in addition to free space. 
Related: https://github.com/VictoriaMetrics/VictoriaLogs/issues/513
=> lib/fs: Add total disk space retrieval

docs/victoriametrics/Cluster-VictoriaMetrics.md, docs/victoriametrics/README.md
* remove duplicated content between single and cluster versions
* mention recommendation to group component types by jobs in scrape config
* link the example of scrape configs
* update wording
=> docs: update monitoring section

docs/victoriametrics/_index.md, docs/victoriametrics/changelog/_index.md
multiple pages, that reference same document in `{% content %}` shortcode same content, but different canonical URLs, added canonical parameter to override default url
=> docs: override canonical url of pages, that have multiple copies

docs/victoriametrics/changelog/CHANGELOG.md, lib/netutil/proxyprotocol.go, lib/netutil/proxyprotocol_test.go, lib/netutil/tcplistener.go
lib/netutil: properly accept proxy protocol
Previously, tcp listener perform synchronous proxy protocol header
read during connection accept. It could significantly reduce vmauth
performance and lead to timeout at serving http requests.
This commit changes this logic and performs proxy protocol header
parsing during first Read request from connection or RemoteAddr method
call. It significantly improves performance and reduce possible
bottleneck at connections accept method.
=> vmauth properly accept proxy-protocol header

.github/workflows/build.yml, .github/workflows/test.yml, Makefile, lib/appmetrics/appmetrics.go
The commit changes CI behavior:
- Run build in parallel for different os\arch
- Run unit\integration\lint in parallel
- Remove the custom Go cache step in favor of the logic provided in `actions/setup-go`. The custom cache was used to build key based on  go.sum and makefiles. This logic is preserved. 
- Introduce cache for golangci-lint. 
=> .github/workflows: Run cross builds  and tests in parallel

apptest/vmagent.go, apptest/vmauth.go
Do not check vmauth_config_last_reload_success_timestamp_seconds since it may contain the timestamp < time.Now() due to how lib/fasttime works.
Instead, compare the number of config reloads.
follow up on https://github.com/VictoriaMetrics/VictoriaMetrics/pull/9369 and https://github.com/VictoriaMetrics/VictoriaMetrics/pull/9572
Also, split the config update and reload into two separate functions. 
master:
```
$gotest -race ./apptest/tests/ -run=TestSingleVMAuthRouterWithInternalAddr -count=40
ok  	github.com/VictoriaMetrics/VictoriaMetrics/apptest/tests	90.176s
```
pr:
```
$gotest -race ./apptest/tests/ -run=TestSingleVMAuthRouterWithInternalAddr -count=40
ok  	github.com/VictoriaMetrics/VictoriaMetrics/apptest/tests	46.130s
```
=> apptest: Fix flaky TestSingleVMAuthRouterWithAuth

docs/victoriametrics/changelog/CHANGELOG.md, lib/backup/actions/util.go, lib/backup/s3remote/s3.go
fixes https://github.com/VictoriaMetrics/VictoriaMetrics/issues/9532
set checksum algorithm to SHA256, not sure if this property should be configurable
=> lib/backup: added checksum algorithm for all S3 PutObject requests

docs/victoriametrics/changelog/CHANGELOG.md, go.mod, go.sum, vendor/github.com/VictoriaMetrics/metricsql/utils.go, vendor/modules.txt
Fixes [#9527](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/9527) 
Related PR: https://github.com/VictoriaMetrics/metricsql/pull/55
=> metricsql: improve timestamp function compatibility with Prometheus when used with sub-expressions

app/vmagent/remotewrite/client.go
It seems db39f045e1e9008bdeda2c23a06234d2efa54f5e accidentally reverted #9419 changes.
```patch
--- a/app/vmagent/remotewrite/client.go
+++ b/app/vmagent/remotewrite/client.go
@@ -448,7 +448,8 @@ again:
}
metrics.GetOrCreateCounter(fmt.Sprintf(`vmagent_remotewrite_requests_total{url=%q, status_code="%d"}`, c.sanitizedURL, statusCode)).Inc()
-	if statusCode == 409 {
+	switch statusCode {
+	case 409:
logBlockRejected(block, c.sanitizedURL, resp)
// Just drop block on 409 status code like Prometheus does.
@@ -461,7 +462,13 @@ again:
// - Remote Write v2 specification explicitly specifies a `415 Unsupported Media Type` for unsupported encodings.
// - Real-world implementations of v1 use both 400 and 415 status codes.
// See more in research: …
```
=> app/vmagent/remotewrite: restore protocol downgrade logic

app/vmctl/vm_native.go
Some messages were written to `stdout` using `fmt.Printf` and `fmt.Println`, while the other messages like import statistics were written to `stderr` through the `log` package.
This led to ordering problems where the `Import finished!` + `VictoriaMetrics importer stats` messages, which expected to be the last messages, appeared before `Continue import process with filter` messages, creating confusing output for users.
```
2025/08/20 13:07:26 Import finished!
2025/08/20 13:07:26 VictoriaMetrics importer stats:
time spent while importing: 20h49m10.8497184s;
total bytes: 277.1 GB;
bytes/s: 3.7 MB;
requests: 7978614;
requests retries: 0;
2025/08/20 13:07:26 Total time: 20h49m10.851006088s
Continue import process with filter
filter: match[]={__name__!=""}
start: 2025-08-08T00:00:00Z
end: …
```
=> vmctl: inconsistent vm-native logs

benchmarks/Makefile
Add the support of all standard TSDB query types that can be executed against VictoriaMetrics. `double-groupby-all` is commented out as it attempts to retrieve all 1B samples and fails. While this can be fixed by setting the `-search.maxSamplesPerQuery` this query is left disabled anyway because it will consume way too much memory and cpu time. 
=> TSDB: support for all query types

app/vmui/packages/vmui/src/layouts/AnomalyLayout/AnomalyLayout.tsx, app/vmui/packages/vmui/src/router/index.ts
`router.home` represents `/` path, which is the same for all UI apps, but content and title for root path differs depending on application type. added `getDefaultOptions` function, which returns proper home route configuration depending on application type, which allows to remove renamings in respective layouts 
=> app/vmui: removed home page hack

.github/workflows/check-commit-signed.yml
.github/workflow: add check commit signed action
Add GitHub Action to verify commit signatures.
This action checks commit signatures, accepting G (good) and E (signed
but key not available for full verification).
Note: This is not a 100% accurate check. The CI mainly targets unsigned
commits from external contributors.
Reference: https://git-scm.com/docs/pretty-formats#Documentation/pretty-formats.txt-G
=> .github/workflow: add check commit signed action

app/vmalert-tool/unittest/unittest.go
Previously mock storage `net.Listen("tcp", …)` could succeed even if
another process was bound to the same port, due to dual-stack behavior
(`[::]:port` vs `0.0.0.0:port`). That lead to strange test results that
hard to bound to port misuse. Tests queried not mock server but whatever was running on that port. 
Switched to `"tcp4"` to ensure conflicts are detected correctly.
=> app/vmalert-tool: Force ipv4 binding in vmalert unit test

docs/victoriametrics/stream-aggregation/README.md
Fix a stream aggregation pitfall when deduplication intervals differ between storage and vmagent.
Follow up on https://github.com/VictoriaMetrics/VictoriaMetrics/issues/9581
=> docs/stream-aggregation: Add deduplication common mistake

app/vmui/packages/vmui/src/hooks/useSearchParamsFromObject.ts, docs/victoriametrics/changelog/CHANGELOG.md
Fix bug in `useSearchParamsFromObject` hook that prevented filtering on the *Explore Cardinality* page.
=> vmui: fix useSearchParamsFromObject not updating searchParams

lib/flagutil/duration.go, lib/flagutil/duration_test.go
Related: https://github.com/VictoriaMetrics/VictoriaLogs/issues/50
=> flag: update RetentionDuration to Duration for clearer, reusable naming

app/vmui/packages/vmui/src/layouts/Header/Header.tsx, app/vmui/packages/vmui/src/layouts/Header/HeaderControls/HeaderControls.tsx, app/vmui/packages/vmui/src/layouts/Header/HeaderNav/NavSubItem.tsx, app/vmui/packages/vmui/src/layouts/Header/HeaderNav/style.scss, app/vmui/packages/vmui/src/layouts/Header/SidebarNav/SidebarHeader.tsx, app/vmui/packages/vmui/src/layouts/Header/SidebarNav/style.scss, app/vmui/packages/vmui/src/layouts/Header/style.scss
after adding Alerting section all menu items cannot be displayed on mobile devices in a sidebar. this PR:
- makes sidebar scrollable, when it's content overflows screen
- makes sidebar items collapsible
- fixes menu layout on mobile devices with big screens
before:
after:
=> app/vmui: make sidebar scrollable and its items collapsible

docs/victoriametrics/url-examples.md
The export/import format can be confusing for users unfamiliar with its syntax. To make matters worse, the format shown in [export examples](https://docs.victoriametrics.com/victoriametrics/url-examples/#apiv1exportcsv) was incompatible with the one used in [import examples](https://docs.victoriametrics.com/victoriametrics/url-examples/#apiv1importcsv).
This PR updates the examples so they are compatible, allowing users to follow the export and import steps to complete a full data cycle.
=> docs/url-examples: align export example format with import example

app/vmselect/main.go, lib/appmetrics/appmetrics.go, lib/buildinfo/version.go
The application version can be then displayed in the vmui. Showing the application version in vmui should make it easier to determine currently used VM version (at least vmselect version).
------------
@Loori-R it would be could to add the app version in vmui in a follow-up PR or by pushing a commit to this branch.
=> app/vmselect: encode application version into manifest

app/vmselect/graphite/eval.go, lib/streamaggr/streamaggr.go, lib/timerpool/timerpool.go, lib/writeconcurrencylimiter/concurrencylimiter.go
after golang 1.23 it's enough just to stop timer, no need to drain a channel
related issue https://github.com/VictoriaMetrics/VictoriaMetrics/issues/9721, but this is not a fix for it
=> lib/timerpool: removed unneeded code, unified package usage

docs/victoriametrics/vmbackupmanager.md
- state that it is unsafe to use lifecycle rules and describe the reason
- update formatting according latest changes in docs
<details> 
<summary>Updated formatting</summary>
</details>
=> docs/vmbackupmanager: add docs to clarify unsafe usage of lifecycle rules

lib/storage/search.go, lib/storage/storage.go
A small refactoring that reduces Search dependency on Storage:
- Move searchTSIDs() from Search to Storage because this method does not depend on anything Search-specific but does depend on Storage.
- Use metricsTracker instead of storage.metricTracker.
=> lib/storage: Move searchTSIDs to Storage

lib/storage/block_stream_merger.go, lib/storage/merge.go, lib/storage/merge_test.go, lib/storage/merge_timing_test.go, lib/storage/metric_name_search.go, lib/storage/partition.go, lib/storage/search.go, lib/storage/storage.go
Searching metricName by metricID happens many times during a single API call. This requires getting the current set of idbs before those calls happen. Which is fine but requires propagating idbs across the code base. This is also fine in case of OSS version as it is used in Search only.
Propagating idbs across the code base becomes a problem in Enterprise version as it is used in at least 3 places. As a result it becomes very difficult to merge things from OSS to Ent.
Localizing the all the dependencies in one searchMetricName type and reusing this type everywhere should make things simpler.
Related enterprise changes: https://github.com/VictoriaMetrics/VictoriaMetrics-enterprise/compare/search-metric-name-ent?expand=1
=> lib/storage: introduce metricNameSearch type

app/vmui/packages/vmui/src/components/Main/DatePicker/Calendar/Calendar.tsx, app/vmui/packages/vmui/src/components/Main/DatePicker/Calendar/CalendarBody/CalendarBody.tsx, app/vmui/packages/vmui/src/components/Main/DatePicker/Calendar/CalendarHeader/CalendarHeader.tsx, app/vmui/packages/vmui/src/components/Main/DatePicker/Calendar/MonthsList/MonthsList.tsx, app/vmui/packages/vmui/src/components/Main/DatePicker/Calendar/YearsList/YearsList.tsx, app/vmui/packages/vmui/src/components/Main/DatePicker/Calendar/style.scss, app/vmui/packages/vmui/src/components/Main/DatePicker/DatePicker.tsx, app/vmui/packages/vmui/src/components/Main/DatePicker/DateTimeInput/DateTimeInput.tsx
add ability to limit available in datePicker dates using `minDate` and `maxDate` parameters. all dates before `minDate` and after `maxDate` cannot be picked. lower and upper bounds can be set independently.
=> app/vmui: add `minDate` and `maxDate` parameters for DatePicker to allow limiting available dates to select

app/vmui/packages/vmui/src/components/Main/Select/Select.tsx, app/vmui/packages/vmui/src/pages/ExploreAlerts/ExploreRules.tsx
resetting Select component selected items, when all items are selected, this should speed up filtering on alerting page on VMUI
=> app/vmui: reset select values, when 'ALL' selected

docs/victoriametrics/CONTRIBUTING.md
Consistently use the `v0.0.0-YYYYMMDDHHMMSS-commit_hash` reference for the internal deps such as `github.com/VictoriaMetrics/VictoriaMetrics`
dependency, since it allows referring any commit without waiting for the release tag.
=> docs: update internal vendoring contribution guide

docs/victoriametrics/Cluster-VictoriaMetrics.md
The previous text didn't contain links to vmagent's capabilities. Instead, it contained misleading multitenancy-mode link that doesn't seem to be related to the subject.
=> docs: clarify how vmagent addresses multi-level ingestion shortcomings

docs/victoriametrics/changelog/CHANGELOG.md, go.mod, go.sum, vendor/github.com/VictoriaMetrics/metrics/set.go, vendor/github.com/VictoriaMetrics/metrics/summary.go, vendor/modules.txt
Restore sorting order of summary and quantile metrics exposed by VictoriaMetrics components on `/metrics` page.
https://github.com/VictoriaMetrics/metrics/pull/105
=> vendor: update metrics package to v1.40.2

lib/prompb/prompb_timing_test.go
Initially, this benchmark was running 1000 iterations. Later in c005245741fc3d7d744f258959be2a5ae388f8ec it was refactored and bumped to 10_000. This alerts continuous benchmark systems, so this commit brings it back to 1000
=> lib/promb: run 1000 iterations for write request benchmark

docs/victoriametrics/vmagent.md
clarify how sharding in vmagent works when srv url is used
=> docs: clarify how sharding in vmagent works when srv url is used
